### ISSUE TITLE
Better lifecycle events

### ISSUE THREAD

**Issue by Kelin2025** [vuejs/vue#7966] opened 2018-04-04 22:21 UTC
### What problem does this feature solve?
Hello. I came with a little specific but, I think, useful ideas.  
Vue has undocumented (or?) lifecycle events. I have some nested high-ordered components
- Custom inputп
- Search component with custom input
I wanted to add "autofocus" on `@hook:mounted`  for search input but solution is not nice because of 2 problems:
- `$listeners` also adds `@hook:mounted` event. It causes both mounted events call ([demo](https://codesandbox.io/s/921k2n76p4))
- It would be better to have component instance passed to event

### What does the proposed API look like?
1. Add `.self` flag (or with another name) for lifecycle events that will compare component instances (like `.self` compares targets for native events)
- 2nd: Add component instance to events. It will allow us not to use `$refs` for use cases like this one

**Comment by blake-newman** [comment] 2018-04-04 22:49
Could you add a reproduction for examples? Will make it easier to understand your point of view?

**Comment by Kelin2025** [comment] 2018-04-04 23:37
A very minimal example: [**click**](https://codesandbox.io/s/xrkwr4oq9o)  

P.S. Sorry for inline templates, I was lazy to create some files

**Comment by blake-newman** [comment] 2018-04-05 00:07
Okay, because the reproduction is confusing to follow. (Please next time spend some time organising, as i just spent 20 minutes trying to work through your ambitions)

I still don't understand your proposed feature / bug fix. Please define your requirements and output more clearly so we can triage the issue further.

**Comment by sirlancelot** [comment] 2018-04-05 02:33
I don't understand this. Would you be able to perhaps describe the problem you're having instead via Discord? I'm not sure what you're describing is a bug or a feature, but more likely a usage question.

**Comment by yyx990803** [comment] 2018-04-05 05:09
Closing because feature requests should have more thoroughly and carefully elaborated technical usage examples AND use case / motivations. For ideas that are not quite fully formulated, please discuss on Discord first before opening an issue.

**Closed by yyx990803** 2018-04-05 05:09 UTC
