### ISSUE TITLE
Webassembly integration. Split the core into two parts.

### ISSUE THREAD

**Issue by o-alexandrov** [vuejs/vue#8193] opened 2018-05-16 17:56 UTC
### What problem does this feature solve?
Performance improvements.

### What does the proposed API look like?
Split the core into two parts:
- JS. Keep doing what you are already doing with the framework.
- Webassembly. Experiment with the **syntax sugar [walt](https://github.com/ballercat/walt)** to have compiled JS core in `.wasm`
  - I read other closed [issues on this topic](https://github.com/vuejs/vue/issues/7768) and saw:
    > This is like building a completely new framework (with similar syntax) - definitely not something the core team is interested in / have bandwidth for, but I wouldn't discourage anyone interested to try.
  - **The syntax sugar, walt, potentially can make the split much-much easier, since it is still JS**.

Things to consider:
- Both JS and Webassembly can be called from each other, so it is time to start mixing parts.
- Server-side rendering. This is the worst aspect in Vue.js. `JSON` client-side and server-side bundles is a ridiculous architecture to be honest.
  - If used with `serverless-webpack` to make a lambda function, **there is no optimization possible on the dependencies, such as tree shaking** as you are creating `.json` bundles that are then imported for the render function and webpack is unable to trace what parts of dependencies aren't needed. Therefore, SSR development stage is unfortunately in a very poor condition.
- SSR is happening on the server-side. Node.js 8  can run `.wasm`, so that **it could have been totally compiled**.

Personally, we would start making progress in it ourselves, but there is no incentive for us to start working on it at the moment.
Therefore, it would be great, if there are interested parties in performance improvements in the community, who can dedicate time to it.

**Comment by posva** [comment] 2018-05-16 18:33
Just to be clear, this is something we don't have the bandwidth to do yet either. I also think it is too early to have an open discussion on this

Also, sometimes people is really mistaken about the performance vs easy-to-use tradeoff which is very important to Vue as we want to make it easy for people to start using Vue. Web asm is not (yet) going to have such a big impact on performance as the bottleneck (DOM) will still be the same
Not sure why you mention SSR, web assembly is not going to change how the SSR works...

**Comment by OlzhasAlexandrov** [comment] 2018-05-16 18:46
@posva 
**1. SSR is the key** here because of:
- the browser support of `.wasm` which could be ignored server-side, hence migrated completely to webassembly.
- the whole idea of compiling to binary will drop the [vue-server-renderer](https://www.npmjs.com/package/vue-server-renderer) package and other aspects of how it is architected at the moment.

2. Simplicity:
- it is only `syntax sugar` that we are talking about, nothing major.
- **important**, keep in mind that JS can be called from Webassembly and vice versa.
  - therefore, absolutely nothing will change for the majority of the users as they will continue to write absolutely the same code.

Webassembly should be triggered `on and off` based on the browser support on the client-side, where as the **server-side should be completely rewritten and the current approach should be dropped**.

**Comment by posva** [comment] 2018-05-16 19:03
That's an expensive face detection algorithm... Its normal to see such an improvement. As I said, the main slow thing is Dom manipulations.
Anyway, feel free to add other points that may be useful

**Comment by OlzhasAlexandrov** [comment] 2018-05-16 19:18
I believe there are two things that you should consider:
1. What makes Vue a better alternative to React and Angular?
2. A natural webassembly integration might be the key that:
- brings much more attention to Vue
- leading to increased community that doesn't move back to react and angular

Imagine React implements it, what would make the community to continue using Vue as it is going to cost much more from the infrastructure perspective? Forgetting apps (react-native), thinking only from  the web perspective, it could have been a major blow.

There are already talks about React and WebAssembly, so I believe it is important for the community to prepare for the competition that will arise, there is no doubt to it. Hopefully, Vue integrates WebAssembly sooner than later.

**Comment by fnlctrl** [comment] 2018-05-16 23:25
> Imagine React implements it

From [What WebAssembly means for React - Lin Clark aka @linclark at @ReactEurope 2017](https://youtu.be/3GHJ4cbxsVQ?t=1287)
"But will it help with the performance with react applications in the browser? The truth is, the short-term immediate impact of this on performance isn't clear." which is the euphemism of saying no.

As @posva said, the perf bottleneck is on DOM api, and not javascript itself, nor the virtual dom diffing algorithm. It's meaningless to speed something that already takes like <10ms to 1ms, while still spending 100+ms on DOM APIs.

Besides, WebAssembly isn't magic and it has great limitations. You can't expect to compile some no-dom-access javascript to it. You can't use objects in wasm. I can barely imagine a JS library to live with that and implement their own objects on top of bytes.

> file sizes are much bigger, operates much slower

On the contrary, wasm files are way much larger because it's compiled binary. Thinks of the size of C source code vs compiled executable. You can also check out this true wasm powered UI framework here: https://github.com/aspnet/blazor (which is compiled from C#), and see their demo: https://blazor-demo.github.io/
![image](https://user-images.githubusercontent.com/5557143/40148854-d054c6a6-59a2-11e8-9ca3-556fd4bbca54.png)

That's >1MB gzipped of all these files. For a bare-to-the-bone app that has a counter and can make some requests. Truly amazing. Mind blown.

**Comment by OlzhasAlexandrov** [comment] 2018-05-17 03:07
@fnlctrl 
### Your reference to a video
You are pointing to a video that is **1 year old**, the presenter makes a lot of points that are in the process of changing, most importantly:
1. No garbage collection => [there is ongoing work](https://github.com/WebAssembly/design/issues/1079)
2. No access to DOM API => it is in the list of [of the high-level goals](https://github.com/WebAssembly/design/blob/master/HighLevelGoals.md)

And some of the other ongoing work [in a video (27m50s)](https://youtu.be/bac0dGQbUto?t=27m50s)

### Your points
> On the contrary, wasm files are way much larger because it's compiled binary.
**No, not true.** Here is why:
1. Comparison with an experimental project that is in **[Alpha stage only for the last 14 days](https://github.com/aspnet/Blazor/releases)** is strange.
2. You are stating that `source code` will weigh less than bytecode. It doesn't make sense. Everyone on the web states that WebAssembly makes less network overhead, resulting in faster downloading the code, hence performance improvements. 
3. Please take a [look here](https://developer.mozilla.org/en-US/docs/WebAssembly/Concepts#How_does_WebAssembly_fit_into_the_web_platform), there is no additional runtime passed over the net or anything like that because it is running **absolutely the same as JS** => **in a VM**.

### Performance
> The power of wasm lies in boosting CPU-intensive applications
I am not an expert in this area, but it doesn't also make sense as games that are GPU-intensive that weren't playable on the web **are playable with WebAssembly**. There is also [WebVR with WebAssembly](https://youtu.be/bac0dGQbUto?t=31m20s)

Again, nobody tells it is ready or make the switch now. However, if we start making progress now, we will be better off later on, when more optimizations are available, and might happen by the time the initial preparations are made.

It is a question of when, so starting now will help us to have a better understanding when DOM access and garbage collection will be available.

**Comment by OlzhasAlexandrov** [comment] 2018-05-17 03:16
### How we could help this change to happen faster?
I believe JS developers should take a closer look to:
- [webpack wasm loader](https://github.com/ballercat/wasm-loader)
- [walt - syntax sugar on top of JavaScript](https://github.com/ballercat/walt)

**Comment by Becavalier** [comment] 2018-05-17 04:44
As @fnlctrl said, the real bottleneck of current JS framework is the cpu consumption on DOM related operations, but this can not be fixed with the current MVP WebAssembly standard. 

On the other hand, there will be a lot of overhead when the executing pointer switching between JavaScript and WebAssembly context, and this is another problem you need to concern.

@OlzhasAlexandrov  BTW, I think you need to learn more about how dose WebAssembly work, and what is it strength, what kind of frontend situations would be suitable for using current WebAssembly.

Here are some materials for you information:
https://webassembly.org/docs/future-features/
https://webassembly.org/docs/mvp/

Thanks.

**Comment by OlzhasAlexandrov** [comment] 2018-05-17 05:02
@Becavalier 
You are saying:
> On the other hand, there will be a lot of overhead when the executing pointer switching between JavaScript and WebAssembly context, and this is another problem you need to concern.

It should be further analyzed, but the **short answer is no, you are incorrect**.
Think about it, why would anyone write native node.js addons, if switching between native modules and JS would produce less optimized apps? You would be correct for a task that does almost nothing, but not for anything major.
[Here is one of the benchmarks](https://medium.com/developers-writing/how-to-get-a-performance-boost-using-node-js-native-addons-fd3a24719c85), but you can obviously find more.

Also, you are welcome to watch the talks above, so you could hear once again that mixing JS and WebAssembly isn't a bad thing.

One more point, WebAssembly gained support by Webpack since its [4th version](http://www.i-programmer.info/news/167-javascript/11602-webpack-4-adds-webassembly-support.html) and had [gained first class support](https://medium.com/webpack/webpack-awarded-125-000-from-moss-program-f63eeaaf4e15) for more than a year already.

**Comment by Becavalier** [comment] 2018-05-17 05:50
@OlzhasAlexandrov 
Yes, I agree with you that the WebAssembly will change the web, but it's at not current time, it will be in the future after the Post-MVP standard complete.

The overhead between JavaScript context and WebAssembly context would narrow down the application scenarios of current WebAssembly to just only "pure computing" applications, such as: "Graphic Processing" and "Compressing Library" related applications. These apps do not need to frequently switching between those two context environments, so that they can really save a lot cpu consumption and get a good running efficiency with the help of WebAssembly.

But for the frontend frameworks like "vuejs", without the implementation of GC, WebAssembly really can not help a lot. It doesn't need to have that much of math computing even using "virtual DOM" as the wrapper of real DOM, and the "diff" algorithm still have a good performance because of the good implementation of vuejs and the deep optimization of JavaScript engine.

last but not least, the CG and WG member are really trying their best to achieve the Post MVP standard of WebAssembly and also a better LLVM backend for WebAssembly, I think you can look forward to the day that WebAssembly will change the Web, but not now and here.

**Comment by webia1** [comment] 2018-05-17 06:12
I think, that’s great discussion, Vue would be the ultimate number one within the js-frameworks,..

**Comment by GeertArien** [comment] 2018-05-18 07:48
Without getting mixed in this discussion, I just came across this thread by accident, I just want to add my two cents. We're currently in the process of migrating a fairly large project from asmjs to WASM, so I'm actively following WASM performance in browsers. And what was said about there being no performance improvements in browsers is just straight up wrong. 

For example take this [bug-ticket ](https://bugzilla.mozilla.org/show_bug.cgi?id=1319203) for FireFox60, this bug-fix increased the performance of our app two times in FF! Yet it doesn't show up in the FF release notes. Word of advise, instead of checking browser release notes check the release notes of the javascript engines, as that's where the performance increases are implemented. And also check the ticket trackers, if they are publicly available.

Then there's also stuff like [streaming compilation](https://hacks.mozilla.org/2018/01/making-webassembly-even-faster-firefoxs-new-streaming-and-tiering-compiler/) that was recently added to firefox and chrome, without much fanfare.

Also, and I don't know if this is relevant to this project, but [react-native-dom](https://github.com/vincentriemer/react-native-dom) was just announced at [React-Europe](https://www.youtube.com/watch?v=hCyCIHKYRqg&t=165m0s), with layout powered by WASM.

**Comment by nnodot** [comment] 2018-05-18 08:51
I find this topic very interesting as I am interested in both wasm and Vue.js!

First, a bit of context. I have actually used wasm for a real world use case: viewing very big JPEG 2000 images (several GB) in the browser and run some image processing on them. So, while I'm not an expert, I get my hands dirty and play a little bit with that very promising new technology. For the Vue.js part, I must confess I am a newbie (a month or two), but what makes me very happy with it is its simplicity and expressiveness (and the excellent doc, thanks to all the team :-) ).

Here are my observations and thoughts about wasm.

* wasm can be very fast. I have seen up to 25 times faster than JavaScript on some image processing algorithm (convolution). I am talking about the same algorithm written in JavaScript and then rewritten in C then compiled with emscripten into wasm. But for your information, emscripten can also generate some optimized JavaScript which is "only" 2 times slower than wasm for the convolution algorithm and that surprisingly can be faster for some other algorithms. But, as always with performance, that depends a lot on the context. My conclusion is that wasm promise of speed is fullfilled, but JavaScript engines are also very optimised and perform very well. So there is no clear win.
* wasm files can be very small. As already noted it is in fact one of the requirements of the MVP. But some wasm file created by emscripten can be very big (as in the Blazor example) in part because emscripten can bring some code for standard library.
* One of the core advantage of wasm, is as a compilation target. With emscripten you can bring legacy C/C++ code base into the browser. This is what is done for Google Earth, for AutoCad, for some game, etc. But often it is for lower parts of the code (like physics engine), not the actual display code.
* I agree that, for now, there can be some overhead on calling wasm from JS or JS from wasm, and so on manipulating DOM from wasm.
* The first identified use cases that can clearly benefit from wasm are not the UI ones.

So, with my experience, for now I guess that wasm is not a very good candidate for performance improvement for Vue.js. But as note by @OlzhasAlexandrov, everything is moving. It is a new technology and things can improve in the future. If one want to go this path, I guess the best it to first identify some bottlenecks of Vue.js by measuring things and check if wasm can be a good candidate to improve performance by doing some experiments.

But for me, as I said, the killer feature of Vue.js is its simplicity. So I prefer a slightly slower solution but very easy to use, than a very fast one that is more complex. And if wasm is used, it means there will be an other development technology (walt or something else), which comes with maintenance cost for the dev team. So there will be some compromises to do between all that.

**Comment by Dwood15** [comment] 2018-05-18 17:59
Vue.js [already has typescript support](https://vuejs.org/v2/guide/typescript.html), I wonder how much it would take to work [assembly script](https://github.com/AssemblyScript/assemblyscript) into vue as an option?

This may be somewhat offtopic to the issue, but as someone who really likes to use Vue, I would certainly enjoy taking the paradigm/framework into the context of a 3d game's ui... While that would take ton of effort... it would be interesting to be able to use the vue paradigm to compose and interact with WebGL-ui's via something like an html canvas or [offscreen-canvas](https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas)

**Comment by Dwood15** [comment] 2018-05-21 03:53
I've spent some more time thinking about this topic, and want to add some extra thoughts before I lose them.

After considering my personal experiences using Vue, I have a hard time believing the bottleneck for Vue is in the JS DOM api. Are there benchmarks showcasing this? My personal experience is that you're not using Vue for the performance, you're using it because it makes designing ui an elegant experience. 

Runtime type-checking of props, the ridiculous callstack depth of exceptions, it's still all on the same thread, and more, seem to be leaning against it.

I wonder if the wasm -> js interop layer would be such a slowdown. honestly, I'm with the Vue core team - not really sold on wasm being a performance boon to Vue.

@OlzhasAlexandrov - if you want to help Vue make a jump to Wasm, we need benchmarks. Just because wasm speeds up some expensive image processing doesn't mean Vue's bottlenecks are the same.

@the core team: You really can't underestimate the power of built-in run-time type-safety that wasm could give Vue. Manually checking with typeof and instanceof really isn't ideal.

Potential for other performance boosts on the other hand, might possibly include using Vuex in a wasm environment, via web workers. While it's theoretically possible, I don't know if anyone has tried.

**Comment by OlzhasAlexandrov** [comment] 2018-05-21 12:33
In short, look how bad it [vue-server-renderer](https://github.com/vuejs/vue/blob/dev/src/server/bundle-renderer/create-bundle-renderer.js) is for serverless is:
1. First, cold start, triggers huge JSON parsing with a lot of `typeof` checks.
I am sorry for all devs who are using it, including myself.

Imagine how great it would be, if we compile it to wasm.

**Comment by OEvgeny** [comment] 2018-05-23 11:22
So, another 2 cents.

> In short, look how bad vue-server-renderer (link to source) is for serverless:

Just to me this statement does not answer the question: "Why WebAssembly should be used to address mentioned issues?". In fact issue description also doesn't. Just because there are only assumptions about WebAssembly capabilities/strong-sides (less bytes, more performant) and examples unrelated to usecases meet in Vue.

I believe there are better ways for fixing mentioned issues without utilizing WebAssebly. 

As for WebAssembly integration, lets take a look at [Glimmer](https://github.com/glimmerjs/glimmer-vm) as an example (which is nearly close to Vue in its goals). They built a compiler to compile handlebars templates into binaries for Glimmer VM. This aims to increase both network and DOM updates performance. The compiler and VM are (still?) written in TypeScript. As far as I know there are only plans for WebAssembly version. Please note that templating-engine is only the part of whole thing. So you already have a clue how much effort is needed to achieve such goal. I mean it is not possible to just replace one compiler with another to get WebAssembly binaries in place of JavaScript sources. It's a lot of work (for nearly no viable reason imho).

If anyone sees possible path for Vue to implement such integration, I guess it's very welcome to discuss though.

**Comment by OlzhasAlexandrov** [comment] 2018-05-23 14:43
@OEvgeny 
There have been so many already highlighted:
- benefits of migrating to WebAssembly 
- cons of current approach for SSR
so not to continue repeating the same things over again, I will build on what has been previously said:

I suggest not to try to rewrite or use AssemblyScript for the whole Vue ecosystem at once.
Rewriting a small package for a SSR function, [vue-server-renderer](https://github.com/vuejs/vue/blob/dev/src/server/bundle-renderer/create-bundle-renderer.js), is a primitive task to start with.

It is a common approach to divide a big project into a bunch of small pieces.
Experimenting on a small package from the Vue.js ecosystem is a good starting point.

**Comment by kripken** [comment] 2018-05-23 20:07
> As for WebAssembly integration, lets take a look at Glimmer as an example[..] As far as I know there are only plans for WebAssembly version.

There is a PR for porting an initial small part of Glimmer to Rust/wasm: https://github.com/glimmerjs/glimmer-vm/pull/752 My understanding is that part is mostly done, but it is waiting for a dependency (wasm2asm in binaryen, which will allow it to run in browsers like IE11 that lack wasm support). The dependency should be ready soon, so it's possible we'll see wasm adoption in Glimmer at that point.

**Comment by OEvgeny** [comment] 2018-05-24 09:55
> There is a PR for porting an initial small part of Glimmer to Rust/wasm

Great news! Very happy for Glimmer team. As PR title says "Initial stab at porting `asm/stack.ts` to Rust", I think there are a lot related to Rust/wasm changes as PR is quite big. Maybe things will go smoother with AssemblyScript/walt. Anyway any example on AssemblyScript /walt integration with existing js production-ready project/library is really appreciated.

> Rewriting a small package for a SSR function, vue-server-renderer, is a primitive task to start with.

I'm not sure it is so, maybe if you're smart enough.

**Comment by mihail-shishkov** [comment] 2018-05-27 21:00
Blazor's story is entirely different. Blazor runs on top of Mono (.net runtime) that is compiled to WASM. It actually executes real .NET assemblies/dlls in interpreter mode. It interprets MSIL and the guys building it have stated many times that this will be addressed. Mono team (Miguel de Icaza, creator of Xamarin and Mono) are working on ahead of time compilation that will make possible compiling blazor apps straight down to WASM. Currently the entire .NET "VM" is downloaded with the app itself + some standard libraries that have plenty of meaningless code in them like File IO (which does not make sens in the browser). That's why it is >1MB in size. When things are optimized enough I am pretty sure that the same app written in angular and blazor will be smaller in blazor and will run faster in blazor (given that angular has not switched to wasm). You may want to take a look at this one https://github.com/koute/stdweb which is a way to manipulate the DOM with Rust. No interpreting or VM or VM here just plain WASM.

**Comment by fnlctrl** [comment] 2018-05-27 22:10
@mihail-shishkov Would you please build a stdweb demo (namely, the todomvc example) and put it here? The repo doesn't include a pre-built one and I can't seem to get the demo to compile on my windows machine. I guess it's also too much of a hassle for people who just want to see a demo to install the complete rust toolchain.

**Comment by fnlctrl** [comment] 2018-05-29 08:08
So I installed a ubuntu vm and rust toolchain, and finally built the stdweb todomvc demo:
![image](https://user-images.githubusercontent.com/5557143/40644200-02813540-6355-11e8-827d-ddf17998a02c.png)

For now, that's 6KB js + 430KB wasm, for a todomvc demo. (and 6KB js + 131KB wasm = 137KB gzipped)

And compared to [vue's todomvc demo](https://fiddle.jshell.net/yyx990803/4dr2fLb7/show/light/), 2KB gzipped js + 22KB gzipped runtime, that's 522% bigger in size.

Perhaps it wasn't a complete waste of 2 hours to setup a rust env and compile that demo, since at least I confirmed by assumption by actually trying it out. I'll just leave the built demo [here](https://drive.google.com/open?id=1X0U4X5yteuvzGSuIjoMaLSkgcYZVRQ5H). See it for yourself.

Yes of course, it's still "experimental". I guess we'll have to wait to see that "size advantage" in the future, perhaps Soon™.

As for performance, there's no difference at all since the todomvc demo is too simple. Below are the timeline for adding a todo item.
Vue:
![image](https://user-images.githubusercontent.com/5557143/40645558-48096bb0-6359-11e8-81b5-1a48200b38a1.png)

stdweb: 
![image](https://user-images.githubusercontent.com/5557143/40645571-532c42ec-6359-11e8-8dbc-4b8d1c60025d.png)

I guess we'll have to wait for a more complex demo to find out. For now, I'll just keep assuming wasm won't bring much performance improvement to traditional applications that heavily uses DOM APIs to draw the UI.

**Comment by Dwood15** [comment] 2018-05-29 15:28
@fnlctrl did you miss the whole part where they mention that "Currently the entire .NET 'VM' is downloaded with the app itself" ?

I mean, @mihail-shishkov literally just said it downloads the entire .net vm which then executes full, real .NET assemblies. to go ahead and conclude that wasm will bring no performance improvements in this scenario seems misguided.

**Comment by liangzeng** [comment] 2018-06-09 11:57
In most cases, extreme performance is not a requirement, and a skilled programming language and ecology are important.

Fragmentation of technology should be avoided, so we can use https://github.com/AssemblyScript/assemblyscript for performance-related attempts.

**Comment by EqualMa** [comment] 2019-01-07 19:25
I agree with you. Server side may improve much performance if computing modules are warm. (In fact browser side is not so important when talking about performance. ) Thankfully vue 3 will be in typescript and will be splitted to many small modules so it may be easy to extract computing modules and compile to warm with AssemblyScript.

**Comment by marcoippolito** [comment] 2019-12-23 08:50
Hi all,
i'm struggling to understand what to set in webpack configuration and in vue.config.js, and how to split the generated js code. 
Do you have any working example of using webassembly code in conjunction with vue.js?

**Comment by marcoippolito** [comment] 2019-12-26 05:53
This example https://www.mirkosertic.de/blog/2018/12/webassembly-and-vuejs/ is Java-related since Bytecoder is for Java. Is there a similar example for C++ / C ?

**Comment by marcoippolito** [comment] 2019-12-30 11:09
@OEvgeny @EqualMa @zalelion would you be so kind in having a look a this thread about webassembly in vue.js?  https://github.com/emscripten-core/emscripten/issues/10114

The author of the book "WebAssembly in Action" is kindly trying to figure out how to make wasm working within Vue.js, but, since he has no experience with Vue.js, I ask you to have a loot at it. 

Thank you very much

**Comment by posva** [comment] 2021-06-03 13:28
Closing as this has become inactive and there isn't any intention to migrate to web assembly a library like Vue

**Closed by posva** 2021-06-03 13:28 UTC
Labels: discussion
