### ISSUE TITLE
Existing class not removed in v1.0.19+

### ISSUE THREAD

**Issue by fergaldoyle** [vuejs/vue#3048] opened 2016-06-09 15:33 UTC
### Vue.js version
1.0.19

### Reproduction Link
Example using v1.0.19 (not working as expected)
https://jsfiddle.net/ps6vrun1/1/

Example using v1.0.18 (working as expected)
https://jsfiddle.net/jhapcwy1/1/

### Steps to reproduce
Add a class to an element, and also a binding which will toggle the class
`<div class="loader" :class="{'loader': hasClass}">`

### What is Expected?
class `loader` should be removed when `hasClass` is `false`

### What is actually happening?
class `loader` remains on the div when `hasClass` is `false`

**Comment by simplesmiler** [comment] 2016-06-10 07:14
Duplicate of https://github.com/vuejs/vue/issues/2597 (wontfix)
> If you want the class to be controlled by Vue then you shouldn't put the static class there in the first place.

**Closed by simplesmiler** 2016-06-10 07:14 UTC
