### ISSUE TITLE
components transtion-group is not able to distribute props to the components which declared by the tag props.

### ISSUE THREAD

**Issue by misakamaiyako** [vuejs/vue#7382] opened 2018-01-04 10:38 UTC
### What problem does this feature solve?
for example,there is a row component which includes some cols,i wanna the cols have transition effect,and give row some props.But ,the props i wrote does no effect on the row component.and if i use 'row > transtion-group' combination, some css will lose there effect

### What does the proposed API look like?
<transtion-group type=row :option={row's props}></transtion-group>

**Comment by posva** [comment] 2018-01-04 11:43
Duplicate of #5095

**Closed by posva** 2018-01-04 11:43 UTC
