### ISSUE TITLE
Unable to build Vue on Windows using npm/yarn run build

### ISSUE THREAD

**Issue by remcohuijser** [vuejs/vue#4338] opened 2016-11-29 16:12 UTC
### Versions
Vue.js = 2.0.2
Node.js = 6.9.1
NPM = 4.0.2
Windows 10

### Steps to reproduce
- Clone repo from GitHub
- npm install
- npm run build

or
- Clone repo from GitHub
- yarn install
- yarn run build

### What is Expected?
The expected behavior is that all versions of vue are build in the dist folder.

### What is actually happening?
Error: Could not load C:\Development\github\vue\src\core/index (imported by C:\Development\github\vue\src\entries\web-runtime.js): ENOENT: no such file or directory, open 'C:\Development\github\vue\src\core\index'
at C:\Development\github\vue\node_modules\rollup\dist\rollup.js:8833:10
at process._tickCallback (internal/process/next_tick.js:103:7)
at Module.runMain (module.js:606:11)
at run (bootstrap_node.js:394:7)
at startup (bootstrap_node.js:149:9)
at bootstrap_node.js:509:3

### Workaround
It appears that all imports that use the aliases defined in build/alias.js file do not work when the extension .js is not used. When .js is added to all imports, the build succeeds.

**Comment by defcc** [comment] 2016-11-30 03:39
Seems to be a bug of `rollup-plugin-alias`. https://github.com/frostney/rollup-plugin-alias/issues/11

**Comment by yyx990803** [comment] 2016-11-30 04:06
Closing since the source of the issue is in a dependency, and is not a bug in the framework itself.

**Closed by yyx990803** 2016-11-30 04:06 UTC

**Comment by fenduru** [comment] 2017-08-04 19:31
I'm trying to file a PR for Vue, but I cannot get it to build - is there any recommendation on how to move forward?
