### ISSUE TITLE
Scoped class leaks into children

### ISSUE THREAD

**Issue by ffxsam** [vuejs/vue#7548] opened 2018-01-28 07:15 UTC
### Version
2.5.13

### Reproduction link
[https://codesandbox.io/s/6yk5o1x573](https://codesandbox.io/s/6yk5o1x573)

### Steps to reproduce
In parent component, apply a scoped class to a div. In the child, name the class the same and make sure it's scoped, but use different CSS properties so there's no overwriting.

### What is expected?
I would expect scoped classes to actually be scoped.

### What is actually happening?
Scoped styles are leaking into the children. The divs are sharing 'data-v' attributes which is very bad.

**Comment by posva** [comment] 2018-01-28 10:19
Duplicate of https://github.com/vuejs/vue-loader/issues/957

**Closed by posva** 2018-01-28 10:19 UTC
