### ISSUE TITLE
Vue causes browser to become unresponsive when createElement is called with Promise-returning function

### ISSUE THREAD

**Issue by DanielRosenwasser** [vuejs/vue#6558] opened 2017-09-09 20:33 UTC
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/2pbthd1v/](https://jsfiddle.net/2pbthd1v/)

### Steps to reproduce
When calling `createElement`, pass a function that returns a promise which resolves to a Vue options bag.

For example:

```html
<div id="app">
  <p>{{ message }}</p>
</div>
```

```ts
var options = {
  template: '<div id="replacement">Hello!!</div>',
}

new Vue({
  el: "#app",
  render(h) {
    return h(() => new Promise(r => r(options)));
  }
});
```

### What is expected?
Either something useful or an error message.

### What is actually happening?
The entire page stops responding.

---
This was part of [the .d.ts test suite](https://github.com/vuejs/vue/blob/e51c0c0e68c53363caaf7f5893460a360b0e6bd7/types/test/options-test.ts#L99-L103). I wanted to see if a test case was legitimate, but I ended up finding that it triggers some sort of bad behavior.

**Comment by HerringtonDarkholme** [comment] 2017-09-10 15:39
Thanks! This is a valid bug. It freezes browsers and node.

**Comment by posva** [comment] 2017-09-10 15:46
I don't think it is a bug, `createElement` isn't meant to work with Promises, right?

**Comment by HerringtonDarkholme** [comment] 2017-09-10 15:47
It doesn't matter if we need to accept Promise as API. We should not freeze browser or node server when users give Vue wrong input.

**Comment by posva** [comment] 2017-09-10 16:13
Oh, yeah I agree with that, it should be fixed if possible, it's unreasonable to freeze the platform 😆 . The reason I'm saying it's not a bug is because from my perspective a bug is a situation not working while it should

**Comment by HerringtonDarkholme** [comment] 2017-09-10 16:20
Preliminary investigation shows Vue relies on **the function**  as context to resolve async component.

In this case, render function will always return a new function instance so the handle Vue attaches to the async component function is lost. So Vue will think the component isn't properly resolved.

The fix is simple, move the inline arrow function outside, with a stable identifier `var asyncComp = () => Promise.resolve(option)` will fix this. Because Vue can find the context it previously attaches to the function.

I guess really no one is using this API. Also the solution to fix it isn't clear to me :/

**Comment by yyx990803** [comment] 2017-09-13 01:54
Exactly what @HerringtonDarkholme said - when the Promise resolves, it will cause the current component to re-render, resulting in a new async factory function, thus entering an infinite update loop.

I also don't see a simple fix to this, but this is not supported usage anyway. I guess what we can do is documenting this behavior in the async component section?

**Closed by yyx990803** 2017-09-13 01:54 UTC
Labels: improvement

**Comment by blocka** [comment] 2017-12-27 11:57
Is there a workaround? I have a use case where I want to dynamically load a component based on data that is loaded, but I don't want to have to specify each component outright.

Something like:
```js
return h(() => resolveComponent(this.data))
```

**Comment by mandaputtra** [comment] 2018-10-28 12:37
Can it be documented or maybe log some error when its happen?
