### ISSUE TITLE
Cannot read property 'composing' of undefined

### ISSUE THREAD

**Issue by johnleider** [vuejs/vue#3213] opened 2016-07-03 01:37 UTC
### Vue.js version
2.0.alpha-8 / 7

### Reproduction Link

http://forum.vuejs.org/topic/4353/the-correct-way-to-use-twoway-directive-in-vue-2-0/3
### Steps to reproduce
Use the provided example
### What is Expected?
Update of value on the vm
### What is actually happening?
In genDefaultModel, code is set to a string $event.target.composing.  During the function call, $event has no target property.  Changing that line to ( "$event.hasOwnproperty('target') && $event.target.composing) allows it to continue, but then fails with cannot read property 'value' of undefined.

**Comment by sqal** [comment] 2016-07-03 11:14
Are you referring to [Select 2 example](https://github.com/vuejs/vue/blob/next/examples/select2/index.html) ? Please check Evan comment here https://github.com/vuejs/vue/issues/3179#issuecomment-229410710

As you can see, the syntax has changed a little bit, so select 2 example is up to date but $emit update  will be shipped in next alpha-9 release

**Comment by LinusBorg** [comment] 2016-07-03 11:18
Yep. The select example is alread updated to reflect the latest changes in the `next` branch, and in this case it's a breaking change for alpha-8 previous versions, as outlined in the comment that @sqal linked to.

If you clone the repo locally and check out the `next` branch, the example works as intended.

I will close this issue as this is not a bug.

**Closed by LinusBorg** 2016-07-03 11:18 UTC
