### ISSUE TITLE
v-if cannot access slot scope with new slot syntax

### ISSUE THREAD

**Issue by econic** [vuejs/vue#9862] opened 2019-04-11 09:44 UTC
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/s/7j9o6o4310?fontsize=14](https://codesandbox.io/s/7j9o6o4310?fontsize=14)

### Steps to reproduce
Use a component that defines a scoped slot like this
```
<MyComponent>
  <template v-if="scope.foo" #myslotname="scope">...</template>
</MyComponent>
```

### What is expected?
The template should evaluate the slot directive first, v-if second. Just as it is done with v-for first, v-if second.

### What is actually happening?
The template evaluates the v-if first, resulting in an error (unknown component property)

---
This functionality was present in the deprecated slot syntax, i stumbled upon it while refactoring to the new one.
It is possible to workaround this with a nested template with the respected v-if

I'm using latest Vue, TypeScript, SFC

**Comment by posva** [comment] 2019-04-11 11:14
I couldn't find the duplicate of this but this is now expected behaviour because the v-if has higher priority. As you said, using a nested template is the way to go

**Closed by posva** 2019-04-11 11:14 UTC
