### ISSUE TITLE
Custom Components slot content no trigger parent‘s touchstart event

### ISSUE THREAD

**Issue by wxkcoder** [vuejs/vue#10356] opened 2019-08-06 02:31 UTC
### Version
2.6.10

### Reproduction link
[https://github.com/wxkcoder/bugs_demo](https://github.com/wxkcoder/bugs_demo)

### Steps to reproduce
vue version：2.6.10
ios version：10.3.3 or 11.4
use safiri mobile browser

page A use 'this.$router.push({name:B})' Jump to Page B
Page B import component C
Component C bind a touchstart event
the problem is Component C use slot label Input content，click that content is dose not trigger C's touchstart event

Direct access to page B can trigger C‘s touchstart event
change ios version to 12.3.1 can trigger C‘s touchstart event
change vue version to 2.5.22 can trigger C‘s touchstart event

pleace try to run this demo https://github.com/wxkcoder/bugs_demo on ios 10.3.3

### What is expected?
no trigger

### What is actually happening?
trigger

**Comment by posva** [comment] 2019-08-06 06:34
Duplicate of https://github.com/vuejs/vue/issues/10348

Please stop opening the same issue again and again

**Closed by posva** 2019-08-06 06:34 UTC

**Comment by wxkcoder** [comment] 2019-08-06 06:38
My question hasn't been solved. Your answer is wrong.

**Comment by posva** [comment] 2019-08-06 06:59
As said previously, Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by wxkcoder** [comment] 2019-08-06 10:30
this is vue‘s bug

**Comment by wxkcoder** [comment] 2019-08-06 10:31
You didn't understand my question at all.

**Comment by wxkcoder** [comment] 2019-08-06 10:34
Can you change to someone who understands Chinese to look at this question?

**Comment by wxkcoder** [comment] 2019-08-06 10:38
> Duplicate of #10348
> 
> Please stop opening the same issue again and again

pleace try to run this demo https://github.com/wxkcoder/bugs_demo on ios 10.3.3

**Comment by wxkcoder** [comment] 2019-08-09 03:14
I'm so sorry，I said it wrong，this bug is runing in wxchat webview not safiri
