### ISSUE TITLE
Knowing what a component emits at a glance

### ISSUE THREAD

**Issue by MichaelJGW** [vuejs/vue#8953] opened 2018-10-15 16:33 UTC
### What problem does this feature solve?
When managing components it is important to have all the information you can interact with at a glance.
In general, a component has two primary interactions props it takes and events it emits.

We have the ability to know at a glance for Props as you can go to the props section of the component and you know with 100% certainty which props are available, the types of the props if they are required, and so on.
We do not have this same ease when it comes to what events a component can emit.
We have $emit for a component but this can be anywhere in the component and it is not a streamlined process. With this being the nature of $emits we lose the ability to know at a glance.

It would be nice to extend the component structure to include an emits section that if included Vue throws an error if an $emit event happens that has not been listed. This can also we extended to include types.
 

### What does the proposed API look like?
```
Vue.component('addOne',{
  template: `<button v-on:click="add()">Add One</button>`,
  props: {
    num: {
      type: Number,
      required: true
    }
  },
  emits: {
    result: {
      type: Number
    }
  },
  methods: {
    add () {
      this.$emit('result', this.num + 1)
    }
  }
})
```

**Comment by posva** [comment] 2018-10-15 17:57
Duplicate of #6040

**Closed by posva** 2018-10-15 17:57 UTC
