### ISSUE TITLE
when use vue2.0 and bootstrap-datepicker, and use  v-model can not get the date value.

### ISSUE THREAD

**Issue by 15992033543** [vuejs/vue#4231] opened 2016-11-17 06:42 UTC
[https://jsfiddle.net/gLfesj48/](url)

**Comment by fnlctrl** [comment] 2016-11-17 06:49
Hi, thanks for filling this issue. Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) and provide a live reproduction on jsfiddle, codepen etc. Thanks!

**Comment by yyx990803** [comment] 2016-11-17 14:08
The fiddle isn't working, but it's most likely due to `bootstrap-datepicker` only triggering a jQuery change event instead of a real `change` event.

**Comment by Xelia** [comment] 2016-11-17 14:50
I use bootstrap datepicker with vue like this: https://jsfiddle.net/3a2055ub/

**Comment by yyx990803** [comment] 2016-11-18 14:52
This is a wontfix for 2.0. Although we catered for it in 1.x, I don't think it makes sense for us to cater for the behavior of arbitrary 3rd party libraries - especially when there's a workaround like @Xelia's.

**Closed by yyx990803** 2016-11-18 14:52 UTC
Labels: need repro

**Comment by granda** [comment] 2016-11-18 14:58
Sorry to tack onto a closed issue but it's context related.

@yyx990803 Is using `$("#startDate")` the optimal way to target an element within `mounted()`? Should we be using something similar to `refs` like in React?

**Comment by simplesmiler** [comment] 2016-11-18 15:20
@granda there is [`ref`](https://vuejs.org/v2/api/#ref) (`v-ref` in 1.0) exactly for that purpose. It's substantial most of the time, but not always.

**Comment by sinaza** [comment] 2018-03-23 15:25
After making the `datepicker` work I ran into another issue that is worth noting. I don't wanna see anyone suffer like I did!

So here is the situation, the application has a button that makes something true, then a `v-if` shows a second `datepicker` based on that true value. The `mounted()` doesn't trigger again and second `datepicker` shows the same weird behavior that we are discussing here! The workaround is to change `v-if` with `v-show`, so that `mounted()` works for it in the first place.
