### ISSUE TITLE
bind async property

### ISSUE THREAD

**Issue by hainee** [vuejs/vue#11789] opened 2020-11-24 02:15 UTC
### What problem does this feature solve?
Can vuejs support binding of asynchronous properties?

### What does the proposed API look like?
var data = {}
Object.defineProperty(data, 'asyncProperty', {
  async get() {
    // async network or database query
    return true;
  }
});

**Comment by posva** [comment] 2020-11-24 08:12
Duplicate of https://github.com/vuejs/vue/issues/7520

**Closed by posva** 2020-11-24 08:12 UTC
