### ISSUE TITLE
Parent class style not getting applied on functional SFC child

### ISSUE THREAD

**Issue by benmandr** [vuejs/vue#11257] opened 2020-03-27 16:56 UTC
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/s/quizzical-hooks-flxdp](https://codesandbox.io/s/quizzical-hooks-flxdp)

### Steps to reproduce
No steps. Just check out the reproduction.

### What is expected?
The class styles in App.vue to be applied on the functional SFC.

### What is actually happening?
Parent class is added to the classlist of child, but the css is not generated for the class.

---
If you remove the 'scoped' keyword from functional component, then all the styles are applied. But the need is to use this with scoped styles, as with normal components is done.

**Comment by posva** [comment] 2020-03-27 20:34
Duplicate of https://github.com/vuejs/vue-loader/issues/1136

**Closed by posva** 2020-03-27 20:34 UTC
