### ISSUE TITLE
Shorthand attribute/prop syntax

### ISSUE THREAD

**Issue by jasonlfunk** [vuejs/vue#7144] opened 2017-11-28 07:36 UTC
### What problem does this feature solve?
I often find myself writing code like this:

`<component :data='data' :name='name' :email='email'></component>`

This code is redundant and isn't fun to write. 

### What does the proposed API look like?
Using es6 [Object Literal Shorthand](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer) as inspiration, the component could instead be written like this:

`<component :data :name :email></component>`

**Comment by posva** [comment] 2017-11-28 07:41
Duplicate of #5835

**Closed by posva** 2017-11-28 07:41 UTC
