### ISSUE TITLE
Merging of HTML classes via class attribute and v-bind broken

### ISSUE THREAD

**Issue by janschoenherr** [vuejs/vue#3382] opened 2016-08-03 15:30 UTC
### Vue.js version

1.0.26
### Reproduction Link

http://jsfiddle.net/d3xwtrqn/
### Steps to reproduce

As shown in the jsfiddle: The combination of a `class` attribute and the dynamic `:class` leads to a merged class attribute. However using v-bind does not.
### What is Expected?

Both ways should merge correctly.

**Comment by vuchl** [comment] 2016-08-03 20:38
If you do [`:v-bind`](http://jsfiddle.net/tcf7urnu/2/) instead of `v-bind` it works. Also [`v-bind:class=classes"`](http://jsfiddle.net/tcf7urnu/3/) works

**Comment by iagafonov** [comment] 2016-08-03 20:48
`v-bind="..."` will not work, it'is not supported as i know. Shorthand for this is `:="..."` :-). It should be `v-bind:<attribute>="..."` this is not a bug

**Comment by iagafonov** [comment] 2016-08-03 20:54
`:v-bind` is element attribute 'v-bind' binding to value, like binding 'data-something'. I have thought that it is possible =D

**Comment by LinusBorg** [comment] 2016-08-03 21:00
As explained by @iagafonov this is not a bug, but a template syntax error on OP's part.

I'm therefore closing this.

**Comment by yyx990803** [comment] 2016-08-03 21:26
`v-bind` does support binding an object, so the original fiddle is using it as intended.

**Comment by LinusBorg** [comment] 2016-08-03 21:42
Oopps.

This is the second time in a few hours that I found out something new about a Vue feature of which I thought I knew everything...

**Comment by dschnare** [comment] 2017-09-26 21:01
This appears to be fixed as of v2.4.4: http://jsfiddle.net/d3xwtrqn/5/

**Comment by LinusBorg** [comment] 2017-09-26 21:54
This issue is about the 1.x branch, not 2.x

**Comment by yyx990803** [comment] 2018-04-17 21:38
Closing 1.x issues as 1.x is now end of life and will only receive critical security patches.

**Closed by yyx990803** 2018-04-17 21:38 UTC
Labels: 1.x, bug
