### ISSUE TITLE
npm run build fails on compiling to npm package for vue 2.7.13

### ISSUE THREAD

**Issue by PumpkinBW** [vuejs/vue#13041] opened 2023-06-29 01:50 UTC
### Version
2.7.13

### Reproduction link
[github.com](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)

### Steps to reproduce
git clone https://github.com/vuejs/vue/tree/v2.7.13

yarn at root of project

npm run build at root of project

following these steps outlined here
https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md

### What is expected?
the entire Vue NPM package should exist and be built into [root]/dist

### What is actually happening?
npm run build

vue@2.7.13 build
node scripts/build.js

node:internal/modules/cjs/loader:944
throw err;
^

Error: Cannot find module '@vue/consolidate/package.json'
Require stack:

**Comment by posva** [comment] 2023-06-29 07:17
Duplicate of https://github.com/vuejs/vue/issues/13040

**Comment by posva** [comment] 2023-06-29 07:17
Please, search existing issues and pull requests before opening issues, it saves maintainers a lot of time 🙏

**Closed by posva** 2023-06-29 07:17 UTC
