### ISSUE TITLE
svg path tags not support

### ISSUE THREAD

**Issue by Jokcy** [vuejs/vue#2819] opened 2016-05-09 12:34 UTC
### Vue.js version
1.0.21

### My code here
my svg-icon component:
```
<template>
  <svg viewBox="0 0 24 24"
       preserveAspectRatio="xMidYMid meet"
       fit
       :style="style">
    <g v-if="path"><path :d="path"/></g>
    <slot v-if="!path"></slot>
  </svg>
</template>

<script type="text/babel">
  export default {
    props: {
      path: {
        type: String,
        default: ''
      },
      size: {
        type: Number,
        default: 24
      }
    },
    computed: {
      style () {
        return {
          fill: 'currentcolor',
          verticalAlign: 'middle',
          width: this.size,
          height: this.size
        }
      }
    }
  }
</script>
```
and sometimes I want to use it like this:
```
<template>
  <svg-icon :size="size">
    <circle cx="6.181" cy="4.063" r="2.591"></circle>
    <path d="M.6 12.202a5.614 5.614 0 0 1 11.228 0"></path>
    <g>
      <circle cx="11.98" cy="6.993" r="1.569"></circle>
      <path d="M12.24 12.202c.018-1.853-.625-2.927-1.35-3.495-.29-.227.721-.185 1.11-.185 1.877 0 3.4 1.802 3.4 3.68"></path>
    </g>
  </svg-icon>
</template>

<script>
  import svgIcon from '../icon/icon.vue'
  export default {
    props: ['size'],
    components: {
      svgIcon
    }
  }
</script>
```

### What is Expected?
I expect both pass a path props and slot is OK

### What is actually happening?
slot is not OK, and path props seems fine.

the warn showed when use slot
*vue.common.js?e881:987[Vue warn]: Unknown custom element: <g> - did you register the component correctly? For recursive components, make sure to provide the "name" option.*

**Comment by posva** [comment] 2016-05-09 13:09
Hi, this is a duplicate of #2726

**Closed by posva** 2016-05-09 13:09 UTC
