### ISSUE TITLE
contents(not Component) in slots early rendered?

### ISSUE THREAD

**Issue by dongivan** [vuejs/vue#4667] opened 2017-01-06 05:49 UTC
### Vue.js version
2.1.8

### Reproduction Link
first: [https://jsfiddle.net/6zb7d5xh/](https://jsfiddle.net/6zb7d5xh/)
second:[https://jsfiddle.net/t2qk8rxm/](https://jsfiddle.net/t2qk8rxm/)

### Steps to reproduce
just open the two jsfiddle

### What is Expected?
it will show "We have 4 items!"  after 3 seconds u click Run button

### What is actually happening?

firstly, sorry for my poor english.

in the frist jsfiddle, codes run successfully and will show "We have 4 items!"  after 3 seconds u click Run button. 
in the second jsfiddle, codes run failed. there will be a TypeError because we try to read the property 'length' of null.

the difference between these two jsfiddles is in line 25: in the first jsfiddle i put a Bar component in the slot of Foo, and in the second one it is "{{ items.length }}" instead of the Bar component. 
Bar component only render a "{{  items.length }}" and do nothing else, however there are different behaviors.
 if u change line 28 of 2nd jsfiddle to "items: []", it will run successfully. it is clearly that Vue reads the properties before sending the slot fragment to Components(so that u can set null to Bar, and because of 'v-if' in Foo, Bar will not be rendered until we set a array to its items. but u cannot output a property of null). i guess there is a bug or special design on the behavior of slot?

**Comment by HerringtonDarkholme** [comment] 2017-01-06 06:38
Thanks for using Vue.

The second example breaks as intended. The reason is quite similar to [compilation scope](https://vuejs.org/v2/guide/components.html#Compilation-Scope). That is, a component in slot must be compiled in the parent **template** . And then the slot content can be fed to container component, in this case, `Foo`.

The first example works because you pass null as props to `Bar` component, where Vue guards against runtime error.

So the example here is by design. Thanks for your understanding.

**Comment by posva** [comment] 2017-01-06 10:28
@HerringtonDarkholme Should we close this issue, then?

**Closed** 2017-01-06 10:44 UTC
