### ISSUE TITLE
Vue strips methods from sub classes of Arrays.

### ISSUE THREAD

**Issue by ajmar** [vuejs/vue#10751] opened 2019-10-24 01:57 UTC
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/mpqx6y8r/2/](https://jsfiddle.net/mpqx6y8r/2/)

### Steps to reproduce
Run the JSFiddle with the browser console open.

A `created` hook on the Vue component will attempt to log to the console the return value of `this.Pet.getSpecies()` and `this.WaitingList.frontPerson()`.

However, Vue will fail the second call since this array method (class ExtendArray extends Array) has been stripped during data registration. The same does not happen with plain Objects (class ExtendObject extends Object).

### What is expected?
Console output:

'Pet: Dog',

'WaitingList: Jack'

### What is actually happening?
Console output:

'Pet: Dog',

'TypeError: this.WaitingList.frontPerson is not a function'

**Comment by posva** [comment] 2019-10-24 02:58
Duplicate of https://github.com/vuejs/vue/issues/9259

**Closed by posva** 2019-10-24 02:58 UTC
