### ISSUE TITLE
Computed properties context broken if prop with type array exist [TypeScript]

### ISSUE THREAD

**Issue by ondrej-janosik** [vuejs/vue#8421] opened 2018-06-27 14:39 UTC
### Version
2.5.16

### Reproduction link
[https://github.com/ondrej-janosik/vue-bug-props/blob/master/src/App.vue](https://github.com/ondrej-janosik/vue-bug-props/blob/master/src/App.vue)

### Steps to reproduce
1) Create a new project with VUE CLI, just add typescript
![image](https://user-images.githubusercontent.com/18070427/41981037-4a4b4282-7a28-11e8-812b-168bf93f5734.png)
2) Open is VS code
2) Create a property in data in App.vue
![image](https://user-images.githubusercontent.com/18070427/41981060-5765ff02-7a28-11e8-88df-154083375ef4.png)
3) Access this property in a computed method - works
![image](https://user-images.githubusercontent.com/18070427/41981083-62836e10-7a28-11e8-8d61-0a83ee132e93.png)
4) Add prop with type array
![image](https://user-images.githubusercontent.com/18070427/41981104-6ac55822-7a28-11e8-898e-4681c0087410.png)
5) Computed property context is broken - not work
![image](https://user-images.githubusercontent.com/18070427/41981194-9e4c6f78-7a28-11e8-8cf7-c114e3ab36d6.png)
6) Change prop type to for example to object - works
![image](https://user-images.githubusercontent.com/18070427/41981213-a92b4f22-7a28-11e8-89f2-d61da38bc687.png)

### What is expected?
A computed property should have the same context even if prop with type array is presented

### What is actually happening?
Computed property context is missing

**Comment by sodatea** [comment] 2018-06-27 17:59
Duplicate of #8406 #6841
Please keep an eye on #6856 - we'll start merging pull requests soon.

**Closed by sodatea** 2018-06-27 17:59 UTC
