### ISSUE TITLE
Transition with appear hook set at component level 

### ISSUE THREAD

**Issue by Twinpix** [vuejs/vue#6868] opened 2017-10-20 10:40 UTC
### Version
2.5.2

### Reproduction link
[https://jsfiddle.net/Twinpix/sfjhLcxw/](https://jsfiddle.net/Twinpix/sfjhLcxw/)

### Steps to reproduce
Click on showA or showB button to see which transition hooks is fired

### What is expected?
When clicking on showA or showB button, appear hooks should be fired first on the first time the component is loaded 

### What is actually happening?
On transition, enter hooks are the only ones fired

---
I need this feature because for my projects I need a different animation/transition when a component is first loaded. I'm using vue-router to load component so I put the issue for vue-router, but now I realized it-s more a vue issue. thanks for help.

**Comment by posva** [comment] 2017-10-20 12:42
Do not open the same issue in both repos please.
Duplicate of vuejs/vue-router#1839

---

You could save somewhere the state about _is it the first time this component has appeared_ to trigger different transitions. You can even put that into a custom component that uses a transition component

**Closed by posva** 2017-10-20 12:42 UTC
