### ISSUE TITLE
render function called when nothing has changed

### ISSUE THREAD

**Issue by fenduru** [vuejs/vue#3499] opened 2016-08-22 21:23 UTC
### Vue.js version
2.0.0-rc.3

### Reproduction Link
https://jsfiddle.net/z4n5vw60/

### Steps to reproduce
Click the "increment" button and observe console

### What is Expected?
Neither `Foo` nor `Bar` components should re-render, as none of their properties or children have changed.

### What is actually happening?
The `Bar` components are re-rendered.

**Comment by jingman** [comment] 2016-08-23 01:51
I was just headed here to report what is probably the same issue, so I'll add in my findings in case it helps.

I noticed a `<select>` dropdown was flickering, even though its model and options were unchanged. Vue's `setSelected` function was being fired for the `<select>`, and causing a repaint.

http://jsfiddle.net/jingman/85b96530/2/

![repaint](http://i.giphy.com/l0MYI0k4NxtTfidDq.gif)

It seems that if a _different_ object's properties are being rendered to the page (`bar.name` in my fiddle), and _that_ object is _replaced_, the `<select>` will be re-rendered.

If you just change the prop, it doesn't trigger the re-render.

**Comment by fnlctrl** [comment] 2016-08-23 02:03
@jingman I've tested on chrome on windows, doesn't reproduce the bug. So I guess it's safari-related.

**Comment by jingman** [comment] 2016-08-23 02:07
@fnlctrl I'm on Chrome for Mac Version 52.0.2743.116 (64-bit)

Oddly enough, my issue actually _doesn't_ occur in Safari :wink:

**Comment by fnlctrl** [comment] 2016-08-23 02:16
That's odd indeed.. Further tested on Firefox 48.0.1 x64 -> bug
and Edge 38.14393.0.0 -> no reproduction

**Comment by LinusBorg** [comment] 2016-08-23 07:50
I think this is not a bug (talking about the original post's fiddle). 

Components which use `$slots` have to be re-rendered when the parent changes, because the content of `$slots` could have changed.

**Comment by LinusBorg** [comment] 2016-08-23 07:52
@jingman please open a new issue for our reported problem, it's certainly something entirely different.

I will close this issue as the OPs problem is not a bug, but expected behaviour.

**Closed by LinusBorg** 2016-08-23 07:52 UTC

**Comment by yintothayang** [comment] 2016-08-24 05:05
In your face Fee!
