### ISSUE TITLE
Dynamic Arguments not support to use uppercase

### ISSUE THREAD

**Issue by FutureElement** [vuejs/vue#10243] opened 2019-07-08 02:54 UTC
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/hataketed/m0t2ng8b/4/](https://jsfiddle.net/hataketed/m0t2ng8b/4/)

### Steps to reproduce
just run and see the console errors

### What is expected?
click alert

### What is actually happening?
vue.js:634 [Vue warn]: Property or method "eventname" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

(found in <Root>)
warn @ vue.js:634
vue.js:634 [Vue warn]: Invalid value for dynamic directive argument (expected string or null): undefined

(found in <Anonymous>)
warn @ vue.js:634
vue.js:634 [Vue warn]: Property or method "attributename" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

(found in <Root>)
warn @ vue.js:634
vue.js:634 [Vue warn]: Invalid value for dynamic directive argument (expected string or null): undefined

(found in <Anonymous>)

**Comment by posva** [comment] 2019-07-08 06:58
Duplicate of https://github.com/vuejs/vue/issues/9528

**Closed by posva** 2019-07-08 06:58 UTC
