### ISSUE TITLE
Using dynamic components with slots will produce an error warning

### ISSUE THREAD

**Issue by 2472289148** [vuejs/vue#10798] opened 2019-11-05 06:56 UTC
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/s/js-duixiangzhongdezhidushichangliang-u8lzg?fontsize=14](https://codesandbox.io/s/js-duixiangzhongdezhidushichangliang-u8lzg?fontsize=14)

### Steps to reproduce
Add a dynamic component with slots to tbody lable.

### What is expected?
Do not pop up error messages in the console.

### What is actually happening?
Although it works normally, an error is reported.

**Comment by posva** [comment] 2019-11-05 07:20
Duplicate of https://github.com/vuejs/vue/issues/10152

**Closed by posva** 2019-11-05 07:20 UTC

**Comment by 2472289148** [comment] 2019-11-05 09:58
> [＃10152的](https://github.com/vuejs/vue/issues/10152)重复[](https://github.com/vuejs/vue/issues/10152)
Hello, this is the first time I met a bug in the framework itself. I don't know how to solve it. I saw someone submit a branch to fix various problems, but I don't know whether there is a conflict between them. I want to find a Vue with less bug version for my project. What should I do?
