### ISSUE TITLE
VUE error in Safari 11

### ISSUE THREAD

**Issue by JonasKress** [vuejs/vue#8362] opened 2018-06-15 14:50 UTC
### Version
2.5.2

### Reproduction link
[https://wikidata-termbox.wmflabs.org/](https://wikidata-termbox.wmflabs.org/)

### Steps to reproduce
Open the link in Safari 11

### What is expected?
Language box should be rendered on top like on older versions of Safari and basically all other browsers.

### What is actually happening?
You only see statements section and error is thrown in console :
[Vue warn]: Error in render: "TypeError: undefined is not an object (evaluating 'this.$props.languagesSettings.get('term')[this.getCurrentLanguage()].title')"

---
Git repo: https://github.com/wmde/prototyp_mobile_termboox

**Comment by Justineo** [comment] 2018-06-15 15:35
I can't reproduce your problem in Safari 11. BTW the reproduction should be as concise as possible, it's not helpful if there is too much irrelevant code.

**Comment by EvanHahn** [comment] 2018-06-15 15:54
I was able to reproduce this on Safari 11.1.1.

**Comment by blake-newman** [comment] 2018-06-15 16:16
@JonasKress Have you tried using the latest minor version to see if this is fixed in a later version?

**Comment by sodatea** [comment] 2018-06-15 16:54
I don't think it's a Vue issue.

The root cause is in these two functions:
https://github.com/wmde/prototyp_mobile_termboox/blob/master/src/App.vue#L126-L213

While Chrome returns both `['en-US', 'en']` for `window.navigator.languages`, Safari 11 only returns `en-US`.
So your application will set the default language as `en-us` for Safari 11.

But the API response (`/wikidata/w/api.php?action=wbgetentities&format=json&ids=Q64&props=aliases%7Clabels%7Cdescriptions`) does not contain an `en-us` key (it has `en`, `en-gb`, `en-ca`, but no `en-us`), thus leading to this error.

**Closed by sodatea** 2018-06-15 16:54 UTC
