### ISSUE TITLE
VNode.elm missing for nested slots after component update

### ISSUE THREAD

**Issue by jkzing** [vuejs/vue#5427] opened 2017-04-13 03:54 UTC
### Version
2.2.6

### Reproduction link
[https://jsfiddle.net/jingkaizhao/f11tpysz/5/](https://jsfiddle.net/jingkaizhao/f11tpysz/5/)

### Steps to reproduce
1. open and run fiddle
2. open chrome devtool
3. click 'update' button
4. see result in console

### What is expected?
In updated hook, vnode inside slots children (this.$slots.default) should have a reference to its DOM element on property vnode.elm

### What is actually happening?
vnode.elm is undefined

---
Did some investigation on it. 
It just happened on nested component, (\<slot\> as children for another component). And it only happened after patching, it means in the initial stage (mounted hook), the vnode has correct reference to its DOM node, but after update (updated hook), the elm reference is missing.

**Comment by HerringtonDarkholme** [comment] 2017-04-13 17:03
It seems slot vnode will be copied across different components. So the vnode in nested copmonent is not updated. Still needs deeper investigation...

**Comment by yyx990803** [comment] 2017-04-18 04:12
This is somewhat expected behavior because slot nodes are shallow-cloned during render, so when `nested` passes the slot nodes down to `block`, `block` clones the slot nodes and then patches them (adding `.elm` in the process), however, the slot nodes in `nested` remain non-patched.

This is a wontfix because you should not be relying on `vnode.elm` in your render functions. This is not part of intended usage for vnodes.

**Closed by yyx990803** 2017-04-18 04:12 UTC
