### ISSUE TITLE
"functional" need special treatment in "compiler"

### ISSUE THREAD

**Issue by zhangshichun** [vuejs/vue#10050] opened 2019-05-20 02:19 UTC
### What problem does this feature solve?
in vue.js 2.0 ,we can return more then one VNode in render fucntion,but it's not support in template,even if we use "functional" in <template>:
for examples:
```
<script>
export default {
  functional: true,
  render(createElement, context) {
    const arr = context.scopedSlots.default()
    const suffix = createElement('span', 123)
    arr.push(suffix)
    return arr
  }
}
</script>
```
this is OK!

```
<template functional>
  <slot></slot>
  <span>123</span>
</template>
<script>
export default {

}
</script>
```
but this is not OK!
<template> should be consistent with render function if "functional" is an attr in <template>

### What does the proposed API look like?
```
<template functional>
  <slot></slot>
  <span>123</span>
</template>
```

**Comment by posva** [comment] 2019-05-20 07:40
Duplicate of https://github.com/vuejs/vue-loader/issues/1168

**Closed by posva** 2019-05-20 07:40 UTC
