### ISSUE TITLE
External SVGs not loading in Chrome when inside a <template> block

### ISSUE THREAD

**Issue by matkovsky** [vuejs/vue#2782] opened 2016-04-30 16:17 UTC
### Vue.js version
1.0.21

### Reproduction Link
http://matkovsky.com/vue-svg/
(The left icon is inside a `<template>` block, the right one is not.)

### Steps to reproduce
Put an `<svg>` tag with an external svg file (with symbols) inside a `<template v-if="foo === bar">` block.

### What is Expected?
The SVG should be there. (And it is there in Safari, Firefox, Opera, but not in Chrome.)

### What is actually happening?
The SVG is not loaded. Not even if the same symbol is already used on the site elsewhere.

----

I'm not entirely sure whether this is a Chrome bug or a Vue bug.

**Comment by Nirazul** [comment] 2016-04-30 16:27
I've quickly tried it out in a [fiddle](http://codepen.io/Nirazul/pen/xVQxNq).
When the svg is loaded within the HTML, it seems to work.

One solution you could try is changing the use tag to: `<use v-bind="{ 'xlink:href': '#' + symbol }"></use>`

**Comment by matkovsky** [comment] 2016-04-30 16:44
@Nirazul Yep, that works. Unfortunately that approach is not the right one for our current project.

**Comment by posva** [comment] 2016-05-01 08:50
Hello,

Have you tried using `href` without `xlink:`?

Otherwise you could set up a directive:
```js
export default {
  update (value) {
    let useEl = document.createElementNS('http://www.w3.org/2000/svg', 'use')
    useEl.setAttributeNS('http://www.w3.org/1999/xlink', 'href', value)
    this.el.innerHTML = ''
    this.el.appendChild(useEl)
  }
}
```
```html
<svg v-svg="'./icons.svg#cabin-baggage--small'"></svg>
```

Tell me if any of these work for you.
Please, next time provide a jsfiddle so we can edit it to better help you. You also used a minified version of Vue so we cannot even use the Vue Devtools 😢

**Comment by Nirazul** [comment] 2016-05-01 10:42
@matkovsky 
A failsafe way to make this work is ajaxing your svg file into your html at the beginning. So you can leverage browser cache and have the benefits of the more failsafe local approach. Unfortunately, using svgs from a path is still error prone. 
I don't think that this is a vuejs error. I guess that Chrome ignores svg symbols within template tags and doesn't update it afterwards when it's loaded into the real dom. I'm not all too sure about the details.

**Comment by yyx990803** [comment] 2016-05-01 14:57
This is indeed a chrome bug (and duplicate of https://github.com/vuejs/vue/issues/2661)

I was able to isolate the repro requirements (see comments of #2661) but didn't have time to open a proper bug for Chrome. Feel free to do that ;)

**Closed by yyx990803** 2016-05-01 14:57 UTC
