### ISSUE TITLE
Breaking change in 2.1.5 involving v-show and transition

### ISSUE THREAD

**Issue by jbruni** [vuejs/vue#4473] opened 2016-12-14 05:46 UTC
### Vue.js version
2.1.5+

### Reproduction Link
- <s>http://codepen.io/jbruni/pen/JbmZrj</s> (original pen, still valid)
- http://codepen.io/jbruni/pen/vyVzao (new pen, simplified)

### Steps to reproduce
1. Please check the CodePen linked above. It contains the code working in 2.1.4, with simple instructions.
2. Next, click the settings button in the JS pane, update the VueJS version in the CDN link, and save.
3. Try again, and you will immediately see the difference in behaviour.

### What is Expected?
The behaviour shown in the reproduction link should keep working.

### What is actually happening?
After the upgrade to 2.1.5 (or 2.1.6), it does not work anymore.

-----

Based on the release notes, I made a build creating a new branch, from v2.1.6 tag checkout, and then reverting this commit: vuejs/vue@612d32105a4ba1d636e8b617cbcb0a3e59919a9e, and I got things working again. This commit is a fix to vuejs/vue#4418, but the breaking change is coming from it.

**NOTE**: *This note and the new pen in the "Reproduction Link" above are edits to the original submission. Everything else is the same. Below, I will inform details of the original case. They are still relevant, but not essential. The new and simplified case shall suffice.*

As one can see in the reproduction link, as well as at [this gist](https://gist.github.com/jbruni/6a879ae2313c2713c71881617089ff23), we have a directive called `v-click-outside`.  This directive runs the VM method passed as the directive's attribute value, when a click happens outside the DOM element using the directive. We are using it to close dropdown menus when a click is done anywhere outside it. The dropdowns are using `<transition>` to show/hide.

I'm not sure if our implementation relies in the previous imperfect implementation, and we shall fix our code, or if it really should keep working as it has been written - and the fix done in Vue. I have not taken the time to investigate further. By now, I have only identified, reported and traced down the issue to this report.

Thank you.

**Comment by jbruni** [comment] 2016-12-14 07:44
Ok. I have studied it deeper. I have a pull request (will push soon) and some considerations to make.

Meanwhile, this is a tremendously simplified version of the **reproduction** case:

- http://codepen.io/jbruni/pen/vyVzao

Again, you run ok in 2.1.4, and when switch to 2.1.5 or 2.1.6, the issue appears.

But now the code of the case is very simple.

**Comment by jbruni** [comment] 2016-12-14 09:05
Pull request is done. Technically, it boils down to swapping the place of a single line of code: https://github.com/vuejs/vue/pull/4475/files

It fixes both the reproduction links above. (I don't know if it fixes #4474, which seems to be related.) It is **not** a complete reversal of  vuejs/vue@612d321, but it undoes the main assumption which motivated it.

I will quote #4418: "*starting an animation on @enter that relies on retrieving the global position of an element would fail due to the lack of offsets/offset parents as a result of display: none*"

The assumption on this statement has been embraced, resulting in [a unit test specification](https://github.com/vuejs/vue/blob/v2.1.6/test/unit/features/transition/transition.spec.js#L301).

But this assumption is a use case. It is not general. As we can see, jQuery's `slideDown` relies on display being 'none', and fails when it is not.

This is not a jQuery issue. It is not counter-intuitive to expect, when starting an "enter" animation, to have the element not displayed. Right?

In fact, we shall expect the element to be not displayed when we are about to start its "enter" animation.

Another way to confirm that the assumption cannot be embraced is simple. Just take a look: 

```
          beforeLeave: (el) => {
            expect(el.style.display).toBe('')
            expect(el).toBe(vm.$el.children[0])
            expect(el.className).toBe('test')
            beforeLeaveSpy(el)
          },
          leave: (el) => {
            expect(el.style.display).toBe('')
            onLeaveSpy(el)
          },
          afterLeave: (el) => {
            expect(el.style.display).toBe('none')
            afterLeaveSpy(el)
          },
          beforeEnter: (el) => {
            expect(el.className).toBe('test')
            expect(el.style.display).toBe('none')
            beforeEnterSpy(el)
          },
          enter: (el) => {
            expect(el.style.display).toBe('')
            onEnterSpy(el)
          },
          afterEnter: (el) => {
            expect(el.style.display).toBe('')
            afterEnterSpy(el)
          }
```

This is the current spec. Pay attention: it expects the "display" to be the very same, in both "enter" and "leave". This is a bit counter-intuitive.

Look: "leave" expects the same value than "beforeLeave", and the value is expected to be changed only "afterLeave". Meanwhile, "enter" does not expect the same value than "beforeEnter". It expects an already changed value, before the "afterEnter".

This exposes the problem.

-----------

Now, looking for the solution.

There is no doubt about the values that should be expected for "beforeEnter" and "afterLeave" (display: 'none') and "afterEnter" and "beforeLeave" (display '').

But what is the meaning of expecting a specific value for "enter" and "leave"?

jQuery wants "display: none" to run its animation, otherwise is considers it displayed and does nothing. Another animation wants to calculate stuff based on element's position. Which expectation will be hard coded?

Let's hard-code none, and let the @enter's author deal with it.

Changing the toggling to **before** "enter", as has been done, is breaking change, and puts the burden on everyone's working code.

Furthermore, do we want to explain to a new user that his `slideDown` will not work if he doesn't manually set "display: none" before @enter? Even if he already set initial style as "display: none"? And that he must do it because Vue automatically set display to none before the animation? Yes, this is an option.

These are the reasons I believe the PR should be accepted:
1. It does not break code.
2. It is not counter-intuitive.

If someone needs "display" to be "" **before** the @enter, one can do it in the **@beforeEnter**, or in the beginning of the @enter.

In the other way, if we set "display" to "none" at @beforeEnter, it will be in vain, because it will be reverted internally (and expected in unit tests!) to be "". We must manually put it in the beginning of "@enter" our code to set "display: none".

I hope this PR gets merged... otherwise I will have to do the above.

Thank you.

**Comment by LinusBorg** [comment] 2016-12-14 14:33
/ping @yyx990803 This is probably something you have to answer...

**Comment by yyx990803** [comment] 2016-12-14 15:51
So, the fix is intended, because enter hooks by design should be called at the moment when:

- right after the node is inserted (for `v-if`)
- right after the node is made visible (for `v-show`)

Previously, this behavior was inconsistent between `v-if` and `v-show`.

The fix for your usage is pretty simple: just add `hide()` before `slideDown()`: http://codepen.io/yyx990803/pen/rWqXEK

**Closed by yyx990803** 2016-12-14 15:51 UTC

**Comment by jbruni** [comment] 2016-12-14 17:17
Ok. Thanks. Indeed, the fix is easy. I was almost getting there. Difficult (for me) was to understand what was going on. I'm sorry I got a bit upset... there are tight deadlines... the app was working and suddenly wasn't anymore. Keep up the fantastic work! :+1:
