### ISSUE TITLE
Support custom prop validation errors

### ISSUE THREAD

**Issue by tomers** [vuejs/vue#8391] opened 2018-06-21 12:18 UTC
### What problem does this feature solve?
Sometimes prop validation error messages are to vague, and one would like to specify his own custom error message, instead of the default "Invalid prop: custom validator check failed for prop" message.

### What does the proposed API look like?

I suggest supporting the validator to be an object. Instead of:
```js
export default {
  name: 'MyComponent',
  props: {
    type: {
      type: String,
      validator: v => ['positive', 'negative', 'warning', 'info'].includes(v)
    }
  }
}
```
Have the following:
```js
export default {
  name: 'MyComponent',
  props: {
    type: {
      type: String,
      validator: {
        handler: v => ['positive', 'negative', 'warning', 'info'].includes(v),
        message: "Type must be one of 'positive', 'negative', 'warning', 'info'"
      }
    }
  }
}
```

**Comment by tomers** [comment] 2018-06-21 13:32
Also message as functions should be supported:
```js
export default {
  name: 'MyComponent',
  props: {
    type: {
      type: String,
      validator: {
        handler: v => ['positive', 'negative', 'warning', 'info'].includes(v),
        message: val => `Invalid value ${val}; Type must be one of 'positive', 'negative', 'warning', 'info'`
      }
    }
  }
}
```

**Comment by sodatea** [comment] 2018-06-21 16:35
Duplicate of https://github.com/vuejs/vue/issues/7186

**Closed by sodatea** 2018-06-21 16:35 UTC
