### ISSUE TITLE
Space character in label not working

### ISSUE THREAD

**Issue by approached** [vuejs/vue#9103] opened 2018-11-23 09:59 UTC
### Version
2.5.17

### Reproduction link
[https://jsfiddle.net/onbzk0m6/](https://jsfiddle.net/onbzk0m6/)

### Steps to reproduce
Just load the vue instance. See link to reproduction.

### What is expected?
whitespace character
`Text: "     Drehmaschinen"`

### What is actually happening?
a string with `&nbsp;`
`Text: "&nbsp;&nbsp;&nbsp;Drehmaschinen"`

---
If you remove the vuejs code or change the 'el' attribute, it will work.

**Comment by posva** [comment] 2018-11-23 10:30
Duplicate of https://github.com/vuejs/vue/issues/8895

**Closed by posva** 2018-11-23 10:30 UTC
