### ISSUE TITLE
:value binding on <select> doesn't reflect changes

### ISSUE THREAD

**Issue by abiaskosty** [vuejs/vue#4394] opened 2016-12-06 08:13 UTC
### Vue.js version
2.1.4

### Reproduction Link
https://jsfiddle.net/aleksey_beskosty/zz5svy6q/

### Steps to reproduce
Select element is declared as: 
```<select :value="val">...</select>```

### What is Expected?
When `val` is changed, select element updates its value and shows it.

### What is actually happening?
`val` is changed but select doesn't update value property.

**Comment by yyx990803** [comment] 2016-12-06 08:43
duplicate of #4369 (fixed in 1cf377f)

**Closed by yyx990803** 2016-12-06 08:43 UTC

**Comment by dtruel** [comment] 2018-06-26 17:57
I'm still having this problem on first load.  I basically made a wrapper component for a select that uses :value and @input instead of v-model.  On first load of the wrapper component, it's random chance as to whether the correct value will be displayed in the select, or whether it is empty.  I know the value is there because it displays when I put {{value}} in the same wrapper component right next to the <select>.  Also, if I change :value to v-model it works every time. So there must still be some sort of race condition going on. I'm using Vue 2.5.13
