### ISSUE TITLE
No Reactivity on ES6 Collections: Map, Set, WeakMap, WeakSet

### ISSUE THREAD

**Issue by frankier** [vuejs/vue#10077] opened 2019-05-28 14:15 UTC
### What problem does this feature solve?
Currently, adding one of Map, Set, WeakMap, WeakSet as a data attribute of a Vue component will mean there. Vue should do the same as it does with Array and patch methods like add() and remove()

Adding this feature solves the problem of for example being able to store unique lists of anything (Sets) or maps with structures as keys (since object keys always behave as strings).

The expected behaviour is that when add() does not actually modify a set, nothing would be triggered.

It's possible there is no good use for WeakMap, WeakSet. In that case there's no need to add these too.

### What does the proposed API look like?
There's no change in the API from a user perspective. There would need to be documentation that Vue does basically the

**Comment by posva** [comment] 2019-05-28 14:57
Duplicate of https://github.com/vuejs/vue/issues/6774

**Closed by posva** 2019-05-28 14:57 UTC
