### ISSUE TITLE
Prop named value is always passed as a string.

### ISSUE THREAD

**Issue by sidharthramesh** [vuejs/vue#11978] opened 2021-03-24 09:46 UTC
### Version
2.6.11

### Reproduction link
[https://codepen.io/tornadoalert/pen/rNjVzbd](https://codepen.io/tornadoalert/pen/rNjVzbd)

### Steps to reproduce
Setting the value as prop on a custom element fails. It gets passed as a string [Object Object] instead.

```html
<custom-element :value.prop="message"></custom-element>
```
```js
new Vue({
  el: '#app',
  data: {
       message: {'hello': 'world'}
  }
})
```

### What is expected?
The :value.prop should be passed as an object

### What is actually happening?
The :value.prop is being passed as a string "[Object Object]"

**Comment by posva** [comment] 2021-03-24 09:55
Duplicate of https://github.com/vuejs/vue/issues/10255

**Closed by posva** 2021-03-24 09:55 UTC
