### ISSUE TITLE
"no template or render function" error occurred when only providing 'el' options when creating vue instance

### ISSUE THREAD

**Issue by tomwang1013** [vuejs/vue#4997] opened 2017-02-24 10:29 UTC
There is 3 files involved:

`a.vue`: define a component named 'a'
`b.js`: import component a
`c.pug(jade template file)`: html of the page

In b.js:

```javascript
var Vue = require('vue');
var A = require('a.vue');

new Vue({ el: '#divid' })
...
```

In c.pug:

```pug
div(id='divid')
    a(p1=v1 p2=v2)
```

And when i load the page of c.pug, i got the error: 
```
Failed to mount component: template or render function not defined
```

As i learned from the doc: https://vuejs.org/v2/guide/instance.html#Lifecycle-Diagram
If the `template` option is missed, we will use `el`'s outhtml as the template, so we should not see the error:

![image](https://cloud.githubusercontent.com/assets/1826003/23299979/88a2bfdc-fabe-11e6-90b8-979521b7efdd.png)

Am i missing something or the doc is incorrect? I only want to convert small part of the page(`#divid`) into component, not the whole page.

**Comment by simplesmiler** [comment] 2017-02-24 10:46
Hello!

Thanks for reporting the issue. Please follow the Issue Reporting Guidelines and provide a minimal reproduction demonstrating the issue. In your case that would be a repo.

My guess is that your script is included in the head and is executed before the element exists in the DOM.

**Comment by tomwang1013** [comment] 2017-02-24 14:27
@simplesmiler i am sure that my script. i.e. `b.js` is at the foot of the page. i try to repro it in jsfiddle, but i used `webpack` and `a.vue` single file component and don't know how to use in jsfiddle. I will give as more detail as i can:

I wanted to mount component `a.vue` to `#divid` in `c.pug` (which is rendered by expressjs).  `b.js` is:

```javascript
var Vue = require('vue');
var A = require('a.vue');
var $ = require('jquery');

$(function() {
    new Vue({el: '#divid'});
});
```

Then `c.pug` includes `b.js`, putting it at the foot of it.  `b.js` is compiled by `webpack`, using `vue-loader`.
I don't know why it does not work, it seems the same as the example from guide:
```html
<div id="example">
  <my-component></my-component>
</div>
```

```javascript
// register
Vue.component('my-component', {
  template: '<div>A custom component!</div>'
})
// create a root instance
new Vue({
  el: '#example'
})
```
The difference is i use single file component and `require` it using webpack.

When this does not work, i tried the `render` function: 

// c.pug: **remove the component**
```pug
div(id='divid')
```

// b.js: **add render function**
```javascript
var Vue = require('vue');
var A = require('a.vue');
...
new Vue('#divid', {
    render: function(createElement) {
        return createElement(A, { props: { p1: v2, p2: v2 }})
    }
})
```

And no error occurred, it worked!

**Comment by posva** [comment] 2017-02-24 14:45
@tomwang1013 In that case provide a minimal repository with the repro

**Comment by yyx990803** [comment] 2017-02-24 16:53
You are likely using the runtime-only build: https://vuejs.org/v2/guide/installation.html#Standalone-vs-Runtime-only-Build

**Comment by tomwang1013** [comment] 2017-02-25 10:03
@yyx990803 I switch to `vue.common.js` and got different error:
```
Unknown custom element: <a> - did you register the component correctly? For recursive components, make sure to provide the "name" option
```

It seems when i require a component from single file like: `var A = require('a.vue');`, the returned component is NOT automatically globally registered. Is it?

The guide: https://vuejs.org/v2/guide/single-file-components.html said not much about how to use it.

If component from `.vue` file can't be directly used by html rendered by server, how to use it typically? Create another `.vue` to include it? Then how to mount the top-level single-file component to some element? I've red the guide several times and can't get the answer.

Sorry, maybe i should go to elsewhere like stackoverflow, but i've paid much time to this question, so please let me finish it. Next time i will go elsewhere first. Thanks.

**Comment by posva** [comment] 2017-02-25 13:02
> The guide said not much about it: https://vuejs.org/v2/guide/single-file-components.html

It says a lot... https://vuejs.org/v2/guide/single-file-components.html#Getting-Started
If some parts are not clear, we're happy to get some feedback on https://github.com/vuejs/vuejs.org/

Basically, templates in `vue` files can be compiled by using a webpack loader

I'm sure you'll be able to find the answers on the docs if you keep reading 🙂 

Closing because this has clearly turned into a question. If after using one of the official templates you find out the same error, make sure to come back with the repro in a repository.
If you still need to ask more questions, the [forum](https://forum.vuejs.org/) is very active and you'll definitely find help there

PS: naming a component `a` is definitely a bad idea because of the anchor tag in HTML. If you're testing, creating components with names like `foo` and `bar` is a safer solution

**Closed by posva** 2017-02-25 13:02 UTC
Labels: need repro

**Comment by tomwang1013** [comment] 2017-02-26 05:39
@yyx990803 @posva Thank you all. It now works. I've make a little artical about it:

https://github.com/tomwang1013/learn-webpack-vuejs/blob/master/2017-02/26-vue-first-componet-problem.md

I start to learn vue last week, hoping it can help other beginners if they have simalar problem.
