### ISSUE TITLE
[1.0.27] Weird custom directive behaviour

### ISSUE THREAD

**Issue by schleumer** [vuejs/vue#3779] opened 2016-09-27 00:48 UTC
### Vue.js version
1.0.27

### Reproduction Link
https://jsfiddle.net/oocnvztb/2/

### Steps to reproduce
Create a custom directive, every param, even binded params, became strings, empty arrays became boolean(something somewhere is calling `toString`).

### What is Expected?
Binded values

### What is actually happening?
String representation of values

**Comment by yyx990803** [comment] 2016-09-27 03:27
Duplicate of #3768

**Closed by yyx990803** 2016-09-27 03:27 UTC
