### ISSUE TITLE
Vue.set in plain array cause Cannot read properties of undefined (reading 'shallow') in 2.7.3

### ISSUE THREAD

**Issue by gitpaladin** [vuejs/vue#12635] opened 2022-07-08 02:27 UTC
### Reproduction link
[codesandbox.io](https://codesandbox.io/embed/vue2-sfc-playground-forked-32ii7p?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
```javascript
import Vue from "vue";

const a = [1, 2, 3];
Vue.set(a, 1, 100);   // Cannot read properties of undefined (reading 'shallow')
```

### What is expected?
Set the array element by index.

### What is actually happening?
Error occured.

---
Introduced in 2.7.3 with commit

https://github.com/vuejs/vue/commit/360272bde32e93b1a8d611e4b97af1300c38e7a3#diff-2e26135213b820cfd0eaba327405d14d405a4eee7d14a5c4acfcc2c84ef14692R244

**Comment by yyx990803** [comment] 2022-07-08 02:40
Duplicate of #12632

**Closed by yyx990803** 2022-07-08 02:40 UTC

**Comment by mayank1513** [comment] 2022-07-08 02:42
Great! amazed to see the speed at which issues are resolved. Was hoping to fix a simple issue and kick-start contributing to Vue source code.

Nice!
