### ISSUE TITLE
v-model not work properly when use `v-on="$listeners"`

### ISSUE THREAD

**Issue by lkmadushan** [vuejs/vue#7791] opened 2018-03-11 12:43 UTC
### Version
2.5.15

### Reproduction link
[https://jsfiddle.net/cckLd9te/950/](https://jsfiddle.net/cckLd9te/950/)

### Steps to reproduce
when you type on the input, view not update with the input value

### What is expected?
view should display input value properly

### What is actually happening?
input value changes to an object

**Comment by posva** [comment] 2018-03-11 14:11
Duplicate of #7042

**Closed by posva** 2018-03-11 14:11 UTC
