### ISSUE TITLE
Vue does not detect changes in Map collection

### ISSUE THREAD

**Issue by sohail85** [vuejs/vue#7289] opened 2017-12-20 09:10 UTC
### Version
2.5.13

### Reproduction link
[https://jsfiddle.net/sohail85/d72g4jxt/](https://jsfiddle.net/sohail85/d72g4jxt/)

### Steps to reproduce
Map collections are not reactive, even computed properties depending to Map collections does not changes when their dependency changed

### What is expected?
Map collection like other data structure should be reactive

### What is actually happening?
instance variable of type Map collection does not reflect its changes to UI

**Comment by javoski** [comment] 2017-12-20 09:21
Duplicate of #6774

**Closed by javoski** 2017-12-20 09:21 UTC
