### ISSUE TITLE
multiple v-if not work in root of template tag

### ISSUE THREAD

**Issue by Shmasya** [vuejs/vue#4155] opened 2016-11-08 17:11 UTC
In my code
```
  <div id="app">
    <test-component type="normal"></test-component>
    <test-component type="block"></test-component>
  </div>

  <template id="template-test-component">
    <li v-if="type == 'normal'" class="test">
      test
    </li>
    <div v-if="type == 'block'" class="test">
      <p>Hello, World!</p>
    </div>
  </template>

  <script>
    var testComponent = Vue.extend({
      template: '#template-test-component',
      props: ['type']
    });

    var app = new Vue({
      el: '#app',
      components: {
        'test-component': testComponent
      }
    })
  </script>
```
This work in plunk, but on real project this code not work. v-if work only in div wrapper, example:

```
  <template id="template-test-component">
    <div class=wrapper>
      <li v-if="type == 'normal'" class="test">
        test
      </li>
      <div v-if="type == 'block'" class="test">
        <p>Hello, World!</p>
      </div>
    </div>
  </template>
  ```
But .wrapper screws up my layout.

**Comment by crswll** [comment] 2016-11-08 18:30
A component is required to have one root element.

It looks like you actually want two different components here, like `<block>` and `<normal>`, then the `v-if`'s won't be needed.

```html
<block></block>
<normal></normal>
```

If `type` is dynamic you can use `<component :is="type">`

```html
<component :is="type"></component>
```

Then the actual component being used will be whatever `type` is.

**Comment by Shmasya** [comment] 2016-11-08 18:41
@crswll I have 2 views one component and not 2 different component. Therefore, your way is not the best ..

**Comment by fnlctrl** [comment] 2016-11-08 19:09
Closing as it'a duplicate of https://github.com/vuejs/vue/issues/4128, quote from Evan:
> The problem here is that without code analysis of all your v-if expressions (in fact it's near impossible because it depends on your component's runtime state), there's no way to tell whether it will really return only one element.
You can get around this by either using a dynamic component (turning all conditional branches into components), or use a render function instead.

**Closed by fnlctrl** 2016-11-08 19:09 UTC

**Comment by yyx990803** [comment] 2016-11-08 19:53
This **might** be improved in the future, where we just compile everything and warn you at runtime if more than 1 root node is returned.

**Comment by Shmasya** [comment] 2016-11-08 22:19
@yyx990803 thx, i wait this 👍

**Comment by muyi0327** [comment] 2016-11-16 08:16
i wait this too.

**Comment by kirbyfan64** [comment] 2017-09-30 01:28
Couldn't this work with `v-if` + `v-elif` + `v-else`? Then only one part is guaranteed to be rendered.
