### ISSUE TITLE
When the recalculated values of the dependent computed properties have not changed, the calculated properties of all dependent are recalculated.

### ISSUE THREAD

**Issue by txs1992** [vuejs/vue#8751] opened 2018-09-04 10:09 UTC
### What problem does this feature solve?

Sorry, the following content is not translated accurately, so use Chinese.

[Example](https://jsfiddle.net/_MT_/6zscxLpj/7/)

当程序中出现链式计算属性依赖时，我们可能希望的是仅当被依赖的计算属性变更时，它所依赖的计算属性才会重新去计算。而不是因为被依赖的计算属性重新计算链了，所以所有依赖它的计算属性都要重新计算。这样在链式的依赖的计算属性中，可以节省很多计算工作。

### What does the proposed API look like?
仅当被依赖的计算属性变更时，它所依赖的计算属性才会重新去计算。

**Comment by Justineo** [comment] 2018-09-04 10:25
Duplicate of #7767

---

And F.Y.I. 2.5.17-beta.0 had shipped this enhancement (#7824) but it caused regression (#8446) so was not included in 2.5.17.

**Closed by Justineo** 2018-09-04 10:25 UTC
