### ISSUE TITLE
Unwanted method firing when using a directive

### ISSUE THREAD

**Issue by ZainW** [vuejs/vue#9739] opened 2019-03-19 19:46 UTC
### Version
2.6.8

### Reproduction link
[https://codesandbox.io/s/lpkp7lkkm](https://codesandbox.io/s/lpkp7lkkm)

### Steps to reproduce
1. press toggle button

### What is expected?
only the toggle method should be triggered

### What is actually happening?
the toggle method AND the hide method trigger right away

---
if you revert to vue 2.5.22 this code works, it however does not work on latest 2.6.x. was upgrading from 2.5.x to 2.6.x and noticed that this broke.

**Comment by posva** [comment] 2019-03-19 21:10
Duplicate of #9340

**Closed by posva** 2019-03-19 21:10 UTC
