### ISSUE TITLE
v-bind.prop doesn't pass object types

### ISSUE THREAD

**Issue by ngfk** [vuejs/vue#10546] opened 2019-09-22 12:15 UTC
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/ngfkoster/9cxmrnsg/60/](https://jsfiddle.net/ngfkoster/9cxmrnsg/60/)

### Steps to reproduce
Reproduction link  shows a custom element with a "value" property expecting an array.

Regular binding fails as expected because it isn't an attribute. Property binding works but transforms the array to a string. Third item shows the expected result created using native code.

### What is expected?
v-bind.prop should pass the array

### What is actually happening?
v-bind.prop passes the the array as a string

---
Issue #9138 might be similar.

**Comment by posva** [comment] 2019-09-22 14:24
Duplicate of #9138

**Closed by posva** 2019-09-22 14:24 UTC
