### ISSUE TITLE
Event propogation before component is created and conditional rendering

### ISSUE THREAD

**Issue by lucpotage** [vuejs/vue#9615] opened 2019-03-04 10:55 UTC
### Version
2.6.8

### Reproduction link
[https://codesandbox.io/s/wwoxp636jk](https://codesandbox.io/s/wwoxp636jk)

### Steps to reproduce
Add a click listener on window in a child component

### What is expected?
Before Vue 2.6, the click event was not propagated to the child component because it was not created yet.

### What is actually happening?
The click event is now propagated to the child after it is created and mounted.

---
Do I need now to explicitly add the modifier `.stop` to all my parent click events if I add click listeners on window in my child components?

**Comment by posva** [comment] 2019-03-04 11:07
Duplicate of #9616 
Also see https://github.com/vuejs/vue/issues/9478 and https://github.com/vuejs/vue/issues/9464

**Closed by posva** 2019-03-04 11:07 UTC
