### ISSUE TITLE
Operation input box,after leaving the page, the component data is not released

### ISSUE THREAD

**Issue by hf0913** [vuejs/vue#11600] opened 2020-08-17 06:08 UTC
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/unruffled-night-t32t2?file=/src/router.js:253-257](https://codesandbox.io/s/unruffled-night-t32t2?file=/src/router.js:253-257)

### code
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.jsdelivr.net/npm/vue"></script>
    <script src="https://unpkg.com/vue-router/dist/vue-router.js"></script>
    <title>input momery leak</title>
</head>

<body>
    <div id="app">
        <router-link to="/input">Go to input page</router-link>
        <br />
        <router-link to="/empty">Go to empty page</router-link>
        <router-view></router-view>
    </div>

    <script>
        const Inp = {
            data: function () {
                return {
                    v: '',
                    test: []
                }
            },
            mounted() {
                for (let i = 2000000; i > 0; i--) {
                    this.test.push(i)
                }
            },
            template: `<input v-model="v"></input>`
        },
            Empty = { template: '<div>empty</div>' },
            routes = [
                { path: '/input', component: Inp },
                { path: '/empty', component: Empty }
            ],
            router = new VueRouter({
                routes
            }),
            app = new Vue({
                el: '#app',
                router
            })
    </script>
</body>

</html>

### Steps to reproduce
1.Click Go to input page link,collect garbage and take a snapshot with devtools   
2.Enter any value in the input box,collect garbage and take a snapshot with devtools   
3.Click Go to empty page link,collect garbage and take a snapshot with devtools  

### What is expected?
Data memory release in component data

### What is actually happening?
Not released,variables test are still in memory

---
If the input box does nothing and leaves the page, the component data can be freed normally

**Comment by posva** [comment] 2020-08-17 13:23
Duplicate of https://github.com/vuejs/vue/issues/10004

**Closed by posva** 2020-08-17 13:23 UTC
