### ISSUE TITLE
qtwebengine click event not working

### ISSUE THREAD

**Issue by liu419249629** [vuejs/vue#12347] opened 2021-11-05 07:58 UTC
### Version
2.6.14

### Reproduction link
[codepen.io](https://codepen.io/damaowife/pen/wvqyXrW)

### Steps to reproduce
1.qtwebengine (navigator.userAgent :Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.6.3 Chrome/49.0.2623.111 Safari/537.36)
2.vue version (2.6.14)
3. someTimes click event not working (Open QT for a long time.)

### What is expected?
work fine

### What is actually happening?
When click event not working, we found something:
at "vue/src/platforms/web/runtime/modules/events.js" lines 70: `e.timeStamp >= attachedTimestamp` is false

**Comment by liu419249629** [comment] 2021-11-05 07:59
![image](https://user-images.githubusercontent.com/17897624/140477491-35742122-3663-4a0d-8d85-611f123a6a9f.png)

![image](https://user-images.githubusercontent.com/17897624/140477518-6cc22dd5-44da-4124-82bc-206cf04c1829.png)

**Comment by posva** [comment] 2021-11-05 08:55
Duplicate of https://github.com/vuejs/vue/issues/11014

**Closed by posva** 2021-11-05 08:55 UTC
