### ISSUE TITLE
template内增加支持?.语法

### ISSUE THREAD

**Issue by ikarosu** [vuejs/vue#11219] opened 2020-03-18 08:35 UTC
### What problem does this feature solve?
?.语法已经成为ES2020标准，希望模版编译引擎尽快支持

### What does the proposed API look like?
v-if="data?.sub?.id"

**Comment by Justineo** [comment] 2020-03-18 08:53
Duplicate of #11088

**Closed by Justineo** 2020-03-18 08:53 UTC
