### ISSUE TITLE
Class methods lost when object passed to a scoped slot

### ISSUE THREAD

**Issue by KKSzymanowski** [vuejs/vue#7021] opened 2017-11-08 14:07 UTC
### Version
2.5.3

### Reproduction link
[https://jsfiddle.net/smyv26u2/](https://jsfiddle.net/smyv26u2/)

### Steps to reproduce
Uncomment the price with VAT.

### What is expected?
The second list should also display the price with VAT

### What is actually happening?
There is an error in the console:
```
TypeError: product.priceWithVat is not a function
```

**Comment by KKSzymanowski** [comment] 2017-11-08 14:16
It works using a plain JS object instead of a class: https://jsfiddle.net/7tfvoctd/

**Comment by GMaiolo** [comment] 2017-11-09 00:46
I just took a quick look at the [renderSlot function](https://github.com/vuejs/vue/blob/dev/src/core/instance/render-helpers/render-slot.js) and found this:

```
if (scopedSlotFn) { // scoped slot
  props = props || {}
  if (bindObject) {
    ...
    ...
    props = extend(extend({}, bindObject), props)
  }
  ...
}
```

And the [extend function](https://github.com/vuejs/vue/blob/dev/src/shared/util.js):

```
export function extend (to: Object, _from: ?Object): Object {
  for (const key in _from) {
    to[key] = _from[key]
  }
  return to
}
```

So, my best guess is that as the `product` instance of `Product` class is being merged with an object literal, all of its prototype's methods are being discarded because of the `for in` iterating over the _enumerable properties_ of the object, **and the constructor & any defined methods are _non-enumerable properties_ of the class's prototype object**.

Using an object literal instead of a class instance would be the best workaround if possible.

**Comment by yyx990803** [comment] 2017-11-09 03:17
This is expected behavior, because scoped slot props are not passed directly, it's always copied as a plain object. Just imagine if you have another `v-bind:foo="123"` alongside the `v-bind="product"`, `foo` needs to be merged with the keys found in `product`.

**Closed by yyx990803** 2017-11-09 03:17 UTC

**Comment by Moskydesign** [comment] 2018-03-07 09:01
Wrapping your class instance in an object bypasses this problem.

**Comment by KKSzymanowski** [comment] 2018-03-07 09:05
What do you mean? Can you give me an example?

**Comment by Moskydesign** [comment] 2018-03-07 10:00
Instead of:

`<slot v-bind="MyClassObject"></slot>`
    
You do something like this:

```
let MyWrappedClassObject = {'object': MyClassObject}
<slot v-bind="MyWrappedClassObject"></slot>

<template slot-scope="MyWrappedClassObject">
  {{ MyWrappedClassObject.object.value }}
</template>
```

**Comment by KKSzymanowski** [comment] 2018-03-07 11:49
That works, thanks.
You can also utilise shorthand properties and object destructuring to make it cleaner.

In component:
```html
<slot v-bind="{product}"></slot>
```
In parent:
```html
<template slot-scope="{product}">
    {{ product.priceWithVat() }}
</template>
```
