### ISSUE TITLE
Unexpected convertation of string prop into boolean

### ISSUE THREAD

**Issue by Gotterbild** [vuejs/vue#11367] opened 2020-05-01 12:19 UTC
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/ndxL039y/2/](https://jsfiddle.net/ndxL039y/2/)

### Steps to reproduce
Just add a property that can accept both boolean and string:
```
...
props: {
  value: [Boolean, String]
},
...
```

Then feed an empty string value into this property. Empty string value will be converted to boolean value, to `true`.

### What is expected?
If property can accept both boolean and string value, then empty string value should behave as any other string value and shouldn't be converted into boolean.

### What is actually happening?
Empty string value is converted into boolean `true` value.

---
Tested in Vue 2.7.1, but 2.7.1 is not availalble in your Issue Helper.

**Comment by posva** [comment] 2020-05-01 13:18
Duplicate of https://github.com/vuejs/vue/issues/4710

**Closed by posva** 2020-05-01 13:18 UTC

**Comment by Gotterbild** [comment] 2020-05-05 11:47
@posva Wring, it is not a duplicate.

#4710 is just about conversion.

My case is different. In my case prop expects Boolean or String. But if you pass an empty string, it is comprehend as Boolean.

So the fix would be to prioritize non-boolean values lower than other types when both Boolean and other type is expected.

**Comment by posva** [comment] 2020-05-05 12:06
Take a look at the linked issues in the duplicate and do the minimal search work: https://github.com/vuejs/vue/issues?q=is%3Aissue+sort%3Aupdated-desc+order+prop+boolean+is%3Aclosed

The order with a `Boolean` prop matters, put it after the `String` if you want to keep empty strings when passing `<comp attr />` or `<comp attr="" />` (which are the same from HTML perspective: https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#boolean-attributes)

**Comment by Gotterbild** [comment] 2020-05-05 12:26
Thanks, @posva. I searched `boolean string prop conversion` but didn't find anything relevant on the first page of results.

The fact that order matters here definitely requires a mention in docs. And not in API docs, but main one. I'll try to find time to post a Pull Request for that.
