### ISSUE TITLE
template  no wrap

### ISSUE THREAD

**Issue by hqzh** [vuejs/vue#9197] opened 2018-12-13 12:10 UTC
### What problem does this feature solve?

`
<template>
<span></span>
<span></span>
</template>
`

### What does the proposed API look like?
`
<template>
<>
<span></span>
<span></span>
</>
</template>
`

**Comment by sodatea** [comment] 2018-12-13 12:21
Duplicate of https://github.com/vuejs/vue/issues/7088

**Closed by sodatea** 2018-12-13 12:21 UTC
