### ISSUE TITLE
Allow more than 1 root element for Template

### ISSUE THREAD

**Issue by tochoromero** [vuejs/vue#7088] opened 2017-11-20 22:23 UTC
### What problem does this feature solve?
Right now you can only have 1 root element per template. I know this is by design, but I find myself wrapping everything around a `<div>` a lot. Now, most of the time is not a big deal, I can live with that, the problem is when either Bootstrap requires a very specific hierarchy, or when dealing with Tables that also require a very specific hierarchy and wrapping everything on a div is not an option.

### What does the proposed API look like?
Now, there will be a couple of things to figure out, mainly to what element will the properties provided on the Custom Element will be attached to. I think there two things that can be done:
1) Find the first child and stick everything to it.
2) Provide a custom attribute to indicate to what element they should be attached to.

**Comment by sirlancelot** [comment] 2017-11-20 22:28
Can you build a specific scenario in which you need a template with multiple root nodes? I've been using Bootstrap and tables with Vue since the beginning and have never needed multiple root nodes.

**Comment by posva** [comment] 2017-11-20 22:39
> Provide a custom attribute to indicate to what element they should be attached to.

FYI you can use `$listeners` and `$props` to easily pass down things to the element you want

You can have multiple root elements in functional components:

```js
render: h => [h('p', 'one'), h('p', 'two')]
```

Personally, I actually like the fact that we only have one root as it clears out the questions you just listed because there's only one possible answer

**Comment by tochoromero** [comment] 2017-11-20 23:35
On my very specific Table use case I have a `Category` component that I would like to contain two `<tbody>` root elements. In the first `<tbody>` I will show the Category information, in the second `<tbody>` I will list all the Category Items with its details. And the main Category body will control the visibility of the second one. I want it to look something like this:

**Category.vue**
```html
<template>
   <tbody>
	<tr @click="showItems = true">
		<td>{{ category.id }}</td>
		<td>{{ category.name }}</td>
	</tr>
   </tbody>
   <tbody v-show="showItems">
      <tr v-for="item in category.items">...<tr>
   </tbody>
</template>
```
Now I know I could move them to two separate components and have them communicate, but they really belong together, they have computed properties and methods they will share, and yes I can move those to a mixin, but that just makes everything a bit more complex.

Now, regarding Bootstrap, I recently stumbled on this:
I was using an `input-group` and I needed to have something like this:
```html
<div class="input-group">
    <span class="input-group-addon"><i class="fa fa-dollar"></i></span>
    <input v-show="isDisabled" class="form-control form-control-sm"/>
    <vue-numeric v-show="!isDisabled" class="form-control"/>
</div>
```
Now, the input/vue-numeric pair is reusable, I actually have quite some logic around those two, so I wanted to reuse them, but the input-group itself is not reusable, since in some places I don't need an input group or the input group is very different.
Now when I move the `<input>` and the `<vue-numeric>` into its own component I'm forced to use `v-if` and `v-else`. Unfortunately, that caused a whole lot of other problems, I needed both elements to be mounted at all times, and working around it wasn't fun, my problems would be gone if I could just have them both mounted and just `v-show` them as necessary. Of course, I found a way to work around it, but it wasn't the clean simpler approach I wanted and that I can achieve in other frameworks.

I truly love Vue, this is a just a tiny minor complain and I will never go back. It would just be nice to have the option. The nice thing about this feature is that if you don't want to you don't have to use it even think about it, just keep wrapping everything in a div.

**Comment by tochoromero** [comment] 2017-11-20 23:37
> FYI you can use $listeners and $props to easily pass down things to the element you want

I was wondering about that, I remember reading that long time ago, but couldn't find it, thanks for the tip

**Comment by titouancreach** [comment] 2017-11-30 16:28
The new react version has Fragment: https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html. They can do:

```
<template>
  <> <!-- render nothing -->
   <tbody>
	<tr @click="showItems = true">
		<td>{{ category.id }}</td>
		<td>{{ category.name }}</td>
	</tr>
   </tbody>
   <tbody v-show="showItems">
      <tr v-for="item in category.items">...<tr>
   </tbody>
   </>
</template>
```
What about using this syntax in Vue ?

**Comment by tochoromero** [comment] 2017-11-30 16:49
Honest question here, why do we even need to wrap everything on a single root element, is this a technical limitation or an arbitrary decision?

**Comment by yyx990803** [comment] 2017-11-30 16:59
Technical, due to how the diff algorithm is written. It's obviously possible to update it, but it takes significant changes to the current algorithm (React did that during a complete rewrite).

**Comment by tochoromero** [comment] 2017-11-30 17:12
Got it, thank you for the details

**Comment by pxwee5** [comment] 2017-12-01 02:02
@sirlancelot Or when you're using Nuxt, where everything is a Vue SFC.

**Comment by mosinve** [comment] 2017-12-06 06:39
@tochoromero.  IMHO, your example can be easily refactored by extracting items list to another child component. My view of components - they should be atomized. If it container of items, then it shoud consist of container component and item component.

**Comment by trusktr** [comment] 2018-01-16 09:00
> Honest question here, why do we even need to wrap everything on a single root element, is this a technical limitation or an arbitrary decision?

> Technical, due to how the diff algorithm is written.

How's this very technical to implement?

```html
<template>
   <tbody></tbody>
   <tbody></tbody>
</template>
```

can easily be transpiled to

```js
render: h => [ h('tbody'), h('tbody') ]
```

thus solving the problem (idk what it was doing before, but this seems trivial).

**Comment by trusktr** [comment] 2018-01-16 09:15
Here's proof that that works: https://jsfiddle.net/b049qboe/1

**Comment by LinusBorg** [comment] 2018-01-16 09:20
@trusktr The technical problem is not with the conversion of template to render function, it's with the strcture of the virtualdom that the render function builds.

Each child component is controlled represented in its parent virtual  dom by a single `vnode`. In the current implementation, the diffing algorithm (responsible for comparing the current with the old virtualDOM and patching differences into the real DOM) can rely on the fact that every vnode of a child component has a single matching HTML element in the real dom, so the next vnode in the virutalDOM after the child component vnode is guaranteed to match the next HTML Element in the real DOM.

Allowing for fragments requires sgnificant changes to that algorithm, since we now would somehow keep the parent updated at all times how many root nodes the child is currently rendering, so when the parent re-renders, it knows how many HTML-Elements it has to "skip" to reach the next HTML Element that doesn't belong to the child component,

That's a *very* intricate/complicated piece of code at the heart of Vu, and it is critical for render .performance, so it's not only important to make it work *correctly* but also to make it *highl performant*

That's a pretty hefty task. As Evan mentioned, React waited for a complete re-write of its rendering layer to remove that restriction.

**Comment by trusktr** [comment] 2018-01-16 09:31
Are you implying that opting not to convert multiple roots from a template into multiple roots in a render function (which works) is because of performance, but it nonetheless would work? Can you make a fiddle that shows when it doesn't work?

**Comment by LinusBorg** [comment] 2018-01-16 09:34
> Are you implying that opting not to convert multiple roots from a template into multiple roots in a render function (which works) is because of performance, but it nonetheless would work?

No. I'm saying that the current virtualDOM diff&patch algorithm relies on the fact that each child component has exactly one root node, so it would break with more than one root node in a child component.

**Comment by sirlancelot** [comment] 2018-01-16 17:31
I'm still not convinced that multiple roots is even needed. If the core team is currently working on supporting it then that's great, but I don't feel like they should if it's not on the roadmap already.

Every time I've thought _"Hey I might need multiple root nodes for this,"_ it puts me on a dangerous path of adding too much complexity to a single component. I *always* end up with a better, simpler solution that lives well within the single root node paradigm.

Most of my solutions for the above usually rely on _scoped slots_. I highly recommend learning how to use them well. You will never need to think about multiple root nodes again.

**Comment by LinusBorg** [comment] 2018-01-16 17:41
> If the core team is currently working on supporting it then that's great, but I don't feel like they should if it's not on the roadmap already.

It's a "nice to have" on the roadmap, and won't happen anytime soon, as it would also be a breaking change - any 3rdparty component written with multiple root nodes wouldn't work with `2.x`.

**Comment by trusktr** [comment] 2018-01-16 20:45
Can one of you show how to rewrite my above fiddle with "scoped slots" to show that it is possible to output two `<tr>` elements at a time from a component, into a `<table>` of an outer component (just like my example), using template(s) instead of render function(s).

When I tried using slots, it would'nt let me put a slot element as root of a component.

@LinusBorg, will the ability to return an array from a `render` function be removed?

**Comment by LinusBorg** [comment] 2018-01-16 20:49
> @LinusBorg, will the ability to return an array from a render function be removed?

No, why would you think we would remove anything?

 Returning an array from a render function doesn't work, never worked and will continue not to work in Vue 2 - the notable exception were, are and will be functional components, for the reasons l laid out further up.

**Comment by effulgentsia** [comment] 2018-01-16 21:22
> functional components don't have that restriction because the are not represented with a vnode in the parent, since they don't have an instance and don't manage their own virtualdom

Last I checked (though possibly this has changed since then), a Vue SFC with `<template functional>` did not support multiple "root" elements within the `<template>`. Given the above comment, would it be fairly straightforward to allow that within functional template SFCs? I think that might go a long way to addressing many of the desired use-cases for it without requiring a rewrite of any fundamental architecture?

**Comment by trusktr** [comment] 2018-01-16 21:49
Oh, I see, it only works with `functional:true`.

Well, I don't need help writing single-root components or converting into single-root components.

It's just that having multiple roots allows for useful patterns where otherwise certain patterns are not doable without multi-root components. This is why React added the `<>` because community needed it.

So, I was trying to understand why it was removed when it is useful.

So, this issue is just hoping that the feature is added because it seems valid to let people compose more freely.

FWIW, this sort of composing isn't *currently* doable with Custom Elements. Only virtual component systems allow this at the moment, as the component instances don't actually get placed into the DOM.

A `display: contents` CSS style is coming soon (currently behind flags), which will allow Web Components to [achieve the same thing](https://www.chromestatus.com/feature/5663606012116992) (i.e. to achieve the same as what multi-root rendering would in Vue)

For example, here's some chatter the same problems on [w3c/webcomponents](https://github.com/w3c/webcomponents/issues/723#issuecomment-358116067) and [StackOverflow](want to render two <tr> elements).

**Comment by trusktr** [comment] 2018-01-16 21:53
Fixed a broken link in the last comment

**Comment by LinusBorg** [comment] 2018-01-16 22:13
> So, I was trying to understand why it was removed when it is useful.

If that refers to the "removal" between Vue 1 and Vue 2: It was a design decision mainly because it's much easier, performant and was how virtualdoms generally work(ed).

Again, React had to rewrite the whole rendering engine to get a setup that does it in a performant way.

We understand its useful in some scenarios, but there's a tradeoff between usefulness and the amount of work involved.

**Comment by effulgentsia** [comment] 2018-01-17 23:22
> We understand its useful in some scenarios, but there's a tradeoff between usefulness and the amount of work required to make it happen.

@LinusBorg: any thoughts on my earlier question about allowing it in functional template SFCs? Would that be sufficiently low work?

**Comment by LinusBorg** [comment] 2018-01-18 06:34
TBH I wasn't aware that this doesn't work, still have to test this. 

But yeah, rust should be a fixable problem, it's "only" about template compilation.

**Comment by danielsvane** [comment] 2018-01-18 11:05
It would be nice if `<template functional>` allowed multiple root elements.

**Comment by LinusBorg** [comment] 2018-01-18 11:09
Could someone open an issue in vue-loader, then?

**Comment by mese79** [comment] 2018-02-09 19:25
Having multiple root elements in template would be nice and for some js libraries or ui frameworks it seems necessary.
So far i've reached to a workaround like this:
Defining a *dummy* component:
```
<template>
	<div>
		<!-- dummy -->
		<slot></slot>
	</div>
</template>

<script>
export default {
	data: function() {
		return {
			parent: null,
			children: null
		}
	},
	beforeMount: function() {
		this.parent = this.$el.parentElement
		this.children = this.$el.childNodes
		
		this.parent.removeChild(this.$el)

		jQuery(this.parent).append(jQuery(this.children))
	},
	mounted: function() {
		console.log('Dummy:', this.children)
	}
}
</script>
```
Then use it like:
```
<template>
	<Dummy>
		<Header />
		<Nav />
		<section class="container">
			<div>test</div>
		</section>
	</Dummy>
</template>

<script>
import Header from '~/components/Header'
import Nav from '~/components/Nav'
import Dummy from '~/components/Dummy'

export default {
	components: {
                Dummy,
		Header,
		Nav
  	},
  	mounted: function() {
		console.log("index was mounted", this);
  	}
};
</script>
```
By the way i couldn't manage to fix it without using *jquery* ;)

**Comment by TopCoderMyDream** [comment] 2018-02-14 05:03
vue 是中国人的骄傲.

**Comment by rr326** [comment] 2018-02-19 15:08
Here is another use case I'm struggling with:

My parent component defines a grid with multiple named template-areas. Ideally my child component would do:

    <template>
        <div class="gridareaone">Stuff</div> 
        <div class="gridareatwo">Other stuff</div>
    </template>

But since the child component has to have a single wrapping element, it doesn't work. I can work around it, but it causes problems.

**Comment by trusktr** [comment] 2018-02-19 21:48
> Could someone open an issue in vue-loader, then?

https://github.com/vuejs/vue-loader/issues/1167

**Comment by euoia** [comment] 2018-02-21 12:23
I'm also struggling with the lack of multiple root nodes in components. I have reviewed the comments in this issue and written up my problem below.

My layout uses [CSS grid](https://css-tricks.com/snippets/css/complete-guide-grid/). In a CSS grid, the grid areas apply to the direct child of the `display: grid` element. Since a Vue component must have a single root element, it is not possible to have a component represent multiple grid areas (e.g. multiple rows or columns). This is essentially the same as the problem @tochoromero raised where a single component cannot represent multiple `<tbody>` elements. For my use case, the best workaround I have found is to forgo a component and use `<template>`  instead (second example below).

@trusktr mentioned that `display: contents` is coming soon. `display: contents` can be used as an imperfect workaround for this problem for CSS grids. I say _imperfect_ because `display: contents` is not semantically equivalent to replacing the parent div with its children in the DOM. This can be seen in the first example below where the`#app > div` selector applies to the `display: contents` div and not its children.

In response to @sirlancelot I have created some fiddles which show the issue. I am keen to see how @sirlancelot would work around this issue (and the `<tbody>` problem), since it's useful to have a range of options available.

Here's an example using `display: contents` and a single root div in the component:
https://jsfiddle.net/avv3vgae/28/

Here's an example of the `<template>` workaround:
https://jsfiddle.net/h7rav21u/13/

With tables, if you want a component to represent multiple `<tr>` that's possible by using `<tbody>` as the root element. As discussed, it is not possible for a component to represent multiple `<tbody>` and I don't think `display: contents` can help us here.

@LinusBorg if you'll permit me a meta question: where is the best place to continue discussion of the implementation of this feature?

**Comment by LinusBorg** [comment] 2018-02-21 13:57
@euoia There's not a real place for that yet, but we are ni the middle of setting up a seperate repository where RFCs can be suggested and discussed with the community. That would probably be the best place for this.

It will be available soon and will be properly announced when the time has come.

**Comment by brianboyko** [comment] 2018-02-21 22:17
I have a pretty compelling real-world case where I'm not sure how I can proceed without having access to multiple root nodes.  

I'm developing what's essentially a table+accordion.  That is, the table adds more rows when you click on it to show more details for that entry.

My table is located in the Researcher Groups component, which has a sub-component: "app-researcher-group-entry (ResearcherGroupEntry).  

I'm using Vue-Material, but the problem would be the same if I was using a plain <tr>.  

Anyway, my structure is kind of like:

```
   // ResearcherGroups.vue
<template>
    <md-table>
        <md-table-row>
          <md-table-head></md-table-head>
          <md-table-head>Researcher</md-table-head>
          <md-table-head>Type</md-table-head>
          <md-table-head></md-table-head>
          <md-table-head></md-table-head>
        </md-table-row>
        <app-researcher-group-entry v-for="(group, index) in researcherGroups" :key="group.label" :groupData="group" :indexValue="index"></app-researcher-group-entry>
    </md-table>
</template>
```

And in ResearcherGroupEntry.vue: 

```
<template>
<md-table-row>
    <md-table-cell>
      <md-button class="md-icon-button md-primary" @click="toggleExpansion">
        <md-icon v-if="expanded">keyboard_arrow_down</md-icon>
        <md-icon v-else>keyboard_arrow_right</md-icon>
      </md-button>
      <md-button @click="toggleExpansion" class="index-icon md-icon-button md-raised md-primary">{{indexValue + 1}}</md-button>
    </md-table-cell>
    <md-table-cell>{{groupData.label}}</md-table-cell>
    <md-table-cell>Group</md-table-cell>
    <md-table-cell>
      <md-button @click="openTab" class="md-primary">
        <md-icon>add_box</md-icon>
        Add Client / Client Type
      </md-button>
    </md-table-cell>
    <md-table-cell>
      <md-button class="md-primary">
        <md-icon>settings</md-icon>
        Settings
      </md-button>
    </md-table-cell>
  <app-add-client-to-group-tab :indexValue="indexValue" :groupData="groupData" :closeTab="closeTab" :addClientToGroupTab="addClientToGroupTab"></app-add-client-to-group-tab>
  </md-table-row>
    
</template>
```

Here's where the problem comes in.  I want to be able to expand the clients like this from our mockup:
<img width="1233" alt="screen shot 2018-02-21 at 4 10 51 pm" src="https://user-images.githubusercontent.com/3599223/36508267-d904fa50-1721-11e8-933f-d0e278ad7be3.png">

This would be *trivially easy* if I could just add another <md-table-row> into the ResearcherGroupEntry component.  Unfortunately, wrapping <md-table-row> with a div or span tag won't work here (it messes up the table).  

If I wasnt using Vue Material, I might have considered using JSX for this component, because then I could simply use .map in the parent to create an array of components based on the two variables.  I might still be able to do that with v-for directives, but I'm not sure.  What I may have to do is create, from props, a crazy pseudo array merging in parents and children, but that's *UUUUUGLY* code.

**Comment by titouancreach** [comment] 2018-02-21 22:33
Why use vue material prevents you to use jsx (or render function)?

**Comment by brianboyko** [comment] 2018-02-21 22:44
Because I'm not sure the JSX would recognize the components.  Maybe not.  Maybe a render function is needed here.

**Comment by SomeWeirdo** [comment] 2018-04-24 21:37
@ashraj98 Unrelated to this project, what's the best way to contact you for a guaranteed reply? Or rather, if it's your email how long until you usually respond? No rush on anything.

**Comment by cherscarlett** [comment] 2018-05-02 02:41
I feel like a compelling reason is simply that we shouldn't forced into using arbitrary `<div />`'s in SFC's, especially when there are many use cases that they cause problems. If my component or page's root element is `<ul />`, but I want to stick a `./loader.svg` into the list while it loads, I now have to wrap my `<ul />` and `<Loader />` into a `<div />` that I do not need. Whether that's passing `functional` and adding a `<Fragment />`, I don't think it matters.

It's a real problem that people are using hacks to solve, like the above `jQuery` frightening and clever piece above.

**Comment by titouancreach** [comment] 2018-05-02 07:29
I think we all agree to say that is a missing feature. The Vue developpers say that is currently difficult to implement because of the diff algorithm. One of the solution for now is to not create a child component when we have this use case. We can split the parent component into multiple render functions and compose our parent. (It is easier with JSX)

For [this](https://github.com/vuejs/vue/issues/7088#issuecomment-366720489), we can do: 

```javascript
const genChildren = h => {
  return [h('div', "someStuff"), h(div, "Other stuff")];
}


// parent component
render(h) {
  return h('myGridWrapper', genChildren(h))
}

```

**Comment by adi518** [comment] 2018-05-02 10:05
@titouancreach How would this work? you're not getting the multiple root elements error? I assume `myGridWrapper` would be a render-less component (rendering a slot with a render function). Then, whatever you throw in it, you're going to get the error.

**Comment by titouancreach** [comment] 2018-05-02 10:42
@adi518 You are getting an error if a component tries to render multiple nodes. But a function can returns an array, that is valid javascript

**Comment by adi518** [comment] 2018-05-02 12:16
Why, so what are the caveats of this workaround?

**Comment by fnlctrl** [comment] 2018-05-02 15:42
@adi518 
That's not a workaround... It's just adding a wrapping `<div>` around multiple nodes.
The only workaround is to use a functional component that doesn't have this single root limit, but you lose data/methods that normal components have.

**Comment by adi518** [comment] 2018-05-02 17:05
@titouancreach Sorry, I didn't see the reference to that snippet. In that case, yes, a functional does the job.

@fnlctrl Yea, only a functional component works, but no instance is a show stopper.

**Comment by titouancreach** [comment] 2018-05-03 08:09
@adi518 @fnlctrl the workaround is to split the big render function into multiple functions instead of creating a child component.

**Comment by jakemitchellxyz** [comment] 2018-05-06 17:16
Here's another use case. If you know how I could do this without multiple root nodes, please do tell, I'm kindof stumped.

Some details:
- I need the two elements in the same component because they reference each other. I could abstract the data out, but that seems messy and then scoping is weird.
- I cannot wrap these two elements in a div or anything because both elements are dynamically positioned on the page over other elements and I can't have elements covering other stuff because that will block mouseover events. I could disable mouse events on that parent wrapper, but having that invisible box there seems pointless.
- The dataset stuff is set by a script in another component not listed here, just take those for granted.

```
<template lang="html">
  <!-- 2D Target box to intercept mouseclicks on the 3D targets -->
  <div id="targetBox" @click="goto" @mouseenter="hover" @mouseleave="unhover"></div>

  <!-- Details Popup -->
  <div v-show="tShow" id="contextPopup">
    <h3 class="name">{{ tName }}</h3>
    <hr>
    <ul class="functions">
      <li v-for="func of tFunctions">{{ func }}</li>
    </ul>
    <div :class="[ 'triangle', 'small', tCorner ]"></div>
    <div :class="[ 'pointer', tCorner ]"></div>
  </div>
</template>

<script>
export default {
  name: 'Popups',
  data() {
    return {
      tShow: false,
      tName: '',
      tFunctions: [],
      tCorner: ''
    }
  },
  methods: {
    goto() {
      let target = document.getElementById('targetBox').dataset.dest
      if (target == this.$route.name) return
      this.$router.push({ name: target })
      this.tShow = false
    },
    hover() {
      let target = document.getElementById('targetBox')
      let popup = document.getElementById('contextPopup')

      // Update context popup info
      this.tName = target.dataset.name
      this.tFunctions = target.dataset.functions.split(';')

      // Figure out which corner to render contextPopup
      let l = (target.dataset.l == 'true') ? 'l' : 'r'
      let t = (target.dataset.t == 'true') ? 't' : 'b'
      this.tCorner = t + l

      // Position in a corner
      popup.style.left = target.dataset.popLeft + 'px'
      popup.style.top = target.dataset.popTop + 'px'

      // Render the popup
      this.tShow = true
    },
    unhover() { this.tShow = false }
  },
}
</script>

```

**Comment by adi518** [comment] 2018-05-09 22:54
@titouancreach That will only work with a functional component.

**Comment by erikweebly** [comment] 2018-05-10 23:48
Is a general solution just to have two components, one that purely handles the DOM layout, and another that configures the actual elements? So....

```vue
<!-- a-table-of-two-bodies.vue -->
<template>
  <table>
    <slot name="first-body" />
    <slot name="second-body />
  </table>
<template>
```
And then to use it:
```vue
<a-table-of-two-bodies>
   <tbody slot="first-body">
	<tr @click="showItems = true">
		<td>{{ category.id }}</td>
		<td>{{ category.name }}</td>
	</tr>
   </tbody>
   <tbody slot="second-body" v-show="showItems">
      <tr v-for="item in category.items">...<tr>
   </tbody>
</a-table-of-two-bodies>
```
Maybe this is what @sirlancelot was referring to?

**Comment by titouancreach** [comment] 2018-05-14 07:30
@adi518 This will work with anything because we don't create any children here, we are just splitting (compose) the render function. It's just pure javascript.

**Comment by bbugh** [comment] 2018-05-28 15:30
@tochoromero how did you solve your `input-group-addon` issue with Bootstrap? I came here via the same problem, that Bootstrap has really specific ordering for these addons and an extra wrapping div breaks it.

**Comment by tochoromero** [comment] 2018-05-28 15:54
@bbugh I really didn't solve it, I just tried to make my component as generic as possible but still wrapping it on a `div` with the `input-group` class :(

**Comment by chipit24** [comment] 2018-06-11 17:54
Another possible workaround, besides using `display: contents`, is using https://linusborg.github.io/portal-vue. With `portal-vue`, the grid could be set up something like this:

```html
<!-- grid-container.vue -->
<portal-target multiple name="grid" />

<!-- grid-child-1.vue -->
<portal to="grid">
  <div>child 1 content</div>
  <div>more child 1 content</div>
</portal>

<!-- grid-child-2.vue -->
<portal to="grid"><div>child 2 content</div></portal>
```

The above would render the following:

```
<div class="vue-portal-target">
  <div>child 1 content</div>
  <div>more child 1 content</div>
  <div>child 2 content</div>
</div>
```

**Comment by adi518** [comment] 2018-06-11 18:05
@chipit24 Yes, but that solution still includes a parent element. The whole point is being able to render with a parent.

**Comment by yordis** [comment] 2018-06-11 18:21
@adi518 but `Fragment` is a parent element but is a virtual one so I am confused with what you mean by that.

Should it render any element? no it shouldn't
Could be like Fragment? absolutely, the whole issue with this is rendering an extra element, no necessarily using another component as a wrapper.

**Comment by chipit24** [comment] 2018-06-11 18:55
@adi518 The `portal` elements in my example do not render a parent element, so I'm not sure what you mean.

This is a top hit for me in Google, and I'm posting an example that wasn't mentioned before of how to work around not having actual fragments. The example I posted works for my use case.

**Comment by adi518** [comment] 2018-06-11 20:49
It won't work in the sense that the Portal component adds its wrapper element, as it is a stateful component `<div class="vue-portal-target">{{ $children }}</div>` . You are still constrained. Your solution is good for that case. When you _really_ need no parent elements at all you are stuck until Vue actually adds this functionality.

**Comment by y-nk** [comment] 2018-06-13 02:27
I'm sorry if i'm posting stupid answer. I'm still rookie in VueJS. I think I kinda found a suitable solution which supports all the requirements : fragment can be root, and are not functional.

Can you guys check this : https://www.npmjs.com/package/vue-fragments ?

**Comment by adi518** [comment] 2018-06-13 02:53
@y-nk That's an interesting approach.

**Comment by y-nk** [comment] 2018-06-13 08:59
@adi518 my understanding of vDOM doesn't allow me to do it for SSR. My main problem is about finding the parent of that fragment enabled node. it seems impossible to find the exact place it is inserted and i don't know why. such a mystery is ... mesmerizing. If anybody can help, that would be more than welcome...

**Comment by adi518** [comment] 2018-06-13 18:36
@y-nk Done some adjustment to your solution: https://github.com/y-nk/vue-fragments/issues/1

**Comment by yordis** [comment] 2018-06-13 19:28
I don't believe that this issue is more complicated than 

```
Vue.component("vue-fragment", {
  functional: true,
  render(h, { children }) {
    return children;
  }
});
```

Functional components allow you to send back a list of elements instead of a single one.

```
<vue-fragment>
      <h1>Hello</h1>
      <p>World</p>
    </vue-fragment>
```

This will render directly into the parent component the children without adding an extra component.

**Comment by y-nk** [comment] 2018-06-14 01:59
@adi518 thanks a lot for your feedbacks/corrections :) i'm trying hard to work on SSR but it's a case i cannot really crack yet.

**Comment by y-nk** [comment] 2018-06-20 08:44
@adi518 added `abstract` so it's now totally transparent within the tree (parent and children are linked correctly without the v-fragment node in between)

anyone to review/correct/contribute-to-ssr ?

**Comment by JoshuaSoileau** [comment] 2018-07-09 20:59
+1 for a solution for this

**Comment by rentalhost** [comment] 2018-07-18 02:55
**Additional note:** while `<tbody>` will solves 90% of `<table>` issues, cases where it should generates two `<option>` need a bit of hack. 

Simplified case:

```
<template>
    <option :value="x">X</option>
    <option :value="x + 1">X + 1</option>
</template>
```

Currently is impossible do that without some kind of wrapper hack, because anything inside `<select>` that not `<optgroup>` or `<option>` will be ignored by browser, and `<optgroup>` will change the behavior.

The same could be applied to example below:

```
<template v-for="x in range">
    <option :value="x" v-text="someMagic(x)"></option>
</template>
```

Someone have some clue to where we could try improve the current code to support that? At least a start point, so some devs could try to help the vue team too.

**Comment by effulgentsia** [comment] 2018-07-19 18:44
@rentalhost: I'm not a Vue dev, but thank you for the `<option>` use-case. I'm curious, can you elaborate a bit more on it? What's your use-case of wanting `<option>` values output in a different template than the one that outputs the `<select>`?

**Comment by rentalhost** [comment] 2018-07-20 03:07
@effulgentsia so... basically, I have an API that will returns a file tree like that [pastebin](https://pastebin.com/H5QPkHNd). User can select any file from some folder. So the final structure should be like ([jsfiddle](https://jsfiddle.net/k26j3rne/1/)): (Note the InnerFolder indent because it is inside of OuterFolder.)

```html
<select>
    <option disabled>🖿 OuterFolder</option>
    <option> FileA.ext</option>
    <option> FileB.ext</option>
    <option disabled></option>
    <option disabled> 🖿 InnerFolder</option>
    <option>  FileA.ext</option>
    <option>  FileB.ext</option>
</select>
```

The problem is that due to original API structure, the best way to do should be like:

```vue
<!-- VFolder.vue -->
<template>
    <select>
        <v-folder-option :folder="folder" :depth="0"></v-folder-option>
        <!-- where "folder" is the JSON root. -->
    </select>
</template>

<!-- VFolderOption.vue -->
<template>
    <option disabled></option>
    <option disabled v-text="depthSpacing() + folder.title"></option>
    <option v-for="node in folder.nodes" v-text="depthSpacing() + node.title"></option>
    <v-folder-option v-for="child in folder.children" :folder="child" :depth="depth + 1"></v-folder-option>
</template>
```

But this approach is impossible for now.

So what I had to did was to "collapse" the API JSON to a "single level", so I got something like that [pastebin](https://pastebin.com/WJJnmD7p). With that I could build a yet compatible way, like that:

```vue
<!-- VFolder.vue -->
<template>
    <select>
        <template v-for="node in nodes">
            <template v-if="node.type === 'folder'">
                <option disabled></option>
                <option disabled v-text="depthSpacing(node.depth) + node.title"></option>
            </template>
            <template v-else>
                <option v-text="depthSpacing(node.depth) + node.title"></option>
            </template>
        </template>
    </select>
</template>
```

The vue seems more simple, but the collapse method should be considered as part of a new complexity.

**Comment by adamchenwei** [comment] 2018-09-12 18:49
so there is still not yet a solution to render multiple children like `React.Fragment` does?
Just wondering, I know stuff like this can take time, just has been seen suggestions but did not see any follow up... 

Note: I am writing Vue with JSX btw...

**Comment by lebesnec** [comment] 2018-09-14 16:01
if allowing multiple root is too difficult to implement, would'nt it be possible to provide a custom tag which serves as an invisible wrapper, exactly like the `<template>` tag ? (except that the `<template>` tag cannot be included inside another `<template>` tag).

**Comment by sirlancelot** [comment] 2018-09-14 23:33
Two solutions have existed for quite some time now:

* Use a vue functional component (see the [second comment of this issue](https://github.com/vuejs/vue/issues/7088#issuecomment-345855657))
* Use [vue-fragments](https://github.com/y-nk/vue-fragments) (third-party extension)

@posva Can we get this thread locked so that future readers will see these solutions?

**Comment by posva** [comment] 2021-02-24 11:30
Closing as this was implemented in Vue 3 but cannot be backported to Vue 2

**Closed by posva** 2021-02-24 11:30 UTC
Labels: feature request
