### ISSUE TITLE
push   shift causes rerender of all items

### ISSUE THREAD

**Issue by hastom** [vuejs/vue#6827] opened 2017-10-16 14:14 UTC
### Version
2.5.2

### Reproduction link
[https://jsfiddle.net/hastom/uomhejLe/4/](https://jsfiddle.net/hastom/uomhejLe/4/

### Steps to reproduce
1. Inspect list with dev tools
2. Click add to end button
3. All <li> nodes highlithed that means they were updated

### What is expected?
First item dropped, new item inserted at the end of the list, other items stay still

### What is actually happening?
All items dropped, new items inserted

---
I first discovered this behavior while trying to create a dynamic list moving up and down with transiotion (of "top" property) on each element. Moving down was OK, transition applied correctly. Moving up was just moving elements without any trasition. I went deeper and discovered whole list was rerendered so transition was not applied.

**Comment by posva** [comment] 2017-10-16 16:20
`v-html` changes the whole HTML
If you're talking about real lists, then you can control which one is reused by using the `key` attribute

**Comment by hastom** [comment] 2017-10-16 18:07
@posva sorry, provided wrong fiddle link.
That one is right https://jsfiddle.net/hastom/uomhejLe/4/

**Comment by posva** [comment] 2017-10-16 20:41
Ah, thanks!
I'm not sure it's something that can be improved for sure, it may be due to the strategy used to patch the nodes

**Comment by hastom** [comment] 2017-10-16 20:57
It seems strange to me that only push + shift causes rerender. Only push is ok, only unshift also ok, pop + unshift also fine. And btw if i wrap unshift with setTimeout(...,0) it fixes issue. (But i do not want to use such hacks)

**Comment by yyx990803** [comment] 2017-10-17 03:11
Duplicate of #4362

**Closed by yyx990803** 2017-10-17 03:11 UTC
