### ISSUE TITLE
unreachable code after return statement

### ISSUE THREAD

**Issue by sealte** [vuejs/vue#8133] opened 2018-05-04 09:44 UTC
### Version
2.5.16

### Reproduction link
[https://cn.vuejs.org/v2/guide/transitions.html#%E5%8A%A8%E6%80%81%E8%BF%87%E6%B8%A1](https://cn.vuejs.org/v2/guide/transitions.html#%E5%8A%A8%E6%80%81%E8%BF%87%E6%B8%A1)

### Steps to reproduce
none

### What is expected?
none

### What is actually happening?
Firefox Quantum 59.0.3(64-bit)

debugger console:
unreachable code after return statement  (vue.js:3:21)

**Comment by LinusBorg** [comment] 2018-05-04 11:37
Closing because you didn't follow the issue requirements. 

We have no way to reproduce this.

**Closed by LinusBorg** 2018-05-04 11:37 UTC

**Comment by aurimus** [comment] 2019-11-25 00:42
I have the same issue

### Version
2.6.10

### Reproduction link
[https://github.com/aurimus/google-calendar-weekly-timetable](https://github.com/aurimus/google-calendar-weekly-timetable)

### Steps to reproduce
You would have to install the plugin in WordPress

### What is expected?
I don't expect Firefox to give this warning for the inside of vue.js

### What is actually happening?
Firefox (but not Chrome) gives 4 warnings for the inside of vue.js code (downloaded from vuejs.org)

unreachable code after return statement
vue.js:3:35

unreachable code after return statement
vue.js:3:56

unreachable code after return statement
vue.js:3:32

unreachable code after return statement
vue.js:3:41
