### ISSUE TITLE
Application freezes with 10.000 Components [Chrome De-Optimization]

### ISSUE THREAD

**Issue by martinoppitz** [vuejs/vue#5023] opened 2017-02-27 09:40 UTC
### Vue.js version
2.2.1

### Reproduction Link

(Caution: It may freeze your browser) https://jsfiddle.net/ywqwd19w/9/

### Steps to reproduce
increment
```js
var BENCHMARK_LIST_LENGTH = 1000;
```

### What is Expected?
Application continues to render quickly.

### What is actually happening?
Application freezes with BENCHMARK_LIST_LENGTH = 10000; *needs 120.000 ms*

### Compared with AngularJS@1.6.2 and Angular@4.0.0-rc.1

**var BENCHMARK_LIST_LENGTH = 10.000;**

AngularJS 1.6.2 (**1.737 ms**)
Angular: 4.0.0-rc.1 (**936 ms**)

**Comment by Akryum** [comment] 2017-02-27 10:07
You may want to use [functional components](https://vuejs.org/v2/guide/render-function.html#Functional-Components) in performance-critical scenarios ([example](https://jsfiddle.net/Akryum/dtm2zan2/)).

**Comment by LinusBorg** [comment] 2017-02-27 10:14
Still thats weird ...

**Comment by Akryum** [comment] 2017-02-27 10:21
Isn't Vue setting up reactivity on every component taking some time?

**Comment by posva** [comment] 2017-02-27 10:25
You can use the minified version: `<script src="https://unpkg.com/vue/dist/vue.min.js"></script>` to get a _real_ benchmark. Although you should use compiled templates too.

**Comment by LinusBorg** [comment] 2017-02-27 10:31
it's only one array on the wrapper component, containing numbers. there's not much to set up.

Some observations:

* original benchmark renders after 6.4s for me
* `Object.freeze(BENCHMARK_LIST)` doesn't make any difference  (as expected, since reactive setup required for this is minimal)
* Adding a `:key`="item"` even makes it a tad slower at 6.8s
* using 2.1.1 renders after  3.6s (so a regression perhaps?)

### Using Minified versions (as @posva said, that's the real benchmark):

* `2.1.1`:  2.3s
* `2.2.1`: 2.2s

So 2.2 is not slower (no regression) on my machine.

Can't compare to the angular values from OP as he didn't provide those benchmarks as a fiddle.

**Comment by posva** [comment] 2017-02-27 10:53
btw compiling templates is easy too:

```js
const App = {
  data: () => {
    console.info(Math.round(window.performance.now() - BENCHMARK_TIMER) + ' ms'); // eslint-disable-line no-console
    return {
      items: BENCHMARK_LIST
    }
  },
  ...Vue.compile(`<div>
  <version v-for="item in items"></version>
</div>`)
}
```

**Comment by LinusBorg** [comment] 2017-02-27 11:16
...and some further updates: in latest Chrome on Windows I can kind of replicate this.

First of all, this is a bad implementation
```javascript
mounted: function() {
    this.timer = Math.round(window.performance.now() - BENCHMARK_TIMER);
  },
```
because it forces Vue to re-render each component right after the initial render and re-patch the DOM.

In latest chrome, this needs ~90s to render (!!) - my above previous tests where done on an outdated version (using portable chrome due to company IT restrictions... don'T ask)

However, changing `mounted` to `created` gives me about the same numbers as in my previous analysis above.

So somethings really off here :/ `created` should bring a little improvemend, of course, but not like 10000% ^^

**Comment by LinusBorg** [comment] 2017-02-27 11:19
...and a 3rd test: The "crash" scenario performs much better in IE11 (!!!):

![image](https://cloud.githubusercontent.com/assets/1444526/23359547/fab3e374-fce6-11e6-8b4f-46ea9283ceb2.png)

Far from good as well, but it seems we have a de-optimization in Chrome here, so this is likely related to #5012 ?

**Comment by yyx990803** [comment] 2017-02-27 14:03
Yeah, seems there's again a Chrome-only deopt... the same thing runs around 400ms in Safari for me :/

**Comment by kailniris** [comment] 2017-02-27 14:10
I am no expert but does not this related to the new V8 update?
https://v8project.blogspot.hu/2016/12/v8-release-56.html
Originally I experienced the #5012 issue with Chromium 56 if I remember correctly.

**Comment by martinoppitz** [comment] 2017-02-27 15:21
Thanks you all.

I recep this. Now the functional variant is fast. 10.000 components in round about 2s.

Is there a transpiler to make inline html to functional style. I think that is like Angular-AOT.

Now I will check Angular 4 with AOT.

**Comment by martinoppitz** [comment] 2017-03-01 04:25
Hello. 

I think the difference beetween Angular and Vue is the moment of component instantiation.

Vue instantiate all components before the app starts.

Angular instantiate components everytime it will used.

Now I believe that Vue startup time increases with the number of components.

**This was obviously my original mistake.**

**Comment by LinusBorg** [comment] 2017-03-06 09:33
> Vue instantiate all components before the app starts.

Uhm... no? Not 100% sure what you mean, but the answer is most probably: "no"

**Comment by martinoppitz** [comment] 2017-03-06 10:42
``♧0♧

**Comment by LinusBorg** [comment] 2017-03-06 11:50
I still don't understand what you mean, what gets instantiated, what gets bound (and to what)?

Yes, Vue does create constructors (if you meqn that) for all components (that are not lazy-loaded), but so would angular with its class decorator, wouldn't it?

**Comment by LinusBorg** [comment] 2017-03-06 11:53
Also I don't see how any of this should her anything to do with the chrome de-optimization discussed in this issue...

**Comment by martinoppitz** [comment] 2017-03-06 13:06
Yes that is not my issue and topic

**Comment by martinoppitz** [comment] 2017-03-06 13:07
Read the issue at the top.

**Comment by martinoppitz** [comment] 2017-03-06 13:07
10.000 different components cat freeze the app. I must try it again.

**Comment by Uriziel01** [comment] 2017-03-06 13:28
@martinoppitz chill out please, everyone (including @LinusBorg) is just trying to help You here.

And just for the note:
Please try to speak your thoughts in a more clear/understandable matter so there will be no future misunderstandings. Im sure someone will solve your concerns eventually.

Have a nice day!

**Comment by LinusBorg** [comment] 2017-03-06 13:55
@Uriziel01 I'm totally chill, don't worry :)

I just want to make sure I understand Martin's question, to be able to answer properly, which I'm having a hard time with.

> Read the issue at the top.

I have. You can see that I was one of the first to try and get to the bottom of this.

> About the issue: The bug with rendering 10.000 components is

We have a bug/de-optimization in Chrome's VM? We can't do much about this, it has to be fixed in Chrome/V8.

Fortunately, someone from Google's team replied about this [here](https://github.com/vuejs/vue/issues/5012#issuecomment-284172367), and they seem to have fixed it [here](https://github.com/vuejs/vue/issues/5012#issuecomment-284387034)

So we have to wait till this goes live.

Apart from that, I still don't understand what this question means - I' willing to answer it once I understand it:

> I think the difference beetween Angular and Vue is the moment of component instantiation.
> Vue instantiate all components before the app starts.
> Angular instantiate components everytime it will used.

**Comment by martinoppitz** [comment] 2017-03-06 18:05
Hello.

"Sorry I am not angry." - Everything is fine.

I would like to say, that my issue is non-Chrome De-Optimization topic. The title was changed from @LinusBorg.

Next I will provide a running example on  https://jsfiddle.net.

See you next.

Thank you all - sorry for my unclear messages!

**Comment by martinoppitz** [comment] 2017-03-06 22:14
Hello.

Here is a vue implementation with one component. You can increment the constant `BENCHMARK_NUMBER_OF_DIFFERENT_COMPONENTS` and you will see, that the startup-time is increase.

Link: https://jsfiddle.net/moppitz/8bL8jad1/11/

Now I will check an Angular implementation.

**Comment by yyx990803** [comment] 2017-03-07 02:00
@martinoppitz yeah, that is expected behavior. The benchmark shows that Vue instances are heavier than Angular component instances, but this metric alone doesn't really say much about performance in real world scenarios where component instantiation is usually only a small proportion of all the bootstrap work. And as you said, it's also unrealistic to have 200,000 component instances - most of the time it will be in the hundreds.

We of course will continue to improve the startup performance, but for this particular aspect there aren't much actionable items for now.

**Closed by yyx990803** 2017-03-07 02:00 UTC

**Comment by martinoppitz** [comment] 2017-03-07 05:21
@yyx990803 Thank you for your confirmation.
