### ISSUE TITLE
transition   keep-alive 导致组件加载错误

### ISSUE THREAD

**Issue by xiaohaiH** [vuejs/vue#10316] opened 2019-07-26 02:51 UTC
### Version
2.6.10

### Reproduction link
[https://codepen.io/xiaohai/pen/zgKwyZ?editors=1010](https://codepen.io/xiaohai/pen/zgKwyZ?editors=1010)

### Steps to reproduce
1. 点击二级路由A
2. 点击一级路由
3. 点击二级路由B
此时加载的组件却是 二级路由A

### What is expected?
修复这个问题

### What is actually happening?
使用 transition 与 keep-alive 时, transition 的 mode 设置为 out-in, 会导致路由组件加载错误

**Comment by posva** [comment] 2019-07-26 07:15
Duplicate of https://github.com/vuejs/vue-router/issues/1242

**Closed by posva** 2019-07-26 07:15 UTC
