### ISSUE TITLE
@click.prevent causes checkbox :checked property to not render

### ISSUE THREAD

**Issue by Meekohi** [vuejs/vue#10282] opened 2019-07-16 19:16 UTC
### Version
2.6.10

### Reproduction link
[https://codepen.io/meekohi/pen/jjgezj](https://codepen.io/meekohi/pen/jjgezj)

### Steps to reproduce
Use `@click.prevent=` along with a `:checked='booleanComponentProp'` on a checkbox. Clicking the checkbox correctly updates all data, but the checkbox visually remains in whatever the original state was.

### What is expected?
Checkbox should update based on the `:checked` property.

### What is actually happening?
Checkbox does not update.

---
This bug did not exist in Vue 2.5.22 -- it seems like Vue 2.6 started relying on the native `click` event to change the state of the box for the simple case, but if the underlying property changes via some other mechanism (for example a prop updating) then the checkbox visual appearance gets out of sync with the underlying data.

**Comment by posva** [comment] 2019-07-16 19:30
Duplicate of https://github.com/vuejs/vue/issues/9535
Related to changes in micro/macro tasks (https://github.com/vuejs/vue/issues/9340)

**Closed by posva** 2019-07-16 19:30 UTC
