### ISSUE TITLE
History Mode - Cannot Refresh Page Without 404

### ISSUE THREAD

**Issue by baberuth22** [vuejs/vue#4735] opened 2017-01-18 00:48 UTC
In order to have nice looking paths without hash or bang, I am using history mode:

var router = new VueRouter({
  routes: routes,
  mode: 'history'
})

However, when I refresh a page, I get a 404 error.  If I remove mode: 'history', I can go directly to urls at a path and refresh pages in my browser.

Can I remove hash and bang (#!) from my urls and be able to refresh pages and use direct urls to a path?

**Comment by rpkilby** [comment] 2017-01-18 01:01
Same issue as #4697?

**Comment by SkaterDad** [comment] 2017-01-18 01:02
This is an issue with your web server configuration.   Your server needs to be set up to deliver your page for all URLs (assuming you don't have other endpoints on the server). 

What server or service are you using to deliver your page?

**Comment by defcc** [comment] 2017-01-18 01:45
Thanks @baberuth22 , this is an issue with vue-router, you could open an issue in the vue-router repository next time.

---------

As @rpkilby and @SkaterDad mentioned,  duplicate of #4697. You could get more information here:  https://router.vuejs.org/en/essentials/history-mode.html

**Closed by defcc** 2017-01-18 01:45 UTC

**Comment by baberuth22** [comment] 2017-01-18 02:02
@SkaterDad I am using a Linux box with Apache server.   For development I am using an OSX.

**Comment by BonBonSlick** [comment] 2019-08-21 15:21
Docs are outdated.
My configs
```
location / {
  try_files $uri $uri/ /index.html;
}
```

error

`500 Internal Server Error`


```
location / {
  try_files $uri $uri/ /;
}
```

error
`Refused to execute script from 'https://131232/video/main.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.`

**Comment by csperando** [comment] 2023-03-26 04:30
It is not clear from the docs, but you may have to update multiple config files for nginx to handle these rewrites on refresh correctly. This article was very helpful to me: https://techformist.com/request-redirect-nginx-spa/#nginx-redirection-in-spas

I was running a vue app in a docker container and needed to copy edited versions of both `/etc/nginx/conf.d/default.conf` and `/etc/nginx/nginx.conf`. Now everything is working as expected.
