### ISSUE TITLE
Shorthand for property passing :value vs :value="value"

### ISSUE THREAD

**Issue by buzdyk** [vuejs/vue#10463] opened 2019-09-02 10:08 UTC
### What problem does this feature solve?
Subject pretty much sums it all up. More often than not a property name matches a variable name. Typing :value="value" :options="options" looks a bit excessive.

Feature is strictly cosmetics but it would help us to write less and more expressive code.

### What does the proposed API look like?
`<component :prop1 :prop2 />` would automatically pass prop1 and prop2 to the component. If prop1/prop2 is not defined undefined would be passed instead. Additionally a warning would be printed to the console.

**Comment by posva** [comment] 2019-09-02 10:10
Duplicate of https://github.com/vuejs/vue/issues/5835

**Closed by posva** 2019-09-02 10:10 UTC
