### ISSUE TITLE
`updated` life cycle invoked after component has been destroyed

### ISSUE THREAD

**Issue by fate-lovely** [vuejs/vue#8252] opened 2018-05-27 14:03 UTC
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/50wL7mdz/337120/](https://jsfiddle.net/50wL7mdz/337120/)

### Steps to reproduce
1. open console
2. click todo item
3. you will see `destroyed` and `updated`

### What is expected?
only `destroyed` is printed.

`updated` life cycle should not be invoked after component has been destroyed.

### What is actually happening?
`updated` life cycle invoked after component has been destroyed.

**Comment by Justineo** [comment] 2018-05-27 14:36
See #8076.

**Comment by posva** [comment] 2018-05-27 15:00
Duplicate of #8076

**Closed by posva** 2018-05-27 15:00 UTC
