### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by ptzremoute** [vuejs/vue#12228] opened 2021-08-19 15:29 UTC
### Version
2.6.14

### Reproduction link
[https://jsfiddle.net/3wbpgrky/](https://jsfiddle.net/3wbpgrky/)

### Steps to reproduce
Use v-for on hude array and template tag or functional component which return array of elements. "RangeError: Maximum call stack size exceeded" exception will be thrown.

### What is expected?
normal rendering

### What is actually happening?
exception

---
call stack:

RangeError: Maximum call stack size exceeded
    at normalizeArrayChildren (vue:2402)
    at normalizeChildren (vue:2377)
    at _createElement (vue:3427)
    at createElement (vue:3381)
    at Proxy.vm._c (vue:3518)
    at Proxy.eval (eval at createFunction (vue:11698), <anonymous>:3:62)
    at Vue._render (vue:3572)
    at Vue.updateComponent (vue:4082)
    at Watcher.get (vue:4494)
    at new Watcher (vue:4483)

Exception will be at 'simpleNormalizeChildren ' if functional component is used.

**Comment by posva** [comment] 2021-08-19 15:49
Duplicate of #11389

**Closed by posva** 2021-08-19 15:49 UTC
