### ISSUE TITLE
Maximum call stack exceeded when using with custom components

### ISSUE THREAD

**Issue by konstantinrachev** [vuejs/vue#7788] opened 2018-03-10 11:23 UTC
### Version
2.5.14

### Reproduction link
[https://jsfiddle.net/50wL7mdz/175425/](https://jsfiddle.net/50wL7mdz/175425/)

### Steps to reproduce
1. Including vue(v.2.5.14) and element.io styles and library.
2. Opening new form.
3. Opening new form element.
4. Using custom date picker element.

### What is expected?
It is expected to render a custom UI component for date picking.

### What is actually happening?
The element is not being render as the console is filled with errors.

[Vue warn]: Error in render: "RangeError: Maximum call stack size exceeded", vue.js:597
RangeError: Maximum call stack size exceeded, vue.js:1745

---
The issue is related to the latest vue.js version as it is working as expected with all up to 2.5.13.

**Comment by posva** [comment] 2018-03-10 12:28
Duplicate of #7786

**Closed by posva** 2018-03-10 12:28 UTC

**Comment by dorianWB** [comment] 2018-03-19 17:07
I still get this error, but I haven't got the time to put together a reproduction case right now. I know that it exists in 2.5.16 still and going back to 2.5.13 resolves the issue and the error looks like `RangeError: Maximum call stack size exceeded
    at Function.[Symbol.hasInstance] (<anonymous>)
    at t (app.c84200b64a284b43c3fe.js:1)` which t is the _traverse function and the error is in https://github.com/vuejs/vue/blob/84a9a9d61057f6f40a9ad2bee456b39ef0a8f001/src/core/observer/traverse.js#L19-L24

**Comment by rowild** [comment] 2018-08-18 11:56
I also get this error, when `document.querySelector()` tries to bind DOM to a configuration element, that is set to store.config via a mutation. (The function is called from root element's mounted() ) ...

**Comment by Darkside73** [comment] 2018-09-11 16:32
Confirming this issue when store in a strict mode (using nuxt)

**Comment by sarkiroka** [comment] 2018-10-10 10:09
Confirming too

**Comment by khendry** [comment] 2018-11-15 13:34
I'm possibly seeing this as well. Can confirm that disabling strict mode in the vuex store seemed to fix the issue.

**Comment by konstantinrachev** [comment] 2018-11-15 17:13
Yeah, strict mode does seem to fix the issue.

**Comment by Gyanxie** [comment] 2019-01-21 10:40
var selfObj= {};
selfObj.self = selfObj; 
new Vue({ 
    computed: { selftWatch: function get() { return selfObj; } } , 
    watch: {  
          selftWatch: {  
                  deep: true, 
                  handler: function () { console.error('seccess run ')}
          } 
   }
});
看了下 _traverse  方法，没有对 对象去重，应该记录所有对象的引用。

**Comment by sellingsolutions** [comment] 2019-09-08 16:13
I was brought to this issue by searching for: 
Error in render: "RangeError: Maximum call stack size exceeded

However, it didn't have anything to do with the naming of components. It's probably related to what @Gyanxie posted above.

My offender was the code snippet below:
`watch: {
    '$vuetify.breakpoint': {
      handler: function(newBreakpoint) {
       
      },
      deep: true,
      immediate: true
    }
  }`

This might prove useful to the next person that runs into this cryptic error message
