### ISSUE TITLE
Don't create refs link without modifier

### ISSUE THREAD

**Issue by Drive4ik** [vuejs/vue#7959] opened 2018-04-03 17:20 UTC
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/vrLubr46/5/](https://jsfiddle.net/vrLubr46/5/)

### Steps to reproduce
`TypeError: "$refs.test is undefined"`

If you add modifier (.prevent .stop etc.) to `@click` error will gone

### What is expected?
Need work without any modifiers

### What is actually happening?
javascript error occurs

**Comment by sirlancelot** [comment] 2018-04-03 18:15
The issue is that during the initial render, `$refs` isn't populated. Overall though, I'd say that code is probably not good. `$refs` shouldn't be used inside templates, it's an escape hatch to be used in code.

You can avoid the bug by adding a method to your component which then calls the linked component like so: https://jsfiddle.net/vrLubr46/13/

**Comment by posva** [comment] 2018-04-04 11:12
Use a method or an inline function instead: `@click="() => $refs.test.open"`
Closing as there is already #3842

**Closed by posva** 2018-04-04 11:12 UTC
