### ISSUE TITLE
No way to catch a template compilation error in production build mode

### ISSUE THREAD

**Issue by joshholat** [vuejs/vue#11643] opened 2020-09-03 19:39 UTC
### Version
2.6.11

### Reproduction link
[https://jsbin.com/zoniwudugo/edit?html,console,output](https://jsbin.com/zoniwudugo/edit?html,console,output)

### Steps to reproduce
Attempt to instantiate an instance of Vue with a template where one of the bound props has no value.

### What is expected?
Given that the template fails to compile in any usable way whatsoever, I'd expect an error to be thrown so that it can be caught and sent to an error monitoring service.

### What is actually happening?
Warnings are turned off in Vue production mode, so there is no warning logged anywhere. Also, an error/exception is not thrown. Any HTML wrapped in the div registered for Vue is not rendered.

---
Our product is a Django app with mostly server rendered views. We're currently adding in some Vue components as we slowly migrate over to a SPA. As such, we ran ran in to this issue when some of our Django template code was incorrectly building a Vue component. Then when Vue tried to instantiate on the frontend, it was erring trying to compile the component template.

**Comment by posva** [comment] 2020-09-04 17:10
Duplicate of https://github.com/vuejs/vue/issues/8467

**Closed by posva** 2020-09-04 17:10 UTC
