### ISSUE TITLE
Scoped CSS not applied for programmatically added elements

### ISSUE THREAD

**Issue by jonasgroendahl** [vuejs/vue#7649] opened 2018-02-14 16:54 UTC
### Version
2.5.13

### Reproduction link
[https://codepen.io/anon/pen/oEGjqO](https://codepen.io/anon/pen/oEGjqO)

### Steps to reproduce
In Vue if you add elements programmatically, the scoped css is not applied to those elements inside the given .vue file. If you add the styling in the style tag or remove the scoped attribute, it will work.

Example:

```
<template>
<div class="item"></div>
</template>

<script>
export default{
created(){
  const item = document.querySelector(".item");
  item.innerHTML = "<div class="box"></div>";
}
</script>
<style scoped>
.box{
width:300px;
height:300px;
background:red
}
</style>
```
Intended or a bug?

### What is expected?
We expect the css to be applied

### What is actually happening?
It's not being applied

**Comment by ktsn** [comment] 2018-02-14 17:41
Duplicate of https://github.com/vuejs/vue-loader/issues/559 and https://github.com/vuejs/vue-loader/issues/749.

**Closed by ktsn** 2018-02-14 17:41 UTC

**Comment by dharmatv** [comment] 2018-10-12 08:13
at present i have same issue, but i am trying a lot with the /deep/ and also >>> but still i didn't get, is there any another solution to this one

Thanks
