### ISSUE TITLE
No [Vue warn] when mutating nested parent props

### ISSUE THREAD

**Issue by Astray-git** [vuejs/vue#7516] opened 2018-01-23 10:55 UTC
### Version
2.5.13

### Reproduction link
[https://jsfiddle.net/jbwxeunb/1/](https://jsfiddle.net/jbwxeunb/1/)

### Steps to reproduce
1. open console
2. click counter

### What is expected?
Show warning when mutating object prop

### What is actually happening?
Warning only shows up when mutating primitive props

**Comment by sqal** [comment] 2018-01-23 14:55
https://github.com/vuejs/vue/issues/6103#issuecomment-315266712

**Comment by posva** [comment] 2018-01-23 15:00
Duplicate of #6103

**Closed by posva** 2018-01-23 15:00 UTC
