### ISSUE TITLE
v-model on custom component behaves differently in IE and Edge

### ISSUE THREAD

**Issue by andrewcourtice** [vuejs/vue#4796] opened 2017-01-26 23:49 UTC
### Vue Version
2.1.10

### Issue Description
Based on other examples I've seen, when embedding a checkbox in a custom component a 'proxy' value has to be used to emulate the native `v-model` behaviour for a checkbox or radio input.

This is particularly important when binding `v-model` on the custom component to an array as opposed to a boolean.

This technique works fine in Firefox and Webkit-based browsers but fails in IE and Edge.

### Demonstration of Issue
[http://jsfiddle.net/andrewcourtice/jgxzbbvv/](http://jsfiddle.net/andrewcourtice/jgxzbbvv/)

### Steps to Reproduce
1. Open the above fiddle in a Firefox or a Webkit-based browser
2. Check the checkboxes and note the array of selected items being updated correctly
3. Open the above fiddle in IE or Edge
4. Check the checkboxes and note the difference in behaviour to step 2

### Expected Outcome
The array of selected items (and the raw output) should be updated as each item is checked.

### Actual Outcome
In IE and Edge the raw output is displaying a boolean value and the checked state of the checkboxes is inconsistent.

Thanks!

**Comment by denistsoi** [comment] 2017-01-27 07:59
Added IE-Edge screencap for reference; (no errors are popping up on the console either)

![screen shot 2017-01-27 at 3 57 56 pm](https://cloud.githubusercontent.com/assets/3061779/22364042/78c3188a-e4a9-11e6-8376-bed81f821da1.png)

**Comment by sqal** [comment] 2017-01-28 11:57
It's worth pointing out this worked fine in Vue <= 2.1.8

**Comment by sunnyone** [comment] 2017-02-02 10:00
+1

**Comment by Thijs5** [comment] 2017-02-14 08:08
+1

**Comment by denistsoi** [comment] 2017-02-14 08:46
@sunnyone, @Thijs5  - and for anyone else; don't populate the issue feed with +1; it's unhelpful and clearly, you need to use the "ADD REACTION" button if you want to drive attention to an issue.

**Comment by posva** [comment] 2017-02-14 09:28
Hey, sorry for the delay. Completely forgot about this.
This happens because the onChange fires before the computed setter in Edge. If you're using a computed setter, you don't need an onChange event handler, you should simply emit in the setter:

http://jsfiddle.net/bsy8ss2L/

**Comment by jdalton** [comment] 2017-02-21 18:54
@posva Could you provide a bit more info on the "onChange fires before the computed setter in Edge". How is the computed setter fired? I'm trying to get enough info for an Edge bug report.

**Comment by yyx990803** [comment] 2017-02-21 21:55
@jdalton AFAIK, the problem is that when clicking on the checkbox, the order of the `click` and `change` events being fired is different in IE/Edge than that in other browsers:

https://jsfiddle.net/rj3g9j0y/

Chrome/Safari/FF: click -> change
IE/Edge: change -> click

I'm not sure if this behavior is specified anywhere in the spec though.

**Comment by jdalton** [comment] 2017-02-21 22:02
Ah nice! Thanks for the simplified repro!

**Comment by posva** [comment] 2017-02-21 22:19
> I'm trying to get enough info for an Edge bug report

@jdalton awesome!

@yyx990803 BTW, should we close this since it's related to the browser firing in a different order?

**Comment by jdalton** [comment] 2017-02-21 22:27
I've reported the issue internally. I'll ping back when I get more info.

**Comment by yyx990803** [comment] 2017-02-22 00:38
@jdalton update: it seems PhantomJS and Safari also fire `change` before `click`.

The [spec](https://www.w3.org/TR/uievents/#event-flow-default-cancel) states that:

> Default actions are usually performed after the event dispatch has been completed, but in exceptional cases they may also be performed immediately before the event is dispatched.

So technically, `change` doesn't have to be fired after `click`. However, imo it really should because logically, `change` is a result of the default action for `click`. For example, if I do `event.preventDefault` inside a click listener on a checkbox, it should prevent the `change` event from happening altogether (this is the current behavior in Chrome/FF, but not in Safari/IE/Edge/PhantomJS).

**Comment by jdalton** [comment] 2017-02-22 00:42
Oh ya, not arguing for the current behavior. I think Edge should align with Chrome/FF.

**Closed** 2017-02-22 02:26 UTC
