### ISSUE TITLE
Bigint should be included when checking whether the value is primitive

### ISSUE THREAD

**Issue by Tzdy** [vuejs/vue#11769] opened 2020-11-13 07:16 UTC
### Version
2.6.11

### Reproduction link
[https://codepen.io/Tsdy/pen/mdEaYzL](https://codepen.io/Tsdy/pen/mdEaYzL)

### Steps to reproduce
src/shared/util.js
```
/**
 * Check if value is primitive.
 */
function isPrimitive (value){
  return (
    typeof value === 'string' ||
    typeof value === 'number' ||
    // $flow-disable-line
    typeof value === 'symbol' ||
    typeof value === 'boolean'
  )
}
console.log(isPrimitive(100n));
// false
```

### What is expected?
Bigint should be included in the primitive type

### What is actually happening?
console.log(isPrimitive(100n));
// false

**Comment by posva** [comment] 2020-11-13 08:26
Duplicate of https://github.com/vuejs/vue/issues/11126

**Closed by posva** 2020-11-13 08:26 UTC
