### ISSUE TITLE
scoped style not working in slot

### ISSUE THREAD

**Issue by shuai-z** [vuejs/vue#10565] opened 2019-09-26 08:16 UTC
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/embed/vue-template-ed9kk](https://codesandbox.io/embed/vue-template-ed9kk)

### Steps to reproduce
- click button

### What is expected?
Text "red" should be in red.

### What is actually happening?
Text "red" is black.

---
class="foo" is needed to make the OLD and NEW vnode the same (in sameVnode), so that Vue will try to patch instead of creating a new element.

**Comment by posva** [comment] 2019-09-26 08:21
Duplicate of https://github.com/vuejs/vue/issues/10452

**Closed by posva** 2019-09-26 08:21 UTC
