### ISSUE TITLE
v-once on template with only text children inside a v-for  does not work

### ISSUE THREAD

**Issue by xiangyuecn** [vuejs/vue#10892] opened 2019-12-04 14:33 UTC
### Version
2.6.10

### Reproduction link
[https://codepen.io/xiangyuecn/pen/eYmmPNP](https://codepen.io/xiangyuecn/pen/eYmmPNP)

### Steps to reproduce
1. Look at the [test code](https://codepen.io/xiangyuecn/pen/eYmmPNP) running interface. `OnceMsg`  area should have been static, but it is not!
2. Look at the `Test 3` part of the [test code](https://codepen.io/xiangyuecn/pen/eYmmPNP). It's exactly the same as the `Test 2` part, but their performance is not the same.
3. Similar to this kind of code, they are the same, but the results are different:
``` html
<div>
	<template v-once>[{{ getTime() }}] {{ name }}</template>
	<span v-once>[{{ getTime() }}] {{ name }}</span>
</div>
```
``` html
<div v-for="obj,idx in logs" :key="idx">
	<div>
		<template v-once>[{{ getTime() }}] {{ obj.msg }}</template>
		<span v-once>[{{ getTime() }}] {{ obj.msg }}</span>
	</div>
</div>
```

> *Use `<template v-once>` because I don't want to use more than one `span`, which will damage the DOM structure.*

### What is expected?
`<template v-once> in v-for` should be consistent with `<template v-once> not in v-for`, `OnceMsg`  area should have been static.

### What is actually happening?
`<template v-once> in v-for` and `<template v-once> not in v-for` are inconsistent, The leftmost time of `OnceMsg` area will change with the cycle.

**Comment by posva** [comment] 2019-12-04 22:35
Seems to be a duplicate of https://github.com/vuejs/vue/issues/8021 with PR at https://github.com/vuejs/vue/pull/8499

**Closed by posva** 2019-12-04 22:35 UTC
Labels: bug, has workaround

**Comment by xiangyuecn** [comment] 2019-12-05 01:44
@posva You may not understand the difference between this question and #8021. When I submitted this question, I have studied `8021`. `8021` has no substantive relationship with my question.

I have done the code test of clone #8499 PR, which has fixed the `8021` problem, but this PR has no effect on my problem.

![](https://user-images.githubusercontent.com/13175029/70196411-977caf00-1743-11ea-8535-c22b49c29c99.png)


--------

**Please pay special attention: My question is `v-once` of `template node tag`, `8021` is the `v-once`  of  `component template text`.**

My problem can be solved by setting a layer of tag(e.g:`span`、`div`) for developers, and `8021 component` structure can't handle it like this.

Please compare the difference between `Test 3` and `Test 4` in my [test code](https://codepen.io/xiangyuecn/pen/eYmmPNP).

--------

**I found that there is no issue in the issues list that is the same as the issue I found. If you understand the issue I said clearly, please open the issue, or give the reason why it can't be opened again.**

**Comment by xiangyuecn** [comment] 2019-12-05 02:06
@posva Oh man, you changed my title. But I found that you didn't write it. Refer to [my test](https://codepen.io/xiangyuecn/pen/eYmmPNP) code `Test 5`.

``` html
${/*Test 5:Non text only children are working, but may not*/""}
<span>
  <template v-once>[{{ getTime() }}] <span>{{ obj.msg }}</span></template> ${/*It works*/""}
  <span>Other</span>
  <template v-once>[{{ getTime() }}] <span>{{ obj.msg }}</span></template> ${/*It doesn't work*/""}
  <span>Other</span>
</span>
```

**Please change the title again.**

**Comment by mozhs** [comment] 2019-12-05 05:03
以下代码：
```
<div v-for="obj,idx in logs" :key="idx">
	<div>
		<template v-once>[{{ getTime() }}] {{ obj.msg }}</template>
		<span v-once>[{{ getTime() }}] {{ obj.msg }}</span>
	</div>
</div>
```
你在定时器中通过 splice 方法改变 logs 数组，会触发 v-for 重新执行，即会重新创建以下节点：
```
<div>
	<template v-once>[{{ getTime() }}] {{ obj.msg }}</template>
	<span v-once>[{{ getTime() }}] {{ obj.msg }}</span>
</div>
```
`v-once` 的定义是「数据变化不会触发DOM更新」，你这里的 v-for 导致重新创建。

以下代码测试的是「v-for里面的 v-once 是否随数据变化而更新」：
```
window.vm = new Vue({
	el: '#app',
	template: `
		<div v-for="item in logs" :key="item.id">
			<template>id: {{item.id}}, value: {{item.value}}</template>
			<br>
			<template v-once>id: {{item.id}}, value: {{item.value}}</template>
		</div>
	`,
	data () {
		return {
			logs: [
				{ id: 1, value: 'log1' },
				{ id: 2, value: 'log3' },
				{ id: 3, value: 'log4' },
			],
		};
	},
	created () {
		setTimeout(() => this.logs[0].value = 'log1.1', 1000);
	},
});
```
