### ISSUE TITLE
Don't render slots until their v-if is true

### ISSUE THREAD

**Issue by james2mid** [vuejs/vue#10019] opened 2019-05-13 15:35 UTC
### What problem does this feature solve?
Say there's a layout component with a navbar at the top and a main content area (the primary slot `<slot/>`). This component has the prop `loading` which, when true, shows a loading spinner in the main content area instead of the elements. I've included a basic example below.

At the moment, even when loading is true and the `v-if` for the `<slot/>` is false, the nodes are still being rendered. Ideally, `loading` here should only become false when all data has been loaded and it is safe to render the `<slot/>` elements.

Yes, I'm aware that I could just `v-if="!!var"` everything, but this can get very tedious and shouldn't be necessary (in my opinion).

I can imagine this would probably require quite a bit of stuff to be changed but I believe this is the ideal and desired functionality in this case. Sorry about the terminology, not quite sure what to call everything.

### What does the proposed API look like?
*Layout.vue*
```vue
<template>
  <div id="layout">
    <Navbar :nav-items="..." />

    <Spinner v-if="loading"/>
    <slot v-else/>
  </div>
</template>

<script>
import Vue from 'vue'

export default Vue.component('Layout', {
  props: {
    /** Whether to display the loading spinner instead of the content. */
    loading: Boolean
  }
})
</script>
```

*Implementation.vue*
```vue
<template>
  <Layout :loading="...">
    <p>{{ rendered.once.loaded }}</p>
  </Layout>
</template>
```

**Comment by posva** [comment] 2019-05-13 15:46
Duplicate of #9756

**Closed by posva** 2019-05-13 15:46 UTC
