### ISSUE TITLE
Absolutely-positioned flexbox child component with transition is duplicated in DOM when visibility is toggled via v-if in Firefox

### ISSUE THREAD

**Issue by decademoon** [vuejs/vue#3280] opened 2016-07-15 04:42 UTC
Vue 1.0.26
Firefox 47.0
### Reproduction Link

http://jsfiddle.net/5sH6A/523/
### Info
- Click the button to toggle the visibility of the `<test>` component.
- The entrance transition works, but the leave transition doesn't, causing the element to remain in the DOM indefinitely.
- Clicking the button multiple times results in multiple `<test>` components in the DOM.

The following things must be present for the bug to occur:
- It must be a component instance with visibility toggled via `v-if`.
- It must be a flexbox child.
- It must be positioned absolutely.
- It must have a transition.
- `Vue.config.debug` must be false.

**Comment by ajnudnyy** [comment] 2016-07-18 09:56
who has faced this iusse before entry cnpm run dev ? wind you mind tell what kind of reasons cause this following problem?
 
<img width="568" alt="2016-07-18 5 53 09 pm" src="https://cloud.githubusercontent.com/assets/18208441/16911393/cd44536e-4d10-11e6-8c40-2ae35fdc21a8.png">

**Comment by sqal** [comment] 2016-07-18 10:57
@ajnudnyy here's not the place for this kind of question, it's not Vue issue. You should look for the help on forum http://forum.vuejs.org/ or http://stackoverflow.com/

**Comment by dariuszsikorski** [comment] 2016-07-30 13:26
[side note] Checked on chrome 51 and even clicking toggle like crazy does not reproduce the reported problem, appears only for Firefox.

**Comment by posva** [comment] 2016-08-09 22:50
This looks like a Firefox bug to me: It doesn't seem to support absolute positioning inside a `display: flex` container. The animation is indeed messed up on Firefox 😕 and I think that's making impossible for Vue to listen for css transition events

**Comment by sqal** [comment] 2016-08-10 08:52
@posva But it works in 2.0 though

http://jsfiddle.net/xt3kabtr/

**Comment by decademoon** [comment] 2016-08-10 09:02
If `Vue.config.debug` is true then the bug doesn't occur. I dunno if that helps.

**Comment by posva** [comment] 2016-08-14 11:44
For the record What is happening here is that the transition is referring to the adjacent empty text node when debug is false and cannot remove the component. With debug = true it refers to the comment node and is somehow able to remove the component.

**Comment by AKST** [comment] 2016-12-11 22:13
Is this fixed in a `1.x` branch at all? I"m working on a project that hasn't been able to upgrade yet.

**Comment by yyx990803** [comment] 2018-04-17 21:38
Closing 1.x issues as 1.x is now end of life and will only receive critical security patches.

**Closed by yyx990803** 2018-04-17 21:38 UTC
Labels: 1.x, bug
