### ISSUE TITLE
Content in default slot causes component to re-render when the parent re-renders

### ISSUE THREAD

**Issue by JosephSilber** [vuejs/vue#8342] opened 2018-06-12 13:26 UTC
### Version
2.5.16

### Reproduction link
[https://codepen.io/JosephSilber/pen/KeWjzr](https://codepen.io/JosephSilber/pen/KeWjzr)

### Description

Passing content in a slot causes the component to re-render when the parent re-renders, even if the component's data hasn't changed.

### Steps to reproduce
1. Create a simple component that shows the amount of times it's been rendered:

    ```js
    Vue.component('times-rendered', {
        created() {
          this.timesRendered = 0
        },
        render(h) {        
          return h('div', `Times rendered: ${++this.timesRendered}`)
        }
    });
    ```

2. Use this component twice. Once with content in the default slot, once without. After the component is mounted, trigger any update to its data:

    ```html
    <template>
        <div>
          <div>{{ updateTrigger }}</div>
          <times-rendered></times-rendered>
          <times-rendered>
            Any content in the default slot causes a re-render. Why?
          </times-rendered>
        </div>
    </template>

    <script>
    export default {
        data: () => ({ updateTrigger: false }),
        
        async mounted() {
          await this.$nextTick()
          
          this.updateTrigger = true
        },
    };
    </script>
    ```

### What is expected?
I would expect each instance of the component to only render once.

### What is actually happening?
The component with content in the slot renders twice.

---
I'm not actually sure whether this is a bug or a feature request. Maybe this is expected behavior currently. If it is, then I guess this would be better classified as a feature request.

**Comment by jacekkarczmarczyk** [comment] 2018-06-12 13:42
Duplicate of https://github.com/vuejs/vue/issues/6351?

**Comment by posva** [comment] 2018-06-13 20:52
The rerender happens because the whole template renders again because of `updateTrigger`
Let's mark this as a duplicate of #6351

**Closed by posva** 2018-06-13 20:52 UTC
