### ISSUE TITLE
suggest change the pipe symbol of filter 建议变更过滤器管道所使用的语法符号

### ISSUE THREAD

**Issue by LongTengDao** [vuejs/vue#6977] opened 2017-10-31 07:16 UTC
### What problem does this feature solve? 这个功能解决了什么问题？

```html
<tag :attr="expression | filter | filter" />
```

The symbol `|` which is in use now, is a JavaScript symbol with it's origin use.
目前所采用的 `|` 符号在 JavaScript 里有其自身的用途。

Maybe the user want to write a exprssion with `|` like this:
使用者很可能想要的，本是一个像这样的包含 `|` 运算符的表达式：

```html
<tag :attr="a & b | c | d" />
```

### What does the proposed API look like? 你期望的 API 是怎样的？

Symbol `;` will never be used in an expression:
`;` 肯定不会出现在一个表达式中（因此没有冲突的可能）：

```html
<tag :attr="expression ; filterA ; filterB" />
```

Origin symbol `~` or `:` or `@` will never follow an expression:
原始语义的 `~` 或 `:` 或 `@` 也不会紧跟在一个表达式后面：

```html
<tag :attr="expression ~ filterA ~ filterB" />
<tag :attr="expression : filterA : filterB" />
<tag :attr="expression @ filterA @ filterB" />
```

Use other unemployed symbols look good:
采用其它未被使用的直观符号：

```html
<tag :attr="expression -> filterA -> filterB" />
```

**Comment by posva** [comment] 2017-10-31 08:38
Duplicate of #2422

Personally, I think that if pipes become part of js, we could adapt the syntax 🙂 
The pipe syntax is widely known because of the shell

**Closed by posva** 2017-10-31 08:38 UTC

**Comment by LongTengDao** [comment] 2017-10-31 13:52
@posva Thank you, and sorry to open duplicate issue. I think I can use `{{ ( a | b | c ) }}` if necessary at the moment.

**Comment by fnlctrl** [comment] 2017-10-31 14:00
FYI pipeline operator proposal: https://github.com/tc39/proposal-pipeline-operator

**Comment by LongTengDao** [comment] 2017-10-31 14:22
> @fnlctrl 
> 
> 参见：管道符语法提案（阶段1）l: https://github.com/tc39/proposal-pipeline-operator

Why do I feel full sense of humor... XD
我怎么觉着这么有喜感……XD
