### ISSUE TITLE
vue2.7 + ts can't recognize the global types declaration in sfc files

### ISSUE THREAD

**Issue by huhm** [vuejs/vue#12649] opened 2022-07-12 02:46 UTC
### Version
2.7.4

### Reproduction link
[sfc.vuejs.org/](https://sfc.vuejs.org/#eNp9kEFvgzAMhf+KlQubVGC7Moo07bJdd84lBReoQhLFptOo+O9zSrXDJlXKIe/F+ezni3oNoTjPqCpVUxvHwGCN6/daMWnVaNd6RwzLUsHHO3P4RAriYE0cR9c3sIeLdgDiz5YreNol1Rk2FWTUHeVkYq0vG8lbLKzvH7JlyXZCfRS/LrfG0kwE4xSsYRQFUA/PzZtxDDMh8IDQW38wFvg7IEGHrTXR8OiFIZWQWL//1U6NU/CR88mE4kTeScbrrPr2IAGrbfrkyRKS1mqQmFSVJR3btJkTFT72pdyKODseJyyQpvwQ/RdhFLBW18w3RinmGWMe0XUYMd5j/in9x03YVZan1h8FAZLe)

### Steps to reproduce
Step1.  create the project with @vue/cli 5.0.8; `vue create vue27-ts-mini`,  
```
        ?  Please pick a preset: Manually select features
	? Check the features needed for your project: Babel, TS, Router, Vuex, CSS Pre-processors, Linter
	? Choose a version of Vue.js that you want to start the project with 2.x
	? Use class-style component syntax? Yes
	? Use Babel alongside TypeScript (required for modern mode, auto-detected polyfills, transpiling JSX)? 
	Yes
	? Use history mode for router? (Requires proper server setup for index fallback in production) Yes     
	? Pick a CSS pre-processor (PostCSS, Autoprefixer and CSS Modules are supported by default): Less
	? Pick a linter / formatter config: Prettier
	? Pick additional lint features: Lint on save
	? Where do you prefer placing config for Babel, ESLint, etc.? In dedicated config files
```

Step2.   `mkdir types &&  mv src/*.d.ts types/  && pnpm i`

Step3.  edit shims-tsx.d.ts, add interface to global

```
import Vue, { VNode } from "vue";

declare global {
  namespace JSX {
    interface Element extends VNode { }
    interface ElementClass extends Vue { }
    interface IntrinsicElements {
      [elem: string]: any;
    }
  }

  interface IHttpResponse<T> {
    Result: number
    Reason?: string
    ErrCode?: number
    // ErrCode?:number
    data?: T

  }

}
```
Step4.  edit `.eslintrc.js `add ` "prettier/prettier": 0,`  to rules section
Step5.   add this code to main.ts and src/views/HomeView.vue

```
 const zz: IHttpResponse<string> = {
        Result: 0,
        data: 'sdfsdf',
      };
      console.log('zz', zz);
```

### What is expected?
No Warning

### What is actually happening?
the main.ts does not has any error.

the src/views/HomeView.vue has an no-undef warning:
[{
	"resource": "/D:/Playground/vue2.7-ts/vue2.7-ts/src/views/HomeView.vue",
	"owner": "eslint",
	"code": {
		"value": "no-undef",
		"target": {
			"$mid": 1,
			"external": "https://eslint.org/docs/rules/no-undef",
			"path": "/docs/rules/no-undef",
			"scheme": "https",
			"authority": "eslint.org"
		}
	},
	"severity": 8,
	"message": "'IHttpResponse' is not defined.",
	"source": "eslint",
	"startLineNumber": 11,
	"startColumn": 11,
	"endLineNumber": 11,
	"endColumn": 24
}]

![image](https://user-images.githubusercontent.com/3477901/178397452-6e13e61d-841b-4722-ba8e-b3676dd3e8c2.png)

**Comment by sodatea** [comment] 2022-07-12 16:18
Duplicate of https://github.com/vuejs/vue-eslint-parser/issues/99#issuecomment-1133922685

**Closed by sodatea** 2022-07-12 16:18 UTC

**Comment by huhm** [comment] 2022-07-13 01:26
thx,it works

**Comment by 1LISA2** [comment] 2022-09-03 04:27
![下载 (5)](https://user-images.githubusercontent.com/103248540/188255796-a43a2840-c814-4076-918b-d113ef38b909.jpeg)
