### ISSUE TITLE
Support container-less (no parent element) components 

### ISSUE THREAD

**Issue by HamedFathi** [vuejs/vue#9523] opened 2019-02-19 05:55 UTC
### What problem does this feature solve?

This is a problem to convert some Bootstrap 4 components (or other CSS frameworks) for example: 

```html
<div class="progress">
  <div class="progress-bar" role="progressbar" style="width: 15%" aria-valuenow="15" aria-valuemin="0" aria-valuemax="100"></div>
  <div class="progress-bar bg-success" role="progressbar" style="width: 30%" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100"></div>
  <div class="progress-bar bg-info" role="progressbar" style="width: 20%" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100"></div>
</div>
```

We can not create two components `progress-group` and `progress` because inside dives can not accept another div (`parent element`). Bootstrap 4 does not work in this way.

Existing `parent element` for each component destroys the Bootstrap 4 structure I can show you another examples:

```html
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="..." class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="..." class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="..." class="d-block w-100" alt="...">
    </div>
  </div>
```

```html
<div class="input-group mb-3">
  <div class="input-group-prepend">
    <span class="input-group-text">$</span>
  </div>
  <input type="text" class="form-control" aria-label="Amount (to the nearest dollar)">
  <div class="input-group-append">
    <span class="input-group-text">.00</span>
  </div>
</div>
```

and a lot more.

So I want to ask for **containerless (a component without `parent element` as a wrapper) feature** for component design system. It can help us to convert a CSS framework to complete Vue toolbox.

### What does the proposed API look like?
I am not sure the right way may be a config as `{ containerless : true }`

**Comment by Justineo** [comment] 2019-02-19 06:16
I don't get your point. I assume your examples are DOM structure required by Bootstrap but I don't see how Vue fails to render such structure. Can you elaborate on what structure you want your `progress-group` and `progress` components render into?

**Comment by askart** [comment] 2019-02-19 06:27
if i've understood you correctly, then
> Fragments & Portals: despite the size reduction, 3.0 comes with built-in support for Fragments (component returning multiple root nodes) and Portals (rendering a sub-tree in another part of the DOM, instead of inside the component).

**Comment by HamedFathi** [comment] 2019-02-19 07:35
@askart 

Yes exactly, unfortunately, my sample on bootstrap was not good enough.

Is it possible for Vue 3.0?

**Comment by Justineo** [comment] 2019-02-19 07:52
If you are asking for fragment support, then it's a duplicate of #7088.



> Is it possible for Vue 3.0?

Yes it's in the roadmap of Vue 3.0. We have no plans to support fragments in 2.x because it requires a major rewrite of our VDOM system.

**Closed by Justineo** 2019-02-19 07:52 UTC
