### ISSUE TITLE
Bug in multiple-select mouse event handling

### ISSUE THREAD

**Issue by mindplay-dk** [vuejs/vue#2032] opened 2015-12-16 12:49 UTC
When you click-drag to select multiple items in a select list (Chrome, Win10) the event handler misses the mouse-up event and doesn't trigger the model update:

![image](http://i.imgur.com/ii1vEk1.gif)

**Comment by yyx990803** [comment] 2015-12-16 16:41
This looks like a bug in Windows Chrome because when the mouse is released outside it's not firing the `change` event.

Safari 9 also has this behavior, but IE9/10/11, Mac Chrome and Firefox all correctly fire the `change` event.

While I'll try to see if there's a way to achieve consistent behavior in Vue, we should also file bugs for Chrome and Safari to fix this behavior.

**Comment by yyx990803** [comment] 2015-12-23 23:32
Confirmed this is indeed a Chrome/Chromium/Webkit bug, fired respectively at:

- https://code.google.com/p/chromium/issues/detail?id=571927
- https://bugs.webkit.org/show_bug.cgi?id=152540

This is a wontfix for Vue.js.

**Closed by yyx990803** 2015-12-23 23:32 UTC
