### ISSUE TITLE
[v2.2.0-beta.1] cannot access $refs in transition enter hook

### ISSUE THREAD

**Issue by sqal** [vuejs/vue#4998] opened 2017-02-24 10:38 UTC
### Vue.js version
v2.2.0-beta.1

### Reproduction Link
2.2.0-beta.1 with bug(?) - https://jsfiddle.net/sqal/6xug3huc/1/
2.1.10 working repo - https://jsfiddle.net/sqal/hx0cb267/1/

### Steps to reproduce
1. Click on the 'show' button to open the menu. In console you should see this error:
`Cannot read property 'updateScroll' of undefined`. It happens because `$refs` object is empty at this time.
2. But.. when we replace @enter hook with @after-enter, then everything works again and we have access to the $refs

And one more important thing. This bug occurs only when we use v-show to control visibility of the element. If we replace v-show with v-if, then this bug no longer happens.

### What is Expected?
I expect to have  access to component `$refs` inside transition @enter hook.

### What is actually happening?
Instead `$refs` object is empty when I try to access it inside @enter hook.

**Comment by yyx990803** [comment] 2017-02-24 23:20
Closed by reverting the ref callback changes. I think we'll just drop the feature because it's difficult to implement it without breaking backwards compat.

**Closed by yyx990803** 2017-02-24 23:20 UTC
Labels: 2.2, regression

**Comment by kindy** [comment] 2017-09-12 11:19
@yyx990803 
Some time we want to be notify if some component is rendered, the callback `ref` is very useful in those cases, else we need to implement events 'inited' in `mounted` for all components we want to monitor.

For the fail in this case, I think it's caused by `resetRefs`.
do we have any plan to get callback `ref` back? or can I give any help on this?

**Comment by tangjinzhou** [comment] 2018-11-15 05:58
@kindy
Maybe we can use directive to implement ref callback function.
I published a plugin [vue-ref](https://github.com/vueComponent/vue-ref), you can try it.
I used it in [ant-design-vue](https://github.com/vueComponent/ant-design-vue) and found no problems for the time being.
