### ISSUE TITLE
Using v-for on a functional component which returns multiple nodes renders "undefined"

### ISSUE THREAD

**Issue by Herteby** [vuejs/vue#8897] opened 2018-10-05 12:41 UTC
### Version
2.5.17

### Reproduction link
[https://jsfiddle.net/Herteby/r2nb09eg/](https://jsfiddle.net/Herteby/r2nb09eg/)

### Steps to reproduce
As the title says, or just look at the fiddle :)

### What is expected?
The slots should be rendered properly.
The combination of v-for and "fragment" should return an Array of VNodes.

### What is actually happening?
The slots render as "undefined"
It returns an Array of Arrays of Vnodes.

---
The problem seems to be that the result becomes an Array of Arrays of VNodes. Seems like it ought to be flattened.
For some reason, if you add an extra element as a sibling, it fixes it.

**Comment by posva** [comment] 2018-10-05 13:52
Duplicate of #8468

**Closed by posva** 2018-10-05 13:52 UTC
