### ISSUE TITLE
input event has a bug in IE

### ISSUE THREAD

**Issue by 592192890** [vuejs/vue#10490] opened 2019-09-06 13:23 UTC
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/zhoulu_hp/x2ab4cug/1/](https://jsfiddle.net/zhoulu_hp/x2ab4cug/1/)

### Steps to reproduce
1. Open the link in IE browser: https://jsfiddle.net/zhoulu_hp/x2ab4cug/1/;
2. Refresh the page more than twice，you will see the page shows a alert dialog. Because input event is trigger. but the code is normal in chrome browser.

### What is expected?
the input event should not be trigger in IE.

### What is actually happening?
input event is trigger inexplicably In IE

**Comment by posva** [comment] 2019-09-06 13:27
Duplicate of https://github.com/vuejs/vue/issues/7138

**Closed by posva** 2019-09-06 13:27 UTC
