### ISSUE TITLE
Options to remove whitespace between HTML Tags and Mustache

### ISSUE THREAD

**Issue by jzz4012650** [vuejs/vue#11585] opened 2020-08-11 07:05 UTC
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/clever-sammet-51l0g?file=/src/components/HelloWorld.vue](https://codesandbox.io/s/clever-sammet-51l0g?file=/src/components/HelloWorld.vue)

### Steps to reproduce
I have template code like below, and I have set vue-loader's option `compilerOptions.whitespace = "condense"`;

```html
  <div class="hello">
    <button>
      {{ msg }}
    </button>
  </div>
```

### What is expected?
no whitespace output between `<button>` and  `{{ msg }}`.

### What is actually happening?
"vue-template-compiler" removed whitespace between HTML tags, but left whitespaces around `{{msg}}`, which causes my button a bit wider than expected.

---
Would you please provider another option for `whitespace`, which can remove whitespaces between tags and Mustache?

**Comment by posva** [comment] 2020-08-11 07:44
Duplicate of https://github.com/vuejs/vue/issues/11359

**Closed by posva** 2020-08-11 07:44 UTC
