### ISSUE TITLE
PhantomJS 2.1.1 v-model unexpected behavior

### ISSUE THREAD

**Issue by matt-oconnell** [vuejs/vue#4896] opened 2017-02-09 19:52 UTC
### Vue.js version
2.1.10

### Reproduction Link
http://jsfiddle.net/mattoconnell408/df4Lnuw6/137/

### Steps to reproduce
Use PhantomJS 2.1.1
Set up a checkbox within a component.
Bind a handler function to the change event on the checkbox
Bind a data value to the `v-model` attribute

### What is Expected?
The expected behavior is shown in the fiddle.
The value bound to `v-model` should change to true when the checkbox is clicked. The handler method should emit the new `v-model` value.

### What is actually happening?
Possible incompatibility issue with Phantom. An initial click on the checkbox should change the value bound in the `v-model` to `true`. Instead, it reports `false`. The v-model value **is** changing with each click. It appears the handler bound to the `@change` event is being called before the v-model value is being updated. This is only happening with Phantom, but works as expected everywhere else.

**Comment by yyx990803** [comment] 2017-02-21 22:39
This is actually duplicate of #4796 - similar to IE, PhantomJS also seems to trigger `change` event before `click`.

**Closed by yyx990803** 2017-02-21 22:39 UTC

**Comment by jdalton** [comment] 2017-02-21 23:56
It's not just PhantomJS, it's also Safari 10.0.3 too.
