### ISSUE TITLE
event handler lost on multiple v-if switches

### ISSUE THREAD

**Issue by Centaur** [vuejs/vue#3553] opened 2016-08-29 15:52 UTC
### Vue.js version
2.0.0-rc.3

### Reproduction Link

https://jsfiddle.net/eft0d9qe/

### Steps to reproduce
Click 'Show Child' button, then 'Close', then 'Show Child' button again, then 'Close' again

### What is Expected?
The `Child` component should be hidden for the second time.

### What is actually happening?
`TypeError: o.fn is not a function` error is throwed in the console, the `closeChild` event handler is not triggered.

**Comment by yyx990803** [comment] 2016-08-29 15:54
Duplicate of #3518 (already fixed)

**Closed by yyx990803** 2016-08-29 15:54 UTC
