### ISSUE TITLE
How to using syntax babel 7 in vue file

### ISSUE THREAD

**Issue by thanhchuongbmd** [vuejs/vue#11745] opened 2020-10-31 02:18 UTC
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/dpcmr1tz/](https://jsfiddle.net/dpcmr1tz/)

### Steps to reproduce
I can not using syntax babel in vue file, it error by vue-template-compile

### What is expected?
I hope to can using syntax babel 7 like example: message?.name, with "message" is a object

### What is actually happening?
I can not using syntax babel in vue file, it error by vue-template-compile

**Comment by Justineo** [comment] 2020-10-31 02:42
Duplicate of #11088

**Closed by Justineo** 2020-10-31 02:42 UTC
