### ISSUE TITLE
Support component with multiple top elements

### ISSUE THREAD

**Issue by mk-pmb** [vuejs/vue#12383] opened 2021-12-15 17:08 UTC
### What problem does this feature solve?
I have a definition list (`<dl>`) where lots of entries are link entries. Link entries have a `<dt>` with a caption and a button, then a `<dd>` with an `<a>` element. Our current code repeats a lot of common markup and attributes for those link entries. I'd like to factor them out into a component, so our definition list can have just the relevant parts, e.g.

```html
<link-dt caption="New Issue" url="https://new-issue.vuejs.org/" />
```

* The intuitive solution would be to make a component with `<dt>…</dt><dd>…</dd>` on the top level. (Current Vue would complain that there should be only one root element.)
* The next best approach would be to wrap it in a `<template>`. (Current Vue would complain that the render function returned multiple elements.)

#### app.html

```html
<!-- … boilerplate here … -->
<dl>
  <dt>Project:</dt><dd>Vue</dd>
  <link-dt caption="Website:"
    url="https://www.vuejs.org/" />
  <dt>Suggested:</dt><dd>1970-01-01</dd>
  <link-dt caption="Bug tracker:"
    url="https://github.com/vuejs/vue/issues/" />
  <link-dt caption="Feature Requests:"
    url="https://new-issue.vuejs.org/?repo=vuejs/vue&type=feature-request" />
</dl>
<!-- … more stuff … -->
```

#### src/components/dt-url-caption-link/dt.js

```js
module.exports = {
  template: require('./dt.html'),
  props: {
    url:        { type: String },
    caption:    { type: String },
  },
};
```

#### src/components/dt-url-caption-link/dt.html

```html
<dt>
  <clipboard-copy-button :cliptext="url" class="pull-right" />
  {{ caption }}:
</dt><dd>
  <a :href="url" class="url-caption-link"
    rel="noreferrer noopener nofollow"
    >{{ url }}</a>
</dd>
```

**Comment by posva** [comment] 2021-12-15 17:29
Duplicate of https://github.com/vuejs/vue/issues/7088

**Closed by posva** 2021-12-15 17:29 UTC
