### ISSUE TITLE
Vue triggers componentchanged forever

### ISSUE THREAD

**Issue by alexcheninfo** [vuejs/vue#2655] opened 2016-04-12 06:16 UTC
Sorry, I'm not sure if I should open this in the Vue CLI or the Vue CLI Webpack template repository. I'll move them if necessary.

The problem is, Vue triggers the `componentchanged` event of an [a-frame](https://aframe.io/docs/core/entity.html#Events) component forever.

This is the code:

```
<a-scene>
  <a-entity>
    <a-camera @componentchanged="onChange()">
    </a-camera>
  </a-entity>
</a-scene>

<script>
export default {
  methods: {
    onChange: function () {
     console.log('Changed!')
  }
}
</script>
```
Here's a demo: https://desolate-island-90618.herokuapp.com/#!/5EfhFj+R3DY1zo8JIGGQhosrSqn7p0t8pON9y5asxnM=

This only happens in `.vue` files. The problem doesn't occur in a simple `new Vue` instance: http://codepen.io/anon/pen/PNQdwO

**Comment by phanan** [comment] 2016-04-13 03:05
Closed as a duplicate of #2656.

**Closed by phanan** 2016-04-13 03:05 UTC
