### ISSUE TITLE
support use unReactivity data in Template

### ISSUE THREAD

**Issue by zhangshichun** [vuejs/vue#10110] opened 2019-06-06 01:21 UTC
### What problem does this feature solve?
for example in render function:
```
const a = 'Hello world unReactivity'

export default {
render(c){
return c(div,[a])
}
}

```
here the a is not a reactivity data,but when we use template,it seems that we must make a to be a reactivity data?sometimes is not in need. 

### What does the proposed API look like?
```
<template>
<div>
{{ a }}
</div>
</template>
<script>
export default {
unReactivity:{
a: 'Hello world unReactivity'
}
}
</script>
```

**Comment by flyyang** [comment] 2019-06-06 02:33
Try this:

```js
const a = 'Hello world unReactivity'
export default {
  data () {
     return {
        a,
     }
  }
}
```

**Comment by zhangshichun** [comment] 2019-06-06 02:42
> Try this:
> 
> ```js
> const a = 'Hello world unReactivity'
> export default {
>   data () {
>      return {
>         a,
>      }
>   }
> }
> ```

now,the 'a' is reactivity. if 'a' is a big Object,performance overhead may be big;'computed' is a light choose,but if there are many 'a',is also a lot performance overhead.
so i wish has a method to use unReactivity data.

**Comment by Justineo** [comment] 2019-06-06 02:43
Duplicate of #2637

**Closed by Justineo** 2019-06-06 02:43 UTC
