### ISSUE TITLE
Interpolation fails on inline string containing HTML

### ISSUE THREAD

**Issue by chrisvfritz** [vuejs/vue#3323] opened 2016-07-25 21:12 UTC
As demonstrated in [this fiddle](https://jsfiddle.net/chrisvfritz/dtvcthkh/), the following is interpreted literally:

``` html
<p>{{{ '<strong>hello</strong> world' }}}</p>
```

Instead, I would expect it to produce:

``` html
<p><strong>hello</strong> world</p>
```

This also occurs with normal interpolation (`{{ }}`).

**Comment by Grafikart** [comment] 2016-08-20 01:26
I create a failing test for it https://github.com/Grafikart/vue/blob/fix-html-interpolation/test/unit/specs/compiler/compile_spec.js#L719 

I try to look at the source to find where it comes from

**Comment by Grafikart** [comment] 2016-08-20 02:27
I'm working on a fix

## Idea for a fix 

This solution is pretty dirty but I see no way around: 
When compiling a node I check if I find a childNode containing an opening delimiter. If I encounter such a case every Node (until the next childNode containing a closing delimiter) should be treated as text.

**Comment by Bilie** [comment] 2016-09-10 09:13
Hi

I am not entirely convinced this should be considered a bug.
According to the [docs](https://vuejs.org/guide/syntax.html#Interpolations): The mustache tag will be replaced with the value of the msg property on the corresponding data object.
In your example there is no data object.

To be able to get an error message I modified your example from
```
<p>{{{ '<strong>hello</strong> world' }}}</p>
```
to
```
<p v-html="<strong>hello</strong> world"></p>
```
as the [docs](https://vuejs.org/api/#v-html) state the triple curly braces will ultimately be compiled as v-html directive.
Then you can see in the console the following warning:
> [Vue warn]: Invalid expression. Generated function body: `<scope.strong>scope.hello</scope.strong>scope.world`

What is happening here is vue is looking for the properties on the data object but cannot find them because they are not there.
Here is a working example: https://jsfiddle.net/bsyxkxy2/

**Comment by chrisvfritz** [comment] 2016-09-25 19:52
@Bilie Your example isn't quite right.

``` html
<p>{{{ '<strong>hello</strong> world' }}}</p>
```

actually compiles to:

``` html
<p v-html="'<strong>hello</strong> world'"></p>
```

And as you can [see here](https://jsfiddle.net/chrisvfritz/nh5vkqav/), the `v-html` version works fine while the interpolated version fails. So it is indeed a bug.

**Comment by KingMario** [comment] 2017-01-19 10:00
@chrisvfritz Since Vue utilizes the Object.defineProperty to convert instance data to observed object, inline expression without instance data would not be compiled at all. So this is not a bug to me too. And I suspect anyone would do inline expression interpolation like this for a good reason.

**Comment by zrw354** [comment] 2017-02-25 18:06
@chrisvfritz> I agree that the issue is a bug and I'd like to share my findings after a few initial debugging sessions with Vue.js v2.1.10. This version seems to only handle double, not triple, curly braces, so I used double curly braces for testing. Vue called a vendor function, parseHTML, to parse the entire template below as a whole string of HTML code.
```html
<div id="demo">
  <p>{{ '<strong>hello</strong> world' }}</p>
</div>
```
The specific paragraph in question was parsed as:
```html
1. Open tag: <p>
2. Text: {{ ' => Note: {{ was further parsed by function parseText as plain text
3. Open tag: <strong>
4. Text: hello
5. Close tag: </strong>
6. Text: world' }} => Note: }} was parsed by parseText as plain text
7. Close tag: </p>
```
I changed the paragraph to the following and got the correct result:
```html
  <p>{{ 'hello world' }}</p>
```
Why? Because it was parsed as the following:
```html
1. Open tag: <p>
2. Text: {{ 'hello world' }} => 
    Note: the pattern of {{ ... }} was correctly parsed by function parseText
    as Vue tokens
3. Close tag: </p>
```
As function parseHTML is vendor code, I wonder whether and how we should change the template parsing algorithm to fix this.

**Comment by chrisvfritz** [comment] 2017-02-25 18:44
@zrw354 Thanks for sharing your research. HTML interpolation has indeed [been removed](https://vuejs.org/v2/guide/migration.html#HTML-Interpolation-removed).

**Comment by simplesmiler** [comment] 2017-02-26 09:16
I don't think this is a bug, but rather html quirks.

First see this demo: https://jsfiddle.net/simplesmiler/14dtfh51/14/. Note, that raw and escaped code have the same effect when used in the attribute, but different effect when used in the body.

![untitled-1](https://cloud.githubusercontent.com/assets/550229/23338372/412a94a6-fc1a-11e6-8f3f-c086fe09f5c7.png)

So the fact that `v-text="'<strong>hello</strong>'"` works is an html quirk, where html tolerates (and even promotes) non-encoded attributes.

When written "properly", it would be `v-text="'&lt;strong&gt;hello&lt;/strong&gt;'"`,
which maps to `{{ '&lt;strong&gt;hello&lt;/strong&gt;' }}` and works exactly as you  would expect.

**Comment by yyx990803** [comment] 2018-04-17 21:38
Closing 1.x issues as 1.x is now end of life and will only receive critical security patches.

**Closed by yyx990803** 2018-04-17 21:38 UTC
Labels: 1.x, bug, contribution welcome
