### ISSUE TITLE
Transition-Group doens't work when a child component has an falsy if on the template

### ISSUE THREAD

**Issue by yannisgu** [vuejs/vue#11319] opened 2020-04-16 07:53 UTC
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/u5kba8ty/](https://jsfiddle.net/u5kba8ty/)

### Steps to reproduce
No steps needed on the repro.
The repro should render a, b, c, d, however it only renders a, c

Also the console shows an error message 

### What is expected?
The repro should render a, b, c, d,.

### What is actually happening?
The repro should renders a,c and there is an JavaScript error

```
TypeError: "c$1.elm.getBoundingClientRect is not a function"
```

---
The merge request to fix this issue is already created: https://github.com/vuejs/vue/pull/11128/files

**Comment by posva** [comment] 2020-04-16 08:06
Duplicate of https://github.com/vuejs/vue/issues/8516

**Closed by posva** 2020-04-16 08:06 UTC
