### ISSUE TITLE
Elements increase when adding data and changing views

### ISSUE THREAD

**Issue by yhor1e** [vuejs/vue#10249] opened 2019-07-09 12:28 UTC
### Version
2.6.10

### Reproduction link
* [https://codepen.io/yhor1e/pen/agPbrL](https://codepen.io/yhor1e/pen/agPbrL)
* [https://github.com/yhor1e/vue-10249-reproduction](https://github.com/yhor1e/vue-10249-reproduction)

### Steps to reproduce
1. Input data to the text field and push the enter button.
2. Take a heap snapshot in Chrome Developer Tools.
3. Click "Go to Second" button.
4. Click "Go to First" button.
5. Take a heap snapshot in Chrome Developer Tools.
6. Compare step5 heap snapshot with step2 heap snapshot. Then elements increased. 

#### examples
**ex1. Done the above steps with 1 input data.**
![1](https://user-images.githubusercontent.com/10266230/60887518-9d9f5a00-a28f-11e9-87e0-6c74e2290318.png)

**ex2. Done the above steps with 10 input data after ex1.**
![2](https://user-images.githubusercontent.com/10266230/60887890-61b8c480-a290-11e9-98ce-833783c61c78.png)

### What is expected?
Elements don't increase. (#Delta is 0)

### What is actually happening?
Elements increase. (#Delta is not 0)

---
This maybe shows memory leaks.
Is this a bug?

**Comment by MichaelJGW** [comment] 2019-07-09 17:52
Testing this by running a snapshot, clearing the elements, collect garbage, then running an additional snapshot it does what is expected.

I think you are seeing the difference before your browser has done its garbage collection. Which would explain this.

**Comment by yhor1e** [comment] 2019-07-10 00:13
@MichaelJGW 

Thank you for your response!

> Testing this by running a snapshot, clearing the elements, collect garbage, then running an additional snapshot it does what is expected.

Would you please tell me the more detailed procedure?
When I should input data?

Or, do you mean I should click the "Collect Garbage" button in Chrome Dev Tools before taking a heap snapshot?
I tried again the following steps but I got the same results.

1.  Input data to the text field and push the enter button.
2. **Click "Collect Garbage" button  in Chrome Developer Tools.**
3. Take a heap snapshot in Chrome Developer Tools.
4. Click "Go to Second" button.
5. Click "Go to First" button.
6. **Click "Collect Garbage" button  in Chrome Developer Tools.**
7. Take a heap snapshot in Chrome Developer Tools.
8. Compare step5 heap snapshot with step2 heap snapshot. Then elements increased.

**Comment by zrh122** [comment] 2019-07-10 03:14
@yhor1e maybe same as #10004.

**Comment by yhor1e** [comment] 2019-07-11 12:11
@zrh122 

I'm sorry for my late response and thank you for your comment.
Now I tried your vue.js on PR #10085. But elements increment is not improved.

https://github.com/yhor1e/vue-10249-using-10085

Would you please tell me if you have another comment.

**Comment by yhor1e** [comment] 2019-07-11 12:38
@zrh122 

I made a mistake.

**Comment by yhor1e** [comment] 2019-07-11 12:56
When is the fixed version release?

**Comment by zrh122** [comment] 2019-07-11 17:48
```js
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Document</title>
  </head>
  <body>
    <button>Toggle</button>
    <div id="container"></div>

    <script>
      const container = document.getElementById('container')

      document
        .getElementsByTagName('button')[0]
        .addEventListener('click', () => {
          if (container.childElementCount > 0) {
            // removing children
            container.removeChild(container.children.item(0))
          } else {
            const con = document.createElement('div')
            const input = document.createElement('input')
            const ul = document.createElement('ul')
            con.appendChild(input)
            con.appendChild(ul)
            for (let i = 0; i < 20; i++) {
                const li = document.createElement('li')
                li.innerText = i
                ul.appendChild(li)
            }
            container.appendChild(con)
          }
        })
    </script>
  </body>
</html>
```
1. click button `Toggle`, show the list and input
2. take a heap snapshot, type something in the input
3. click `Toggle`  twice, show the list and input again, take a heap snapshot
4. add element to the filter, compare two snapshot, the result is same as this issue

click "Collect Garbage" button before taking a heap snapshot. 
Maybe it is an issue of Chrome (my Chrome version 75.0.3770.100).

**Comment by yhor1e** [comment] 2019-07-11 20:34
@zrh122 

Thank you for your quick response!
I tried your code and steps. Then I got the same result as yours.
 
> Maybe it is an issue of Chrome (my Chrome version 75.0.3770.100).

I agree with you. Elements increment is not a matter of vue.js but Chrome or something.

**Comment by yhor1e** [comment] 2019-07-11 20:44
Please tell me when the version fixed #10004 will release, if possible.

**Comment by posva** [comment] 2019-07-12 08:20
Closing this as a Duplicate of #10004 then.

@yhor1e you can subscribe to that issue to get a notification when it gets closed

**Closed by posva** 2019-07-12 08:20 UTC

**Comment by yhor1e** [comment] 2019-07-12 08:38
Thanks @posva
