### ISSUE TITLE
Transition loops and never ends randomly

### ISSUE THREAD

**Issue by nullptr128** [vuejs/vue#2299] opened 2016-02-04 13:28 UTC
Hello!

I've stumbled upon weird problem with Vue.js css transitions directly tied to v-show directive. When I toggle a variable that controls v-show, it *sometimes* play transition animation, but wont set display:none; at the end of animation.

A html template looks like:
http://pastebin.com/3uFXgmYK

And buggy result is:
http://s27.postimg.org/hqizl5ahv/Screenshot_85.png

And it stalls in this state permamently. Please note that both "loading-screen" and "loading-bar" have v-show="loading" but apparently one is set to display:none after animation finishes, while other one stays at "leave" state infinitely.

This bug occurs randomly, sometimes it works correctly and sometimes it hangs. I am not sure whats the problem here. Did I do something wrong?

**Comment by yyx990803** [comment] 2016-02-04 14:42
Please provide an actual reproduction. A single template snippet is far from enough to diagnose the issue.

**Comment by Mat-Moo** [comment] 2016-02-08 19:54
I've got the same sort of issue with v-if where when I use a transition the dom element is not deconstructed at the end... but finding it hard to create a repo for this, will see if I can create a jsbin

**Comment by Mat-Moo** [comment] 2016-02-08 22:34
I've tried to replicate my issue http://jsbin.com/falekacege/edit?html,js,console,output but it doesn't fail, I've also been back to version 1.0.3 ov vue and it is the same behaviour, so either I have a html issue or something else. Best I can do is show a screen shot as well

![v-if issue](https://cloud.githubusercontent.com/assets/908888/12901505/03dae2f2-ceb4-11e5-8c61-e9ab71377325.png)

If I remove transition="slide-down" then it all works as expected!

Sorry I am unable to provide a reproduction :(

**Comment by decademoon** [comment] 2016-02-09 00:35
I also have this problem.

**Comment by nullptr128** [comment] 2016-02-09 07:51
Sorry @yyx990803 I cant paste my code here due to legal reasons.

I'll try to make this on fiddle in the evening. I think it is some sort of race condition or so because it occurs randomly, like 20% of time. I never really jumped into Vue source, so I have no idea what could cause it. For my site, I just switched off transitions as temporary fix, as I couldnt figure what I did wrong here.

I am not sure even how those transitions work? Is there some JS event like "transition on this dom element ended" or you just calculate transition length from CSS and use timeout after which you are hiding element? I can try tinkering with transition times, I'll check if making 2nd (nested one) transition shorter than outer will fix the problem.

**Comment by yyx990803** [comment] 2016-02-26 02:37
It does wait for a `transitionend` event before applying the DOM operation (e.g. setting `display: none`) - so chances are it's related to you are toggling it fast enough so that the transition is skipped?

If that's the case, try using something like `opacity: 0.01` instead of `opacity: 0`. I'm closing this thread since no one is able to provide a repro for me to determine what is the actual cause of the issue :/

**Closed by yyx990803** 2016-02-26 02:37 UTC
Labels: need repro

**Comment by Mat-Moo** [comment] 2016-02-26 17:36
OOH Might have it @yyx990803 http://jsbin.com/zofebu/edit?html,js,console,output
On chrome - Toggle the Shadow checkbox, then toggle the 3d checkbox - if you remove the "Transition on the range=blur" then it works as expected - whoooo!! (Sorry happy to be able to finally reproduce this!)

**Comment by yyx990803** [comment] 2016-02-26 23:25
@Mat-Moo your issue is actually caused by CSS rule specificity - `.row.fixed` has a higher specificity than `.slide-down-transition` because it has two class selectors. You may want to make the transition thing a mixin, or add `!important` to the transition rules.

**Comment by Mat-Moo** [comment] 2016-02-26 23:45
Good catch! Thanks :) Hopefully it is the same issues others are having and this will be helpful.
