### ISSUE TITLE
[Feat] Support new jsx - jsx-runtime

### ISSUE THREAD

**Issue by dolymood** [vuejs/vue#12379] opened 2021-12-10 02:51 UTC
### What problem does this feature solve?
See <https://babeljs.io/docs/en/babel-plugin-transform-react-jsx> for more details.

We can have a better JSX experience.

Even we can process all the directives/ref/slot features with vue/jsx functions.

Transform original `jsx(...)` input to `vue.h(...)`

### What does the proposed API look like?
In:
```tsx
/** @jsxImportSource vue */

const profile = (
  <div>
    <img src="avatar.png" class="profile" />
    <h3>{[user.firstName, user.lastName].join(" ")}</h3>
  </div>
)
```
Out:
```ts
import { jsx as _jsx } from "vue/jsx-runtime";
import { jsxs as _jsxs } from "vue/jsx-runtime";

const profile = _jsxs("div", {
  children: [
    _jsx("img", {
      src: "avatar.png",
      class: "profile",
    }),
    _jsx("h3", {
      children: [user.firstName, user.lastName].join(" "),
    }),
  ],
});
```

**Comment by caozhong1996** [comment] 2021-12-10 03:21
I don't quite get your meaning, we already have [jsx-next](https://github.com/vuejs/jsx-next), what is the different?

**Comment by posva** [comment] 2021-12-10 08:47
Duplicate of https://github.com/vuejs/vue-next/issues/5085#issuecomment-990679378

**Closed by posva** 2021-12-10 08:47 UTC
