### ISSUE TITLE
<input :is="textarea"> broken

### ISSUE THREAD

**Issue by pi0** [vuejs/vue#6361] opened 2017-08-13 10:35 UTC
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/pi0/qnvcgujb](https://jsfiddle.net/pi0/qnvcgujb)

### Steps to reproduce
This is working with 2.3 but not 2.4 anymore: (see provided fiddles)
```html
<input v-model="value" is="textarea"/>
```

### What is expected?
This was the behavior of 2.3.x:

https://jsfiddle.net/pi0/yL4rwesh

### What is actually happening?
When using `:is="textarea"` to dynamically change input type to a text area neither `:value` or `v-model` are not working anymore. (There is also a common case for both which `<component :is="..."` is not working) 

---
Using dynamic components is a common usage for component libraries like BootrapVue which user can dynamically change elements behavior. [here](https://github.com/bootstrap-vue/bootstrap-vue/blob/v0.21.0/lib/components/form-input.vue#L4) is the current implementation we are falling back to `v-if`/`v-else` as a fix, But is it an intentional breaking change?

**Comment by posva** [comment] 2017-08-13 11:03
Didn't @akryum wrote a similar issue (cannot rely find it on the phone)?

**Comment by posva** [comment] 2017-08-13 13:39
Nvmd, it was something different

⚠️ `component` + `is` + textarea/input + `v-model` wasn't working before either because `v-model` is different for components.

the input + `is` is now behaving as a `component` + `is` (instead of treating it as an input) which is why I marked this as a regression
I still haven't checked if we introduced that to fix something else 😅

**Comment by mosinve** [comment] 2017-08-13 17:33
Is #6344 will fix this issue?

**Comment by nickmessing** [comment] 2017-08-14 01:05
@mosinve, no, it doesn't.

**Comment by defcc** [comment] 2017-08-24 00:26
https://github.com/vuejs/vue/blob/a1d1145c9123f7175f3ac20b503cfa507ad455f4/src/platforms/web/compiler/directives/model.js#L43-L55

It seems this commit breaked it. https://github.com/vuejs/vue/commit/a1d1145c9123f7175f3ac20b503cfa507ad455f4#diff-2cd940df9e3891fae0a25ee85235edcdR486

**Comment by defcc** [comment] 2017-08-24 12:55
Maybe we could ensure that `el.component` is a *real* custome component before apply the genComponentModel method ? @posva

**Comment by posva** [comment] 2017-08-24 13:08
@defcc Agree on all the points!

**Comment by yyx990803** [comment] 2017-09-05 22:17
@defcc The problem with that idea is `el.component` can be an expression with dynamic `:is` bindings, so we don't really know at compile time whether it is a component or not.

The original intention of `is` is really only meant for dynamic component switching, and in some cases allowing "upgrading" a normal element to a component (primarily for when using in-dom template + where HTML has element placement restrictions, e.g. trying to use a component inside `<table>`). So somehow I feel the current behavior sticks to that intention better...

Unfortunately, the fix by @cwang22 in #6453 will break cases where users are casting `<input>` into a custom component with `is`.

For specific cases like component libs, it's probably better to manually handle events instead of using `v-model` for finer-grained control.

@pi0 I looked at the latest bootstrap-vue code and it seems `form-input` and `form-textarea` are split into separate components, which I think is a better direction.

**Closed by yyx990803** 2017-09-05 22:17 UTC
Labels: contribution welcome, nice 1st contribution, regression

**Comment by pi0** [comment] 2017-09-05 22:26
Thanks @yyx990803 for good explanation about `:is` directive :)
