### ISSUE TITLE
Event Forwarding

### ISSUE THREAD

**Issue by paul-schaaf** [vuejs/vue#10567] opened 2019-09-26 16:18 UTC
### What problem does this feature solve?
This feature removes boilerplate-ish code to forward events, making the coding experience feel more vue-ish.

In a parent-child-grandchild scenario where the grandchild needs to pass information to the parent, it currently has to emit an event which is then captured by the child who forwards it to the parent.

This feature would remove the need to write the function in the child that forwards the event from the grandchild to the parent.

FYI: This has been implemented in Svelte: 
https://svelte.dev/tutorial/event-forwarding

> But that's a lot of code to write, so Svelte gives us an equivalent shorthand — an on:message event directive without a value means >'forward all message events'.

### What does the proposed API look like?
For Instance:
- "[at]click.forward"
- simply "[at]click"

**Comment by posva** [comment] 2019-09-26 16:20
Duplicate of https://github.com/vuejs/vue/issues/9325

**Closed by posva** 2019-09-26 16:20 UTC
