### ISSUE TITLE
Vue.mixin with change computed

### ISSUE THREAD

**Issue by wuchuguang** [vuejs/vue#3088] opened 2016-06-16 05:59 UTC
i use vue1.0.24 Version.

i want wirte a plugin .
may be use Vue.mixin way to implement

html5 have localStorage.getItem localStorage.setItem.

i want localStorage.xxx responsive view.

like
```
export default {
   cache:['cacheKey1', 'cacheKey2', 'cacheKey2'],
   methods:{
          changeKey1(newVal){
                  this.$cache.set('cacheKey1', newVal);//responsive  view can interaction this change {{cacheKey1}}
          }
   }
}
```

cache.js

```
Vue.mixin({
            created: function () {
                if (this.$options.hasOwnProperty("cache")) {
                    console.log(this.$options.computed);
                    this.$options.computed = this.$options.computed || {};
                    var len = this.$options.cache.length;
                    for(var i=0; i < len; i++){
                        var cacheName = this.$options.cache[i];
                        this.$options.computed[cacheName] = {
                            get:function(){
                                console.log('here1');
                                return this.localStore.get(cacheName);
                            },
                            set:function(val){
                                this.localStore.set(cacheName, val);
                            }
                        }
                        console.log(cacheName);
                    }
                    console.log(this.$options.computed);
                }
            }
        });
```

computed  have data.but not response

**Comment by posva** [comment] 2016-06-16 07:32
Duplicate of #2037

**Closed by posva** 2016-06-16 07:32 UTC
