### ISSUE TITLE
组件被异常的销毁和重载

### ISSUE THREAD

**Issue by dengdan99** [vuejs/vue#9808] opened 2019-04-02 04:01 UTC
### Version
2.5.16

### Reproduction link
[https://codepen.io/dengdan99/pen/qwEGmg?editors=1111](https://codepen.io/dengdan99/pen/qwEGmg?editors=1111)

### Steps to reproduce
setTimeout 完成后，子组件（child）被销毁并重新创建了， 

### What is expected?
子组件不被销毁

### What is actually happening?
子组件被销毁并重新挂载

---
还有几种不会出现
1.  如果myArray1或者myArray2 赋值是个简单数组（成员非对象），就不会出现该问题
2.  模板上去掉div的class，也不会重现问题

**Comment by Justineo** [comment] 2019-04-02 04:15
Duplicate of #9473

**Closed by Justineo** 2019-04-02 04:15 UTC

**Comment by dengdan99** [comment] 2019-04-02 06:13
thanks @Justineo  , but i don't think it's the same problem
