### ISSUE TITLE
Single file component: conditional templates malfunctionning after 2.1.0

### ISSUE THREAD

**Issue by marvinroger** [vuejs/vue#4291] opened 2016-11-23 09:47 UTC
Hi,

Not sure which Vue subproject this issue refers to, but conditional templates started to malfunction in single file component since 2.1.0.

Simple reproduction:

```html
<template>
  <div>
    <template v-if="true === true">
      <section class="section">
        <div class="container">
          Should be shown
        </div>
      </section>
    </template>
    <template v-else>
      <p>Shoud not be shown</p>
    </template>
  </div>
</template>
```

`Should not be shown` is shown, whereas `Should be shown` should be.

Note if you remove the outer div class `container` and leave only the inner text, `Should be shown` is indeed shown.

This only happen with single file component (e.g. [this jsfiddle works](https://jsfiddle.net/L92w2372/1/)).

EDIT: Fix wrong jsfiddle link

**Comment by bartlomieju** [comment] 2016-11-23 09:56
Can confirm, I have exactly same issue since update to 2.1.0 yesterday

**Comment by joturako** [comment] 2016-11-23 10:48
confirmed. spending an afternoon to find this bug and get vue & vue-template-compiler reverted to 2.0.1 in order to work

**Comment by defcc** [comment] 2016-11-23 11:31
Thanks, I am looking into it.

**Comment by ansarizafar** [comment] 2016-11-23 14:07
I am also seeing strange behavior after updating to 2.1.0. My dialog component is not working.  Same code is working with previous version.

````
<div class="ui dimmer modals page" v-if="showBackDrop" style="display: block !important; overflow-y: scroll;" :style="{ visibility: showBackDrop ? 'visible' : 'hidden', opacity: showBackDrop ? '1' : '0'}" @click="closeModal()">
    <transition name="scale">
      <div :id="id" class="ui modal active visibility" v-show="showModal" :class="[size, type, isScroll ? 'scrolling' : ''] " @click="clickContent($event)">
        <slot></slot>
      </div>
    </transition>
  </div>
</transition>
</template>

<script>
export default {
name: 'modal',
  props: {
    size: {
      type: String,
      default: 'small'
    },
    type: {
      type: String,
      default: ''
    },
    closeable: {
      type: Boolean,
      default: true
    },
    isScroll: {
      type: Boolean,
      default: false
    }

      },

  data() {
    return {
      id: `modal_${Math.random()}`,
      showBackDrop: false,
      showModal: false
        }
  },

  mounted() {
    document.body.classList.add("dimmable");

  },

  methods: {
    clickContent(event) {
      event.stopPropagation();
    },
    open() {
      this.showBackDrop = true
      document.body.classList.add("dimmed");
      setTimeout(() => {
        this.showModal = true;
        setTimeout(() => {
          this.$el.firstChild.style.top = ((document.body.offsetHeight - this.$el.firstChild.offsetHeight) / 2) + 'px';
        })
      });

    },
    close() {
      this.showModal = false
      setTimeout(() => {
        this.showBackDrop = false
        document.body.classList.remove("dimmed");
      }, 30);
    },
    closeModal() {
      if (!this.closeable) {
        return;
      }
      this.close();
    }

  }
}
</script>


<style>
.modal .header {background: #f0f8ff !important;}

.scale-enter-active {
  animation: scaleIn .5s;
}

.scale-leave-active {
  animation: scaleOut .5s;
}

.fade-enter-active {
  animation: fadeIn .5s;
}

.fade-leave-active {
  animation: fadeOut .5s;
}
</style>

````

**Comment by posva** [comment] 2016-11-23 14:11
@ansarizafar Roll back to a previous vue version for the moment, we're looking into fixing it and will release a patch asap

**Comment by ansarizafar** [comment] 2016-11-23 14:16
@posva I have already done just that. Thanks

**Comment by yyx990803** [comment] 2016-11-23 14:17
Closing in favor of #4290 since both seem to be the same issue

**Closed by yyx990803** 2016-11-23 14:17 UTC
Labels: 2.0
