### ISSUE TITLE
`boolean | null` prop doesn't accept `null` value

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuejs/vue#12882] opened 2022-11-19 10:22 UTC
### Version
2.7.14

### Reproduction link
[stackblitz.com](https://stackblitz.com/edit/vitejs-vite-zxmy3e?file=src%2Fcomponents%2FHelloWorld.vue,src%2FApp.vue&terminal=dev)

### Steps to reproduce
```ts
// Comp.vue
defineProps<{ msg: boolean | null }>();
```

```html
<!-- App.vue -->
<template>
  <Comp :msg="null" />
</template>
```

### What is expected?
No warnings
Vue 3: https://sfc.vuejs.org/#__DEV__eNp9kLtuwzAMRX+F0JIEiKXdcAMU3Tq0BbpqcRzaVWA9QMkpClf/XqrpIw8gmy55eUWeWdyHIA8Tilo0sSMTEkRMU9hoZ2zwlODB2wA9eQsLqYoo9oV2jTr62ckioQ1jm5AVQNOVmbr3/k4LN42jFqC406g/m1iLY35l2yD30TveYC7D+qcRtajhu1Jq/GfRWrylFGKtVOy7ssg+Sk+D4pekySVjUWK01Zb8e0TiYC3WJxmKiwekitDtkJBuZV5Yr3JLbNYu8ym/WC4pwti6gRmUY/j+HfbG4Qv5EJsZGE8NW+9HbB18QuEEebNcnaH9BzvP8Pj6/CRjIuMG038sOWAFOZ9SzV97tqJr

### What is actually happening?
`Invalid prop type: "null" is not a constructor` and `Invalid prop: type check failed for prop "msg". Expected Boolean, , got Null` warnings

### Additional notes

Warnings per se are not the issue, they can be fixed by changing the prop definition to `msg?: boolean` which also accepts booleans, the issue is that this behaviour is not same as in Vue 3

**Comment by posva** [comment] 2022-11-19 11:10
Duplicate of https://github.com/vuejs/vue/pull/9358 ?

**Closed** 2022-11-19 11:11 UTC
