### ISSUE TITLE
2.0 tree example bug

### ISSUE THREAD

**Issue by aviggngyv** [vuejs/vue#3043] opened 2016-06-08 09:55 UTC
Well, I know this issue is repeat with #2994,  I just want to report this issue, because I note today, new dist/vue.js file is releases, I updated this for my project ,then I get same error code when execute push operating:

> vue.js:2137 [Vue warn]: Error during component render (found in component: <item>)warn @ vue.js:2137get @ vue.js:626run @ vue.js:719runSchedulerQueue @ vue.js:537flushSchedulerQueue @ vue.js:506nextTickHandler @ vue.js:342
> vue.js:2137 [Vue warn]: Error: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

then I found #2994 issue by search, then I found the tree example still have this bug, I hope those infomation is useful to fix it.

Thanks.

**Comment by lonquan** [comment] 2016-06-08 13:17
不知道为什么, 突然很想回复一段中文...

**Comment by lonquan** [comment] 2016-06-08 13:17
不知道为什么, 突然很想回复一段中文...

**Comment by yyx990803** [comment] 2016-06-08 15:32
I can't reproduce this - can you list the detailed steps that lead to the mentioned error?

**Comment by aviggngyv** [comment] 2016-06-08 15:55
![jdfw](https://cloud.githubusercontent.com/assets/7891096/15901017/2b074256-2dd4-11e6-8d07-7d235ff5fb3a.gif)

Look this gif, you will got it , thanks for all your hard work ! Vuejs changed my life!

**Comment by yyx990803** [comment] 2016-06-08 17:29
Thanks for the repro, fixed in `next` branch.

**Closed by yyx990803** 2016-06-08 17:29 UTC
Labels: 2.0
