### ISSUE TITLE
data property and class extended with Array

### ISSUE THREAD

**Issue by nori3tsu** [vuejs/vue#10298] opened 2019-07-22 14:18 UTC
### Version
2.5.17

### Reproduction link
[https://jsfiddle.net/632dch1e/](https://jsfiddle.net/632dch1e/)

### Steps to reproduce
open link to minimal reproduction

### What is expected?
Keep the type even if you set the class that extends Array to data.

### What is actually happening?
Methods defined in a class that extends Array can not be used.
Also, since the class of each object of Array remains as it is, the class structure is broken.

**Comment by posva** [comment] 2019-07-22 14:19
Duplicate of https://github.com/vuejs/vue/issues/9259

**Closed by posva** 2019-07-22 14:19 UTC
