### ISSUE TITLE
how to let vue dont't warm 'Unknown custom element'

### ISSUE THREAD

**Issue by aweiu** [vuejs/vue#3189] opened 2016-06-30 07:13 UTC
in my component,i use some custom element just for making it won't be effected by other style.
such as:
```
<template>
  <!--'my-el' is just a common dom el,not component-->
  <my-el></my-el>
</template>
```
but,vue always warm that ''Unknown custom element...',how to ignore it without runing '`Vue.config.silent = true`'?

**Comment by yyx990803** [comment] 2016-06-30 11:07
Duplicate of #3090

**Closed by yyx990803** 2016-06-30 11:07 UTC

**Comment by semet** [comment] 2020-08-15 03:23
<div class="card " data-partial-height="40" data-toggle="popover" data-trigger="click">


how to tell vue to ignore the data-partial-height, data-toggle and data-trigger?
because in my case, these tag works perfectly at first. but once i add v-for inside the div, the data-partial-height="40" data-toggle="popover" data-trigger="click" is not working anymore,

**Comment by semet** [comment] 2020-08-15 03:23
`<div class="card " data-partial-height="40" data-toggle="popover" data-trigger="click">`

how to tell vue to ignore the data-partial-height, data-toggle and data-trigger?
because in my case, these tag works perfectly at first. but once i add v-for inside the div, the data-partial-height="40" data-toggle="popover" data-trigger="click" is not working anymore,
