### ISSUE TITLE
iOS Safari renders blank page

### ISSUE THREAD

**Issue by cherry-geqi** [vuejs/vue#5533] opened 2017-04-27 07:40 UTC
### Version
2.2.6

### Reproduction link
[https://gist.github.com/cherry-geqi/68b3b83491394851f94d8364ab099a83](https://gist.github.com/cherry-geqi/68b3b83491394851f94d8364ab099a83)

### Steps to reproduce
1. Scroll list page a distance over the height of the screen
2. Click a cell and navigate to detail page
3. Navigate back and see a blank page
4. Swipe the list page and the contents show

### What is expected?
A complete list of contents

### What is actually happening?
A blank page without contents until you swipe on the page

---
Reproduces on iOS Safari (tested on iOS 10.3.1).
Works on Chrome for iOS even though it uses the same engine.

**Comment by phanan** [comment] 2017-04-27 08:12
Even though I can't reproduce, this apparently is a problem with Safari's [back-forward cache](http://stackoverflow.com/questions/37958275/need-help-to-disable-back-forward-cache-on-safari-ios) and not Vue itself.

**Comment by posva** [comment] 2017-04-27 08:25
Should we close this then?
@cherry-geqi Next time make sure to provide an interactive repro and editable repro, like a jsfiddle 🙂 It really helps, even more with mobile issues

**Comment by cherry-geqi** [comment] 2017-04-27 10:14
I'm sorry but I can not provide a jsfiddle repro so it may take a few more steps to repro. The gist is a minimum complete one. To repro, download the gist and then put it under the root directory of a temporary server like `python3 -m http.server` and then request from iOS Safari.

In my device, it is almost a 100% repo.

Here is a screencast:
[blank-page-repro.zip](https://github.com/vuejs/vue/files/961232/blank-page-repro.zip)

It may be a problem with Safari, but we should provide a workaround, should we?

**Comment by yyx990803** [comment] 2017-04-28 03:06
I think this is actually because... you are re-fetching the data every time you navigate to home. You should use a store to cache the fetched data.

**Closed by yyx990803** 2017-04-28 03:06 UTC

**Comment by cherry-geqi** [comment] 2017-04-28 03:21
I'm afraid not. Maybe I didn't make myself clearly but it is really a fatal problem which only repros on iOS Safari. When I navigate back, the page stays blank until interacting with it. The data is loaded and the DOM is constructed. It's more like a browser rendering bug but is there something we can do?

**Comment by yyx990803** [comment] 2017-04-28 03:48
Cannot reproduce on iOS 10.3.1 using the exact code you provided.

**Comment by cherry-geqi** [comment] 2017-04-28 03:59
It's a 100% repro. Scroll the list page(important!) and navigate to detail page and navigate back. I have been working on this for 20 hours at least.

**Comment by yyx990803** [comment] 2017-04-28 04:06
Your iOS version?

**Comment by cherry-geqi** [comment] 2017-04-28 09:48
iOS 10.3.1 along with Wechat 6.5.7 as it switched to WKWebview since 6.5.6.

**Comment by yyx990803** [comment] 2017-04-28 12:35
You should've mentioned that - Safari is NOT WKWebView.

**Comment by cherry-geqi** [comment] 2017-05-02 01:26
Repros on iOS Safari.

**Comment by Centaur** [comment] 2017-05-10 08:34
Yes. This is a problem that is 100% reproducible on ios for my app as well.

**Comment by cherry-geqi** [comment] 2017-05-15 06:39
@Centaur Have you found a workaroud?

**Comment by Centaur** [comment] 2017-05-17 04:35
@cherry-geqi  I added the following code after the data fetch:

```javascript
this.$nextTick(() => {
      window.scrollTo(0, 1)
      window.scrollTo(0, 0)
})
```

At least our test team was satisfied.

**Comment by chenyeah** [comment] 2017-07-21 01:30
I have this problem, but I don't think it's a very good solution

**Comment by ppxialetsgo** [comment] 2017-07-27 06:35
yeah, do you resolve this problem ?   @cherry-geqi

**Comment by cherry-geqi** [comment] 2017-07-27 06:55
The workaround provided by @Centaur just works. This is obviously not an individual case. I suggest vuejs team pay more attention on this. @yyx990803 @posva

**Comment by Hao-Wu** [comment] 2017-09-20 09:43
+1 Exactly the same problem.

100% reproduced on iOS 9/10/11 + wechat(WKwebview)/safari. Can't reproduce in UIWebview of wechat.

The above workaround works for us.

**Comment by TimeBandit** [comment] 2017-10-28 12:06
We are considering Vue for our new project but this thread seems very similar to what I am seeing. Our primary users wont be having the latest phones and I see that sample Vue apps simply don't render on IOS (7.1.2) Safari => IPHONE-4.

Reproduction:
The vue demo here does not render on IOS 7.1.2
[https://lucasleandro1204.github.io/vue-content-loading](https://lucasleandro1204.github.io/vue-content-loading)

But the equivalent React component does:
[https://danilowoz.github.io/react-content-loader/](https://danilowoz.github.io/react-content-loader)

Please advise.

**Comment by zxb5102** [comment] 2017-11-09 08:56
i have the same problem

**Comment by lizhiyao** [comment] 2017-11-13 07:16
I have the same problem.

**Comment by LYDZYL** [comment] 2017-11-13 09:07
I have the same problem.

**Comment by javoski** [comment] 2017-11-13 09:42
It's actually an issue related to Safari instead of Vue, check out this [demo](https://javoski.github.io/bugs-repro/safari-rerender-after-popstate.html) which doesn't involve with Vue.

**Comment by Hao-Wu** [comment] 2017-11-14 03:56
Great! @javoski 's demo indicates the issue is not related with Vue but Safari.

**Comment by Dean-Christian-Armada** [comment] 2018-01-06 02:02
@Hao-Wu @javoski  , I disagree with you with the Safari part, I tried with Google Chrome in my Ipod touch and it also renders the same

**Comment by Dean-Christian-Armada** [comment] 2018-01-06 02:49
@javoski . It says in the web inspector that you have an error as shown in the photo
<img width="989" alt="screen shot 2018-01-06 at 10 48 52" src="https://user-images.githubusercontent.com/9837087/34635776-4323d996-f2cf-11e7-9edb-b4ff930c341e.png">

Seems like the `tick` is not read properly

**Comment by zxb5102** [comment] 2018-01-12 14:12
Hey guys ,I had the same problem.but now I solved my problem.
i found out that my problem was due to the structure of the dom tree

in my case, there are two nested HTML elements.

I think it's because this makes the frame render wrong.

**Comment by kschroeder** [comment] 2018-04-20 20:14
I don't know if I had exactly the same issue, but I had a problem that sounds pretty close to this.  The solution for me was to install `babel-polyfill`.  So, for future people Googling this issue that might be an option that helps.

**Comment by francistec** [comment] 2018-07-21 15:12
Thanks for your workaround @Centaur !!!
You saved me hours of debugging... Thank bro.

**Comment by 3344567** [comment] 2018-09-07 02:32
虽然这个问题解决了，但我还是想说，这不叫ios问题，而就是vue的问题，如果你非要说是ios问题，那如果出了安卓的问题，是不是也不是vue的问题？那还有谁来用vue?

**Comment by OPY-bbt** [comment] 2019-01-07 03:35
the same problem happens on react, if the element use '-webkit-overflow-scrolling: touch', it won't be rendered on return in my case.

**Comment by XieChuanfang** [comment] 2019-01-26 11:33
so ,  how to solve the problem finally except scroll method?  I also encounter the problem on react...
@cherry-geqi @Centaur @posva

**Comment by icemancrem** [comment] 2019-03-06 11:04
> 虽然这个问题解决了，但我还是想说，这不叫ios问题，而就是vue的问题，如果你非要说是ios问题，那如果出了安卓的问题，是不是也不是vue的问题？那还有谁来用vue?
you are five

**Comment by Vnext-HoangBui** [comment] 2019-10-14 08:10
The issue still exists on Safari iOS 12.

@Centaur fix worked, you just have to find the main scrolling element. For my case it was a div inside body element.

**Comment by 3344567** [comment] 2019-11-20 03:31
> > 虽然这个问题解决了，但我还是想说，这不叫ios问题，而就是vue的问题，如果你非要说是ios问题，那如果出了安卓的问题，是不是也不是vue的问题？那还有谁来用vue？
> > 你五岁

你是sjb?

**Comment by fengyuyizai** [comment] 2020-02-27 09:09
vue中可以使用

```
scrollBehavior (to, from, savedPosition) {
    // return 期望滚动到哪个的位置
   return {y: 0}
  }
```

**Comment by PLQin** [comment] 2020-09-07 02:33
#####  \# my problem is…
Vue in ios safari  , When the right slide back to the `home page` , the page will be blank ， Then show the contents of the previous page， finally comes the content of the `home page`  ；

In addition:  It's not just back to the `home page` that has this problem， this phenomenon also exists on other pages ;


#####  \# How did I solve it
Abandon the `Vue Transition` ， emmm  太难了

**Comment by wanghansong** [comment] 2021-01-28 13:12
the seam problem i have met

**Comment by timgoeller** [comment] 2021-07-01 14:31
This happend in PWAs for us, and was caused by using `router.go(-1)`.

**Comment by jkira** [comment] 2023-03-27 14:34
This is still a problem with mobile iOS in 2023. So it goes. Here's a vanilla JS version for anyone with non-Vue pages.
```
window.addEventListener('pageshow', function(event) {
    if (event.persisted) {
        console.log("scrollfix");
        window.scrollTo(0, 1);
        window.scrollTo(0, 0);
    }
});
```
