### ISSUE TITLE
Create a v-if-parent template directive

### ISSUE THREAD

**Issue by Tofandel** [vuejs/vue#10078] opened 2019-05-28 14:32 UTC
### What problem does this feature solve?
I would like to have an optional component but with the content being always rendered (so v-if doesn't work with this use case)

It's currently not possible without a lot of code duplication
```HTML
<my-component v-if="condition">
    <the-content>I'm visible</the-content>
</my-component>
<the-content v-else>I'm visible</the-content>
```

### What does the proposed API look like?
What I would like to be able to write instead is this

```HTML
<my-component v-if-parent="condition">
    <the-content>I'm visible</the-content>
</my-component>
```

**Comment by posva** [comment] 2019-05-28 15:02
It looks to me that you want to reuse parts of the template. This is a duplicate of https://github.com/vuejs/vue/issues/5401

For the moment, to reuse fragments of a template, you need to either create subcomponents or use JSX/render functions

**Closed by posva** 2019-05-28 15:02 UTC

**Comment by Tofandel** [comment] 2019-05-28 16:24
The duplicate you provided would only be a workaround for the issue and will most likely not be implemented until some years

I'm asking for a different v-if which instead of not rendering the component and all it's children would not render the component but still render it's children.

Please reopen this issue

**Comment by posva** [comment] 2019-05-28 16:38
In that case, that should be implemented in a custom component, in user lad. It's not possible to render the children in every scenario as there could be multiple of them

**Comment by Tofandel** [comment] 2019-06-11 08:46
If some people stumble here, this is the component I ended up doing

```js
export default {
    name: "v-if-parent",
    props: {
        condition: {
            type: Boolean,
            required: true
        }
    },
    render() {
        if (this.condition) {
            let parent = this.$scopedSlots.parent()[0];
            parent.children = this.$scopedSlots.default();
            return parent;
        } else {
            return this.$scopedSlots.default()
        }
    }
}
```
And then use it like this

```html
<v-if-parent :condition="showparent">
  <template #parent><div class="parent" /></template>
  <div class="child"> 
    Child should always be visible
  </div>
</v-if-parent>
```
