### ISSUE TITLE
iPad/iPhone keyboard is not shown when input gets focus (works in Vue 2.4.x)

### ISSUE THREAD

**Issue by arnesten** [vuejs/vue#7546] opened 2018-01-27 16:29 UTC
### Version
2.5.13

### Reproduction link
[https://codepen.io/arnesten/pen/zROvgE](https://codepen.io/arnesten/pen/zROvgE)

### Steps to reproduce
1. Open link on iPad or iPhone
2. Tap on the text

### What is expected?
An input becomes visible and gets focus and the on-screen keyboard on iPad/iPhone is shown.

### What is actually happening?
An input becomes visible and gets focus but the on-screen keyboard on iPad/iPhone is NOT shown.

---
This works for Vue 2.4.4. Test here: 
https://codepen.io/arnesten/pen/JpPYmO

It stopped working for Vue 2.5.0. Test here:
https://codepen.io/arnesten/pen/wywKLw

In our web app, we use the UI pattern of clicking on a text (or icon) to start editing something on many places. With Vue 2.4.x iPad/iPhone users would only need to tap once to show the input/textarea and have the on-screen keyboard appear. For 2.5.x iPad/iPhone, they need to tap twice. One time to show the input/textarea and one more time to make the on-screen keyboard appear.

**Comment by Giwayume** [comment] 2018-02-15 21:49
I'm not so sure this is a Vue issue. iOS is really terrible at detecting when to show the on-screen keyboard in web browsers at times. This is likely an iOS bug you could reproduce with some simple vanilla Javascript show/hide.

**Comment by arnesten** [comment] 2018-02-16 07:26
@Giwayume The exact same code is showing the keyboard on focus in Vue 2.4.4. But from Vue 2.5.0 it does not show the keyboard. If you have an iOS device you can try the links above yourself.

**Comment by Giwayume** [comment] 2018-02-16 21:00
@arnesten I understand you didn't change code, just pointing out that Vue would be coding workarounds to iOS bugs. It's the phone's responsibility to show the keyboard since there is no Javascript API that can tell it to.

**Comment by arnesten** [comment] 2018-02-16 21:29
@Giwayume 
I don't know if it can be classified as a bug in iOS, since there is no specification of how the on-screen keyboard should behave. I think the problem is that there is too much delay between the user doing a click and Vue 2.5.0+ updating the DOM and setting focus on the input. In Vue 2.4.4 this delay was shorter so then it worked fine with iOS. 

It is quite common to have a search icon in a mobile web app that you can click on to show and focus a search input. Not opening the keyboard but instead requiring you to do a second click is a relatively big UX issue in that case. So hopefully a fix, or at least a workaround other than downgrading to Vue 2.4.4, can be found for this situation.

**Comment by HerringtonDarkholme** [comment] 2018-02-28 07:47
I guess this is another issue of micro/macro task introduced in 2.5. https://github.com/vuejs/vue/releases/tag/v2.5.0

iOS requires user input for showing keyboard. Before Vue uses micro task so user click counts as a valid trigger for keyboard. However, in 2.5 we uses macro task so iOS no longer treats it as trigger.

**Comment by yarnball** [comment] 2018-08-20 00:44
Seems like this is still an issue to me- should it have been updated?  https://codesandbox.io/s/m53vx15rny

**Comment by falstack** [comment] 2018-08-20 06:43
I resolve this issue by this:

``` html
<div class="page-container">
  <div v-if='showDialog" class="dlalog">
    <div class="footer">
      <button @click="submit">submit</button>
    </div>
  </div>
  <textarea id="textarea">this area fixed, and default display = none</textarea>
  <button class="open-dialog-btn" @click="openDialog">open dialog</button>
</div>
```

``` javascript
mounted() {
  document.getElementById("page-container").addEventListener("click", e => {
    if (/open-dialog-btn/.test(e.target.className)) {
      document.getElementById("textarea").style.display = "block";
      document.getElementById("textarea").focus();
    }
  });
},
methods{
  openDialog() {
    this.showDialog = true
  },
  submit() {
    this.showDialog = false
    document.getElementById("textarea").style.display = "none";
  }
}
```

**Comment by atheneliu** [comment] 2018-12-11 11:05
i got same problem with vue version 2.5.17 when i change vue version  2.4.4 it works 

this.$nextTick(() => {
     this.$refs.textarea.focus()
})

**Comment by vlahanas** [comment] 2018-12-19 13:32
Hello,

any updates on that?

**Comment by yyx990803** [comment] 2018-12-19 18:31
Closed via #8450 (will be out in 2.6)

**Closed by yyx990803** 2018-12-19 18:31 UTC
Labels: nextTick related, regression

**Comment by zhoufeifan** [comment] 2019-01-07 06:20
> Closed via #8450 (will be out in 2.6)

Could you tell me that when vue 2.6  release ?

**Comment by pouu69** [comment] 2019-02-15 04:36
Could you tell me that when vue 2.6 release ?

**Comment by philiprenich** [comment] 2019-02-15 04:46
@pouu69 2.6 has been released already - https://github.com/vuejs/vue/releases
(though I haven't used it and tested against my instance of this bug)

**Comment by pouu69** [comment] 2019-02-28 06:03
i have been upgraded vue v2.6.7 and i wrote below code

``` js
        this.$nextTick(this.$refs.etcInputRef.focus)
```

but iphone not shown keyboard

**Comment by schniper** [comment] 2019-03-04 17:49
Also experiencing this with Quasar

**Comment by AndrewBogdanovTSS** [comment] 2019-12-11 12:53
I use Vue 2.6.10 but it's still reproducible. Keyboard not showing only on iOS, Android works well

**Comment by chinnichaitanya** [comment] 2020-05-20 17:31
I'm on the latest Vue 2.6.11. The issue still exists in the iPhone and iPad. But works well for Android.

**Comment by rgfretes** [comment] 2020-08-06 01:27
Is there any news regarding this bug? I can still reproduce it on v2.6.11

**Comment by zindont** [comment] 2023-10-02 03:12
+1 still issue on 2.7.14

**Comment by jayatulsiani** [comment] 2025-02-05 16:28
still the same issue persists on latest vue version. have tried nextTick, watcher , onMOunted everything !!

**Comment by devinkel** [comment] 2025-09-05 14:57
### My Solution
Use an invisible dummy input to preserve the user gesture until the target input is rendered:

```html
<input ref="dummyInput" style="position:absolute; top:-9999px; opacity:0; pointer-events:none;" tabindex="-1">
```

```javascript

handleClick(event) {
    if (/iPhone|iPad|iPod|Android/i.test(navigator.userAgent)) {
        this.$refs.dummyInput.focus()
    }
    
    this.$emit('open-modal') // or whatever triggers your component
    
    this.waitForInput()
}

waitForInput() {
    const checkInput = () => {
        const input = document.querySelector('.your-input-selector')
        if (input && input.offsetParent !== null) {
            this.applyMobileFocus(input)
        } else {
            setTimeout(checkInput, 100)
        }
    }
    checkInput()
}

applyMobileFocus(input) {
    input.setAttribute('autofocus', 'autofocus')
    input.focus()
    
    if (/iPhone|iPad|iPod/i.test(navigator.userAgent)) {
        setTimeout(() => input.click(), 50)
    }
    
    setTimeout(() => input.removeAttribute('autofocus'), 1000)
}
```

### Tested On
- iOS Safari 12+
- Chrome Mobile 70+
- Vue 2.5.13+

This approach has been working reliably in production for several months across various mobile devices.

**Comment by kekekuli** [comment] 2026-04-28 08:19
It possiably not the vue problem, 
I am on: 
vue: 2.7.16
ios 26

I was facing problem that first click on IOS 26 will not show up keyboard, it need double-click,Android need one click to show up keyboard as expected. I haven't test the other ios verion.

 IOS keyboard behivor is terriable to foresee, but I have found way to solve this. Just add a listener of touchstart for <input> tag works for me

```vue
<input  @touchstart="mannulFocus"/>
```
```js
mannulFocus(e) {
    e.target.focus();
},
```
Then UX just need click once instead double-click.


For people that wonder what happened, I give some links that may be help.

Offcial IOS 26 keyboard behavior explantion: [ios support](https://support.apple.com/en-al/guide/iphone/iph3e2e3d1d/ios)
Flutter developer discussing same problem: [flutterers discusstion](https://github.com/flutter/flutter/issues/110284)
People reporting same issue on offcial forum: [ios forum](https://discussions.apple.com/thread/254245701?sortBy=rank)

**Comment by Giwayume** [comment] 2026-04-28 12:25
Safari on iOS has a quirk where it analyzes your hover styles, and if they are "sufficiently complex" it will first display the hover state on your first tap, then interact with the element on your second tap. Though I haven't heard of this affecting inputs, it is a possibility.

https://www.w3tutorials.net/blog/why-when-do-i-have-to-tap-twice-to-trigger-click-on-ios/
