### ISSUE TITLE
TypeScript with composition-api: in methods, "this" is Vue, not current instance

### ISSUE THREAD

**Issue by RobertGres** [vuejs/vue#11403] opened 2020-05-20 08:25 UTC
### Version
2.6.11

### Reproduction link
[https://codepen.io/robertgres/pen/XWmozGV](https://codepen.io/robertgres/pen/XWmozGV)

### Steps to reproduce
```
import * as vue from '@vue/composition-api'

vue.defineComponent({
  methods: {
    foo() {
       this.baz() // Error
    },
    baz() {}
  },
  mounted() {
     this.foo() // fine
  }
})
```

### What is expected?
No TypeScript errors

### What is actually happening?
TS2339: Property 'baz' does not exist on type 'Vue'.

---
Seems like typings don't take into accout current instance

This fixes given problem (in file types/options.d.ts):

`type DefaultMethods<V, S extends V> =  { [key: string]: (this: S, ...args: any[]) => any };`

instead of:

`type DefaultMethods<V> =  { [key: string]: (this: V, ...args: any[]) => any };`

**Comment by posva** [comment] 2020-05-20 09:56
Duplicate of https://github.com/vuejs/composition-api/issues/144

**Closed by posva** 2020-05-20 09:56 UTC
