### ISSUE TITLE
Checked state bugged in 2.1.7+ when using checkbox :checked="true/false" state with Vuex

### ISSUE THREAD

**Issue by FKobus** [vuejs/vue#4704] opened 2017-01-12 22:48 UTC
Seems fixing the bug from #4521 created a new bug for :checked="" binding when using in combination with vuex states for maintaining checkbox states.

```javascript
<template>
	<ul>
		<li v-for="option in visibleOptions" :key="option.value">
			<input
				type="checkbox"
				:name="filter.key"
				:value="option.value"
				:checked="inArray(option.value, filter.active)"
				@change="updateFilter">
		</li>
	</ul>
</template>
```
In this code example is :checked set to true or false whenever it's in the active filter array.
It seems when this component is updated (via vuex) the :checked stated doesn't get's updated like in 2.1.6. In my application is the state managed _almost_ totally by Vuex. 

### Vue.js version
2.1.7+

### Reproduction Link
http://vroom.automotivated.nl/

### Howto reproduce
When selecting several checkboxes (like brands) and use your **browser back button** to fallback to previous states. (it's managed by the popstate event and uses vuex actions to update actively the new state)

### What is expected
The checkbox should go on or off depending on the previous action or new current state.

### What is actually happening?
Everything get's correctly updated (value wise), except the checkbox isn't honored to update (checked true/false). It keeps in a previous state. When selecting multiple after eachother and navigating back and forward is looks like is off a beat and missing the last changed checkbox.

Code that goes with it:
https://github.com/Automotivated/vroom/blob/master/src/views/elements/filters/Multiple.vue
Full github repo:
https://github.com/Automotivated/vroom/

While reading the [docs](https://vuex.vuejs.org/en/forms.html) in Vuex, it seems to be best practise to do it like I did. 

### When did it work
It worked like a charm in 2.1.6. Seems really that fixing this bug triggered this bug to be created.

**Comment by TheDutchCoder** [comment] 2017-01-12 23:03
If you select multiple boxes and you keep going back, all the other ones seem to properly update.

Are you sure it's not a bug in your code?

**Comment by FKobus** [comment] 2017-01-12 23:09
That's what I described in my issue, it seems to skip the last checked checkbox. I ran several tests and my code didn't change since 2.1.6. When running on 2.1.6 it works perfect. Seems that the changes in 2.1.7 (reffered the issue) are causing the problem.

**Comment by TheDutchCoder** [comment] 2017-01-12 23:10
Gotcha, fair enough, I'll leave this to the experts then ;)

**Comment by yyx990803** [comment] 2017-01-12 23:27
Should be a duplicate of #4620 (and fixed via #4639, not released yet)

**Closed by yyx990803** 2017-01-12 23:27 UTC

**Comment by FKobus** [comment] 2017-01-12 23:37
I runned my code on the dev branch too and the issue remained. Especially because the state doesn't get's updated by the click or change event.

**Comment by yyx990803** [comment] 2017-01-12 23:44
@FKobus did you build the dev branch code?

**Comment by FerryKobus** [comment] 2017-01-13 08:45
@yyx990803 Missed that part. When running it on the new fixes it's behaving as before. Thanks for the response

**Comment by ttakahashi2013** [comment] 2017-09-17 14:50
hi, is this closed in the latest code?
i encountered the same issue.
