### ISSUE TITLE
:style will affect by other value update

### ISSUE THREAD

**Issue by yreenchan** [vuejs/vue#3912] opened 2016-10-12 04:24 UTC
### Vue.js version
2.0.1

### Reproduction Link

I have written an example in jsfiddle
https://jsfiddle.net/yreenchan/vfxtb7ps/1/

### Steps to reproduce
`
var vm = new Vue({
	el: '#app',
	data: {
		isShow: 0,
		second: 1
	}
});
`
1. :style="{opacity: isShow}", the default value of isShow is 0, and the dom is hidden;
2. change the value of another property 'second'

### What is Expected?
Don't effect the :style renderer results when it's value is not changed.

### What is actually happening?
when after i change the value of another property 'second', the hidden dom show again.

**Comment by yyx990803** [comment] 2016-10-12 04:41
Duplicate of #3905

**Closed by yyx990803** 2016-10-12 04:41 UTC
