### ISSUE TITLE
Idiomatic way to handle navigation?

### ISSUE THREAD

**Issue by brandoncarl** [vuejs/vue#2939] opened 2016-05-23 17:17 UTC
Hi Evan and crew –

Truly remarkable product. I've worked with computed for 30 years and this is one of the best things I've encountered.

I've run into an issue recently where a computed navigation isn't updating. Trying to understand the recommended course of action/idiomatic way of handling.

**The Setup**
1. Router encapsulates App
2. App contains NavBar and RouterView
3. RouterView is populated with Pages
4. The NavBar varies somewhat page to page

```
<app>
  <nav-bar></nav-bar>
  <router-view></router-view>
</app>
```

I'm currently keeping the NavBar separate from the page as a) I would like it to remain a fixture even as routes are changed, and b) it's concerns are somewhat separate from the page.

**The Nav Items**

Each Page contains NavItems it would like to append. When the Page is loaded, it emits an event, which allows the App to bind to certain of the pages properties (including navItems). The App's navItems are bound to the NavBar via a prop.

**The Problem**

For some Pages, navItems is a computed property (dynamic), which precedents. When the precedents are updated, the computed navItems is not recalculating.

Ideally I'd like to keep the navItems attached to the Page, and the NavBar attached to the App (as a reusable component). Nonetheless, I'm open to restructuring if there are more appropriate ways of handling.

Thanks!

Brandon

**Comment by simplesmiler** [comment] 2016-05-23 17:47
Hi, Brandon!

I can't think of a way to do this with computed properties. The best I can think of is to categorize the pages by their desired behavior with regards to nav items, store the category on the page, and then make NavBar responsible for calculating `navItems` given the page `$data` (this calculation should not rely on computed properties).

Another way is for the page construct and update the `navItems` manually rather than with computed property syntax, and send in to the NavBar when page enters. If you manage to not overwrite the reference to `navItems`, then all the changes that you make to the `navItems` will propagate.

**Comment by brandoncarl** [comment] 2016-05-23 17:55
Thanks for the quick response @simplesmiler! Much appreciated. I'll toy with some ideas and post what I settle on.

Is there any reason that the following wouldn't work?
`navItems (computed) depends on groups (computed) depends on groupBy (data)`

When I'm updating groupBy, groups is updating, but navItems is not...

**Comment by simplesmiler** [comment] 2016-05-23 18:02
I played with it, and actually it looks like you can send the whole page `vm` to the NavItems, and it will be able to save it to own `vm` and depend on computed properties. I don't know the implications of doing so off the top of my head though.

**Comment by brandoncarl** [comment] 2016-05-23 18:04
Oh interesting – right now I'm sending the Page to the App, which extracts the properties itself. I'll try your approach out as well.

**Comment by brandoncarl** [comment] 2016-05-23 18:50
@simplesmiler What I'm noticing is that if a computed property is not used in a view, it is not updated even if its predecessors update. Is that right? And if so, can I override it?

**Comment by simplesmiler** [comment] 2016-05-23 19:12
Computed properties are lazy, they do update only upon access. But if some binding (directive, including view output) depends on the property, it will be updated reactively. And there is no way to get the "non-updated" value if some of the dependencies got updated. You can find more details in the guide, under [Inside-Computed-Properties](https://vuejs.org/guide/reactivity.html#Inside-Computed-Properties). If you found an issue with how computed properties work, feel free to open a new issue with a reproduction.

**Comment by brandoncarl** [comment] 2016-05-23 19:15
@simplesmiler Posting this to help others:

1. I needed to attach navItems via an enclosing object so that the update would be noticed by the sibling view:

```
// Not this
<nav-bar :items="navItems"></nav-bar>
navItems = []

// This
<nav-bar :options="options"></nav-bar>
options = { items: [] }
```

I also had to add a watcher with { immediate: true }

**Comment by brandoncarl** [comment] 2016-05-23 19:16
@simplesmiler The computed property is not accessed within the component. It's accessed in a sibling component. When its predecessor changed, the computed property did not (most likely because it's not accessed within said component). If that's the intended behavior, I'll close this out! Otherwise I'll file a new issue.

**Comment by yyx990803** [comment] 2016-05-23 19:38
Hi Brandon, thanks for the interest, however GitHub issues are used for bug reports and feature requests. Please move discussions to the [forum](http://forum.vuejs.org/) instead.

**Comment by simplesmiler** [comment] 2016-05-23 19:39
If you can reproduce the issue, then feel free to file it.

A hacky solution to the original issue: https://jsfiddle.net/simplesmiler/xto1h4k4/4/
An idiomatic solution would be to define a set of possible nav items strategies, and to use vuex (or other state container) to store current strategy and necessary data for it.

Was about to close the issue, but Evan was faster.

**Closed by yyx990803** 2016-05-23 19:38 UTC

**Comment by brandoncarl** [comment] 2016-05-23 19:43
Apologies - wasn't sure if this was intended behavior or not, but I'll reserve this for known bugs only going forward.
