### ISSUE TITLE
async computed property support

### ISSUE THREAD

**Issue by LongTengDao** [vuejs/vue#9665] opened 2019-03-09 23:17 UTC
### What problem does this feature solve?

Redundant properties (and low cohesion for each) for asynchronous evaluation:  
为了异步求值虚设条目（并降低每个功能的内聚性）：

```vue
<template>
  <div>{{ result1 }} {{ result2 }}</div>
</template>

<script>
export default {
  props: ["url1", "url2"],
  data () {
    return {
      result1: "",
      result2: ""
    };
  },
  watch: {
    async url1 (url1) {
      this.result1 = await getPromise(url1);
    },
    async url2 (url2) {
      this.result2 = await getPromise(url2);
    }
  }
};
</script>
```

### What does the proposed API look like?

```vue
<template>
  <div>{{ result1 }} {{ result2 }}</div>
</template>

<script>
export default {
  props: ["url1", "url2"],
  computed: {
    result1 () {
      return getPromise(this.url1);
    },
    result2 () {
      return getPromise(this.url2);
    }
  }
};
</script>
```

**Comment by posva** [comment] 2019-03-09 23:47
Duplicate of  #4083

**Closed by posva** 2019-03-09 23:47 UTC
