### ISSUE TITLE
.once fire multiple times if there exist others event binding

### ISSUE THREAD

**Issue by ignoreswing** [vuejs/vue#4719] opened 2017-01-16 09:05 UTC
As far I know, [.once](https://vuejs.org/v2/guide/events.html#Event-Modifiers) would fire only one time.
However, .once would **fire multiple times**, when the DOM is "**not**" the last binding DOM in template.

For example,
```
<button @click.once='doThis'>btn#1</button> <!-- BUG: fire multiuple times!! -->
<button @click='doThis'>btn#2</button>
```
while if I change the order of the two buttons, i.e., 
```
<button @click='doThis'>btn#1</button> 
<button @click.once='doThis'>btn#2</button> <!-- fire only one time -->
```
.once would has the expected behavior.

For the same issue, I can't assign multiple .once listeners for multiple DOMs.
```
<button @click.once='doThis'>btn#1</button> <!-- BUG: fire multiuple times!! -->
<button @click.once='doThat'>btn#2</button> <!-- BUG: fire multiuple times!! -->
<button @click.once='doThis'>btn#3</button> <!-- fire only one time -->
```

I was wondering this is a feature or bug.
Thank you.

### Vue.js version
2.1.8 (latest)
MAC OS 10.11 + Chrome 55

### Reproduction Link
1. order cause .once fail
https://jsfiddle.net/ignoreswing/q90uox65/

2. Can't use multiple .once
https://jsfiddle.net/ignoreswing/t4y6nmzq/

### What is Expected?
1. btn#1 should fire only one time
2. If hitting the buttons, fire alert only "once" for all of the three buttons!

### What is actually happening?
1. btn#1 fire multiple time
2. btn#1 and btn#2 fire multiple times.

**Comment by defcc** [comment] 2017-01-16 09:36
Thanks, duplicate of #4655 , fixed via https://github.com/vuejs/vue/commit/ee6ad6af0e7d39f7f7b22bb5931045d748e03ca7

**Closed by defcc** 2017-01-16 09:36 UTC
