### ISSUE TITLE
Removing first and last element in a list rendered component forces a complete re-rendering of all items

### ISSUE THREAD

**Issue by rasmushaglund** [vuejs/vue#6857] opened 2017-10-19 13:20 UTC
### Version
2.5.2

### Reproduction link
[https://codepen.io/spenspazmer/pen/aLXGGY?editors=1011](https://codepen.io/spenspazmer/pen/aLXGGY?editors=1011)

### Steps to reproduce
1.Create a v-for list with items
2.Inspect and observe the item elements
3.Trigger an action that shifts and pops the list
4.Observe

### What is expected?
The items should be removed without re-rendering the item list.

### What is actually happening?
The whole list is re-rendered.

---
Adding new elements works just as expected, just as triggering several pop or shift operations, doing a single list splice from the end or start. Performing a splice from the beginning and the end respectively triggers the same re-rendering problem.

**Comment by posva** [comment] 2017-10-19 17:34
Duplicate of #4362

**Closed by posva** 2017-10-19 17:34 UTC

**Comment by rasmushaglund** [comment] 2017-10-19 18:04
Well actually the real problem in my case isn't the performance loss of re-rendering per se, but the fact that focus is lost from elements that are removed and then re-added to the DOM. Just as #4362 I'm trying to use a virtual scroller, but can't navigate with the keyboard since the re-rendering removes focus. The only way I've found to go around this is to listen to the blur event and do a re-focus, but that introduces a significant delay and ruins the experience.

The alternative is to handle this in the DOM directly, but that kind of defeat the purpose of using Vue.

**Comment by rasmushaglund** [comment] 2017-10-24 06:50
Ping @posva

I've created an ugly hack that instead of using slice do a series of shift, unshift, push and pop divided into inside and outside of a nextTick. This is a very ugly hack and I really do hope that this is not the recommended Vue-way. As I said above: this needs to be addressed in order to be able to create virtual scrollers with keyboard navigation.

**Comment by posva** [comment] 2017-10-24 10:36
yeah, the other issue is there...
For your input's issue using a key should do the trick but I guess you ask for more help in the forum or the chat if you need it

**Comment by rasmushaglund** [comment] 2017-10-24 12:45
I don't understand @posva, in the codepen repro above key was used, so I'm not sure how that would help. And we can also see that the key attribute is working since the re-rendering only occurs under specific conditions.
