### ISSUE TITLE
async data update for select option will trigger DOM "change" event

### ISSUE THREAD

**Issue by horans** [vuejs/vue#6317] opened 2017-08-08 03:44 UTC
### Version
2.4.2

### Reproduction link
[https://codepen.io/horan/pen/RZpKzP](https://codepen.io/horan/pen/RZpKzP)

### Steps to reproduce
open console panel to check log

### What is expected?
loading initial data for options should not trigger a DOM "change" event (as it should be done by user)

### What is actually happening?
async data update will result with a DOM "change" event, while sync data update will not.

---
this should has something to do with [commit c70addf](https://github.com/vuejs/vue/commit/c70addf7d1a8e820ed80b6ab14aace5aa7b604c5) and it was working fine with v2.4.1.

my app should fire a form submit after user changed option, but now the app will submit right after data initialized. (check commented line in sample js)

**Comment by jkzing** [comment] 2017-08-08 03:52
Thanks for reporting, this should be fixed by [https://github.com/vuejs/vue/pull/6194](https://github.com/vuejs/vue/pull/6194).

**Comment by LinusBorg** [comment] 2017-08-08 11:51
Closing as duplicate of #6193

**Closed by LinusBorg** 2017-08-08 11:51 UTC
