### ISSUE TITLE
Vue.set() doesn't force variable

### ISSUE THREAD

**Issue by maxxdev** [vuejs/vue#6933] opened 2017-10-26 19:30 UTC
### Version
2.5.2

### Reproduction link
[https://jsfiddle.net/xkkbfL3L/1916](https://jsfiddle.net/xkkbfL3L/1916)

### Steps to reproduce
Click to table header more then 1 time.

### What is expected?
List of names should be sorted evrytime when click on header.

### What is actually happening?
The list is sorted once.

---
Works fine if use temp variable like
```
 var tmp = this.sortOrders ;
   Vue.set(tmp, key, order); 
   this.sortOrders = [];
   this.sortOrders = tmp;
```

**Comment by LinusBorg** [comment] 2017-10-27 12:48
The problem is that you already create those keys before that moment, namely in `created ` - and there, you don't use $set().
```javascriptcreated: function () {
  this.columns.forEach(key => {
      this.$set(this.sortOrders, key, 1)
  })
},
```
After this change it works as expected

**Comment by maxxdev** [comment] 2017-10-27 13:01
Not works for me. I've update [Fiddle ](https://jsfiddle.net/xkkbfL3L/1926/)

**Comment by LinusBorg** [comment] 2017-10-27 13:20
It's `Vue.set()` or `this.$set()` - not `Vue.$set()`

https://jsfiddle.net/Linusborg/xkkbfL3L/1927/

**Comment by LinusBorg** [comment] 2017-10-30 10:13
Closing since I can only assume the issue is resolved.

**Closed** 2017-10-30 10:13 UTC
