### ISSUE TITLE
Button with v-if triggers event on v-else button when clicked using form

### ISSUE THREAD

**Issue by andersmar** [vuejs/vue#9866] opened 2019-04-12 09:59 UTC
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/txnamgy8/1/](https://jsfiddle.net/txnamgy8/1/)

### Steps to reproduce
Click the button

### What is expected?
Clicking the button should swap out "button" button with a "submit" button.
The button should change to "Submit" button which will submit form when clicked.

### What is actually happening?
The form submit is triggered when "button" is pressed.

---
Suspect it is a focus issue. 
Method worked before updating to Vue v2.6.10.
Form works as expected when using new v-slots

**Comment by posva** [comment] 2019-04-12 10:00
Duplicate of #9340

**Closed by posva** 2019-04-12 10:00 UTC
