### ISSUE TITLE
"v-slot" abbreviated syntax for default slot does not observe components using is="component-name"

### ISSUE THREAD

**Issue by ryaninvents** [vuejs/vue#11296] opened 2020-04-08 17:18 UTC
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/s/elated-sun-8npx9?file=/src/App.vue](https://codesandbox.io/s/elated-sun-8npx9?file=/src/App.vue)

### Steps to reproduce
Error message displays immediately when viewing repro.

### What is expected?
Vue should recognize that the given `v-slot` is attached to a component, because the element has the `is="hello-world"` attribute set.

### What is actually happening?
Vue sees the `v-slot` attribute on a `section` element, and assumes it is an error.

---
Ordinarily I'd just rewrite my code to directly reference the component (without the `is=` attribute) but I'm rehydrating server-rendered content and need the wrapper to be semantic.

**Comment by posva** [comment] 2020-04-08 18:23
Duplicate of https://github.com/vuejs/vue/issues/10152

**Closed by posva** 2020-04-08 18:23 UTC
