### ISSUE TITLE
[Vue warn]: Invalid handler for event "click": got undefined / vue.common.js?e881:1559 Uncaught (in promise) TypeError: Cannot read property 'invoker' 

### ISSUE THREAD

**Issue by murbanowicz** [vuejs/vue#4259] opened 2016-11-20 22:22 UTC
### Vue.js version
2.0.8

### Steps to reproduce
Do the same?

### What is Expected?
Working...

### What is actually happening?
Hi,

I have list of elements which I want to go to edit when clicked.
I have similar solution in other component and it is working perfectly fine but in new one it is not and can't find why.

When component is rendered I got:
`Invalid handler for event "click": got undefined`

List:
```
<div v-for="annt in anns" class="item two-lines" v-if="!anntInEdit">
          <div class="item-content has-secondary" v-on:click="edit(annt)">
            <div>
              {{ annt.title }}
            </div>
            <div >
              {{ annt.body}}
            </div>
          </div>
          <div class="item-secondary">
          <a><i >delete</i></a>
          </div>
        </div>
```

JS:
```
edit (annt) {
        if (this.anntInEdit == null) {
          this.anntInEdit = annt
          this.anntInEditBackup = Object.assign({}, this.anntInEdit)
        }
        this.anntInEditIndex = this.anns.indexOf(annt)
      },
```

When I will just click, I got Announcement in edit snf div with form is shown, I can use save(ajax), cancel (just set inedit to null) etc. but as soon as I touch any input inside edit div I got:
`[Vue warn]: Invalid handler for event "click": got undefined `
`vue.common.js?e881:1559 Uncaught (in promise) TypeError: Cannot read property 'invoker' of undefined`
and as soon as I get errors, any button in edition is not working at all.

Full error stack:
```
warn	@	vue.common.js?e881:2658
updateListeners	@	vue.common.js?e881:1527
updateDOMListeners	@	vue.common.js?e881:4553
invokeCreateHooks	@	vue.common.js?e881:3951
createElm	@	vue.common.js?e881:3922
updateChildren	@	vue.common.js?e881:4097
patchVnode	@	vue.common.js?e881:4159
updateChildren	@	vue.common.js?e881:4084
patchVnode	@	vue.common.js?e881:4159
updateChildren	@	vue.common.js?e881:4076
patchVnode	@	vue.common.js?e881:4159
patch	@	vue.common.js?e881:4272
Vue._update	@	vue.common.js?e881:1734
(anonymous function)	@	vue.common.js?e881:1707
get	@	vue.common.js?e881:736
run	@	vue.common.js?e881:805
flushSchedulerQueue	@	vue.common.js?e881:623
nextTickHandler	@	vue.common.js?e881:401
﻿```

The same div is used for new/edit and is working perfectly fine for new annoucement.
Any ideas? I don't think there is any error in my code as I really have exactly the same logic in another component and it is working perfectly fine.
Whole JS/HTML are inside the same Vue file.

**Comment by yyx990803** [comment] 2016-11-20 22:23
Thanks for filing the issue. Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) and provide a minimal JSFiddle or JSBin containing a set of reproducible steps that can lead to the behavior you described.

**Comment by murbanowicz** [comment] 2016-11-21 21:48
Got it. It was not about top level function @click . It was about @click for the element which was becoming rendered when top level click was invoked. I had a misspelling in the function name. Unfortunately, Vue is not throwing the name of the missing function and that's the reason why I could not find it because I was looking in wrong place...

Maybe it can be improved somehow?

**Comment by yyx990803** [comment] 2016-11-22 14:30
Closing since the original issue is resolved.

AFAIK Vue will warn you if your v-on expression references a method that does not exist if you are using a browser that supports ES6 Proxy. It's hard to improve without seeing a real reproduction of the issue.

**Closed by yyx990803** 2016-11-22 14:30 UTC
Labels: need repro

**Comment by Dafrok** [comment] 2017-08-19 03:57
If you define a member of data or props as the same name with your handler, it will be broken.

For example, clicking that FOO button causes an error with the message: `Invalid handler for event "click": got null`

```vue
<template>
<div @click="edit">FOO</div>
</template>

<script>
export default {
  data () {
    return {edit: null}
  },
  methods: {
    edit () { /* do something */ }
  }
}
</script>
```

**Comment by bigsee** [comment] 2018-03-23 10:00
Just to add a (perhaps obvious) case that might cause this... I was guilty of another silly reason for getting this error.

The method called on my click handler was accidentally placed under computed properties instead of methods (damn you, syntax highlighting! 🤭🤬😂). What threw me was a combination of generic console error I didn't really understand and the fact that the app rendered in the browser even though compilation had failed in the IDE.

This is the error I got:

<img width="1280" alt="screen shot 2018-03-23 at 10 57 06" src="https://user-images.githubusercontent.com/11768967/37823183-fe5d24fc-2e88-11e8-930b-5e0aaa379808.png">

...but this was the (much more helpful) error from the command line...

<img width="1084" alt="screen shot 2018-03-23 at 10 58 11" src="https://user-images.githubusercontent.com/11768967/37823248-3b6e6b6c-2e89-11e8-909c-329fc1155077.png">

Funny that when compilation has an error, I usually get a black overlay on the browser which blocks render, but didn't in this case. I'm sure there's a good reason for that, which I don't yet understand, but this might be a gotcha for any other n00bs out there... 😀

**Comment by Soumit-the-billionaire** [comment] 2018-08-11 15:38
check whether you have written method or methods ????

**Comment by monsdroid** [comment] 2018-12-12 12:46
```
data () {
      return {
        msg: {
          copyToClipboard: 'sometext',
        }
      }
    },
methods: {
      copyToClipboard () {
```
`@click=copyToClipboard` could call the method once. after that it became `_vm.copyTo...` not found

**Comment by midnight92** [comment] 2019-03-30 14:20
"methods" miss "s"......
