### ISSUE TITLE
And options.model.lazyEvent option

### ISSUE THREAD

**Issue by LongTengDao** [vuejs/vue#10493] opened 2019-09-07 15:18 UTC
### What problem does this feature solve?

`v-model.lazy` on component is ignored and wasted, while `.number` and `.trim` are effective.

### What does the proposed API look like?

```
options: {
    model: {
        prop?: string,// = 'value'
        event?: string,// = 'input'
        lazyEvent?: string,// = 'change'
    }
}
```

**Comment by posva** [comment] 2019-09-09 07:39
Duplicate of https://github.com/vuejs/vue/issues/6914

**Closed by posva** 2019-09-09 07:39 UTC
