### ISSUE TITLE
vue-server-renderer: falsy styles are not filtered

### ISSUE THREAD

**Issue by manniL** [vuejs/vue#9268] opened 2018-12-29 10:26 UTC
### Version
2.5.21

### Reproduction link
[https://github.com/manniL/vue-server-renderer-falsy-styles-bug/](https://github.com/manniL/vue-server-renderer-falsy-styles-bug/)

### Steps to reproduce
1. Clone repo
2. Install deps
3. Run `src/index.js`

### What is expected?
`<h1 data-server-rendered="true" style="color: 'red'">Welcome!!</h1>`

### What is actually happening?
`<h1 data-server-rendered="true" style="height:null;color:red;">Welcome!!</h1> `

### Related

https://github.com/nuxt/nuxt.js/issues/4652

**Comment by posva** [comment] 2018-12-29 11:14
Duplicate of #9231

**Closed by posva** 2018-12-29 11:14 UTC

**Comment by yyx990803** [comment] 2019-01-11 19:59
@manniL incidentally fixing this causes some Nuxt test cases to fail: https://circleci.com/gh/vuejs/regression-testing/143

**Comment by manniL** [comment] 2019-01-11 20:11
@yyx990803 Thanks for the heads up! Looks like most of them are related to the fix itself (where just the HTML string mismatches).

Not sure why the timing-related tests fail though.
Wil ldig in :relaxed:
