### ISSUE TITLE
Extend support for modifier keys (.cmd, .cmdOrCtrl)

### ISSUE THREAD

**Issue by bkzl** [vuejs/vue#4843] opened 2017-02-02 14:49 UTC
What do you think about extending the modifier keys by these:

`.cmd` - only for macOS and represents the command key
`.cmdOrCtrl` - represents command key on macOS and control key on Linux/Windows

The second one (`cmdOrCtrl`) is a widely used concept in [Electron apps](https://github.com/electron/electron/blob/master/docs/api/accelerator.md#platform-notice) to create shortcuts in a more natural way for users of specific systems.

Personally, I have a custom textarea component which implements custom key bindings i.e. `cmd/ctrl + ←` to move the caret to the beginning of textarea. I would love to make this work by using a single, OS-aware modifier.

**Comment by yyx990803** [comment] 2017-02-02 15:12
Isn't this what `.meta` does? https://vuejs.org/v2/guide/events.html#Modifier-Keys

**Comment by bkzl** [comment] 2017-02-02 15:59
Not exactly.

`.meta` responds to Windows key on Windows/Linux and command key on Mac. The same modifier is called "Super" in Electron.

`.cmdOrCtrl` (or any better name) could respond to control key on Windows/Linux and command key on Mac. This is more common situation from the UX point of view than `.meta` as Windows/Linux users generally use control key for the same things that Mac users use command key (`ctrl+v` vs `cmd+v`, `ctrl+z` vs `cmd+z` etc.).

The current solution requires something like this:

```vue
<template>
  <textarea @keydown.meta.left="fooOnMac" @keydown.ctrl.left="fooOnWindowsOrLinux"></textarea>
</template>

<script>
export default {
  methods: {
    foo() {
      // ...
    },
    fooOnMac () {
      // ...
      if (mac) {
        this.foo()
      }
    },
    fooOnWindowsOrLinux () {
      // ...
      if (windows || linux) {
        this.foo()
      }
    }
  }
}
</script>
```

With the new modifier, you could limit that to:

```vue
<template>
  <textarea @keydown.cmdOrCtrl.left="foo"></textarea>
</template>

<script>
export default {
  methods: {
    foo() {
      // ...
    }
  }
}
</script>
```

**Comment by yyx990803** [comment] 2017-02-02 17:51
The problem is that Vue as a front-end library runs not only in Electron - when running in browsers, we cannot consistently detect what OS the app is running in, so we can't perform the platform checks as you did in your first example inside the library itself. You will have to do it in userland code anyway.

Instead, I'd suggest creating a reusable function wrapper:

``` js
function checkCmdOrCtrl (fn) {
  return function (e) {
    if ((mac && e.metaKey) || ((windows || linux) && e.ctrlKey)) {
      return fn.apply(this, arguments)
    }
  }
}
```

Then in components that need this functionality:

``` vue
<template>
  <textarea @keydown.left="foo"></textarea>
</template>

<script>
export default {
  methods: {
    // wrap the function
    foo: checkCmdOrCtrl(function () {
      // ...
    })
  }
}
</script>
```

**Comment by bkzl** [comment] 2017-02-02 19:51
Yeah, I thought about browsers and using `navigator.platform` but you are right. It's getting out of the framework scope and more like an idea for a plugin. Basic wrappers for KeyboardEvent properties are enough for the most of the cases.

---

On the other hand, is this expected behavior of modifiers or should be considered as a bug?

JSFiddle Demo: https://jsfiddle.net/qzdt20ya/

```vue
<template>
  <input @keydown.meta.left="logCmd" @keydown.meta.shift.left="logCmdShift">
</template>

<script>
export default {
  methods: {
    logCmd () {
      console.log('cmd + left pressed')
    },
    logCmdShift () {
      console.log('cmd + shift + left pressed')
    }
  }
}
</script>
```

### What is expected?

Log for pressing `cmd + ←`:

```
cmd + left pressed
```

Log for pressing `cmd + shift + ←`:

```
cmd + shift + left pressed
```

Log for pressing `shift + ←`:

```
```

### What is actually happening?

Log for pressing `cmd + ←`:

```
cmd + left pressed
```

Log for pressing `cmd + shift + ←`:

```
cmd + left pressed
cmd + shift + left pressed
```

Log for pressing `shift + ←`:

```
```

**Comment by yyx990803** [comment] 2017-02-06 18:52
@bkzl I'd say that's expected behavior. `.meta.left` doesn't rule out other modifier keys being pressed at the same time.

**Comment by barata0** [comment] 2017-06-17 12:20
I would suggest adding a modifier to .none as well.

Following the same idea to capture only keys pressed but without CTRL SHIF ALT or META pressed.

```
<template>
  <input @keydown.left="logAllLeftCmd" @keydown.none.left="logOnlyLeftCmd">
</template>

<script>
export default {
  methods: {
    logOnlyLeftCmd () {
      console.log('only left pressed')
    },
    logAllLeftCmd () {
      console.log('left pressed with or without modifiers')
    }
  }
}
</script>

```

**Comment by yyx990803** [comment] 2017-09-14 21:38
Closing since the original suggestion involves platform sniffing which can be quite tricky. This is probably something that's better dealt with in userland.

**Closed by yyx990803** 2017-09-14 21:38 UTC
Labels: 2.x, feature request

**Comment by revolter** [comment] 2017-12-18 21:54
This makes a lot of sense. For a lot of shortcuts, <kbd>ctrl</kbd> in Windows is replaced by <kbd>cmd</kbd> on macOS. Think of multiple file selections (<kbd>ctrl</kbd>/<kbd>cmd</kbd> + click) for example.

**Comment by tarwin** [comment] 2018-08-22 16:37
I agree that this is something that would be super useful. Ctrl is replaced by Cmd on MacOS.

**Comment by arnold-graf** [comment] 2019-07-12 12:48
Also agree that it would be useful, but I understand the arguments made above.

Suggestion: we could call it `ctrlOrMeta`. That way we wouldn’t have to sniff platforms, and both would work. It would be explicit enough not to confuse people too much either.

**Comment by esaruoho** [comment] 2020-02-26 19:31
So.. what happened with ctrlOrMeta? Will it be implemented, or will this require a workaround in the future, too?

**Comment by ThomasKientz** [comment] 2020-07-01 10:11
My workaround :

```
@click.exact="primary()"
@click.meta="secondary()"
@click.ctrl="secondary()"
@contextmenu.prevent
```
