### ISSUE TITLE
Vue binding overrides element attribute

### ISSUE THREAD

**Issue by wostex** [vuejs/vue#5846] opened 2017-06-08 10:57 UTC
### Version
2.3.4

### Reproduction link
[https://jsfiddle.net/wostex/2t2pv9hy/](https://jsfiddle.net/wostex/2t2pv9hy/)

### Steps to reproduce
Create a component with template `<input type="text"/>`

Render this component as `<my-input v-bind="{type: 'foobar'}"></my-input>`. No `type` prop is declared in component itself.

`input`'s `type` HTML attribute gets overwritten with `foobar` 

Source: https://stackoverflow.com/questions/44431754/vue-binding-overrides-element-attribute

### What is expected?
type="text"

### What is actually happening?
type="foobar"

**Comment by wostex** [comment] 2017-06-08 11:04
The same thing with `<my-input v-bind:type="'foobar'"></my-input>`

**Comment by LinusBorg** [comment] 2017-06-08 11:09
That's expected behaviour.

**Comment by posva** [comment] 2017-06-08 13:12
It will be counter intuitive to not override the value, wouldn't it? As it's not something that can get merged it overrides. If you want to explicitly ignore it and always use a text value, you can declare it as a prop (but not use it)

**Closed by posva** 2017-06-08 13:12 UTC

**Comment by chrisvfritz** [comment] 2017-06-10 02:07
@wostex It's one of those slightly controversial features. 🙂  It seems a little strange to me too, giving each component an undocumented API and assuming each parent component knows what the child component's root element will be. In practice though, I've found that the feature very rarely causes a problem as long as you don't _try_ to use it in applications. Some _do_ use it and enjoy it though, so YMMV.

I personally feel it's more meant for component library authors (e.g. for integrating Bootstrap/MDL), who have reported finding it very helpful, since it's more difficult to predict how each component might be used. For example, there are Bootstrap plugins that require adding new attributes/classes, so the ability to add these arbitrary attributes means authors don't have to work so hard to accommodate edge cases.

### In the docs

@LinusBorg You're right, I don't see it anywhere in the docs. Thinking back, I'm wondering if I purposefully left it out because I personally consider it an anti-pattern in application code. We include warnings for any escape hatches from the "props down, events up" workflow, such as:

> Use `$parent` and `$children` sparingly - they mostly serve as an escape-hatch. Prefer using props and events for parent-child communication.

Except with the implicit passing of attributes, it's possible to violate this workflow accidentally. 🙈  Despite my feelings, many do find it useful and want to know about it, so I acquiesce. 😄  I just opened a PR and would love to hear your thoughts on the explanation @LinusBorg, @posva, and @wostex.

### Hopes and dreams? 🤞 

For the next major version of Vue, I might make another push to have this behavior disabled by default - or even altogether, since functional components can technically be used to explicitly pass arbitrary attributes to a root element (or any other element) when desirable. Even with a normal component, custom props can be used for more powerful (and explicit) attribute passing:

``` vue
<div v-bind="groupAttrs" class="form-group">
  <div v-bind="controlAttrs" class="form-control">
    <label v-bind="labelAttrs">{{ label }}</label>
    <input 
      v-bind="inputAttrs"
      :value="value"
      @input="$emit('input', $event.target.value)"
      type="date"
    >
  </div>
</div>
```

``` vue
<input-text
  v-model="birthday"
  inputAttrs="{ 'data-3d-date-picker': true }"
  controlAttrs="{ class: 'date-picker-theme-calico' }"
/>
```

This pattern also allows inspecting arbitrary attributes to provide warnings, for example when:

- a set of classes shouldn't be used together
- the user is trying to use external plugins that are outdated or conflict with each other
- the user is trying to add classes/attributes have been deprecated

**Comment by wostex** [comment] 2017-06-10 09:27
Thanks for your explanation, @chrisvfritz. 

I thought it's a bug because it seems to be out of line with common Vue concepts. Although if other people benefit from using it, maybe this feature should just be documented.

**Comment by posva** [comment] 2017-06-10 12:26
@chrisvfritz I really think this should be kept because removing it would enforce using render function in every component lib and in-app specific ui component

**Comment by chrisvfritz** [comment] 2017-06-11 15:51
@posva I wonder if as a compromise, a new directive could be added to specify the "primary" element (the one that attributes should be added to), since it may not always be the same as the root element. I think that could mostly solve the problem of users having to know implementation details of components.

For example, in the case of a very simple `text-input` component with the following template:

``` html
<div class="form-control">
  <input type="text">
</div>
```

People might be surprised that after adding this class:

``` html
<text-input class="highlighted">
```

This CSS still doesn't work:

``` css
input.highlighted {
  box-shadow: 0 0 10px green;
}
```

Right now, component authors can selectively "forward" attributes by defining them as props and specifying how they should be applied, but this way, they could set a sane default instead of going through so much work and trying to imagine every possible scenario. What do you think?

**Comment by posva** [comment] 2017-06-11 16:25
I think that if you want to control where those attributes (like class) should go, it's better to always use props as this would also work when having to reuse a class or put different attributes in different children:

```html
<label :for="id">..</label>
<input :id="id">
```

Here, `id` needs to be a prop because it must be used at multiple places

The class example is a bit weird imo, because when using an ui lib, you have to check the actual html before trying to add classes and you'll probably end up with something like:

```css
.is-dark .ui-TextInput-Input {
  color: white;
  background: black;
}
```

**Comment by chrisvfritz** [comment] 2017-06-22 13:45
@posva In cases [like this though](https://github.com/almino/semantic-ui-vue2/blob/master/src/elements/Input.vue#L8-L62), it's very tedios to set up a lot of props and bindings. Being able to set a different "primary" element would make this element much simpler. Then for props could only be used for anything that is _not_ an attribute to be passed to the `input` element. Does that make sense? (Also, I'm writing this sitting right next to you - weird... 😲 ).

**Comment by posva** [comment] 2017-06-22 14:06
Indeed, having a primary element in a component looks like something useful enough. Maybe referring to it with a `ref` or a main property:

```html
<template>
    <div>
      <input ref="$main">
    </div>
</template>
```
