### ISSUE TITLE
functional comp. provide -> functional comp. inject

### ISSUE THREAD

**Issue by patriciussanctus** [vuejs/vue#11015] opened 2020-01-16 16:09 UTC
### Version
2.6.11

### Reproduction link
[https://codepen.io/PatriciusSanctus/pen/PowdQpq](https://codepen.io/PatriciusSanctus/pen/PowdQpq)

### Steps to reproduce
```
Vue.component('func-parent', {
  functional: true,
  provide: () => ({ foo: 'bar' }) // || { foo: 'bar' }
})
Vue.component('func-child', {
  functional: true,
  inject: ['foo']
})
```

### What is expected?
i want use injection in render() function

### What is actually happening?
[Vue warn]: Injection "foo" not found

---
without DOM i can't send parent`s props to child for control child behavior (simple example: "grid-row -> grid-col")

**Comment by posva** [comment] 2020-01-16 16:51
Duplicate of https://github.com/vuejs/vue/issues/5837

**Closed by posva** 2020-01-16 16:51 UTC
