### ISSUE TITLE
Handling collections of child components, a Vue pain point?

### ISSUE THREAD

**Issue by thelinuxlich** [vuejs/vue#2207] opened 2016-01-21 23:49 UTC
Consider an example, I have a Filter component which can spawn 0-N FilterItem components(each FilterItem acts like a DSL subquery with property, comparator and value), the parent template would look like this:

```html
<filter :items.sync="items" v-ref:filter></filter>
```

And inside the Filter component:
```html
<filter_item v-for="item in items" :item.sync="item" v-ref:filter_items></filter_item>
```

So the ViewModel using the Filter component mantains an array(filter_items) which contains the state for each FilterItem, but it is a primitive representation, so anytime I want the true representation, I'd need to invoke a method on the $referenced component:

```javascript
// instead of inspecting this.items on the parent, we need to execute something on the component
// which will probably have to iterate this.$refs.filter_items inside the Filter component too
this.$refs.filter.get_crunched_representation();
```

And it gets even more complicated when you want to hydrate these components...anyway, the approach above works but I wonder if it wouldn't be possible to do something like this:

```javascript
this.items.push(new FilterItem({....}))
```
And do the hydration on the component constructor, invoke methods directly on each item instead of the $reference, avoid redundancy.

**Comment by yyx990803** [comment] 2016-01-22 17:20
Isn't the true representation the `items` array?

**Comment by thelinuxlich** [comment] 2016-01-22 17:27
In this case it is a intermediate representation, the data you would pass to a constructor to get the final result(the component)

**Comment by yyx990803** [comment] 2016-01-23 16:25
I think the problem is because you are placing the actual representation as component local state inside the `filter_item` components. In reality they should not be component state, they should be in a global store.

I'm closing this because this is not a bug or a feature request, so it's better continued on the forum.

**Closed by yyx990803** 2016-01-23 16:25 UTC

**Comment by thelinuxlich** [comment] 2016-01-25 17:47
A store wouldn't solve this, because the object would be a intermediate representation, to be turned into the real representation once passed to the component constructor.
