### ISSUE TITLE
"errorCaptured" not working properly with functional child components

### ISSUE THREAD

**Issue by mcjazzyfunky** [vuejs/vue#7009] opened 2017-11-06 19:22 UTC
### Version
2.5.3

### Reproduction link
[https://jsfiddle.net/pp0h9nu4/1/](https://jsfiddle.net/pp0h9nu4/1/)

### Steps to reproduce
1. Please open https://jsfiddle.net/pp0h9nu4/1/ and have a look at the output window. Everything is fine: The output of all three components is shown poperly.

2. Now remove "//" from the comment "// throw new Error('...')" in Component-3's "render" function, run again and have a look in the console: Component-2 has captured the error as expected - still everything fine.

3. Now remove "//" from the comment "// functional: true," in Component-3 and run again and check the console:
The error is not captured by "Component-2" any longer (compared to 2.)

### What is expected?
Errors triggered by child components should be captureable by parent error boundaries, independent whether those child components are funtional or not.

### What is actually happening?
Errors triggered by functional components are not captured by parent error boundaries.

**Comment by LinusBorg** [comment] 2017-11-09 11:11
This is expected behaviour, since the functional component is being run in the main instance's scope, and the result is being passed as slot content to component 2 - this execution of `comp-3` happens *before* `comp-1` or `comp-2`  have actually been instantiated and rendered, so I don't think there's an easy solution to this particular situation.

If you would render `comp-3` in `comp-2`'s template instead, then the error would be captured by `comp-1` as expected:

https://jsfiddle.net/pp0h9nu4/3/

**Comment by yyx990803** [comment] 2017-11-09 17:02
As explained by @LinusBorg, functional components are eager-rendered - their render functions are invoked directly in the render function of the component that uses them, so the error cannot be captured by another component in the same template scope.

I don't think there is a way to "fix" this, unless we change the way functional components are rendered (making them no longer eager-rendered). That might have some benefits in making functional components' behavior more consistent with stateful ones, but I'll close this issue for now since that's a different topic.

**Closed by yyx990803** 2017-11-09 17:02 UTC

**Comment by mcjazzyfunky** [comment] 2017-11-09 17:27
Thanks to @LinusBorg and @yyx990803 for the detailed information.
Just one last remark (no need to answer):
This strange behavior may be "expected" by Vue core developer, but for a "normal" Vue user this behavior stays "strange".
Normaly an ErrorBoundary compent is just a container that either shows its children or (in case of errors thrown by its children) some error details.
It's really not a "feature" that this will only work with non-functional child components.
Would be great if the Vue team would reconsider that "eager-rendering" thing in near future major versions.
Thanks a lot for the great job you guys do with the Vue library.

PS:
Have a look at React16  - this is how things should work in my opinion: 
https://jsfiddle.net/hmw7v8eq/
