### ISSUE TITLE
Transition Filckering

### ISSUE THREAD

**Issue by DontShootMe** [vuejs/vue#8005] opened 2018-04-12 06:48 UTC
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/eywraw8t/31863/](https://jsfiddle.net/eywraw8t/31863/)

### Steps to reproduce
Create a transition effect on a page

### What is expected?
a fluid transition without flickering

### What is actually happening?
During the transition, at the step where the 'Original' DOM element is removed and before the 'Replacement'  is injected there is no 'filler', so the space occuped by the 'Orignal' become empty and generate the flickering because every DOM element next the 'Original' fill this empty space, and at the moment the 'Replacement' is injected the next DOM element are pushed to their original place

**Comment by posva** [comment] 2018-04-12 10:58
Cannot reproduce. Maybe this is happening on a specific browser, if that's the case, please, specify it in the issue. Closing until more details are provided

**Closed by posva** 2018-04-12 10:58 UTC

**Comment by posva** [comment] 2018-04-12 16:33
I tested on latest Firefox and everything worked fine

**Comment by MattFloyd** [comment] 2018-04-12 17:58
I can reproduce this -- Windows 10, Firefox 59.0.2 (64-bit). Not happening in Chrome.

**Comment by DontShootMe** [comment] 2018-04-12 18:17
Yes the test has be done on the latest firefox !

---
> Browser :
>    >  Mozilla Firefox 59.0.2 (64 Bits)

**Comment by DontShootMe** [comment] 2018-05-01 16:46
Hi,
What about this ? 
@posva just a little up to know what to do !
Thank you

**Comment by posva** [comment] 2018-05-01 17:11
I tested on firefox 60 and it doesn't flicker, you may have a browser plugin or something but it doesn't look like a Vue problem

**Comment by DontShootMe** [comment] 2018-05-03 12:13
@fnlctrl  it seems like it's not only a Windows Firefox issue => tested on Linux and Android !
Thank you for your answers !
