### ISSUE TITLE
Elements lose focus on re-render when siblings use v-if, even if element is reused

### ISSUE THREAD

**Issue by adamwathan** [vuejs/vue#9883] opened 2019-04-17 00:13 UTC
### Version
2.6.10

### Reproduction link
[https://codepen.io/anon/pen/ZZvVWv](https://codepen.io/anon/pen/ZZvVWv)

### Steps to reproduce
Create a component that contains a button or input sandwiched in between two other elements that are both conditionally rendered using v-if against the same piece of data:

```js
new Vue({
  el: '#app',
  template: `
  <div id="app">
    <div v-if="open">Hello</div>
    <input key="input" ref="input" @focus="open = true" @blur="open = false">
    <div v-if="open">World</div>
  </div>
  `,
  data: {
    open: false
  }
)
```

Now click the input to try and focus it.

### What is expected?
The two conditional elements appear, the input is focused.

### What is actually happening?
The input is focused but immediately blurred, the component renders twice, and the conditional elements are hidden. It is impossible to actually focus the input. This is bizarre because the element is the exact same DOM node, you can confirm via logging, and that's what `key` is there to ensure.

---
This example looks silly but it's a real problem when you start trying to build things like autocomplete components, where you want to render an invisible clickable backdrop to add simple "click away" behavior (this is how GitHub does click away, it's the only bullet proof approach I've found especially when you start using portals as well) and you also need to render the autocomplete dropdown when the input is focused.

**Comment by dejour** [comment] 2019-04-17 01:25
I will take a look this.

**Comment by Justineo** [comment] 2019-04-17 01:50
Duplicate of #6929

**Closed by Justineo** 2019-04-17 01:50 UTC

**Comment by Justineo** [comment] 2019-04-17 01:54
See also #9473, #9496, #9808.

---

> where you want to render an invisible clickable backdrop to add simple "click away" behavior (this is how GitHub does click away, it's the only bullet proof approach I've found especially when you start using portals as well)

I think you can also listen to `click` events on `document.documentElement` and check if the event target is within the input or the dropdown overlay.

**Comment by dejour** [comment] 2019-04-17 04:08
Problem is in the patching process. With current before and after vnode structure. updateChilden will
use insertBefore (this method will make current element or its children to lose focus) to move input vnode which will trigger input's blur method. Is there a appropriate way to handle this.

**Comment by Justineo** [comment] 2019-04-17 04:21
@dejour Yes, it also causes `<iframe>`s to reload.
