### ISSUE TITLE
Issue with "once" event modifier

### ISSUE THREAD

**Issue by AmrIKhudair** [vuejs/vue#9106] opened 2018-11-24 13:31 UTC
### Version
2.5.17

### Reproduction link
[https://codepen.io/AmrIKhudair/pen/YRLEYo](https://codepen.io/AmrIKhudair/pen/YRLEYo)

### Steps to reproduce
1- open the minimal reproduction
2- Type something (notice that the first time you focus the last input a new input appears)
3- delete one of the todos (other than the last one)
4- Focus the last one again (now a new todo is not created)

### What is expected?
A new todo is created

### What is actually happening?
A new todo isn't created

---
I think it has something to do with reusing dom elements for improving performance

**Comment by posva** [comment] 2018-11-24 16:34
Duplicate of https://github.com/vuejs/vue/issues/8032

**Closed by posva** 2018-11-24 16:34 UTC
