### ISSUE TITLE
transition-leave not leaving on v-for when iteration value changes

### ISSUE THREAD

**Issue by darkylmnx** [vuejs/vue#2614] opened 2016-04-02 19:38 UTC
This bug occurs when i shuffle the original data used in the view

### Vue.js version
1.0.20 - latest via vue-cli

### Reproduction Link
https://jsfiddle.net/s7o1xdyv/

### Steps to reproduce
just click next button at least 3 times

### What is Expected?
The current <LI> to leave with transition and the next  <LI> to enter with transition

### What is actually happening?
you will see 2 <LI> appear instead of 1 because the transition-leave did not leave as expected

I even listend for the leaveCancelled event, it never occured for element still staying.
any idea ? thanks

**Comment by FadyMak** [comment] 2016-04-06 14:26
Hey there! I believe the issue is occurring because you are tracking by id (`track-by="id"`) but toggling the visibility based on the index of the array which gets shuffled (`cti == i `).

I'd suggest tracking by another property or changing the way `cti` is computed. I've created another fiddle for you to see what I mean: [JSFiddle Demo](https://jsfiddle.net/awuxva59/).

Also note that the opacity was changed from `0.1` to `0`.

I'm going to go ahead and close this, however if you feel that this doesn't actually solve the issue please feel free to reopen the issue and we can take a deeper look.

**Closed by FadyMak** 2016-04-06 14:26 UTC
