### ISSUE TITLE
v-model.number allows for things other than numbers

### ISSUE THREAD

**Issue by mmestas** [vuejs/vue#11136] opened 2020-02-21 17:01 UTC
### Version
2.5.13

### Reproduction link
[https://jsfiddle.net/mmestas/ca7v214w/1/](https://jsfiddle.net/mmestas/ca7v214w/1/)

### Steps to reproduce
<input v-model.number="modelName.name"
                     name="inputName"
                     placeholder="0-65"
                     type="number"
                     max="65"
                     min="0"                
                     />

Type in 0-2 or any number value with a "-" after it.

### What is expected?
That only numbers are allowed

### What is actually happening?
the v.model.number with type=number allows for the input of characters other than numbers, specifically, "-".
My guess is this is allowed because of numbers like "-3" but this enables someone to enter (eg: 0-2) into the input.
I had to create special functions using v-on:keypress and v-on:keyup to validate the inputs to not receive something like "0-2"

**Comment by posva** [comment] 2020-02-22 14:48
Duplicate of https://github.com/vuejs/vue/issues/7136

**Closed by posva** 2020-02-22 14:48 UTC
