### ISSUE TITLE
v-model not update when use the Chinese input method

### ISSUE THREAD

**Issue by Jerret321** [vuejs/vue#5158] opened 2017-03-10 03:01 UTC
中文输入法导致 v-model 的值不更新

代码：http://jsbin.com/robetuzuxo/edit?html,js,output
demo: http://output.jsbin.com/robetuzuxo

当用手机浏览器打开 demo 后，点击 input 输入框，切换至中文输入法，随便输入，然后直接点击 submit 按钮（不要点击完成或者 done），发现 v-model 的值没有更新，但是通过原生方法找到 input 的 value，发现 value 值是更新过的，这种情况要怎么处理？目前我们的解决方案是重新封装一个 input component 出来，但是以前的上线的全部业务现在出现这种情况，直接导致业务不可用了. 当然可以使用computed setter getter 解决，但是，由于业务中有大量的表单数据，使用computed改动成本很高. 望尤大能给一个好的解决方案, 谢谢！

Bug:

Chinese input method cause v-model data is not updated.

Code：http://jsbin.com/robetuzuxo/edit?html,js,output
demo: http://output.jsbin.com/robetuzuxo

When you use the mobile browser to open the demo, click the input  field input box, switch to the Chinese input method, casually enter, and then click the submit button (do not click Finish or done) and found that the value of v-model is not updated, but found by native method Input value, found that the value is updated, how to deal with this situation? At present our solution is to re-package an input component out, but the previous on-line all the business now this situation, a direct result of the business is not available. Of course, I can use the computed setter getter to solve it, but because of the large number of forms in the business data, solve it with the use of high cost changes. so hope to give a good solution. Thanks.

**Comment by HerringtonDarkholme** [comment] 2017-03-13 07:18
Possible duplicate of https://github.com/vuejs/vue/issues/5020

**Comment by posva** [comment] 2017-03-13 13:25
@HerringtonDarkholme but this one is using an outdated Vue 2 version
@Jerret321 Can you please update your version and check if the error persists? You can use https://unpkg.com/vue

**Comment by Jerret321** [comment] 2017-03-13 13:31
@posva  we know the reason, some users may not done the Chinese input methods (IME) and we change the `compositionend` to `compositionupdate`. That's ok. But why `vuejs`  use `compositionend` API.

**Closed** 2017-03-13 15:00 UTC

**Comment by Jerret321** [comment] 2017-03-14 01:09
@yyx990803  感谢你的回答，在我们的需求里，用户使用中文输入法输入文字，直接点击submit在safari 或 iOS webview里面显示是空的， 这个逻辑不合理，那怕很丑的未完成的拼音，用户在`知晓`的情况会 `修改`, 而 `空` 哪怕给出用户提醒，用户也无从理解。

**Comment by yyx990803** [comment] 2017-03-14 02:15
你可以在提交的逻辑里检查空值，这样能给出更有针对性的提示。

**Comment by Justineo** [comment] 2017-03-29 03:51
@yyx990803 Actually sometimes it's helpful to get English letters during the composition process. eg. Baidu instantly pop out search suggestions even when users are in the middle of composition by matching those letters to pinyin.

**Comment by zmmbreeze** [comment] 2017-05-15 07:25
@yyx990803 Also met this problem. In my case, I want to create a fallback for `placeholder` property. We use `v-model` to get the value of input. If input has no value, `placeholder`  will be visible. Because of this problem, it's inconsistent with browsers' default behavior.

browsers' default behavior:
![2017-05-15 2 55 21](https://cloud.githubusercontent.com/assets/249872/26046215/6b1b7674-3980-11e7-8525-3775a3b335e4.png)

vue version:
![2017-05-15 2 55 05](https://cloud.githubusercontent.com/assets/249872/26046228/7c7d3204-3980-11e7-9249-46e66d626afa.png)

DEMO：https://jsbin.com/lisawij/1/edit?html,css,js,output

**Comment by HerringtonDarkholme** [comment] 2017-05-15 07:57
My personal suggestion is to register `compositionstart` and `compositionend` manually.

https://jsbin.com/kiwalabaqa/1/edit?html,css,js,output

From Vue's issue tracking, it seems different IMEs and different application logics will require conflicting strategies. Leaving programmers to manually registering listeners might still be the expedient for now.

**Comment by JounQin** [comment] 2018-01-03 03:36
Or add a new modifier on `v-model`?
