### ISSUE TITLE
Inconsistent behaviour with <progress> in indeterminate state

### ISSUE THREAD

**Issue by Llbe** [vuejs/vue#10157] opened 2019-06-14 13:18 UTC
### Version
2.6.10

### Reproduction link
[https://codepen.io/anon/pen/pXjBQq](https://codepen.io/anon/pen/pXjBQq)

### Steps to reproduce
1. Trigger the mousemove event in the result iframe of Codepen. The text "false" is changed to "true"

2. Compare the two `<progress>` elements. One is indeterminate and the other is not

### What is expected?
Both `<progress>` elements should be in an indeterminate state, i.e. not having a value attribute set.

### What is actually happening?
There are two `<progress>` elements here.

1. The first has `:value="progress"` and progress === undefined (verified by the text "true")

2. The second has `:value="undefined"`

Even if both these effectively are identical (set `value` to undefined), they are rendered differently. The first is not indeterminate and the second is.

---
Note that this does not happen if the progress variable is set initially to undefined. It must be changed e.g. via the event callback.

This worked as expected in 2.4.2 but not in 2.4.3 and later.

**Comment by Llbe** [comment] 2019-06-14 13:19
A variation of this issue (I believe it's the same): https://github.com/vuejs/vue/issues/10155

**Comment by posva** [comment] 2019-06-14 18:09
Duplicate of https://github.com/vuejs/vue/issues/7552

**Closed by posva** 2019-06-14 18:09 UTC
