### ISSUE TITLE
'v-for' and 'v-if' bug

### ISSUE THREAD

**Issue by chenzhiguo** [vuejs/vue#2624] opened 2016-04-05 10:07 UTC
### Vue.js version
1.0.20

`<div class="tab-wrap" v-if="object.aList.length > 0" v-for="object in objects">`
This work on Firefox, but not work on Chrome.

`<div class="tab-wrap" v-for="object in objects" v-if="object.aList.length > 0">`
This work on Chrome, but not work on Firefox.

What's up?

升级升出了Bug？！

**Comment by phanan** [comment] 2016-04-05 10:10
Duplicate of #2592. Please see the discussion/solution there.

**Closed by phanan** 2016-04-05 10:10 UTC

**Comment by chenzhiguo** [comment] 2016-04-05 10:16
Can you give me the correct use of example?

**Comment by phanan** [comment] 2016-04-05 10:28
Well see this: https://github.com/vuejs/vue/issues/2592#issuecomment-204819916.
