### ISSUE TITLE
High memory consumption that does not release

### ISSUE THREAD

**Issue by marceloromaomultilaser** [vuejs/vue#7111] opened 2017-11-22 19:35 UTC
### Version
2.5.8

### Reproduction link
[https://jsfiddle.net/4b1t0o8y/](https://jsfiddle.net/4b1t0o8y/)

### Steps to reproduce
Switch between home and foo routes.
Open the Windows task manager and see the memory consumption of the crome tab increase without ever decreasing.

### What is expected?
Allocate the data "items" in the memory and when leaving the route release the memory, or when you return, use the same allocation of ram memory.

### What is actually happening?
Memory consumption only increases.

---
I am developing an application using Electron. And in my application the variable "Items" is populated with 2,500 records every time it opens the route (in jsfiddle exemple it was only 10 ). at this moment 200mb increases the memory, I imagine it is due to the Vue bind. And when leaving the route the memory is not released. When I return to the same route, it increases even more 200mb of memory.

Please help me.

ps.:When I do not set the variable within DATA() (declare "this.item" directly in the created() ) this does not occur, however I need the variable to be reactive.

**Comment by LinusBorg** [comment] 2017-11-22 19:44
Can't reproduce this. memory consumption of the fiddle tab is constant around 30MB for me. And looking at the memory allocation in chrome devtools over time doesn't show anything significant for me, either.

Memory consumption in "windows task manager" ican have far too many influencing factors for this to be a reliable measurement for a memory leak anyway. It should be noticable in devtools, at least.

Can you share any more details?

**Comment by yyx990803** [comment] 2017-11-22 20:01
It's possible that you are using the instance or data in a certain way (e.g. sending them to the electron main process) that makes it unable to be garbage collected.

**Comment by marceloromaomultilaser** [comment] 2017-11-22 20:28
Hi, thanks for quicky reply!

I usually use the devtools, I just mentioned the "tasks manager" for being faster and its possible to see the consumption in "real time" (I do not know if it is possible in the devtools without having to press to collect).

So, here whats happing when I switch routes, the "VueComponent" only increase:

![capturar](https://user-images.githubusercontent.com/26793558/33148284-64d42252-cfb2-11e7-99b6-91c72dd1a5f6.PNG)
![capturar1](https://user-images.githubusercontent.com/26793558/33148285-64f4e3d4-cfb2-11e7-8781-b86f949b0e64.PNG)
![capturar3](https://user-images.githubusercontent.com/26793558/33148286-6538e94e-cfb2-11e7-9af6-1635d535bc01.PNG)

Sorry, i cant share my project cause its a private GitHub, but here the file that route component. if I comment the line 789 (the line thatset 2.500 line to variable) the memory do not increase so much.

[CatalogOrderPage.zip](https://github.com/vuejs/vue/files/1497391/CatalogOrderPage.zip)

Im sure that im not sendind variable to Main process.

**Comment by LinusBorg** [comment] 2017-11-22 20:55
Well you are using a WebWorker - eacht ime you send and receive data from there, it gets "copied", essentially. Depending on how your worker is set up, it might not release the memory.

We can't debug this like this, this is a *way* to complicated setup.

Personal sidenote: big project, true - but why keep all this logic in one component file? Isn't that a nightmare to navigate?

**Comment by marceloromaomultilaser** [comment] 2017-11-22 21:05
Yes... but like I said, if i not set the variable, the problem does not occur, so i think the problem is not with webworker.

And about the logic in one component: thats file its only 10% of project, I distribute the much as could. But that file controls all shopping cart that have a lot of intelligence and complications.

But OK... thanks for trying. I will see what I can do. Example: Not declare at data() and try update manually the computed params.  (that way the memory not increase, thats the point i think the problem is with vue reactive data)

**Comment by LinusBorg** [comment] 2017-11-22 21:10
If there was a big memory leak by simply making data reactive, we would know already. That's like the most basic functionality in Vue that *everyone* uses and we would have a couple dozen issues about it in simpler scenarios.

So it can't be *just* that, there must at least be a combination with some other thing in your setup.

**Comment by marceloromaomultilaser** [comment] 2017-11-22 21:19
Yes, I did not mean that it is a problem of the Vue. Surely I'm doing something wrong, I just wanted a way to find out. =/

**Comment by LinusBorg** [comment] 2017-11-22 21:23
I hope you can find out what it is. We won't be able to help you here unless you can slim this down drastically.

So I'm sorry but I'll close this issue. Good luck!

**Closed by LinusBorg** 2017-11-22 21:23 UTC
Labels: need repro

**Comment by marceloromaomultilaser** [comment] 2017-11-26 14:45
Thanks guys... I got it resolved, it really was WebWorker. I made a more compact page with only some elements and I tested to see when the memory was trapped. =)
Thank you for the excellent work!
