### ISSUE TITLE
"open" seems to be a reserved prop name?

### ISSUE THREAD

**Issue by roed** [vuejs/vue#10381] opened 2019-08-12 13:27 UTC
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/qagby1e4/](https://jsfiddle.net/qagby1e4/)

### Steps to reproduce
Somehow if I use the attribute "open" on a html tag, vue fills the attribute with the value "open". See the attached jfiddle, and inspect the span containing the attribute. If I put the tag outside the vue app, everything is fine. Also, it doesn't matter what the content of the attribute is.

### What is expected?
Vue doesn't mutate the attribute "open" on html tags inside the vue app.

### What is actually happening?
Vue mutates the "open" attribute with the value "open".

---
It doesn't seem to be a reserved keyword, although this file https://github.com/vuejs/vue/blob/dev/src/platforms/web/util/attrs.js does specify it as a boolean attribute. In our case, a mathjax html structure, the open attribute can contain string values.

**Comment by roed** [comment] 2019-08-12 13:30
Seems someone else is having the same issue, a pr is already opened for this: https://github.com/vuejs/vue/pull/10088

**Comment by posva** [comment] 2019-08-12 17:56
Duplicate of https://github.com/vuejs/vue/issues/10087

**Closed by posva** 2019-08-12 17:56 UTC

**Comment by Justineo** [comment] 2019-08-13 01:34
Vue has been treating all attributes as global attributes, which is technically kind of over-simplified. `open` is a boolean attribute for native `<dialog>` elements. But changing the current behavior may introduce break changes which we won't accept ATM.

**Comment by roed** [comment] 2019-08-13 07:40
Not if it is in a v-pre component. In my opinion Vue should not mutate attributes of 'normal' html tags.

**Comment by posva** [comment] 2019-08-13 07:50
Unfortunately we need to mutate them sometimes so it works across browsers. It shouldn't happen with v-pre but that's different and it's already tracked at #10087
