### ISSUE TITLE
Render errors should return contextual information

### ISSUE THREAD

**Issue by victornpb** [vuejs/vue#9333] opened 2019-01-17 13:38 UTC
### What problem does this feature solve?
If you have a complex template with many "interpolations" and you get an exception during render you only get the exception error message, no contextual information what so ever besides inside which component it happened.

```
[Vue warn]: Error in render: "TypeError: Cannot read property 'length' of undefined"

found in

---> <Unification> at src/pages/Hello/Hello.vue
       <VApp>
         <App> at src/App.vue
           <Root>
```

When I get this debugging, turns into basically guess work, I have to use CMD-F to find every place it mentions ".length" and start to like isolate parts of the template, it is very frustrating when the template is hundreds of lines.

![screen shot 2019-01-17 at 11 29 42 am](https://user-images.githubusercontent.com/3372598/51322126-bbf86b80-1a4b-11e9-9c5e-3055111605b6.png)

### What does the proposed API look like?
At least show the actual interpolation/directive that caused it, maybe with part of the template.
```
[Vue warn]: Error in render: "TypeError: Cannot read property 'length' of undefined"

found in

---> <Hello> at src/pages/Hello/Hello.vue:666:69
       <VApp>
         <App> at src/App.vue
           <Root>
               (...)
              <span class="caption">{{currentIndex 1}} / {{items.result.length}}</span>
                                                           ^
```

or at least the expression string `{{items.result.length}}`

line number would be great too.

**Comment by yyx990803** [comment] 2019-01-17 14:19
The root cause is because we currently do not produce source maps for template compilation. This is something we plan to fix in 3.0. (Closing for now since it's already in the roadmap)

Btw, if you have a several hundred lines template, you really should consider refactoring it into smaller components.

**Closed by yyx990803** 2019-01-17 14:19 UTC
