### ISSUE TITLE
Feature request: Expose a list of named slots passed to a component

### ISSUE THREAD

**Issue by dcgauld** [vuejs/vue#2594] opened 2016-03-30 16:25 UTC
The `<slot>` functionality is really useful, however I wonder if having a `vm.$slots` instance property could be useful. Much like [this thread](http://forum.vuejs.org/topic/927/using-v-show-if-with-named-slots), I'd like to show/hide parts of a component depending on whether a particular named slot was passed through. Although the thread was answered, I think having an instance property could make things much cleaner.

I don't really know much about Vue's internals, but it looks like a list is already compiled as `vm._slotContents` [here](https://github.com/vuejs/vue/blob/1af06013c69e77fa9f6545243aa282bcd8453771/src/compiler/resolve-slots.js#L20). Perhaps this was purposefully not exposed as a public API, but being able to perform actions based on whether certain slots were provided seems quite useful to me.

I imagine it'd be similar to `vm.$els`, where each key is the slot's name and each value is its element.

Let me know what you think. Thanks!

**Comment by yyx990803** [comment] 2016-03-30 16:28
Duplicate of #1726

**Closed by yyx990803** 2016-03-30 16:28 UTC

**Comment by dcgauld** [comment] 2016-03-30 16:29
My bad! Thanks.
