### ISSUE TITLE
v-model doesn't work with `is` attribute

### ISSUE THREAD

**Issue by Llbe** [vuejs/vue#7607] opened 2018-02-06 04:38 UTC
### Version
2.5.13

### Reproduction link
[https://jsfiddle.net/6vps8vej/](https://jsfiddle.net/6vps8vej/)

### Steps to reproduce
1. Select one of the <option>

### What is expected?
The {{ selected }} text should appear.

### What is actually happening?
The `selected` value does not change.

---
 - The code works if the `<div is="select">` is changed to a native `<select>`

 - Manually binding with @change works

**Comment by jkzing** [comment] 2018-02-06 11:38
Hi, thanks for reporting this.

However, elements with `is` will be teated as component, and vue compiler will generate different code for component and native element. It's kind of `wontfix` issue I guess, please use `select` directly instead.😃

**Comment by posva** [comment] 2018-02-06 11:57
Duplicate of #7393

**Closed by posva** 2018-02-06 11:57 UTC
