### ISSUE TITLE
Vue.js parses <noscript> tag and whatever is inside it.

### ISSUE THREAD

**Issue by timbenniks** [vuejs/vue#9949] opened 2019-04-29 11:27 UTC
### Version
2.6.10

### Reproduction link
[https://codepen.io/timbenniks/pen/yPOLej](https://codepen.io/timbenniks/pen/yPOLej)

### Steps to reproduce
* Add a _noscript_ tag inside the DOM node that is given to the Vue constructor. 
* In that _noscript_ tag, add an image tag. 
* Open the network tab of the developer tools.
* Load the page.

### What is expected?
The expected result would be that Vue.js ignores whatever is found in the _noscript_ tag.

### What is actually happening?
That is actually happening: observe that Vue.js loads the image inside the _noscript_ tag. Hence, Vue.js parses the _noscript_ tag and whatever is found within it.

---
We found this issue as we are using Vue.js not in SPA mode but sprinkling it on top of existing HTML. When turning off the JS the page still renders HTML. The goal is to have lazy loading images and without JS we still want to see the images. Hence an image tag in a _noscript_ element.

This sounds like an edge case but in fact this is common usage for big e-commerce systems and cms' like Sitecore and Adobe AEM.

**Comment by posva** [comment] 2019-04-29 11:41
Duplicate of #9669

**Closed by posva** 2019-04-29 11:41 UTC
