### ISSUE TITLE
componentInstance is undefined with v-slot syntax on this.$slots[slots] VNodes

### ISSUE THREAD

**Issue by petr001** [vuejs/vue#10554] opened 2019-09-24 13:58 UTC
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/s/vue-template-7rsmp](https://codesandbox.io/s/vue-template-7rsmp)

### Steps to reproduce
componentInstance via this.$slots.foo[bar] which are filled with new v-slot syntax is undefined.

For example:
this.$slots.myslot[0].componentInstance // returns undefined

### What is expected?
Should return VueComponent instance

### What is actually happening?
undefined is returned

---
Old slot="xxx" syntax properly returns VueComponent instance in componentInstance property

**Comment by posva** [comment] 2019-09-24 14:13
With the new syntax, slots effectively become scoped slots and are rendered in the context of the child. This result is consistent with the old `slot-scope`: both yield undefined.
I'm unsure if this is just a consequence of when scoped slots are rendered but at the same time relying on `componentInstance` from the vnode of a slot on the mounted hook is quite weird. What are you using it for? Usually everything is passed to the user through that scoped slot

**Comment by KaelWD** [comment] 2019-09-26 05:28
Probably duplicate of #8350

**Comment by witcher-development** [comment] 2019-10-01 12:34
I have same issue with scopedSlots

**Closed** 2020-02-06 08:51 UTC
