### ISSUE TITLE
 [bug] VUE not recognizing <g> and <line> svg elements inside component html.

### ISSUE THREAD

**Issue by raymondma1** [vuejs/vue#2726] opened 2016-04-25 19:01 UTC
### Vue.js version
1.0.16

### Reproduction Link
http://jsfiddle.net/5sH6A/320/
### Steps to reproduce
JSfiddle above... inspect console and errors will show up. 
### What is Expected?
'g' and 'line' to be treated as svg elements after being dropped in between two svg tags via 'slot''
### What is actually happening?
'g' and 'line' not being recognized as svg elements and being treated as custom components unless warpped in another 'svg' tag on top of an already existing 'svg' tag.

error:  Unknown custom element: 'g'- did you register the component correctly? For recursive components, make sure to provide the "name" option.

**Comment by posva** [comment] 2016-04-25 19:03
Hi @raymondma1, Thanks for filling up the issue. I think you shared the wrong JSFiddle, can you take a look and fix it, please?

**Comment by raymondma1** [comment] 2016-04-25 19:11
updated 

http://jsfiddle.net/5sH6A/320/

sorry about that @posva

**Comment by posva** [comment] 2016-04-25 19:29
@raymondma1 no worries :smile:

**Comment by yyx990803** [comment] 2016-04-25 19:39
The current parsing mechanism cannot detect nested AND unwrapped svg elements. If you want to use them for slots you can wrap them in `<svg>`:

``` html
<a-chart>
  <svg>
    <g slot="content">
    </g>
  </svg>
</a-chart>
```

This is a wontfix in 1.x, but will no longer be an issue in future versions.

**Closed by yyx990803** 2016-04-25 19:39 UTC

**Comment by Romick2005** [comment] 2017-06-13 13:20
How I can deal with my custom "define-radial-gradient" component template for generating different svg gradients:
```
<template>
    <radialGradient cx="0.4" cy="0.3" r="0.5" :id="name">
        <stop offset="0" stop-opacity="1" :stop-color="color"/>
        <stop offset="1" stop-opacity="1" :stop-color="colorLuminance(color, -0.2)"/>
    </radialGradient>
</template>
```

And then in my main component:
```
<svg>
     <template v-for="color in colors">
         <define-radial-gradient :name="'fill-' + color" :color="color"></define-radial-gradient>
     </template>
</svg>
```
A .camel modifier will work only for attributes not for case sensitive tags.
The problem is that is is rendered by browser in lowercase like:
```
<radialgradient cx="0.4" cy="0.3" r="0.5" id="fill-#36A2EB"
    <stop offset="0" stop-opacity="1" stop-color="#36A2EB"></stop>
    <stop offset="1" stop-opacity="1" stop-color="#2b82bc"></stop
</radialgradient>
```
Do you have any suggestion how to avoid such error?
P.S. Also added ignore vue components list:
`Vue.config.ignoredElements = ['radialGradient', 'stop'];`

**Comment by DabeDotCom** [comment] 2018-02-03 05:49
FWIW, I was running into the exact same problem as @Romick2005 (in Vue 2.4.2...)

For anybody else coming from Google, the solution was to wrap the `<radialGradient>` in a [superfluous] `<svg>` element:
```
Vue.component('define-radial-gradient', {
  props: [ 'color' ],
  template: `
  <svg>   <!-- preserve tag case -->
    <radialGradient cx="0.5" cy="0.5" r="0.5" :id="'fill-' + color">
      <stop offset="0" stop-opacity="1" :stop-color="color" />
      <stop offset="1" stop-opacity="1" :stop-color="'#fff'" />
    </radialGradient>
  </svg>
  `,
})

Vue.component('main-component', {
  template: `
  <svg width="100" height="400" viewBox="0 0 100 400">
    <template v-for="(color, index) in ['#F00', '#FF0', '#0F0' ]">
      <define-radial-gradient :color="color" />
      <rect
        :style="{ fill: 'url(#fill-' + color + ')' }"
        :x="5" :y="5 + 100 * index"  :width="90" :height="90"
      />
    </template>
  </svg>
  `
})
```

**Comment by john-dev** [comment] 2023-11-06 11:16
> The current parsing mechanism cannot detect nested AND unwrapped svg elements. If you want to use them for slots you can wrap them in `<svg>`:
> 
> ```
> <a-chart>
>   <svg>
>     <g slot="content">
>     </g>
>   </svg>
> </a-chart>
> ```
> 
> This is a wontfix in 1.x, but will no longer be an issue in future versions.

Seems to still be an issue in vue3

> The current parsing mechanism cannot detect nested AND unwrapped svg elements. If you want to use them for slots you can wrap them in `<svg>`:
> 
> ```
> <a-chart>
>   <svg>
>     <g slot="content">
>     </g>
>   </svg>
> </a-chart>
> ```
> 
> This is a wontfix in 1.x, but will no longer be an issue in future versions.

This doesn't seem to have changed until today in vue3, correct?
Still had to use the additional <svg> workaround.
