### ISSUE TITLE
Maybe false alarm "Duplicate presense of slot found in the same render tree" warnings

### ISSUE THREAD

**Issue by Centaur** [vuejs/vue#3642] opened 2016-09-08 13:46 UTC
### Vue.js version
2.0.0-rc5

### Reproduction Link

https://jsfiddle.net/oldpig/zb4zLxkb/1/

### Steps to reproduce
Click any tab to switch

### What is Expected?
Tab switched, everything goes fine.

### What is actually happening?
There are warnings in console, multiple times each switch.

I am aware that this warning is introduced in rc.5. But I am not sure what goes wrong.

**Comment by posva** [comment] 2016-09-08 17:08
This looks like an error, indeed. The `_rendered` property is never reset. Let me take a look

**Comment by kobezzza** [comment] 2016-09-09 07:38
👍

**Comment by yyx990803** [comment] 2016-09-09 08:40
I realized this after release... It's been fixed in 100a2969aa5c64bd71758c79881cf4531e9907be

**Closed by yyx990803** 2016-09-09 08:40 UTC

**Comment by posva** [comment] 2016-09-09 11:35
Well that'd explain why I was having a bad time trying to reproduce it 😆

**Comment by skyrpex** [comment] 2016-09-12 14:14
Oh, I was going to create an issue for this, too. :ok_hand: I just created a [minimal jsfiddle](https://jsfiddle.net/skyrpex/95s0vjn4/3/) that reproduces the problem (just in case you want to add it to any test...).

That's great!
