### ISSUE TITLE
Unable to get UMD builds to work in browser

### ISSUE THREAD

**Issue by mikeerickson** [vuejs/vue#5004] opened 2017-02-24 19:40 UTC
Before I go down this major rabbit hole of describing my issue with UMD format in browser, does anybody have a working UMD solution (a small test project would be fabulous).

I have been fighting this issue for the last 6 hours and am at a complete loss as to what to do to make this work.

In short, using the standard UMD build (from vue-cli) it does NOT work in the browser when including it via `<script>` tags.

If more detailed information is required, please review this repo 

https://github.com/mikeerickson/cd-vue-component-starter

Console Error

![image](https://cloud.githubusercontent.com/assets/183153/23318125/04be37b0-fa86-11e6-82e8-ba044d70d75e.png)

**Comment by yyx990803** [comment] 2017-02-24 20:20
As much as I'd like to help you, I'm closing this since it seems to be more like a generic "how to use Webpack" question rather than issues with Vue itself.

Also the problem is probably in https://github.com/mikeerickson/cd-vue-component-starter/blob/master/dist/index.js

**Closed by yyx990803** 2017-02-24 20:20 UTC

**Comment by mikeerickson** [comment] 2017-02-24 20:32
@yyx990803 well that is unfortunate.  I have spent 6 hours working on this already. Been all over google and Gitter form with no positive results.

**Comment by LinusBorg** [comment] 2017-02-24 21:01
We have a pretty active forum on forum.vuejs.org, we can certainly help you there. Github issues are exclusively for bugs & Feature work.

**Comment by mikeerickson** [comment] 2017-02-24 21:31
@yyx990803 FWIW, the problem is not in the file you were thinking.   I have gotten it to build correctly using the vue-cli (vue build --prod --lib)   

Not sure where the problem is in my `webpack.prod.config.js` though...  

I will have a stab at the `forum.vuejs.org` as @LinusBorg suggested

**Comment by mikeerickson** [comment] 2017-02-24 21:32
@LinusBorg I was thinking it was a "bug" in my `webpack.prod.config.js` file (which I _thought_ was created by the vue-cli

```
$ vue init webpack umd-test
```

**Comment by mikeerickson** [comment] 2017-02-24 21:37
@LinusBorg OK, lets see how it goes.  I have opened issue on the forum...

https://forum.vuejs.org/t/fixing-a-webpack-build-issue-creating-a-umd-build-of-component/7058

**Comment by yyx990803** [comment] 2017-02-24 22:28
@mikeerickson please understand that issues are reserved for work that we deem "necessary" or "deserves discussion" - helping users with custom modified webpack configurations is **nice**, but absolutely not a responsibility. If I help every Vue user with their webpack issues I'd have 0 hours to work on Vue itself or even for my own personal life.

**Comment by mikeerickson** [comment] 2017-02-24 23:31
Evan

I totally get this and can surely appreciate that position.  We all go through things as OSS devs.   If this issue were covered in docs and/or forum or Gitter then I could easily go that route

The fact of the matter is, there is NO mention of properly configuring Vue components for use with browsers (those which don't use a build tool such as webpack or rollup)

This is the primary reason I opened the issue here in first place.  as I stated, I scoured google etc for some 6+ hours trying to find anything that would lead me down the correct path

At any rate, I appreciate your time and will continue to research this until I can figure it out.

**Comment by yyx990803** [comment] 2017-02-24 23:34
Have you tried `vue build Component.vue --prod --lib`?

**Comment by mikeerickson** [comment] 2017-02-24 23:54
@yyx990803 Yes, and that works (except it is throwing errors because I am using 

```
<style scoped lang="sass">
```

**Comment by mikeerickson** [comment] 2017-02-24 23:55
@yyx990803 If I remove the `lang=sass` flag, then the component works etc.

**Comment by mikeerickson** [comment] 2017-02-24 23:58
@yyx990803 Here is information on the `vue-cli` issue related to sass

https://github.com/vuejs/vue-cli/issues/374

I have been told this is my problem as well, so I have given up... I dont know HOW it could be my problem seeing as I am using the cli and its internal webpack.config, but thats what Linus has stated.  

So, I appreciate you and @LinusBorg trying to help.  At this point, I am just going to bail from Vue all together and return to using Angular (I can build UMD compatible directives without issue there and I cant afford to spend all this time trying to shoehorn Vue

Thats all I have for now :-)

**Comment by LinusBorg** [comment] 2017-02-25 00:09
I'm sorry but I will lock this now. TZhere's no use in dicussing 3 seperate problems across 3 different issues, which are not even bugs, as far as I can tell.

 Happy to help on the forum though :)
