### ISSUE TITLE
v2.0.0-alpha.8 `v-if` bug

### ISSUE THREAD

**Issue by douzi8** [vuejs/vue#3219] opened 2016-07-04 06:31 UTC
### Vue.js version
v2.0.0-alpha.8

### Reproduction Link

https://jsbin.com/dajovivoye/1/edit?html,js,output

### Steps to reproduce

1. new Vue
2. assign data

### What is actually happening?
A tag with `v-if` will also has style attribute

**Comment by yyx990803** [comment] 2016-07-04 17:51
Duplicate of #3176

**Closed by yyx990803** 2016-07-04 17:51 UTC
Labels: bug

**Comment by owlikesj** [comment] 2016-07-05 03:46
It's not the same as #3176 . The second div has v-if command, the third div has a style attribute, after value of isShow is changed, the second div will copy the inline style of the third div. and #3176 is about space in template.

**Comment by yyx990803** [comment] 2016-07-05 12:51
It's fixed by the same fix.
