### ISSUE TITLE
problem with functional component

### ISSUE THREAD

**Issue by qk4089** [vuejs/vue#4554] opened 2016-12-23 08:02 UTC
### Vue.js version
2.1.6

### Reproduction Link
https://jsfiddle.net/xzhwbb1o/2/

### What is Expected?
I want to get the component `item`  up  component `choice`, but when `functional ` , the parent is the `#app`, remove the `functional`  is `choice`, is the default of this? I have read the document [render](cn.vuejs.org/v2/guide/render-function.html#函数化组件), but did not find the relevant tips.

**Comment by LinusBorg** [comment] 2016-12-23 09:34
Coincidentally, I was trying to do pretty much the same a couple of minutes ago. Will look into wether access to the "slot.parent" (like `this.$parent` in normal components) can be done for functional components.

**Comment by posva** [comment] 2016-12-23 12:02
Duplicate of #4550 
You can look there for reasons but basically, this is by design and it's not a good idea to make your component depend on the parents. You'd be better off using the props down events up pattern

**Closed by posva** 2016-12-23 12:02 UTC
