### ISSUE TITLE
Promise rejection in watcher not captured by Vue.config.errorHandler

### ISSUE THREAD

**Issue by vvanpo** [vuejs/vue#11573] opened 2020-08-07 01:55 UTC
### Version
2.6.11

### Reproduction link
[https://github.com/vvanpo/minimal-repros/tree/master/vue2](https://github.com/vvanpo/minimal-repros/tree/master/vue2)

### Steps to reproduce
Finding the same problem as posted here: https://github.com/vuejs/vue/issues/11035

See the minimal repro:

```js
import Vue from 'vue/dist/vue.common.js'

test('errorHandler should capture promise rejections in watchers', () => {
  document.body.innerHTML = '<div id="#app"></div>'

  Vue.config.errorHandler = (err) => {
    console.log(err.toString())
  }

  new Vue({
    template: `<div />`,
    data: () => ({ foo: false, bar: false }),
    mounted() {
      this.foo = true
      this.bar = true
    },
    watch: {
      foo: async () => { throw new Error('foo') },
      bar: () => { throw new Error('bar') },
    },
  }).$mount(document.body.querySelector('#app'))
})
```

Results in the following:
```
(node:67048) UnhandledPromiseRejectionWarning: Error: foo
(node:67048) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:67048) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 PASS  ./test.js
  ✓ errorHandler should capture promise rejections in watchers (19 ms)

  console.log
    Error: bar

      at _vueCommon.default.config.errorHandler (test.js:7:13)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        1.806 s
Ran all test suites.
✨  Done in 2.71s.
```

So you can see that it correctly captured the `bar` watcher's error, but not the promise rejection in `foo`.

### What is expected?
Errors in async watchers can be caught by `Vue.config.errorHandler`.

### What is actually happening?
Promise rejections inside async watchers are not caught by the `errorHandler`.

I've tested it in Vue 3, and there `app.config.errorHandler` captures all promise rejections as expected.

**Comment by posva** [comment] 2020-08-07 06:47
Duplicate of https://github.com/vuejs/vue/issues/10009

**Closed by posva** 2020-08-07 06:47 UTC
