### ISSUE TITLE
DOM is shifted completely if the top and bottom elements alternate

### ISSUE THREAD

**Issue by fer22f** [vuejs/vue#9496] opened 2019-02-14 16:26 UTC
### Version
2.6.6

### Reproduction link
[https://jsfiddle.net/azg65dsv/3/](https://jsfiddle.net/azg65dsv/3/)

### Steps to reproduce
Click the "Push" button and you will see that the focus of the window is now on the top input. Wait a few seconds, and should now see that the focus has been lost from the input.

### What is expected?
The first input should still be focused.

### What is actually happening?
The entire DOM is shifted around, new elements are created for no reason and changed, while the input ends up unfocused.

---
My setup is pretty similar to the fiddle, I have a loading bar at the top and an information box at the bottom. When testing it, however, a lot of weird things happened:

* My custom directive didn't work properly because the underlying element was changed (this was actually my fault, I have now fixed it)
* If I selected the input before data came, it lost focus
* My custom button ripple animation got shifted around to a button at the bottom of the screen

After debugging a little bit, I found the issue. Vue thought that those divs were the same element when calling `sameVnode(oldEndVnode, newEndVnode)`. Adding a custom key into the second div works wonderfully, and no more DOM shifting, but I would like to be warned by the template compiler if something like this could happen (or maybe key all divs?).

### Workaround
Add a `key` to the first div that is not toggled.

**Comment by Justineo** [comment] 2019-02-14 17:15
This seems to share the same root cause with #9473. The focused input will lose focus after it's moved in the DOM tree. (As in #9473 it will make `<iframe>`s reload.)

**Comment by posva** [comment] 2019-02-15 08:35
Duplicate of #4362

**Closed by posva** 2019-02-15 08:35 UTC
