### ISSUE TITLE
Max stack trace error in Chrome with several tags or components

### ISSUE THREAD

**Issue by chumager** [vuejs/vue#11675] opened 2020-09-21 15:17 UTC
### Version
2.6.12

### Reproduction link
[https://jsbin.com/tusikubevu/edit?html,js,console,output](https://jsbin.com/tusikubevu/edit?html,js,console,output)

### Steps to reproduce
If you move between 100 and 125000 there is no problem, but if you choose 130000 there is a max stack trace error in chrome 85.0.4183.102 (stable), this is a VERY minimal reproduction, what really happens to me is with bootstrap-vue table with scopes and several chained components my app stop working and have to capture the error and reload the page, and my client is complaining a lot about it.

### What is expected?
Don't know if you can solve it or if it's a chrome problem, because in FF it doesn't happens

### What is actually happening?
I got this kind of error when using lots of components.

RangeError: Maximum call stack size exceeded
    at normalizeArrayChildren (vue.js:2393)
    at normalizeChildren (vue.js:2368)
    at _createElement (vue.js:3406)
    at createElement (vue.js:3360)
    at Proxy.vm._c (vue.js:3497)
    at Proxy.eval (eval at createFunction (vue.js:11649), <anonymous>:3:19)
    at Vue._render (vue.js:3551)
    at Vue.updateComponent (vue.js:4067)
    at Watcher.get (vue.js:4478)
    at Watcher.run (vue.js:4553)
logError @ vue.js:1897
globalHandleError @ vue.js:1888
handleError @ vue.js:1848
Vue._render @ vue.js:3553
updateComponent @ vue.js:4067
get @ vue.js:4478
run @ vue.js:4553
flushSchedulerQueue @ vue.js:4311
(anonymous) @ vue.js:1989
flushCallbacks @ vue.js:1915
Promise.then (async)
timerFunc @ vue.js:1942
nextTick @ vue.js:1999
queueWatcher @ vue.js:4403
update @ vue.js:4543
notify @ vue.js:745
reactiveSetter @ vue.js:1070
proxySetter @ vue.js:4630
change @ VM33:3
invokeWithErrorHandling @ vue.js:1863
invoker @ vue.js:2188
original._wrapper @ vue.js:7547
ListPicker._handleMouseUp

---
As I said before this happens on Chome, in FF there is no error, and I use 2.6.12, not 2.6.11, but can't choose it.

**Comment by posva** [comment] 2020-09-21 15:27
Duplicate of https://github.com/vuejs/vue/issues/11389

**Closed by posva** 2020-09-21 15:27 UTC
