### ISSUE TITLE
Keep-alive filter by slot's key.

### ISSUE THREAD

**Issue by ruojianll** [vuejs/vue#11901] opened 2021-02-05 12:07 UTC
### What problem does this feature solve?
Keep-alive filter by slot instance.

I need to use it to filter my route component in `router-view` by `:key="$route.fullPath"`

### What does the proposed API look like?
```
<keep-alive :include-keys="function(keyOfSlot:string) or regex or string">
  <component :key="myKey"/>
</keep-alive>
```

**Comment by posva** [comment] 2021-02-05 14:36
Duplicate of #8028

**Closed** 2021-02-05 14:36 UTC
