### ISSUE TITLE
Default slots using functional components still call functional's render() when something else is slotted.

### ISSUE THREAD

**Issue by StefanCardnell** [vuejs/vue#11811] opened 2020-12-07 19:20 UTC
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/happy-pascal-reiyx?fontsize=14&hidenavigation=1&theme=dark](https://codesandbox.io/s/happy-pascal-reiyx?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
1.  Please see linked minimal example.
2. Create a component A which uses a functional component B inside a default slot.
3. Use Component A, but slot in something else so the functional component B does not appear.

### What is expected?
The render() function of the functional component should not be called. As it does not appear, I shouldn't expect its render function to be called.

### What is actually happening?
The render() function is called, as seen by the console output which logs when the function is called.

---
Issues:
    I encountered this when I was creating a table with 10,000 cells and each \<\td\> was a functional component. However the table was able to slot in its own component over the \<\td\>. Doing so meant the slotted clotted was created along with 10,000 unnecessary renders() from the functional component. This added about ~1s load time.

Workarounds:
    Don't put the functional component inside the slot. Instead, the functional component should be used outside and have a v-if on it checking if the slot has not been used. It is the same end result, but render() is not called.

**Comment by posva** [comment] 2020-12-07 20:22
Duplicate of https://github.com/vuejs/vue/issues/10926

**Closed by posva** 2020-12-07 20:22 UTC
