### ISSUE TITLE
Patched elements keep inline styles from old vnodes

### ISSUE THREAD

**Issue by lgdexter** [vuejs/vue#4227] opened 2016-11-17 04:24 UTC
### Vue.js version
2.0.6+

### Reproduction Link
https://jsfiddle.net/gw8g8cos/

![vue-glitch](https://cloud.githubusercontent.com/assets/19538283/20378887/e073b9a6-ac4d-11e6-8254-c1fb079ff122.gif)

### Steps to reproduce
```
$ vue init webpack-simple .
$ npm install vue@2.0.7 vue-template-compiler@2.0.7
```

```vue
<template>
<div>
    <section style="text-align: center" v-if="loading">
        Should be centered.
    </section>
    <section style="margin-top: 6rem;" v-if="!loading">
        Should not be centered.
    </section>
</div>
</template>

<script>
export default {
    name: 'app',
    data () {
        return {
            loading: true
        }
    },
    mounted: function() {
        setTimeout(() => {
            this.loading = false;
        }, 2000);
    }
}
</script>
```

### What is Expected?
Patched elements should not keep inline styles from old vnodes.

### What is actually happening?
During the update operation, patched elements will retain styles from vnodes that will no longer exist in the DOM.

Temporarily solution for end-users: changing inline styles to classes, choosing different tag names or adding a `key` directive will fix the issue. Thanks to @LinusBorg for the latter.

It looks like this PR has introduced this regression https://github.com/vuejs/vue/pull/4138. I've opened a pull request with a failing test that confirms this issue.

**Comment by lgdexter** [comment] 2016-11-17 04:35
Edit: looks like this PR may have introduced a regression https://github.com/vuejs/vue/issues/3997. I'll try to reproduce this in JSFiddle but I can't seem to pinpoint what is causing the problem. It's breaking in random parts of my app.

**Comment by lgdexter** [comment] 2016-11-17 06:38
Figured it out. Here's a quick way to recreate it.

```
$ vue init webpack-simple .
```

```
<template>
<div>
    <section style="text-align: center" v-if="loading">
        Should be centered.
    </section>
    <section style="margin-top: 6rem;" v-if="!loading">
        Should not be centered.
    </section>
</div>
</template>

<script>
export default {
  name: 'app',
  data () {
    return {
      loading: true
    }
  },
  mounted: function() {
    setTimeout(() => {
        this.loading = false;
    }, 2000);
  }
}
</script>
```

I will look for a fix now. Basically, when two elements next to each other alternate state, the Vue compiler thinks it's still the same element.

**Comment by HerringtonDarkholme** [comment] 2016-11-17 09:26
This might be related to https://github.com/vuejs/vue/issues/4205. But I'm not sure. Can you try adding a key property to section?

**Comment by lgdexter** [comment] 2016-11-17 09:34
@HerringtonDarkholme it's definitely related. Still a little annoying to have to deal with this... Adding the `key` tag worked... Would be nice to mention something in the docs about diffing.

**Comment by LinusBorg** [comment] 2016-11-17 09:42
@Igdexter

> Would be nice to mention something in the docs about diffing.

We're on it vuejs/vuejs.org#587

**Comment by lgdexter** [comment] 2016-11-17 09:47
@LinusBorg cool, thanks for the quick response. had quite a shock in production today with 2.0.7

**Comment by LinusBorg** [comment] 2016-11-17 09:52
> had quite a shock in my staging environment today with 2.0.7

This is not an inteded breaking change, mind you. It's generally expected behaviour in many situations, but as already mentioned, documentation about this is still lacking. 

I assume that this worked "accidentally" before, and recent fixes of bugs which, amongst other things, related to handling of style and class bindings, might have changed that.

**Comment by HerringtonDarkholme** [comment] 2016-11-17 09:54
@LinusBorg I wonder whether this is a correct behavior.

The example above can be diffed solely by v-dom. The style attributes should be considered as a v-dom construct.

By comparison, consider this example. https://jsfiddle.net/gw8g8cos/4/
The inner text and class has been updated, the class is not merged, but style is merged.

Also, this issue is different from #4205 , since lifecycle is not managed by virtual dom.
And it is also different from https://github.com/vuejs/vue/issues/4216, since inline-template, speaking in implementation, has a different slot than `render` in vnode representation.

cc @defcc

**Comment by lgdexter** [comment] 2016-11-17 09:55
@LinusBorg I'm guessing the "improvement" to inline styles as per #4138 is what made this issue apparent now. I'm just wondering if this is the correct behavior. Here it's comparing the old node with the new node and then applying style changes by merging them. While it's reusing the same node, I don't think it should technically reuse the style from both nodes.

**Comment by LinusBorg** [comment] 2016-11-17 09:55
Hm you might be right.

**Comment by defcc** [comment] 2016-11-17 12:36
Something wrong with static style and style binding merge. It should be a bug. I am looking into it and trying to fix it.

**Comment by defcc** [comment] 2016-11-17 12:51
[https://github.com/vuejs/vue/blob/dev/src/platforms/web/runtime/modules/style.js#L48](https://github.com/vuejs/vue/blob/dev/src/platforms/web/runtime/modules/style.js#L48)
```js
const style = normalizeStyleBinding(vnode.data.style) || {}
vnode.data.style = style.__ob__ ? extend({}, style) : style
const newStyle = getStyle(vnode, true)
```

The style now only holds the style binding, which will be removed in the next render. The static style and  style binding should be removed both when reusing the same node.

**Comment by defcc** [comment] 2016-11-17 14:05
I'll make a PR to fix it

**Closed** 2016-11-17 16:25 UTC
Labels: 2.0, bug, discussion
