### ISSUE TITLE
Weird binding behavior when slots are involved

### ISSUE THREAD

**Issue by alexdeefuse** [vuejs/vue#6468] opened 2017-08-28 20:08 UTC
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/50wL7mdz/56841/](https://jsfiddle.net/50wL7mdz/56841/)

### Steps to reproduce
Child component attribute changes aren't observed if the component in question is distributed using slots and the change is made from the parent component (the one used to distributed the child component). The change is observed only if another entity on that page uses the exact same binding (Please see the commented out portion in "test-page" marked as "TODO: uncomment to observe").

### What is expected?
In the attached fiddle, clicking the swap button should change the background color for the label from red to blue.

Un-commenting the portion marked as "TODO: uncomment to observe" corrects the behavior.

### What is actually happening?
If no other element on the page doesn't use the exact binding, then the change isn't observed.

---
While implementing a default layout library that gets used over an application, I came across this bug where I was trying to alter a style binding of a component when a button is clicked. This component is distributed using layout slots.

**Comment by jsnanigans** [comment] 2017-08-29 11:40
I believe the problem is that vue cannot detect a change in `labelStyle` when only its children properties are updated, and if its not explicitly used in the template.

A solution would be to recreate the whole `labelStyle` object when changing one style to force a update, this can be easily done with the es2015 spread operator.

So instead of setting the new background color like this: 
```javascript
this.labelStyle.background = newColor
```
You should do it like this:
```javascript
this.labelStyle = {
  ...this.labelStyle,
  background: newColor 
}
```
this will keep everything the same but overwrite the background propery.
here is a working example: https://jsfiddle.net/50wL7mdz/57072/

**Comment by LinusBorg** [comment] 2017-08-29 11:42
@jsnanigans I think you analysis is right, and your workaround would probably work, but it shouldn't be necessary - Vue should pick this up and react to it.

**Comment by alexdeefuse** [comment] 2017-08-29 14:45
@LinusBorg do you have any suggestions on how to fix this? I am interested in the cleanest way to get it to work.

Thanks,
Alex

**Comment by javoski** [comment] 2017-08-30 02:10
Have been fixed with [https://github.com/vuejs/vue/commit/0529040c17b8632032a43d142aac88386f6b4a1f](https://github.com/vuejs/vue/commit/0529040c17b8632032a43d142aac88386f6b4a1f).

**Closed by javoski** 2017-08-30 02:10 UTC
