### ISSUE TITLE
computed properties are re-evaluating more often than expected

### ISSUE THREAD

**Issue by indirectlylit** [vuejs/vue#8540] opened 2018-07-22 02:46 UTC
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/eywraw8t/193744/](https://jsfiddle.net/eywraw8t/193744/)

### Steps to reproduce
* Create some data A and computed props B and C
* Let C depend on B, and B depend on A. Set it up so the value of B should change less often than A
* Then modify A

### What is expected?
The value of C should only be re-computed when the value of B changes, independent of how often A is changing.

### What is actually happening?
The value of C is re-computed whenever A changes. This results in many extra re-computations.

---

[The docs say](https://vuejs.org/v2/guide/computed.html#Computed-Caching-vs-Methods):

> A computed property will only re-evaluate when some of its dependencies have changed.

In this case, I thought there was a bug in my code because certain threshold-based computed properties were triggering re-computes far more often than expected, and some of these re-computes were fairly expensive.

Perhaps is expected behavior? However it was surprising to me, and negates a lot of the potential for cache-based optimization when leveraging computed props.

Compare to this implementation that uses watchers and extra data, but works as expected:

[https://jsfiddle.net/eywraw8t/193746/](https://jsfiddle.net/eywraw8t/193746/)

Here, C is only recomputed when B changes - not whenever A changes.

**Comment by drdevelop** [comment] 2018-07-22 06:00
数组通过索引去改变不会触发watch的回调

**Comment by sqal** [comment] 2018-07-22 10:22
seems to be fixed in 2.5.17-beta.0

**Comment by indirectlylit** [comment] 2018-10-06 15:16
> seems to be fixed in 2.5.17-beta.0

note - reverted and not released due to regressions

**Comment by zfeher** [comment] 2018-10-15 19:32
We also ran into this issue today. 

When can we expect the fix to be released for this? 

We can't use the v2.5.17-beta.0 because some things broke when we tried it so we reverted back to 2.5.16. This problem can cause some headaches, would be nice to have the fix released.

**Comment by Justineo** [comment] 2018-11-05 04:03
Duplicate of #7767

**Closed by Justineo** 2018-11-05 04:03 UTC
