### ISSUE TITLE
Lags when updating the class

### ISSUE THREAD

**Issue by danyadev** [vuejs/vue#9375] opened 2019-01-26 20:39 UTC
### Version
2.6.0-beta.2

### Reproduction link
[https://codepen.io/danyadev/pen/wNGaQo](https://codepen.io/danyadev/pen/wNGaQo)

### Steps to reproduce
1) Scroll to end (hide button)
2) Scroll up (show button)

### What is expected?
No lags (everything is fine in versions below 2.6-beta.1)

### What is actually happening?
Lags while scrolling (if they are not, then increase the number of elements in v-for)

**Comment by egormanga** [comment] 2019-01-27 15:53
Did you mean that `expected` is `actually happening` and vice-versa?

**Comment by yyx990803** [comment] 2019-01-27 20:03
Not seeing any lag with 5000 items... seems to work fine on a phone too. Closing as cannot reproduce.

**Closed by yyx990803** 2019-01-27 20:03 UTC

**Comment by yyx990803** [comment] 2019-01-27 20:31
To clarify, it  2.6.0-beta.1 working ok for you?

**Comment by danyadev** [comment] 2019-01-27 20:34
No

**Comment by egormanga** [comment] 2019-01-27 22:19
Also no lags for me on 5000 elements. Lagging on ~50000 of them and more.

**Comment by danyadev** [comment] 2019-01-29 17:13
Hmm, I checked it on 2.4.0 and 2.4.4 and didn't notice any lags there.

**Comment by danyadev** [comment] 2019-01-30 12:18
I also noticed that on versions 2.5.22 and below, due to any action, some elements not dependent on these actions are no longer updated in the DOM.

**Comment by danyadev** [comment] 2019-01-30 13:13
I found the problem - this is my custom directive.
I will go create a new report with this problem.

**Comment by danyadev** [comment] 2019-01-31 15:41
I found the main reason for these lags (the screenshot shows this piece of code, which I found in the commit v2.6.0-beta.1 commit). Is it possible to do something here?

![image](https://user-images.githubusercontent.com/35631027/52065557-d3753f80-2587-11e9-9141-afd7007897f2.png)

**Comment by yyx990803** [comment] 2019-01-31 17:25
Have you tried beta.3? It calls `performance.now()` only once per update.

**Comment by danyadev** [comment] 2019-01-31 18:07
Um, okay. Still, lags are really due to microtasks. So, I have to not use vue 2.6.0 or higher because of performance and abandon my plans for Vue.observable ...

**Comment by yyx990803** [comment] 2019-01-31 18:39
You should probably use a [virtual scroller](https://github.com/Akryum/vue-virtual-scroller).

**Comment by danyadev** [comment] 2019-02-04 17:37
Hmmm, either you did something, or somehow I fixed it, but there is no more lag on the release build.
