### ISSUE TITLE
Inconsistent drag event behaviour (in jsfiddle vs. local environment)

### ISSUE THREAD

**Issue by szmarci** [vuejs/vue#4479] opened 2016-12-14 18:12 UTC
### Vue.js version
2.1.6

### Reproduction Link
http://jsfiddle.net/bvjfa9xk/8/

### What is Expected? / What is actually happening?

Dragging list item from one bucket to another paints outer item red on a `dragenter` event.
This is what the fiddle does as expected. I start to drag an item from the 3rd column to the 2nd, upon dragstart the 3rd gets the class immediately. The second gets it only when the mouse hovers over it. As I said this is what I expect to happen.
![jsfiddle](https://cloud.githubusercontent.com/assets/1974290/21194273/a00e52fc-c22f-11e6-8be5-0fb1650aa4b4.PNG)

But if I copy the exact same code from the fiddle and paste it in a local folder /index.html, main.js, also link to vue 2.1.6/ This happens:
![local](https://cloud.githubusercontent.com/assets/1974290/21194356/f1d84354-c22f-11e6-9dcc-14e7a874189d.PNG)

Upon dragstart in the 3rd column, the 2nd one immediately gets the class as well. 
Same code, same versions, same browser /latest Chrome/

```
  methods: {
    dragenter: function (ev) {
      debugger
      this.$el.classList.add('drop-target')
      console.log(this)
    }
  }
```

If I place a debugger statement before the class addition, by the time it stops there I see that the column where I started to drag already got the class and `$el` now referring to the second column.

Everything is the same, I don't know why it behaves different (I'm trying to develop a drag-and-drop application and I just bumped to this issue). First I thought it was webpack/node-module related, so I trashed all of these and started on a single html/js file.

**Comment by yyx990803** [comment] 2016-12-14 18:30
Hmm, cannot reproduce this myself, the behavior seems to be exactly the same when I copy your jsfiddle verbatim into a local file. Maybe it has to do with some of your Chrome extensions?

**Comment by szmarci** [comment] 2016-12-15 09:40
Hi @yyx990803 Thanks for looking at it. I deleted all Chrome extensions, emptied cache, browsehistory, etc... It is still wrong in Chrome, but I've found several differences:

If I drag it somewhere in the 2nd half of the cell, it works as it should (only highlights second column as mouse enters it):
![chrome-bug-1](https://cloud.githubusercontent.com/assets/1974290/21218539/57bfdbc4-c2b1-11e6-86da-c84153f3b317.gif)

But if I drag it closed to the left edge, it fails (notice: I even drag it to the right):
![chrome-bug-2](https://cloud.githubusercontent.com/assets/1974290/21218589/89488682-c2b1-11e6-8e61-7dfbb76561d5.gif)

More strange is that it is now fails in the fiddle as well:
![fiddle-1](https://cloud.githubusercontent.com/assets/1974290/21218784/32e1a728-c2b2-11e6-89ea-c930c0ab4cea.gif)

And this is the weirdest (if I drag it closer to the right, it does something completely different):
![fiddle-2](https://cloud.githubusercontent.com/assets/1974290/21218797/416a7176-c2b2-11e6-8b21-edd68d37790d.gif)

Same Chrome version: 55.0.2883.87 m, same code.
On top of that in Edge it is perfect, no matter where I drag:
![ie-1](https://cloud.githubusercontent.com/assets/1974290/21218835/8dbed3aa-c2b2-11e6-9670-240ca15bf863.gif)

I checked on my co-workers system as well. One works fine on Chrome with the fiddle, the other ones fails as well.

**Comment by KingMario** [comment] 2016-12-15 12:10
Chrome Version 54.0.2840.98 (64-bit), not reproducible in jsfiddle
![screenflow](https://cloud.githubusercontent.com/assets/3956876/21223483/590aacec-c302-11e6-8644-663c68f29a07.gif)

**Comment by szmarci** [comment] 2016-12-15 13:18
@KingMario I checked the divs, they seem normal. Besides we are looking at the same fiddle ( http://jsfiddle.net/bvjfa9xk/8/ ) I don't see how they can be layed out differently in the same browser.

**Comment by yyx990803** [comment] 2016-12-15 14:04
Still cannot reproduce. This may have something to do with Windows Chrome?

**Comment by fnlctrl** [comment] 2016-12-15 14:40
Seems to work fine on Windows x64 1607(14393.447), Chrome 55.0.2883.87
![123123](https://cloud.githubusercontent.com/assets/5557143/21228081/6f24cad4-c317-11e6-8515-ada6fd7931cd.gif)

**Comment by yyx990803** [comment] 2016-12-15 14:57
Hmm, sorry @szmarci , but given the test cases, the issue seems unlikely to be related to Vue. Maybe you can try testing it on a different machine...

Anyway, closing for now, but feel free to follow up with more information.

**Closed by yyx990803** 2016-12-15 14:57 UTC
Labels: need repro

**Comment by szmarci** [comment] 2016-12-15 15:29
To make things even more strange:
![fullscreen](https://cloud.githubusercontent.com/assets/1974290/21229912/7586b916-c2e3-11e6-8456-26de9f2d05aa.gif)

If I am in full screen and grab the first item in the list it works. Then I downsize the window and grab the same element it fails.

Also I have tested it on several machines of my coworkers:

Windows 10, latest Chrome - fails,
Windows 10, latest Chrome - fails,
Windows 10, latest Chrome - fails,
Windows 8.1, latest Chrome - works

One would assume it is W10 related, but @fnlctrl uses a W10 build.
I have no idea what this is. I'm gonna check it at home on my Mac

**Comment by szmarci** [comment] 2016-12-16 09:17
update: it works fine on a Mac (OS 10.11), latest Chrome

**Comment by Eggon-666** [comment] 2019-05-22 15:46
Hi, I encountered the same problem in my project. I am also able to reproduce the behavior from the jsfiddle mentioned in this issue. Maybe I can shed some more light on the problem, because I noticed some very specific nuances.

WHAT IS HAPPENING: 
**Dragenter** and **dragleave** events are triggered on an incorrect (i.e. **preceding sibling**) element from **v-for** loop **together with or instead of** the events of the actually dragged element (DragTarget). The problem seems to be related to v-for specifically, I haven’t encountered it on non-v-for’ed elements. It appears on Chrome only.

My own jsfiddle with Vue 2.2.1:
https://jsfiddle.net/Eggon666/d6htzpr0/12/

Bug behavior on this js fiddle is erratic. There are 5 v-for elements:

1. The problem does not always occur on the first drag
2. Buttons 1 and 2 always work fine
3. Button 3 sometimes works fine and sometimes does not trigger any dragenter/dragleave event at all
4. Buttons 4 and 5:
  a.	sometimes work fine (rarely), 
  b.	sometimes they trigger events only on the preceding element (eg dragging No 4 triggers dragenter/leave on No 3)
  c.	sometimes they trigger events on both the dragged element and the preceding element. In such case the order is: 1) PrecedingSibling.Dragenter 2) DragTarget.Dragenter 3) PrecedingSibling.Dragleave 4) DragTarget.DragLeave
  d.	However, if you start the drag and don’t move the pointer outside of the DragTarget the bug **is very unlikely** to occur! If it occurs it never triggers PrecedingSibling only, it triggers both elements: 1) PrecedingSibling.Dragenter 2) DragTarget.Dragenter 3) PrecedingSibling.Dragleave
  e.	On the other hand, if you move the pointer out of the element immediately after drag start, the bug is very likely to occur.
  f.	When the dragenter is triggered on the DragTarget again, i.e. when you move out of the element and come back into it – the sibling event is not triggered anymore, just on the beginning of the drag.

Bug behavior on my local project (Vue 2.6.10) is slightly different. The setup is slightly different as well (v-for is used on components which have some nested divs in them). Bug behavior:

1. The problem does not always occur on the first drag
2. Once the problem occurs for the first time it occurs on every consecutive drag – except for element no 2 which can behave correctly again.
3. Dragging element triggers dragenter/dragleave triggers on both the dragged element and on the preceding v-for sibling (sibling first) or just on the preceding sibling.
  a.	When the dragenter is triggered on the DragTarget again, i.e. when you move the pointer on the child div or when you leave the element and come back into it – the sibling event is not triggered anymore, just on the beginning of the drag.

The difference between js fiddle and local behavior is mainly (but not only) frequency of particular behaviors. On the local setup: 
a. second v-for element is also affected, although can react correctly sometimes,
b. third element very rarely ignores the drag (I’m not sure if this part of bug is not JS fiddle issue)
c. starting from third element, once the bug occurs, it will occur every time (although might oscillate between triggering on preceding sibling only or two elements together),
d. the fact of not moving the cursor out of the DragTarget does not prevent the bug from happening (in contrary to jsfiddle point 4.d ). This might be caused by children divs?

Problem occurs on my two computers (Win7 HP and Win7 Professional), only on Chrome (74.0.3729.157). Mozilla and IE work fine. On one of the computers I removed Chrome with all extensions and history and reinstalled it. The problem persisted. Kaspersky’s Chrome extension is unfortunately automatically loaded on Chrome install, though not activated. Turning off Kaspersky on Windows did not prevent the extension from loading, and I don’t know how to prevent it other than uninstalling Kaspersky which I’d rather not do. Removing the Kaspersky’s extension from Chrome does not change the situation though.

**Comment by mciesin** [comment] 2019-09-18 11:20
I reduced the test case to [vanilla js](https://jsfiddle.net/8tz2gfm4/).

The bug happens when you open the page on Chrome on a HDPI screen with windows scaling (150%). In the console, you can see that when you move item from the list on the right over its own area, Chrome fires two `dragenter` events instead of one. Duplicated event has different `clientX` and `clientY` and that is probably connected with triggering first list's handler :).

**Comment by Eggon-666** [comment] 2019-09-30 14:31
@mciesin  I have this bug on Chrome, standard PC monitor, scale 100%.
