### ISSUE TITLE
Function Component Scoped CSS not applied if used with v-if

### ISSUE THREAD

**Issue by pxwee5** [vuejs/vue#10503] opened 2019-09-11 03:24 UTC
### Version
2.6.10

### Reproduction link
[https://github.com/maoberlehner/transition-to-height-auto-with-vue](https://github.com/maoberlehner/transition-to-height-auto-with-vue)

### Steps to reproduce
Source: https://github.com/maoberlehner/transition-to-height-auto-with-vue

Demo: https://transition-to-height-auto-with-vue.netlify.com/

Source has scoped css on the `*` rule. However in the demo, it is not applied. 

However if you change `v-if` to `v-show`, the `*` rule will be applied to that scope. 

### What is expected?
The functional component's scope is added on both v-if and v-show usage.

### What is actually happening?
The functional component's scope is added only on v-show and not applied on v-if.

**Comment by posva** [comment] 2019-09-11 07:32
Duplicate of https://github.com/vuejs/vue/issues/10416

**Closed by posva** 2019-09-11 07:32 UTC
