### ISSUE TITLE
New Event handler modifiers "self" & "capture" doesn't work on Chrome 41

### ISSUE THREAD

**Issue by yaowenz** [vuejs/vue#2380] opened 2016-02-23 07:19 UTC
### Vue.js version
1.0.16

### Reproduction Link
http://jsbin.com/xowizalice/1/edit?html,css,js,console,output  

Chrome 41 on Windows 7

### Results

when use v-on:click, everything is find. When use modifier "self" / "capture", the event doesn't emit.

### Update

I test on latest Chrome 48 it's OK. What's the difference between chrome 41 and 48 ?

**Comment by vuchl** [comment] 2016-02-23 07:53
When i clcik the buttons in Firefox ESR 38 it emits the `alert();` on all 3 buttons

**Comment by yaowenz** [comment] 2016-02-23 11:27
@vuchl 

I use chrome 41.

**Comment by vuchl** [comment] 2016-02-23 12:33
I tested in Chrome 48. Works too.

**Comment by yyx990803** [comment] 2016-02-24 15:52
Why are you not using the latest Chrome?

Closing since cannot reproduce in latest Chrome stable.

**Closed by yyx990803** 2016-02-24 15:52 UTC

**Comment by vvpvvp** [comment] 2016-02-29 06:31
I also meet this problem too, is there new version of Vue can solve this question.
And also event object don't have attribute currentTarget and relatedTarget.
