### ISSUE TITLE
Get the data after filters?

### ISSUE THREAD

**Issue by flyyang** [vuejs/vue#2506] opened 2016-03-18 10:05 UTC
Say I have a pagination component. I do a lot filter of the origin data.

```
   <tr v-for= "item in items | filter1 | filter2 ... | filtern"></tr>
   <pagination :length="lengthAfterFilter"><pagination>
``` 
The pagination component need to get the data length after filtered.Is there possible means to achieve this?

Seems it's common to trigger something after the last filter...

**Comment by posva** [comment] 2016-03-18 10:24
Hello!

You should post questions on the [vue.js forum](forum.vuejs.org) or in the [vue.js gitter](https://gitter.im/vuejs/vue). You'll have better answers :smile: 

As for your question my guess is to use a computed property or to have an extra filter to save data on the vm, so you can use it later.

I'm closing the issue since it's not a bug nor a feature request/suggestion. If you think there should be a better way of doing this, feel free to reopen the issue (and eventually changing the title) as a feature request.

**Closed by posva** 2016-03-18 10:24 UTC
