### ISSUE TITLE
Functional components don't add class attribute from parent

### ISSUE THREAD

**Issue by rleite** [vuejs/vue#10254] opened 2019-07-10 11:44 UTC
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/s/functional-components-issue-ubtr8](https://codesandbox.io/s/functional-components-issue-ubtr8)

### Steps to reproduce
Create a functional component.
Add that component to another with a class attribute

### What is expected?
The class attribute should be added to the root element of the component 

### What is actually happening?
The class attribute is ignored

**Comment by posva** [comment] 2019-07-10 11:46
Duplicate of https://github.com/vuejs/vue/issues/7554

**Closed by posva** 2019-07-10 11:46 UTC

**Comment by rleite** [comment] 2019-07-10 11:49
Thanks @posva
