### ISSUE TITLE
Webpack no longer compiles as of 2.1.9

### ISSUE THREAD

**Issue by smitt04** [vuejs/vue#4837] opened 2017-02-01 20:57 UTC
Not sure what the problem is but webpack seems to compile fine on 2.1.8, but 2.1.9 and later it will no longer complete. It just runs forever with no errors or anything.  I don't have time to create a test, but when i do I can create one. Just submitting issue to be reminded and maybe someone else also has issue.

I am using webpack 2.2.0-rc3

**Comment by fnlctrl** [comment] 2017-02-02 01:45
Cannot reproduce with vue 2.1.10, webpack 2.2.1, vue-loader 10.0.2.
Please try to upgrade everything to the latest version and see if the problem persists,
if so, please check your webpack configs, and create a reproduction repo. 
Closing now as it doesn't seem to be related to vue.

Also, you might want to check 
1. If `vue` and `vue-template-complier`'s version are the same.
2. If there's any webpack config/params suppressing errors.

**Closed by fnlctrl** 2017-02-02 01:45 UTC
