### ISSUE TITLE
Unchecking a radiobutton not working with `v-on:click.prevent` on another radiobutton with same `name`

### ISSUE THREAD

**Issue by ThomasLandauer** [vuejs/vue#11781] opened 2020-11-19 17:13 UTC
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/0vxoaz75/](https://jsfiddle.net/0vxoaz75/)

### Steps to reproduce
Click on the "Unset" radiobutton.

### What is expected?
The checked radiobutton (top row) should be unchecked.

### What is actually happening?
Nothing.

---
* Vue DevTools are showing me that the value is actually being set to `null`. But the view isn't updated.
* If I do the value change inside DevTools(i.e. without clicking), it works as expected.
* Or when I remove the `name` from the "Unset" radiobutton, it works too.
* Or when I remove `.prevent`, it works too. From my understanding, `.prevent` in this case should only prevent the clicked radiobutton from getting checked; not prevent the others from being unchecked.

**Comment by posva** [comment] 2020-11-19 18:41
Duplicate of https://github.com/vuejs/vue/issues/9535

**Closed by posva** 2020-11-19 18:41 UTC
