### ISSUE TITLE
[v2.5.17-beta.0] Array changes do not always trigger computed property updates

### ISSUE THREAD

**Issue by aaronrosenthal** [vuejs/vue#7960] opened 2018-04-04 02:36 UTC
### Version
2.5.17-beta.0

### Reproduction link
[https://jsfiddle.net/9b6nktpu/](https://jsfiddle.net/9b6nktpu/)

### Steps to reproduce
Create a computed property that maps an array with values from a Vuex store.

### What is expected?
The computed property should update when the dependent array is changed.

### What is actually happening?
The computed property only updates the first time the dependent array is changed. Later changes to the array do not trigger an update.

---
This worked as expected in 2.5.16 but seems to have broken with 2.5.17-beta.0. I know the beta changelog mentions some known breaking changes so those could be the culprit.

**Comment by schoonc** [comment] 2018-04-04 09:27
I can't reproduce in chrome. Which browser?

**Comment by Gudradain** [comment] 2018-04-04 19:42
The problem seems to be when Vue.set is called in the mutation. When it is called, it seems like the computed property no longer react to the list but only react to the new property that was define with Vue.set in Vuex.

Here is a practically identical fiddle that works correctly since the Vue.set is never called: https://jsfiddle.net/jzoprvtv/10/

**Comment by sodatea** [comment] 2018-04-06 09:35
Seems to be caused by https://github.com/vuejs/vue/commit/653aac2c57d15f0e93a2c1cc7e6fad156658df19
Can I take up this issue? @yyx990803

**Comment by yyx990803** [comment] 2018-04-06 21:52
@sodatea yes please

**Comment by yyx990803** [comment] 2018-10-22 19:58
Closing as the original commit that caused the regression has been reverted in 6b1d431

**Closed by yyx990803** 2018-10-22 19:58 UTC
Labels: has PR, regression
