### ISSUE TITLE
First letter disapears with textarea v-model.lazy and @input

### ISSUE THREAD

**Issue by kessiacastro** [vuejs/vue#6199] opened 2017-07-24 15:14 UTC
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/kessiacastro/gn9w320q/](https://jsfiddle.net/kessiacastro/gn9w320q/)

### Steps to reproduce
When anything is typed in a textarea with v-model.lazy and @input event checking the e.target.value the first letter typed disapears of the textarea. It also happens when using @keydown event.

### What is expected?
The typed message should appear normally in the textarea.

### What is actually happening?
Only the first letter disappears in the text area.

**Comment by jkzing** [comment] 2017-07-24 17:01
I think it's an expected behavior and that's how `.lazy` works: the `change` event will only fire when textarea loses focus.
More specific in your repro code: when type in any character, `input` event fired, and `this.disableButton = e.target.value` got executed and which caused a re-render. In that re-render, vue does render value of `message` into textarea, which is still empty then because `change` event never fired during this process.

**Comment by posva** [comment] 2017-07-24 17:02
It looks like the template compilation is adding too many things.
A workaround will be:

```html
<textarea value.prop="message" @change="message = $event.target.value"@input="checkValue"></textarea>
```

**Comment by posva** [comment] 2017-07-24 17:20
Closing because it's working as expected, it's an edge case though
You can workaround by putting the texarea into a component: https://jsfiddle.net/5nfqd4e8/

**Closed by posva** 2017-07-24 17:20 UTC
