### ISSUE TITLE
ref on a component is returning only an element

### ISSUE THREAD

**Issue by rhysburnie** [vuejs/vue#4068] opened 2016-10-31 01:53 UTC
Hi,

The new documentation for vue 2 states: 

> When used on a normal element, the ref will be the DOM element,
> and when used on a component, the ref will be the component instance.

I have `<floorplan-viewer ref="floorplanViewer"`

When I try to access any properties on the expected component I get errors

When I log `this.$refs.floorplanViewer` is logs the element `<floorplan-viewer></floorplan-viewer>`

Previously in vue 1 it would have logged the component instance and the docs for vue 2 says it will also, why am I only getting an element - I need to access the instance and its properties

**Comment by rhysburnie** [comment] 2016-10-31 02:52
Update to this:

I tried in another project and didn't have any issues so I suspect what this is but I'm unsure how to proceed now.

The component I have `FloorplanViewer` has been used in two way thus far with no issue.

On is in our device app where it is for pure presentation of data/functionality.

The other is in a floorplan data editor in our cms.

 ---

The cms needs to use it in compiler mode since we need to populate some props with php.

_cms usage_ index.html:
```
<div id="app" class="container">

      <input type="hidden" name="floorplan-data" id="floorplan-data" value=''>
      <floorplan-app :level-names="['Ground Floor', 'First Floor', 'Second Floor']" :categories="[]" :thumb-size="120"></floorplan-app>

    </div>
    <script>
```

_actual app usage_ index.html:
```
<div id="app"></app>
```
It's used in a route component.

Previously in vue 1 I have been able to access anything on the component via `this.$refs.floorplanViewer` however now it only seems possible to do so if you are not using the compiler mode at html level - which we need in our cms to dump php data.

Can you confirm this is expected behaviour now in vue 2?

**Comment by rhysburnie** [comment] 2016-10-31 04:39
I also get:

`vue.js?3de6:2611[Vue warn]: Unknown custom element: <floorplan-viewer> - did you register the component correctly? For recursive components, make sure to provide the "name" option`

Event tho I have always has a name property on the component and after importing it, if I log it the name is clearly visible:

```
import FloorplanViewer from './components/floorplan/floorplan-viewer';

console.log(FloorplanViewer);
// floorplanViewer.name === 'floorplan-viewer'

export default {
  components: [FloorplanViewer],
```

**Comment by rhysburnie** [comment] 2016-10-31 04:56
Created a new component with no extra code with a name of `floorplan-viewer` and imported that as `FloorplanViewer` same behaviour:

All these methods fail:

`components: [FloorplanViewer]` should use name to register
`components: { 'floorplan-viewer': FloorplanViewer }` explicit still doesn't work

**Comment by fnlctrl** [comment] 2016-10-31 05:09
Hi, thanks for filling this issue. Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) and provide a live reproduction on jsfiddle, codepen etc. Thanks!

**Comment by rhysburnie** [comment] 2016-10-31 06:12
I think I've worked out whats going on but don't know why one component breaks and one doesn't.

In my vue1 version Ive always had this:

```
  components: [
    FloorplanViewer,
    FloorplanThumbnails,
  ]
```

Because it's an array it only works because vue finds the `name` property of each.

However for some unexplained reason under vue 2 it was finding the `name` for the thumbnails component but not for the viewer even tho it was definitely there.

Through trial an error i tried:

```
  components: {
    FloorplanViewer,
    FloorplanThumbnails,
  }
```

as in the shorthand for:
```
  components: {
    FloorplanViewer: FloorplanViewer,
    FloorplanThumbnails: FloorplanThumbnails,
  }
```

because vue does its camel/kabab conversion it works fine.

The weird thing is why didn't the array method which used to work not work, and not work for one component but not the other?

Even if the array method was dropped it doesn't make sense that I was only getting an error for the thumbnails component.

This could easily be dismissed as the viewer missing  the name prop or typo but it has always had:

```
export default {
  name: 'floorplan-viewer',
```

I know in vue 1 you could use the array method or object method but cant find where its stated in vue 2 docs, has the array method been dropped in favour of the object method only, in some ways thats probably better.

**Comment by LinusBorg** [comment] 2016-11-07 08:46
Closing this as the original issue seems to be resolved, and no reproduction of a general bug was provided.

**Closed by LinusBorg** 2016-11-07 08:46 UTC
Labels: need repro
