### ISSUE TITLE
100% CPU usage with CRLF line endings on Windows

### ISSUE THREAD

**Issue by parthibd** [vuejs/vue#12248] opened 2021-08-30 02:22 UTC
### Version
2.6.14

### Reproduction link
[github.com](https://github.com/oguimbal/vuebug-simple)

### Steps to reproduce
Just follow the steps as mentioned in the repo.

### What is expected?
Browser based template compiler should report error about wrong template syntax.

### What is actually happening?
100% CPU usage with OS crash

---
This happens on Windows with CRLF line endings. The template compiler just gets stuck in an infinite loop in the browser.

**Comment by parthibd** [comment] 2021-08-30 02:23
@posva

**Comment by parthibd** [comment] 2021-08-30 02:27
Related:

https://github.com/vuejs/vue/issues/10547

**Comment by posva** [comment] 2021-08-30 07:09
Duplicate of https://github.com/vuejs/vue/issues/10547

**Closed by posva** 2021-08-30 07:09 UTC
