### ISSUE TITLE
arr.slice not always reuses dom with v-for and key

### ISSUE THREAD

**Issue by rikte88** [vuejs/vue#7809] opened 2018-03-12 20:40 UTC
### Version
2.5.13

### Reproduction link
[https://jsfiddle.net/8s42h4bp/25/](https://jsfiddle.net/8s42h4bp/25/)

### Steps to reproduce
`<div v-for="row in visible" :key="row">{{row}}</div>`

Case A (no problem): visible = rows.slice(100, 110) followed by visible = rows.slice(99, 109)

Case B (problem): visible = rows.slice(100, 110) followed by visible = rows.slice(101, 111)

The first reuses DOM elements, while the latter appears to create new ones. This can be seen by inspecting the div boxes in firefox and see them all flashing orange when clicking the "down" button, but not the "up" button in the minimal reproduction. Why is this so, is it some kind of optimization, or is it a bug?

I am trying to do this when scrolling a page up/down to only show rows that are in view in a huge table. It is visibly faster to scroll up than down, despite all elements being absolutely positioned. Happens in both Chrome and Firefox.

### What is expected?
DOM elements are reused in both case A and B.

### What is actually happening?
DOM elements appear to be recreated in case B, potentially causing unnecessary performance hit and contradicting:
https://vuejs.org/v2/guide/list.html#Replacing-an-Array

---
Loving Vue, keep up the great work!

**Comment by rikte88** [comment] 2018-03-12 20:58
![down redraws](https://user-images.githubusercontent.com/29840824/37309174-64fc4482-2640-11e8-9979-e81f32341ed6.png)
![up reuses dom](https://user-images.githubusercontent.com/29840824/37309179-6abe3e20-2640-11e8-9bf4-7c9dccdd1533.png)

**Comment by yyx990803** [comment] 2018-03-12 21:34
Should be a duplicate of #4362

**Closed by yyx990803** 2018-03-12 21:34 UTC

**Comment by rikte88** [comment] 2018-03-13 07:39
For others that may run into the same problem, it is possible to get a lot better performance by doing push, waiting for nextTick and then shift. Multiple pushs and shifts can happen in the same cycle without triggering the issue.
