### ISSUE TITLE
Computed property "getShowCreateDialog" was assigned to but it has no setter

### ISSUE THREAD

**Issue by Lutreer** [vuejs/vue#6290] opened 2017-08-04 04:38 UTC
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/chrisvfritz/50wL7mdz/](https://jsfiddle.net/chrisvfritz/50wL7mdz/)

### Steps to reproduce
```
computed: {
  ...mapGetters('clazz', {
    getShowCreateDialog: 'getShowCreateDialog'
  })
}
```
### What is expected?
no warn

### What is actually happening?
[Vue warn] Computed property "getShowCreateDialog" was assigned to but it has no setter

**Comment by ktsn** [comment] 2017-08-04 06:07
Please provide real reproduction.

**Comment by blingGold** [comment] 2017-08-04 07:13
In version 2.4.2，there is a update of computed property. In vue/src/core/instance/state.js，there is a statement, 'feat: warn when assigning to computed property with no setter'.
So，you must add a setter to computed property

**Comment by posva** [comment] 2017-08-04 07:17
That is because you're trying to set a property of the state or a getter that you mapped to your instance with `mapState` or `mapGetters`: http://jsfiddle.net/sxrL3tef/2/

This may happen if you pass the computed property to a `v-model` handled by another component. 

If you find a case where it's happening while it shouldn't, please tell me so I can reopen this

**Closed by posva** 2017-08-04 07:17 UTC
Labels: need repro

**Comment by Lutreer** [comment] 2017-08-05 01:27
@posva Thanks,that's because I used ".sync" that would change a property by "@update.anotherState = 'val => property = val'". 
But ".sync" is always trying to set a property immediately. So how can I use ".sync" correctly？
