### ISSUE TITLE
False Props Shorthand (false-assertion operator)

### ISSUE THREAD

**Issue by theAlexPatin** [vuejs/vue#11562] opened 2020-08-04 14:39 UTC
### What problem does this feature solve?
Currently, you can set a `true` value on a prop by simply using the prop's name (i.e. `<input readonly...>`), but there is no equivalence for setting `false` values (i.e. `<input :readonly="false">`).

In most cases (like above), `false` is already the default value, but there are still many instances where a prop's default is `true` and must be overridden. The API is cumbersome in those instances.

### What does the proposed API look like?
I'm proposing a simple, in-template, "false-assertion" shorthand that could significantly improve the Vue developer experience. The "false-assertion" operator would explicitly set props to `false`.

### Current API
```<input :readonly="false"/>```

### Proposed API
```<input !readonly/>```

**Comment by posva** [comment] 2020-08-04 14:46
Duplicate of https://github.com/vuejs/vue/issues/8549

If you thin this is worth pursuing, please follow the RFC process https://github.com/vuejs/rfcs

**Closed by posva** 2020-08-04 14:46 UTC
