### ISSUE TITLE
Slot content is not rendered in foreginObject, when forigenObject is root tag of separate component

### ISSUE THREAD

**Issue by alaroma** [vuejs/vue#11832] opened 2020-12-18 12:02 UTC
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/epic-neumann-m8hqz](https://codesandbox.io/s/epic-neumann-m8hqz)

### Steps to reproduce
Open link

### What is expected?
Should display button under the text

### What is actually happening?
Button is not displayed

---
I try to add separate vue component in svg. This component has foreginObject tag as root and contains button, wich was inserted thorought slot in another component. It do not work, I mean button is hidden in browser. However the button exist in DOM, more over has sizes

At the same time if forigenObject tag is declared in component with svg it is work. I can see button.
example: https://codesandbox.io/s/inspiring-mclaren-t1z09

I supose, there is porblem with slot content rendering in foreginObject, when forigenObject is root tag of separate component

**Comment by posva** [comment] 2020-12-18 12:08
Duplicate of https://github.com/vuejs/vue/issues/11315

**Closed by posva** 2020-12-18 12:08 UTC
