### ISSUE TITLE
Vue.config.errorHandler dosn't handle the error thrown by Async Watcher method

### ISSUE THREAD

**Issue by foyzhao** [vuejs/vue#10824] opened 2019-11-14 09:50 UTC
### What problem does this feature solve?
I'm using a global error handler for process errors during component render function and watchers. 

But it does not catch the exception thrown in the list method below:
```
export default {
  data() {
    return {
      key: null,
    };
  },
  watch: {
    async key() {
      await this.list();
    },
  },
  methods: {
    async list() {
      return axios.get('An invalid url');
    },
  },
};
```

### What does the proposed API look like?
No need to change API

**Comment by jacekkarczmarczyk** [comment] 2019-11-14 10:01
Duplicate of https://github.com/vuejs/vue/issues/10009

**Closed** 2019-11-14 12:39 UTC
