### ISSUE TITLE
<component is="input"> doesn't bind :value="..." correctly

### ISSUE THREAD

**Issue by brian-c** [vuejs/vue#8905] opened 2018-10-08 18:27 UTC
### Version
2.5.17

### Reproduction link
[https://jsfiddle.net/4n9jcgxL/](https://jsfiddle.net/4n9jcgxL/)

### Steps to reproduce
Change the text in the "normal" input. `value` bindings update as expected.

Change the text in the "component" input. `value` bindings still update as expected.

Change the text in the "normal" input again. The "component" input does not update. However, its `value="..."` attribute appears to be correct.

### What is expected?
The `<component is="input" :value="value">` should update when `value` changes.

### What is actually happening?
It looks like after editing a `<component is="input">` the value property and the value attribute get out of sync, which stops the UI from updating.

(My use case actually looks something like `<component :is="multiline ? 'textarea' : 'input'"></component>`, for what it's worth.)

**Comment by alanaasmaa** [comment] 2018-10-08 18:51
https://jsfiddle.net/4n9jcgxL/1/

This works.

Source: https://github.com/vuejs/vue/issues/7393

**Comment by posva** [comment] 2018-10-08 19:32
Duplicate of #7393

**Closed by posva** 2018-10-08 19:32 UTC

**Comment by brian-c** [comment] 2018-10-08 20:06
There it is, thank you both!
