### ISSUE TITLE
vue2.0.5 in android wechat throw "Uncaught ReferenceError: _create2 is not defined " exception

### ISSUE THREAD

**Issue by bryonliu** [vuejs/vue#4202] opened 2016-11-15 02:50 UTC
vue version :2.0.5
explorer useragent :
    "Mozilla/5.0 (Linux; Android 5.0.1; SM-N9106W Build/LRX22C) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/37.0.0.0 Mobile MQQBrowser/6.8 TBS/036872 Safari/537.36 MicroMessenger/6.3.30.920 NetType/WIFI Language/zh_CN"

### Steps to reproduce
        open this link "www.foxlibrary.top/html/test.html" in wechat(android phone) . and use the  wechat developer tool .  this just happen on the android phone .
      
### What is Expected?
        page working
### What is actually happening?
       throw exception.

**Comment by bryonliu** [comment] 2016-11-15 02:53
- Uncaught ReferenceError: _create2 is not defined vue.js?dced:239
- (anonymous function) vue.js?dced:239
- (anonymous function) vue.js?dced:7
- (anonymous function) vue.js?dced:6

**Comment by fnlctrl** [comment] 2016-11-15 07:22
Hi, thanks for filling this issue. Please provide a minimum example that cause the problem (a jsfiddle, or a github repo). Your link only provided minified bundled code which couldn't be of help.

**Comment by yyx990803** [comment] 2016-11-15 15:30
Cannot reproduce in Android WeChat browser with Vue 2.0.5. Make sure you are using the correct build. Closing as there is no evidence this is caused by Vue, please re-open when you can follow up with more information.

**Closed by yyx990803** 2016-11-15 15:30 UTC
Labels: need repro

**Comment by x531tanxl** [comment] 2016-11-28 07:28
@bryonliu I also have this problem. Maybe it's because the "devtool" option of webpack. I get this error when this option contains "eval". You can try removing "eval" from this option if you have this configuration.
