### ISSUE TITLE
Custom Directives inside v-if templates do not trigger ready hooks when displayed

### ISSUE THREAD

**Issue by beornlake** [vuejs/vue#2791] opened 2016-05-02 16:24 UTC
### Vue.js version
1.0.21

### Reproduction Link
https://jsfiddle.net/bpy0s4pv/

### Steps to reproduce
- Change the value inside the input box and notice that the model is updated to match.
- Switch to the Second input box variant.
- Change the value again.

### What is Expected?
- The data model is updated with the value in the second box.

### What is actually happening?
- The model is not updated to match the value in the second input box. This is because the second box never receives the `hook:ready` event, so it never sets up its binding logic.
- Toggle back-and-forth between First and Second inputs; notice that the binding continues to be broken.
- If you remove the `v-if` attributes from the input blocks in the HTML, then you can see that both input blocks receive the `hook:ready` event when the script is run.

**Comment by simplesmiler** [comment] 2016-05-03 12:06
Hello!

Hooks are emitted on the `vm`, and have nothing to to with the life cycle of directives. By the time your second directive is bound, `hook:ready` is already emitted, so the directive never receives it.

As per your use case. By the time the directive is being bound, the element that it is being bound to already exists, so there's no point in waiting for the `hook:ready`: https://jsfiddle.net/simplesmiler/bpy0s4pv/1/

I'm closing this for now, as this is not a bug.

**Closed by simplesmiler** 2016-05-03 12:06 UTC

**Comment by beornlake** [comment] 2016-05-03 15:06
Okay, thank you for the clarification. Your description is much more clear than the documentation!
