### ISSUE TITLE
Always allow Babel to transform expressions in templates

### ISSUE THREAD

**Issue by Justineo** [vuejs/vue#6307] opened 2017-08-07 08:18 UTC
### Version
2.4.2

### Reproduction link
[https://github.com/Justineo/vue-esnext-in-template](https://github.com/Justineo/vue-esnext-in-template)

### Steps to reproduce
`vue init webpack esnext-in-template`

`src/components/Hello.vue`:

```vue
<template>
<div :class="{ a: true, ...b }"></div>
</template>

<script>
export default {
  data () {
    return { b: true }
  }
}
</script>
```

(`babel-preset-stage-2` is already enabled after initializing with `vue-cli`.)

### What is expected?
The `class` value should be `a b`.

### What is actually happening?
```
Error compiling template:

- invalid expression: :class="{ a: true, ...b }"
```

---
`vue-template-compiler` seems to be [validating the expression before it goes through Babel](https://github.com/vuejs/vue/blob/c628103ca1ec4d0798c67412f6c458055a2073c8/packages/vue-template-compiler/build.js#L3764) with trying to evaluate `new Function(exp)`. This makes ES features that can be used in templates limited to those Node supports and causes confusion: I can translate spread operators for arrays both in templates and elsewhere but I can translate spread operators for objects anywhere except in templates. I think this might not be intentional so I mark this as a bug.

**Comment by nickmessing** [comment] 2017-08-07 10:15
As a workaround for now you can use latest Node with `--harmony` flag to build it.

**Comment by Justineo** [comment] 2017-08-07 11:38
@nickmessing

Thanks for the work around. But there are still some problem for this solution:

1. It's not possible to always include the workaround so it made the affected projects less portable.
2. Future ES features will always land as Babel plugins before in Node, even with `--harmony` flag.

**Comment by nickmessing** [comment] 2017-08-07 11:48
@Justineo, I personally would not like to change this mechanism because if we move that away from babel-template-compiler it would result in runtime errors which make it hard to track down mistakes in templates. Another way is to try and parse it with babel instead of `new Function()` but that is slow and I need to research actual performance impact.

**Comment by nickmessing** [comment] 2017-08-07 23:47
@Justineo, unfortunately, using `babylon` to parse expression breaks our current solution since it parses keywords successfully (ex: `(do + 1)`) and adds extra dependency. Looks like it's not an option and we are limited to use only code that is supported by node in expressions. `--harmony` solves the spread problem at the moment.

**Comment by Justineo** [comment] 2017-08-08 03:16
Thanks Nick. I think it's better to point this out in the docs to prevent confusion. I'll make a PR later if you don't mind.

**Comment by xiuxingdeshandaiwang** [comment] 2017-08-08 03:21
i have learned a lot

**Comment by nickmessing** [comment] 2017-08-08 03:22
Closing this issue, doesn't seem that we can consider this further.

**Comment by chrisvfritz** [comment] 2017-08-08 16:02
@nickmessing Any reason we couldn't just use `babel-node` instead of `node` for the build step in the Webpack template?

**Comment by posva** [comment] 2017-08-08 17:13
@chrisvfritz I wouldn't recommend using babel-node, it has some performance overload

**Comment by chrisvfritz** [comment] 2017-08-08 17:34
@posva How much slower are we talking about though? I think predictable behavior is worth slightly slower builds - or even moderately slower builds. Isn't that already a trade-off we're choosing when we write tests? Or when we include a build system that compiles to more predictably supported JavaScript? 😉

**Comment by chrisvfritz** [comment] 2017-08-08 17:46
My concern is that adding a note to the documentation won't be sufficient. When people encounter this problem, it will be nearly impossible to find that note and they could easily waste a day trying to figure out why this feature isn't working correctly - or probably more likely, just give up, assuming the Vue template compiler is buggy or lied about supporting Babel features.

If it _really_ isn't feasible to find a consistent workaround, I think we'll need some other way to communicate to users, like catch errors in the Vue template compiler to provide a warning about this behavior.

**Comment by posva** [comment] 2017-08-08 20:12
@chrisvfritz I haven't tested using babel-node with the webpack template (nor do I know if it's possible). I cannot remember what it was, but I keep a slightly bad memory of using it for node projects.

**Comment by nickmessing** [comment] 2017-08-08 20:18
@posva, @chrisvfritz, it's not an option here anyway since it doesn't transpire code from `new Function`, I think I know a way to make it work with `babylon` but only if we make it a dependency of template compiler, can this be considered?

**Comment by chrisvfritz** [comment] 2017-08-08 20:27
@nickmessing @posva While we investigate, would either of you mind if we reopened this for now, just to make sure we don't forget about it? Since it's not really a problem documentation can solve, I'm thinking we should only close when we can do one of these:

1. Prevent the issue completely (in our templates, if not in vue-template-compiler directly)
2. Provide the user a warning/hint when an error is raised that may be caused by an unsupported feature in node
3. As a last resort, decide neither is feasible and that encountering this difficult-to-diagnose behavior will just be one of those horror stories Vue users tell late at night, around the campfire 😅 

@nickmessing I think most users aren't too concerned about the size of dev dependencies, so that would be alright for me if it would make things work as users expect. 🙂

**Comment by nickmessing** [comment] 2017-08-08 20:29
@chrisvfritz, unfortunately I don't know how to have it without bundling Babylon into runtime build :-S

**Comment by posva** [comment] 2017-08-08 20:45
@chrisvfritz No worries 😆

**Comment by chrisvfritz** [comment] 2017-08-08 21:10
@nickmessing Ah, I see. Crazy idea then: could we avoid pulling babylon into the template compiler with something like below at the beginning of the `checkExpression` function?

``` js
if (envIsNode) {
  exp = eval('require("babylon")').parse(exp, userBabelConfig)
}
```

That's closer to pseudocode than a real solution, but do you think the strategy I'm getting at might be feasible?

**Comment by nickmessing** [comment] 2017-08-08 21:11
@chrisvfritz, actually yes, I'll try that way.

**Comment by yyx990803** [comment] 2017-11-20 16:33
With spread operators natively supported in Node 8.3+, I'll close this as a wontfix for now.

In order to use Object rest spread in templates, you need to:

- Use Node v8.3+

- Configure `buble` option for `vue-loader`:

  ``` js
  buble: { objectAssign: 'Object.assign' }
  ```

- If targeting any IE, make sure to include polyfill for `Object.assign`.

**Closed by yyx990803** 2017-11-20 16:33 UTC
Labels: improvement

**Comment by chrisvfritz** [comment] 2017-11-20 21:42
@LinusBorg @yyx990803 During Vue CLI 3 builds, perhaps we should also emit a warning for older versions of Node.

**Comment by a-x-** [comment] 2019-05-17 06:38
What about optional chaining and other babel plugins in the templates?

**Comment by agileago** [comment] 2019-05-20 03:37
when the vue-loader support optional chaining ? This is a very important feature

**Comment by Justineo** [comment] 2019-05-20 03:44
Vue is currently transpiling template with a [fork](https://github.com/yyx990803/buble) of [Bublé](https://buble.surge.sh/guide/) and there's no plan to support extra syntax. You can now use a method or computed property in the `<script>` section where optional chaining can be supported with a Babel plugin because Vue Loader handles the script part with Babel.

**Comment by agileago** [comment] 2019-05-20 10:27
@Justineo it is cumbersome. it is not like vue style (simple)

**Comment by bilouw** [comment] 2020-01-22 18:25
Hi guys,

I want to use chaining operator in template part, is there any solution to do that ? 

My problem is that i'm in a "v-if" hell! I need to check every nested structure with v-if to avoid bugs and errors in case of null value ... so this operator would be nice to avoid too many v-if. 

I could use the operator in a computed properties, but my point is to clean my code of useless syntax, and calling a method with argument is bigger than writing a v-if...

**Comment by oliverzy** [comment] 2020-02-06 05:37
Right now optional chaining has been officially part of ECMAScript 2020 (Chrome 80), therefore I think maybe we should reconsider this feature request again.

**Comment by Fuphoenixes** [comment] 2020-10-19 10:17
I want to use chaining operator in template part too, is there any solution to do that ?

**Comment by JuniorTour** [comment] 2021-08-01 11:16
Try [vue-template-babel-compiler](https://github.com/JuniorTour/vue-template-babel-compiler) 

It uses `Babel` to enable `Optional Chaining(?.)`, `Nullish Coalescing(??)` and many new ES syntax for `Vue.js SFC`.

## [Github Repo: vue-template-babel-compiler](https://github.com/JuniorTour/vue-template-babel-compiler)

## DEMO
![DEMO](https://user-images.githubusercontent.com/14243906/127761300-076db45a-cdce-4fda-bd02-1f4fa96de6d8.png)

## Usage
[Please refer to REAMDE for detail usage](https://github.com/JuniorTour/vue-template-babel-compiler#usage)

Support  for `Vue-CLI, Nuxt.js, Webpack` , any environment use `vue-loader`.
