### ISSUE TITLE
Render time of list of components increases in dev mode after each render

### ISSUE THREAD

**Issue by just-nobody** [vuejs/vue#5174] opened 2017-03-12 13:01 UTC
### Vue.js version
2.2.2

### Reproduction Link

https://jsfiddle.net/Kingdaro/1jpsbjz9/

### Steps to reproduce
Toggle the list of elements on and off.

### What is Expected?
Consistent speed between component list re-renders.

### What is actually happening?
With "use component" unchecked: rendering is instantaneous.

With "use component" checked: rendering the components takes longer and longer each time the elements are rendered.

Tested in Firefox, Edge, Chrome and Opera. It seems to be most noticeable with Chrome and Opera.

This does not appear to happen in production mode, but cases like this during testing will mean eventually waiting _full seconds_ for many components to render.

**Comment by fnlctrl** [comment] 2017-03-12 13:39
Hi, thanks for filling this issue.
`Good rendering speed` is way too broad, and without a benchmark comparison between other frameworks we cannot settle on a reasonable definition of `Good`.
Vue has always been dedicated to improving rendering performance, but unfortunately this issue can't really help us improve anything, since it's more of a complaint rather than constructive ideas on what exactly can be improved, so I'm closing it.

**Comment by just-nobody** [comment] 2017-03-12 14:07
That's fair. I'll clarify, then: the rendering speed should be _consistent_ between renders, fast or slow, but it's taking more and more time each time the list of elements are being rendered. This leads me to believe there's some sort of memory leak somewhere, where extra function calls are being done on data that should have been GC'd already.

**Comment by posva** [comment] 2017-03-12 15:16
Creating 1000 stateful components is obviously slower than creating 1000 spans

**Comment by just-nobody** [comment] 2017-03-12 15:59
That's not the issue.

> ...it's taking more and more time each time the list of elements are being rendered.

Check the "use component" box, and toggle the components a few times to get a good idea of what I'm talking about here. The rendering of the components gets progressively slower each time.

And I mentioned that this doesn't happen with the production build, but the possibility of a memory leak of some kind is what pushed me to report this.

**Comment by posva** [comment] 2017-03-12 16:07
Ok, sorry for that, the title is so misleading. There's indeed a strange increase of render time that only happens on dev mode. I checked and there's no memory leak.

**Comment by just-nobody** [comment] 2017-03-12 16:09
It's difficult issue to find and describe, so no worries.

**Comment by yyx990803** [comment] 2017-03-13 07:08
This seems to be caused by calls to `window.performance.measure`. Might have leaking calls somewhere.

**Closed** 2017-03-13 07:38 UTC
Labels: 2.x, improvement
