### ISSUE TITLE
Recursive components problem: Vue.component() does not respect "name" prop defined in options

### ISSUE THREAD

**Issue by fenivana** [vuejs/vue#3039] opened 2016-06-06 12:53 UTC
JSFiddle: http://jsfiddle.net/fenivana/wso9prne/

Vue.js version: latest

tree.js:
```js
module.exports = {
	name: 'v-tree',
  props: ['list'],
  template: '<ul>' +
              '<li v-for="item in list">{{item.value}}' + 
                '<v-tree v-if="item.children" :list="item.children"></v-tree>' + 
              '</li>' +
            '</ul>'
};
```

app.js:
```js
var tree = require('./tree');

// registered the tree component with a different name
// e.g. add namespace
// this will cause error
Vue.component('ns-tree', tree);

// but if I registered it with
// Vue.component('ns-tree', Vue.extend(tree));
// this works fine.

new Vue({
    el: 'body',
    data: {
    	list: [
      	{ value: 'foo' },
        { value: 'bar', children: [
          { value: 'baz' }
        ] }
      ]
    }
});
```

app.html:
```html
<ns-tree :list="list"><</ns-tree>
```

Throws error:
```
VM408 vue.js:1018 [Vue warn]: Unknown custom element: <v-tree> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
```

Using `Vue.component('ns-tree', Vue.extend(tree))` works fine, but this is verbose, and I need to tell the users of this component that you need to call `Vue.extend()` before `Vue.component()`, or you must register as the same name as the internal name.

**Comment by kazupon** [comment] 2016-06-07 02:44
Hi!
Thank you for your reporting!

You can use the `name` options at only `Vue.extend()`.
Please see the below document.
http://vuejs.org/api/#name

I think that you can resolve with a way the below jsfiddle URL.
http://jsfiddle.net/kazupon/7u1xpaoh/1/

**Comment by yyx990803** [comment] 2016-06-07 02:49
I think this is something that can be fixed since the expected behavior is reasonable.

**Comment by kazupon** [comment] 2016-06-07 03:11
@yyx990803 
So that means, if we specified component included `name` option to `Vue.components()`, Should we register the component, not global id but `name` option?

**Comment by fenivana** [comment] 2016-06-07 03:31
@kazupon The component is published on npm and github, the author doesn't know what name the users will use.

I think we can check whether `name` is defined
```js
if (!definition.name) {
  definition.name = id
}

**Comment by kazupon** [comment] 2016-06-07 04:31
@fenivana 
Thanks for your explanation!

Oh, I see.
I'll try to fix this issue.

**Comment by fenivana** [comment] 2016-06-07 07:57
@kazupon Thanks! I really like the quick response of Vuejs Team, you're awesome!

**Comment by yyx990803** [comment] 2016-06-08 16:18
Closed via #3040

**Closed by yyx990803** 2016-06-08 16:18 UTC
Labels: improvement

**Comment by peshkov3** [comment] 2016-10-07 05:46
@kazupon 
Thank you for your work! VueJS is awesome. 
Could you please correct the official example?  (It does not contain 'name' attribute in Vue.component definition)
https://vuejs.org/examples/tree-view.html

**Comment by fingerpich** [comment] 2017-07-05 09:09
How do i set different name and id in .vue file?

**Comment by EmadAdly** [comment] 2017-08-06 13:49
@fingerpich 

```js
<script>
export default {
  name: 'is-name',
...
</script>
```

**Comment by fingerpich** [comment] 2017-08-06 15:30
@EmadAdly I want to have different name and id in **.vue file** because I have used a component recursively.
how do you set the id (global name)?

**Comment by appurist** [comment] 2017-08-26 06:56
@fingerpich I'm still working on some of these concepts myself, but I think you'd do the following to set the component name globally... In the same file where you create the Vue instance (i.e. where `new Vue(...)` is), above/before that Vue instance creation, add something like:
```
import MyComponent from '@/components/MyComponent.vue';
Vue.component('my-component',MyComponent)
```
Defining them in the `components:` member in the app or another component makes them only available to the template used there.

**Comment by appurist** [comment] 2017-08-26 07:01
BTW, I found this issue because I was getting the `did you register the component correctly?` error as well. It seems the name member of a single-file .vue component is ignored. I've stopped including them there and started naming them in the `components:` member where they are referenced (or globally as above), e.g.:
```
import MyComponent from '@/components/MyComponent.vue';
export default {
  components: {
    'my-component': MyComponent
  }
```
That will only be valid there, but the other approach above can be used for global registrations.

It seems more appropriate to me to only register them where they are used (locally), however I'm not sure of the performance impact of registering them locally repeatedly, if it's a component nested within _many_ components.

**Comment by lethak** [comment] 2017-11-01 14:14
Indeed, name in single-file .vue component seems ignored.

I am running into this right now

**Comment by YellowPanda11** [comment] 2017-12-18 19:39
Dynamically importing the single-file component solved the issue for me.

**Comment by LazzyGuy** [comment] 2018-01-26 17:30
https://jsfiddle.net/s67y0ohb/

help me out

**Comment by KimAbliter** [comment] 2018-04-02 15:49
I also have same issue, it displays "Unknown custom element: < random-quote > - did you register the component correctly? For recursive components, make sure to provide the "name" option."
here is my code:
- app.js 
```
var Vue = require('vue')
Vue.config.debug = true // Comment this line for production

new Vue({
    el: '#app',
    created: function() {
        this.laravue.init.call(this, ['home']);
    },
    data: {
        laravue: require('./laravue.coffee')
    },
    components: require('./components.coffee') 
})
```
- components.coffee
```module.exports =
    # Custom Elements
    'titles': require './components/title.coffee'
    'random-quote': require './components/random-quote.coffee'

    # Views
    'home-view': require './views/home.coffee'
```

- random-quote.coffee
```
module.exports =
    template: require './random-quote.template.html'
    created: () ->
        random = Math.floor(Math.random() * 6)
        @quote = @quotes[random]

    data: () ->
        ret =
            quote: ''
            quotes: [
                "Notice the small things. The rewards are inversely proportional."
                "Even the largest avalanche is triggered by small things."
                "Great things are done by a series of small things brought together."
                "Great things are not done by impulse, but by a series of small things brought together."
                "Coming together is a beginning; keeping together is progress; working together is success."
                "From small beginnings come great things."
            ]
```

- random-quote.template.html
```
<div class="quote">{{quote}}</div> 
```

**Comment by tomexx** [comment] 2018-10-24 12:30
Any success solving this?

**Comment by MaximStone** [comment] 2018-10-29 06:57
> Dynamically importing the single-file component solved the issue for me.

I tried to dynamically global register .vue components, but I have the same errors.

Can you explain what you did? And provide some code examples please. Thanks!

**Comment by JivanRoquet** [comment] 2019-03-03 07:23
@iambrennanwalsh thanks that's helpful but the fact that you use the word `name` as the component's name in this example couldn't be more confusing.

I actually think that, given the context of this issue (back to its very title), there was no worse word to choose from in the whole English dictionary :)

**Comment by Spartaques** [comment] 2019-10-14 18:02
Thx you a lot:)

**Comment by shohruh2241759** [comment] 2020-04-17 10:16
components:{
    'task': require('components/Task.vue').default
  }

it is not working who is known this
