### ISSUE TITLE
v-if & event handler

### ISSUE THREAD

**Issue by frlinw** [vuejs/vue#9340] opened 2019-01-18 16:09 UTC
### Version
2.6.0-beta.1

### Reproduction link
https://codepen.io/frlinw/pen/OreZMz

### Steps to reproduce
Click on "Click me"

### What is expected?
demo with v2.5.22 show the expected behavior: https://codepen.io/frlinw/pen/XoLYMR 

the "Dropdown" component should not be able to handle a click event which is supposed to create it

### What is actually happening?
the Dropdown is automatically closed because it handles the click event

**Comment by yyx990803** [comment] 2019-01-18 20:13
I think this is going to be a wontfix. The root cause is the change from macrotask back to microtask for changes triggered inside event handlers in 2.6. This was also the behavior for any version before 2.5.

Essentially, if an update is triggered in an event handler, it is queued using a microtask. **In Chrome, microtasks are fired in between event propagation invocations.** So the update happens **before** the click event propagates to the document.

We introduced the macrotask change in 2.5 (6e41679a) trying to fix edge cases like yours, but in turn introduced [a number of other issues](https://github.com/vuejs/vue/issues?q=is%3Aissue+label%3A%22nextTick+related%22+is%3Aclosed) which outweighed the benefits - so we decided to [revert back to microtask in 2.6](850555d1faa9be7d8306adffd95c7dee5e58717f).

We did also include a fix that would handle similar edge cases but **only if the event handlers are attached via `v-on`**. Your case is unfortunately impossible to account for because you are manually attaching an event listener on the document. The workaround, as you have found, is adding the listener with a small delay.

**Closed by yyx990803** 2019-01-18 20:13 UTC

**Comment by baybal** [comment] 2019-08-05 14:13
Sorry for resurrecting this again, but there definitely is a case for such things:

1. You prevent a value change in DOM from event
2. You do some validation logic
3. You change the :checked or any other event driven DOM change

$nextTick, as said before no longer releases the DOM, thus if you do the change in the next microtask, DOM change will still be prevented

This is a case to provide the functionality of a previous implementation of a $nextTick, or at least be transparent about whether you run the microtask before of after the event finishes propagation

@yyx990803 

I think the biggest showstopper case for that is how you handle media events https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Media_events

That's a hornet's nest in terms of browser incompatibility and you some times need to do things like listen for stop event and then relaunch the audio as soon as the stop event finishes propagation to prevent the playback from interruption, or you need to prevent the seek event, and change the playback position, or prevent video muting/unmuting conditionally, without few millisecond 'pop.'

For cases like that, people have no alternative to something like that now, but the issue with few millisecond delay is still there.

``` 
event.preventDefault()
await new Promise(resolve => setTimeout(resolve,1))
this.checkIfYouActuallyNeedToStopPlaybackOnTheNextBrowserTick()
```

**Comment by baybal** [comment] 2019-08-05 14:26
If such option will be introduced, just warn people in big red letters that safari has issues with it beforehand.
