### ISSUE TITLE
createElement conflict with text style button

### ISSUE THREAD

**Issue by maplewizard** [vuejs/vue#6461] opened 2017-08-28 06:37 UTC
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/mzyknkbr/2/](https://jsfiddle.net/mzyknkbr/2/)

### Steps to reproduce
Push the change button

### What is expected?
expect the button text will change

### What is actually happening?
The program caused errors as:
```
vue.js:572 TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at Proxy.toString (vue.js:81)
    at Proxy.eval (eval at createFunction (vue.js:9818), <anonymous>:2:125)
    at VueComponent.Vue._render (vue.js:4123)
    at VueComponent.updateComponent (vue.js:2542)
    at Watcher.get (vue.js:2883)
    at Watcher.run (vue.js:2960)
    at flushSchedulerQueue (vue.js:2728)
    at Array.<anonymous> (vue.js:707)
    at nextTickHandler (vue.js:654)
```

**Comment by HerringtonDarkholme** [comment] 2017-08-28 08:41
Hi, the `this.value` shouldn't be VNode, which is returned by `$createElement`. Vue's interpolation is only for string, number or plain object.

You can use `v-if` to toggle between showing text and element.

**Comment by posva** [comment] 2017-08-28 08:45
Closing since this is expected behaviour

**Closed by posva** 2017-08-28 08:45 UTC

**Comment by HerringtonDarkholme** [comment] 2017-08-28 08:48
In case OP want combine dynamic render function and template authoring. One can reassign `$slots` field and manually call `$forceUpdate`. 

https://jsfiddle.net/mzyknkbr/3/
