### ISSUE TITLE
Using v-bind to add selected attribute to option element doesn’t add selected attribute to DOM

### ISSUE THREAD

**Issue by philipp-rudloff-sendcloud** [vuejs/vue#12079] opened 2021-05-17 15:03 UTC
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/sqh8jL65/4/](https://jsfiddle.net/sqh8jL65/4/)

### Steps to reproduce
1. Add the bindings `:selected="'selected'"` and `:random="'random'"` to an `option` element.

### What is expected?
The `option` element is rendered in the DOM with both the `selected="selected"` and `random="random"` attributes present.

### What is actually happening?
The `option` element is rendered in the DOM with only the `random="random"` attribute present.

---
When writing a template with a `select` element which is using `@change` and `:selected` bindings on its `option` elements, I expect the resulting DOM to contain the `selected` attribute. I need this because that’s how native HTML behaves and because it would allow me to select the selected option using vue-test-utils and `wrapper.find('option[selected]')` which is currently impossible (**Update**: one can use `wrapper.find('option:checked')` as a workaround).

**Comment by posva** [comment] 2021-05-17 16:20
Duplicate of https://github.com/vuejs/vue/issues/8016

**Closed by posva** 2021-05-17 16:20 UTC
