### ISSUE TITLE
Race Condition - Data overridden by computed property 

### ISSUE THREAD

**Issue by lukepolo** [vuejs/vue#4649] opened 2017-01-04 16:07 UTC
### Vue.js version
2.0.2

### Reproduction Link
http://jsfiddle.net/df4Lnuw6/100/
### Steps to reproduce
Click on set user department, then click on set departments.

### What is Expected?
`data.form.department_id` = `2`

### What is actually happening?
`data.form.department_id` = `null`

**Comment by smolinari** [comment] 2017-01-05 10:06
I'd like to understand the problem. Is the goal to set the selected value, for instance when editing a record, before the actual selections are available to render?

Scott

**Comment by smolinari** [comment] 2017-01-05 14:32
Is there no way to get the selection options before setting the selected value?

Scott

**Comment by lukepolo** [comment] 2017-01-05 15:52
I "could" , but seems like something vue could handle , as it doesn't seem intuitive that a property gets overridden because some other data gets loaded in after. (also if you do not catch this while developing you may push out bad code)

**Comment by smolinari** [comment] 2017-01-05 16:47
The options of a select are what I consider application data and as a ground rule, I personally always see application data having priorty over the user data in terms of rendering. In other words, if I have a form, I make sure all the application specific data is loaded to render the form first, before I fill it with user created data. That is just my take on the situation. It definitely doesn't mean it is right.

Scott

**Comment by yyx990803** [comment] 2017-01-11 20:48
Closing as duplicate of #4524

**Closed by yyx990803** 2017-01-11 20:48 UTC
Labels: 2.x
