### ISSUE TITLE
Scoped HTML

### ISSUE THREAD

**Issue by nfplee** [vuejs/vue#12370] opened 2021-12-01 14:06 UTC
### What problem does this feature solve?
Allows you to create a scoped block of HTML without having to create a component (similar to petite-vue).

This has already been mentioned [here](https://github.com/vuejs/vue/issues/12212). However after searching for the issue/PR for hours I still cannot find it.

Please could you either keep this issue, re-open the original issue or add a comment which atleast links to the issue/pr.

### What does the proposed API look like?
```
<div v-scope="{ count: 0 }">
  {{ count }}
  <button @click="count++">inc</button>
</div>
```

**Comment by posva** [comment] 2021-12-01 14:56
Duplicate of https://github.com/vuejs/vue/pull/7325

**Comment by posva** [comment] 2021-12-01 14:57
Please, search existing issues and pull requests before opening issues, it saves maintainers a lot of time 🙏 (As mentioned in the other issue: https://github.com/vuejs/vue/pulls?q=is%3Apr+sort%3Aupdated-desc+v-scope+is%3Aclosed+)

**Closed by posva** 2021-12-01 14:56 UTC

**Comment by nfplee** [comment] 2021-12-01 15:15
Thanks for the link but I commented on the other issue 18 days ago without reply. I also mentioned in my issue I had spent hours searching for the original issue.
