### ISSUE TITLE
v-model doesn't work with <component is="input">

### ISSUE THREAD

**Issue by mesqueeb** [vuejs/vue#11639] opened 2020-09-03 07:39 UTC
### Version
2.6.11

### Reproduction link
[https://codepen.io/mesqueeb/pen/eYZGode](https://codepen.io/mesqueeb/pen/eYZGode)

### Steps to reproduce
```vue
<h6>works with v-model</h6>
<input v-model="message" />

<h6>does not work with v-model</h6>
<component :is="'input'" v-model="message" />
```

### What is expected?
- `<component :is="'input'" />`

should give the same result as
- `<input />` and it does.

They render the same, they also each emit the same events you can capture with `@input`.

Yet somehow, the one with `component is="input"` does not work with v-model.

### What is actually happening?
the one with `component is="input"` does not work with v-model.

**Comment by posva** [comment] 2020-09-03 08:22
Duplicate of https://github.com/vuejs/vue/issues/4763

**Closed by posva** 2020-09-03 08:22 UTC
