### ISSUE TITLE
An error in wechat devtools

### ISSUE THREAD

**Issue by mylhei** [vuejs/vue#9886] opened 2019-04-17 08:42 UTC
### Version
2.6.10

### Reproduction link
[https://test.ipalfish.com/klian/web/dist/m/picture/vip-code.html?from=singlemessage&isappinstalled=0](https://test.ipalfish.com/klian/web/dist/m/picture/vip-code.html?from=singlemessage&isappinstalled=0)

### Steps to reproduce
config project by vue-cli 3.0,  then load page in wechat devtools

see the error below:

libs.213765e4.js:1 Uncaught SyntaxError: Invalid regular expression: /[^a-zA-ZÂ·Ã€-Ã–Ã˜-Ã¶Ã¸-Í½Í¿-á¿¿â€Œ-â€â€¿-â€â°-â†â°€-â¿¯ã€-íŸ¿ï¤€-ï·ï·°-ï¿½.$_\d]/: Range out of order in character class
    at RegExp (<anonymous>)
    at Module.<anonymous> (libs.213765e4.js:1)
    at Module.2b0e (libs.213765e4.js:1)
    at r (vip-code.f5f61c2a.js:1)
    at Object.a1c6 (vip-code.f5f61c2a.js:1)
    at r (vip-code.f5f61c2a.js:1)
    at Module.56d7 (vip-code.f5f61c2a.js:1)
    at r (vip-code.f5f61c2a.js:1)
    at Object.17 (vip-code.f5f61c2a.js:1)
    at r (vip-code.f5f61c2a.js:1)

### What is expected?
render successfully

### What is actually happening?
report an error

---
it seem to a bug in vue.esm.js line 478
var unicodeLetters = 'a-zA-Z\u00B7\u00C0-\u00D6\u00D8-\u00F6\u00F8-\u037D\u037F-\u1FFF\u200C-\u200D\u203F-\u2040\u2070-\u218F\u2C00-\u2FEF\u3001-\uD7FF\uF900-\uFDCF\uFDF0-\
it only happen when production
`config.devtool = isDev ? 'cheap-module-eval-source-map' : 'hidden-source-map'`

**Comment by posva** [comment] 2019-04-17 08:47
Duplicate of  #9456 
Fixed on #9595

**Closed by posva** 2019-04-17 08:47 UTC
