### ISSUE TITLE
buggy type inference for props with array type

### ISSUE THREAD

**Issue by indus** [vuejs/vue#7895] opened 2018-03-26 10:40 UTC
### Version
2.5.16

### Reproduction link
[https://raw.githubusercontent.com/indus/stuff/master/vue_issue.jpg](https://raw.githubusercontent.com/indus/stuff/master/vue_issue.jpg)
(sorry - haven't found an online tool that shows type annotations)

### Steps to reproduce
type the following in an TS enabled Editor like VS Code:

``` TypeScript
new Vue({
    el: '#app',
    props: {
        object: {
            type: Array,
            required: true,
            default: () => []
        }
    },
    data: function () {
        return {
            message: 'Hello Vue.js!'
        }
    },
    created: function () {
        this.message;
    }
})
```

### What is expected?
correct type inference (at least) for 'message'

### What is actually happening?
getting Error: "Property 'message' doesn't exist" 

---
This doesn't happen when the type of the prop is Object:

``` JavaScript
new Vue({
    el: '#app',
    props: {
        object: {
            type: Object,
            required: true,
            default: () => {}
        }
    },
    data: function () {
        return {
            message: 'Hello Vue.js!'
        }
    },
    created: function () {
        this.message;
    }
})
```

or 'data' is just a simple object and not a function

``` JavaScript
new Vue({
    el: '#app',
    props: {
        object: {
            type: Array,
            required: true,
            default: () => []
        }
    },
    data: {
        message: 'Hello Vue.js!'
    },
    created: function () {
        this.message;
    }
})
```

**Comment by ktsn** [comment] 2018-03-26 11:56
This looks like duplicate of #7640 if you are using TypeScript 2.7.
If it's not the same issue, please provide a example github repo that reproduce it.

**Comment by HerringtonDarkholme** [comment] 2018-03-26 12:18
This is exactly the duplicate of #7640.

`type: Array` breaks the overloading function `Vue.extend`. The last alternative of overloading is picked so `this`-type isn't included.

The workaround is manual annotation.


```ts
import Vue, {PropOptions} from "vue"

Vue.extend({
    props: {
        myProp: {
            type: Array,
        } as PropOptions<any[]>,
    },
})
```

**Closed** 2018-03-26 12:18 UTC
Labels: typescript

**Comment by ffxsam** [comment] 2019-02-22 01:07
@HerringtonDarkholme Thanks for that workaround. Kind of hard to believe this is still an issue.
