### ISSUE TITLE
webpack hot-updates are not being applied in vue@2.0.0.rc-3, vue-loader@9.4.0, vue-hot-reload-api@2.0.6

### ISSUE THREAD

**Issue by gbisheimer** [vuejs/vue#3515] opened 2016-08-24 15:29 UTC
### Vue.js version
2.0.0.rc-3

### Reproduction Link
Check this repository [link](https://github.com/gbisheimer/vue-bug1)

### Steps to reproduce
1) Run repository project.
2) Open [http://localhost:8080](http://localhost:8080) in the browser 
3) You should see "Change me"
4) Change the text in file app/assets/javascripts/App.vue and save. Webpack should detect the change and rebuild the bundle.

### What is Expected?
Change should be reflected when hot-update is applied.

### What is actually happening?
You can see the hot-update js file being injected into the HEAD but no changes are being applied to the DOM

**Comment by LinusBorg** [comment] 2016-08-24 16:12
https://github.com/vuejs/vue/wiki/Vue-2.0-RC-Starter-Resources#standalone-vs-runtime-builds

Read that whole section.

**Comment by gbisheimer** [comment] 2016-08-24 19:24
Thanks @LinusBorg for the answer.

I used 'vue/dist/vue.js' instead of just 'vue' because it gives me the following warning:

`[Vue warn]: Failed to mount component: template or render function not defined. (found in root instance)`

And the components is not rendered at all.

**Comment by yyx990803** [comment] 2016-08-24 19:38
Configure the alias per instructions in the link and it should work as expected.

**Comment by gbisheimer** [comment] 2016-08-24 20:30
@yyx990803, I made that change and it keeps doing the same thing. hot-update is not applied to the element.

Correct me if I'm wrong, but In this configuration, I'm using vue-loader with webpack, so all the templates should be compiled to render functions already and I can use the runtime-only version of Vue, right?

I have a working version with beta-7. I will upload that to the repository for comparison.

**Comment by yyx990803** [comment] 2016-08-24 20:36
@gbisheimer where did you get this setup from? It seems it's a custom-modified version of the webpack template, but it's most likely not configured correctly instead of a bug.

**Comment by gbisheimer** [comment] 2016-08-24 20:39
@yyx990803 

[Here](https://github.com/gbisheimer/vue-bug1/tree/working-beta-7) I uploaded a working version with beta.7.

I used vue-cli output project as base but I modified it a little bit to integrate it into a rails project.

**Comment by gbisheimer** [comment] 2016-08-24 22:58
It seems related to vue and vue-loader. If you use the master branch of the reproduction repo and replace the node_modules/vue and vue-loader folders with the ones in working-beta-7 branch, it works as expected.

Nothing else was modified.

**Comment by yyx990803** [comment] 2016-08-25 00:43
Just replacing `vue-loader` is incorrect, because npm3 installs flat deps and without replacing those you are creating version mismatches. I would

1. remove the `vue-html-loader`, `vue-style-loader`, `vue-hot-reload-api` deps since they are not needed for latest `vue-loader`. They are now deps of `vue-loader` itself.

2. Make sure you have the alias configured correctly.

3. Remove `node_modules` and re-install everything fresh.

I'll close this because a modified setup involves too many variants that we may not be responsible for - it would be a different matter if the same can be reproduced in an official 2.0 template. If the problem persists, please try to further narrow down the issue and open issue at `vue-loader`.

**Closed by yyx990803** 2016-08-25 00:43 UTC
