### ISSUE TITLE
Auto generate a key in v-for if one is not specified

### ISSUE THREAD

**Issue by catskull** [vuejs/vue#9235] opened 2018-12-20 20:35 UTC
### What problem does this feature solve?
If a key is not supplied in v-for, there will be a warning linking to the docs (which is helpful). However if Vue really just needs a unique ID so it can keep track of the elements, and the developer doesn't need a key, then Vue should just create it's own key to use rather than warning the developer.

Often items I have in a v-for don't really have any unique identifiers that would be good to use for a key, so I'm left with doing janky things to create a unique key, which seems brittle since unique identifier generation is a non-trivial problem. Someone proposed using something like https://github.com/ericelliott/cuid to do it, but I though, why not just have Vue do it for me under the hood?

### What does the proposed API look like?
Current API:
```
<div v-for="item in items" :key="item.id">
  <!-- content -->
</div>
```

Current API which results in a warning:
```
<div v-for="item in items">
  <!-- content -->
</div>
```

Proposed API which will not result in a warning:
```
<div v-for="item in items">
  <!-- content -->
</div>
```

**Comment by catskull** [comment] 2018-12-20 20:36
I am not familiar with the Vue source, but it appears this would be implemented somewhere here: https://github.com/vuejs/vue/blob/dev/src/compiler/codegen/index.js#L199

Instead of the warning, it would just need to generate a key and use it.

**Comment by posva** [comment] 2018-12-20 20:40
Duplicate of #6235

**Closed by posva** 2018-12-20 20:40 UTC
