### ISSUE TITLE
computed variable with arrow functions (second argument on setter)

### ISSUE THREAD

**Issue by patriciussanctus** [vuejs/vue#7688] opened 2018-02-22 12:26 UTC
### What problem does this feature solve?
One guy [finded](https://forum.vuejs.org/t/computed-properties-now-work-with-arrow-functions/19605), that computed getter may use with arrow function and destructed variables/methods.

I went ahead, and appended this case to ```set()```, but failed, because setter not called component.  
Later, i tried use ```arguments```: ```(locale => arguments[1].a.methods.updateLocale(locale))```, but vuex can't use ```dispatch``` to this, because undefined.

I think this API looks nice and will reduce many new lines :D

### What does the proposed API look like?
```
export default {
  computed: {
    ...mapGetters(['global']),
    locale: {
      get: ({ global }) => global.locale,
      set: (locale, { updateLocale }) => updateLocale(locale)
    }
  },
  methods: {
    ...mapActions(['updateLocale'])
  }
}
```

**Comment by posva** [comment] 2018-02-22 13:49
Duplicate of https://github.com/vuejs/vuex/issues/1085

Make sure to open the issue at the right repo 😉

**Closed by posva** 2018-02-22 13:49 UTC

**Comment by devinholloway** [comment] 2019-03-09 17:48
I don't believe this is a duplicate of vuejs/vuex#1085. The OP was requesting that a computed setter be passed the component reference as a second argument (which is nothing to do with vuex).

A computed getter is already passed a component reference which allows one to reference component data in an arrow function. But the setter cannot reference component data if defined as an arrow function.

`
computed: {
  myComputed: {
    get: vm => vm.myData,
    set(value) {
      this.$store.dispatch('updateData', value);
    }
  }
}
`
If the setter was passed a component reference as the 2nd argument, you could do this:
`
computed: {
  myComputed: {
    get: vm => vm.myData,
    set: (value, vm) => vm.$store.dispatch('updateData', value)
  }
}
`
Consider re-opening?

**Comment by posva** [comment] 2019-03-09 18:47
it was indeed different, opened a properly explained issue with no vuex (which was confusing)
