### ISSUE TITLE
Radio buttons out of sync with their v-model after using the Back button in Chrome/Edge

### ISSUE THREAD

**Issue by davermont** [vuejs/vue#12192] opened 2021-07-22 12:34 UTC
### Version
2.6.14

### Reproduction link
[http://microseeds.com/vue-bug.html](http://microseeds.com/vue-bug.html)

### Steps to reproduce
- use Chrome to load http://microseeds.com/vue-bug.html
- select Two
- click Submit
- click Chrome's Back button

### What is expected?
The value displayed should agree with the selected radio button

### What is actually happening?
The value displayed is "One" but the "Two" radio button is selected

---
The problem shows up in Chrome and Edge, but works as expected in Firefox.

**Comment by posva** [comment] 2021-07-22 12:45
Duplicate of https://github.com/vuejs/vue/issues/11165

**Closed by posva** 2021-07-22 12:45 UTC
