### ISSUE TITLE
Vue.directive does not lazy load definition like Vue.component((resolve,reject)=>...)

### ISSUE THREAD

**Issue by Nthalk** [vuejs/vue#5476] opened 2017-04-20 02:20 UTC
### What problem does this feature solve?
Because large applications may have MANY custom directives in addition to custom components, it makes sense to treat loading of external definitions similarly.

Because the Vue.directive(name, bindOrUpdate) signature exists, we would have to have another call signature, perhaps a 3rd argument?

### What does the proposed API look like?
```
Vue.directive("my-attribute", null, function(resolve, reject){
  $.getScript("/vue/directives/my-attribute.directive.js").then(resolve, reject);
});
```

**Comment by yyx990803** [comment] 2017-04-20 03:00
Duplicate of #4982

**Closed by yyx990803** 2017-04-20 03:00 UTC
