### ISSUE TITLE
removing an object from an array doesn't seem to work on deep object

### ISSUE THREAD

**Issue by kfirba** [vuejs/vue#1708] opened 2015-11-04 18:18 UTC
Hey.

As a part of my application I load some collections from the server based on the current route and cache them in my `$root` instance. My `$root` data has something like:

```js

data: function () {
    return {
        user: null,
        // some more...
        collection: null
    }
}
```

Now when I access a page like `/account/folders/10/collection` and I load the collection I cache it behind the scenes and use the `$set` method (only the first time I fetch ANY folder's collection) to store that in the format:

```js
collection['folder' + this.$route.params.folder_id].data = ['an', 'array', 'with', 'objects']
```

So if I cache folder 1723 the cache object will be something like:

```
collection.folder1723.data
```

Now I have a functionality where I let the user delete an object from the collection by the object's id. In order to find that object's index in the array I scan the array and do a quick comparison and attempt to call the `$remove` method:

```js
this.$root.collection['folder' + this.$route.params.folder_id].data.some(function (el, index, arr) {
    if (el.id == object_id) {
        console.log(index)
        arr.splice(index, 1)
        return true
    }
})
console.log(this.$root.collection['folder' + this.$route.params.folder_id].data[0])
```

You may think that the above works but it doesn't. 

However the element isn't being deleted from the array. I can see in the console the item that I was trying to delete. I hardcoded for this example the the `data[0]` because I know for sure that the index I'm trying to remove is `0` so I just tried to see what the result is.

**Comment by yyx990803** [comment] 2015-11-04 18:50
Hard to tell what is wrong without an actual reproduction.

**Comment by kfirba** [comment] 2015-11-04 19:29
@yyx990803 I just found a workaround which is weird but may give you a hint.

I changed the deletion method to:

```js
this.$root.collection['folder' + this.$route.params.folder_id].data.some(function (el, index) {
    if (el.id == object_id) {
         this.$root.receipts['folder' + this.$route.params.folder_id].data.splice(index, 1)
         return true
    }
}.bind(this))
```

So if I address the array directly and use the `splice` method it works.. that's super weird. Any clue?

**Comment by yyx990803** [comment] 2015-11-04 22:35
I really doubt that's what makes the difference, but again I can't really help without an actual repro.

**Comment by kfirba** [comment] 2015-11-05 04:33
@yyx990803 I will try to make a reproduction. By the way, addressing the array like I suggested in my comment indeed solves the problem and that why I was super surprised..

**Comment by simplesmiler** [comment] 2015-11-05 10:20
@kfirba does it work if you change it to the following?
``` js
var data = this.$root.collection['folder' + this.$route.params.folder_id].data;
var index = data.findIndex(function(el) {
  if (el.id === object_id) return true;
});
data.splice(index, 1);
```

**Comment by young-steveo** [comment] 2015-11-05 12:41
@kfirba Are you using a polyfill for `Array.prototype.some`?  Something tells me the array in the callback is a copy.

**Comment by kfirba** [comment] 2015-11-05 13:28
@simplesmiler I will try that once I get home.

@young-steveo I'm not using any explicit polyfill. The `some` method should be supported from IE9. I do use browserify with Babel for es6 but I don't think it creates a polyfill for that method.

**Comment by kfirba** [comment] 2015-11-05 16:11
@simplesmiler uhmm.. it works.

**Comment by yyx990803** [comment] 2015-11-05 16:17
You should try in your original code, say store the reference to the array as `data`, and in the `some` callback, log `arr === data` to see if they are in fact the same array. If it logs false, then likely you are using something that messes with ES5 Array methods.

**Comment by kfirba** [comment] 2015-11-05 16:29
@yyx990803 I get `true`. However, it doesn't remove the object from the array... that's super weird..

```js
console.log(this.$root.collection['folder' + this.$route.params.folder_id].data === arr) // <-- true
 arr.splice(index, 1) // <-- nope, doesn't work...
return true
```

**Comment by lebedenko** [comment] 2015-11-06 15:53
@kfirba Unfortunately objects are not observed. Only scalar values and arrays if you call some mutation methods like shift, push, splice etc. So it doesn't matter how you remove items from data array which is a property of collection object

**Comment by yyx990803** [comment] 2015-11-06 23:18
@kfirba that is weird indeed, but I can't reproduce this behavior. Closing for now - if you can provide a repro I can dig in further.

**Closed by yyx990803** 2015-11-06 23:18 UTC
Labels: need repro
