### ISSUE TITLE
Support provide/inject on functional components that are the immediate descendant of the provider

### ISSUE THREAD

**Issue by phroggyy** [vuejs/vue#11559] opened 2020-08-04 07:19 UTC
### What problem does this feature solve?
[This comment](https://github.com/vuejs/vue/issues/5194#issuecomment-465964034) from #5194 covers the use case quite well. In short, there is no way to do the following:

```html
<SomeProvider foo="bar">
    <FunctionalFoo/>
</SomeProvider>
```

The inner functional component cannot access any injected properties.

This occurs because the FC is rendered in the nearest vue context, which happens to be the provider in this case, and it's not possible to inject and provide within the same component.

### What does the proposed API look like?
The same as now, but supporting injections in functional components that are the immediate children of a provider.

This could either be achieved by supporting injections inside the same component as the provider, or passing the injections down similar to how we pass props down.

**Comment by posva** [comment] 2020-08-04 07:22
Duplicate of https://github.com/vuejs/vue/issues/5837

**Closed by posva** 2020-08-04 07:22 UTC
