### ISSUE TITLE
Improve document for Deploy Vue.js in 2018

### ISSUE THREAD

**Issue by 1c7** [vuejs/vue#8389] opened 2018-06-21 09:10 UTC
### What problem does this feature solve?
Step by Step guide on how to deploy Vue.js properly

### What does the proposed API look like?
No API, just document change

**Comment by 1c7** [comment] 2018-06-21 09:11
## Please improve document on how to deploy Vue.js to Production Enviroment
currently https://vuejs.org/v2/guide/deployment.html
is not that helpful.

and information on Google also not that helpful.

**Comment by 1c7** [comment] 2018-06-21 09:15
it's my first time open issue in Vue.js
I follow the guide using https://new-issue.vuejs.org/?repo=vuejs/vue
if the format are somehow still wrong, let me know, Thanks

**Comment by 1c7** [comment] 2018-06-21 09:20
## Why forum post not helpful
https://forum.vuejs.org/t/api-spa-deployment-best-practices/14544
receive 0 comment

https://forum.vuejs.org/t/vue-webpack-template-deployment-flow/2992
receive 0 comment

**Comment by Jinjiang** [comment] 2018-06-21 09:42
Hi @1c7
I think your question could be answered through search engine like: [How to deploy (and use) static web assets on mainstream CDN services](https://bing.com/search?q=how+to+deploy+static+web+assets+on+mainstream+CDN+services). Actually you don't need do any more special things on Vue.js itself.
Thanks.

**Comment by posva** [comment] 2018-06-21 09:43
Deploying a Vue app is the same as deploying a static website or a node app if you have SSR. You don't need anything specific to Vue 🙂 
This is a duplicate of https://github.com/vuejs/vuejs.org/issues/1517

**Closed by posva** 2018-06-21 09:43 UTC
