### ISSUE TITLE
Unable to watch for Set data type changes

### ISSUE THREAD

**Issue by xiaowei9495** [vuejs/vue#10383] opened 2019-08-13 01:33 UTC
### Version
2.6.10

### Reproduction link
[https://github.com/xiaowei9495/vue-watch-set-demo](https://github.com/xiaowei9495/vue-watch-set-demo)

### Steps to reproduce
yarn -> yarn serve -> Home Page -> add button

### What is expected?
watch Set

### What is actually happening?
No watch

**Comment by posva** [comment] 2019-08-13 07:07
Duplicate of https://github.com/vuejs/vue/issues/6774

**Closed by posva** 2019-08-13 07:07 UTC
