### ISSUE TITLE
VDOM update cycle inconsistent behaviour

### ISSUE THREAD

**Issue by andrejborstnik** [vuejs/vue#5136] opened 2017-03-08 12:43 UTC
When using variables to show/hide certain parts of DOM we encounter an apparent race condition - depending on how long the variable takes to change. The use case is requests vs. cached requests. While the requests are executed on the next tick, the cached requests are executed in the same tick as other operations, that would change the DOM. This interferes with DOM, even if we use nextTick/setTimeout to apply the results. 

The issue is bigger though, as nextTick and setTimeout behave differently with different browsers. See  [https://jsfiddle.net/6rgwatyo/2/](https://jsfiddle.net/6rgwatyo/2/)

In chrome nextTick overrides the first change and we only see the second div; setTimeout works as expected (most of the time). In safari we can see the first div if we spam nextTick, but never with setTimeout. In firefox we don't see the first div. 

We always see the first div with a timeout of 50ms. But with a timeout of 10ms we have a constant race condition across browsers.

**Comment by znck** [comment] 2017-03-08 12:55
I find no inconsistency. 

Updated: https://jsfiddle.net/znck/6rgwatyo/3/

**Comment by andrejborstnik** [comment] 2017-03-08 13:12
You showed that the variable (obviously) changes in correct order. But the DOM does not and its behaviour is inconsistent across browsers. Even if the render time is longer than the render time for one div, the nextTick does not seem to wait for the next DOM render. 

Updated: [https://jsfiddle.net/6rgwatyo/4/](https://jsfiddle.net/6rgwatyo/4/)

**Comment by znck** [comment] 2017-03-08 13:20
Check console output. You can see after clicking "Reload At next click" `#first` is in dom.

Updated: https://jsfiddle.net/znck/6rgwatyo/5/

------
If I'm missing something then comment back, else I'm closing the issue.

**Comment by yyx990803** [comment] 2017-03-08 13:24
All 3 browsers behave exactly the same for me. Please request a reopen if you can update your fiddle to better demonstrate the difference.

**Comment by LinusBorg** [comment] 2017-03-08 13:26
I think the issue @andrejborstnik is having is that in one case, you can *see* the 'first' div briefly flickering into view, while in the other (nextTick), you don't see anything, so nothing appears to have changed.

But if you add breakpoints, you can actually see that the 'first' div is added top the dom, but it's replaced again so quickly that you can't see it.

**Comment by andrejborstnik** [comment] 2017-03-08 13:54
Yes, different browsers render the DOM at different intervals apparently. So it appears inconsistent. Does VDOM batch DOM changes between ticks before applying them to the browser? In Vue 1 we did not observe this behaviour. From the behaviour I suspect the changes are batched into the same DOM update.

I expected nextTick to "delay" the change so that the second change is delayed until the first one is applied to the DOM (seen). 

The exact issue I have in my application is that the first div is hidden (by changing the variable = list length) from DOM, before the second is fully rendered (showing the old list. rendering the long list = a few seconds). I would expect that the first div is visible until the second div is rendered.
If I introduce a delay of 50ms the first div is always hidden only after the second div is fully rendered.

**Comment by LinusBorg** [comment] 2017-03-08 13:58
Habe you read the guide on [Reactivity in Depth](https://vuejs.org/v2/guide/reactivity.html)?

It has a section about the [Async Update Queue](https://vuejs.org/v2/guide/reactivity.html#Async-Update-Queue) that might think clearer for you.

**Comment by andrejborstnik** [comment] 2017-03-08 14:01
Yes, I read it but I do not see how this solves the issue. Are you saying the browser batches the DOM manipulations on its own?

In that case I think it is wrong to use the functions that cause this behaviour in nextTick, as the function promises to wait until the next DOM tick.

**Comment by andrejborstnik** [comment] 2017-03-08 14:14
@LinusBorg 
> As I already mentioned, add breakpoints to actually see this with your own eyes.

I know it is added to the DOM and removed immediately. But if I use ```setTimeout(..., 50)``` it is added to DOM and removed only after the second div is rendered (even if it takes a few seconds). When I use ```nextTick``` the first div is added and immediately removed, adding the second div. Only then is the second div rendered to have the correct contents.

**Comment by LinusBorg** [comment] 2017-03-08 14:17
> I know it is added to the DOM and removed immediately. But if I use setTimeout(..., 50) it is added to DOM and removed only after the second div is rendered (even if it takes a few seconds). When I use nextTick the first div is added and immediately removed, adding the second div. Only then is the second div rendered to have the correct contents.

I don'T see how your fiddle demonstrates this. Can you share a better example? Especially about this part:

>  removed only after the second div is rendered (even if it takes a few seconds).

**Comment by andrejborstnik** [comment] 2017-03-08 14:24
> I don'T see how your fiddle demonstrates this. Can you share a better example? Especially about this part:
> > removed only after the second div is rendered (even if it takes a few seconds).

Yes, I did not want to bother you with my exact case, but I guess I was not precise enough in the description.

Fiddle: [https://jsfiddle.net/6rgwatyo/7/](https://jsfiddle.net/6rgwatyo/7/)
And the behavior changes between browsers (probably because of different implementations/usage of the async queue functions).

**Comment by LinusBorg** [comment] 2017-03-08 14:40
Okay, now I see what you are talking about, but unfortunately I'm running oput of time today. Will certainly come back to this later!

**Comment by andrejborstnik** [comment] 2017-03-08 14:41
Ok, thank you.

**Comment by LinusBorg** [comment] 2017-03-08 14:47
Before I go, I re-open this so it doesn't get lost, because I think we at least have an issue with the docs that needs refinement.

The problem is that when `nextTick` relies on native `Promise.then()`, the callback is aded to the microtask queue of the browser and seems to run *after* the DOM has been updated but *before* the browser repaints to show those changes on the screen - so when this callback contains a blocking snc task, the DOM update we did before `nextTick` is neber visible (although it's there).

**Comment by yyx990803** [comment] 2017-03-09 02:01
To be honest I don't think there's much we can do about this - it has nothing to do with different `nextTick` implementations because all evergreen browsers support Promises, so they are all using the same internal implementation. So the behavior inconsistencies is not caused by Vue, but rather by how different browsers handle microtasks/timers/repaints differently.

This is kinda like using the same Promise API but getting different results in different browsers. Unfortunate, but there's little you can do about it.

The only possible way for Vue to try to normalize the behavior is by not using microtasks, which is simply not possible because of backwards compatibility. So my suggestion is simply avoid relying on such behavior and pick something that behaves consistently for your use case.

**Closed by yyx990803** 2017-03-09 02:01 UTC
Labels: discussion

**Comment by andrejborstnik** [comment] 2017-03-09 08:34
Thank you. I am already using ```setTimeout(..., 50)``` and it seems to work fine. The documentation should probably be updated to state that there is a chance of events like this happening and maybe provide a workaround.

**Comment by LinusBorg** [comment] 2017-03-09 08:39
>  it has nothing to do with different nextTick implementations because all evergreen browsers support Promises,

IT has insofar as older browsers fall back on setTimeout, which is not using the microtask queue.

I agree that we should update the docs about this, with a note that blocking sync operations in a `nextTick` callback will block UI updates in some browsers.
