### ISSUE TITLE
vue style bind can be improved

### ISSUE THREAD

**Issue by wulucxy** [vuejs/vue#11345] opened 2020-04-24 07:03 UTC
### What problem does this feature solve?
I have bind some style properties, like this:

```
position = {left: 40, top: 50}
```
so my first thought is this:

```
<div class={`basic-tooltip ${className}`} style={position}>
```
the result is style is not show at all。
I have to change to this:

```
// this really sucks~
const positionStyle = {}
if (style.left) {
  positionStyle.left = `${style.left || 0}px`
}
if (style.right) {
  positionStyle.left = `${style.right || 0}px`
}
if (style.top) {
  positionStyle.left = `${style.top || 0}px`
}
if (style.bottom) {
  positionStyle.bottom = `${style.bottom || 0}px`
}

<div class={`basic-tooltip ${className}`} style={positionStyle}>
```

so why don't the first way be supported, this is much more elegant than the second way。

### What does the proposed API look like?
render(){
 const position = {left: 40, top: 50}

return <div class={`basic-tooltip ${className}`} style={position} /> 
}

**Comment by posva** [comment] 2020-04-24 07:04
Duplicate of https://github.com/vuejs/vue/issues/8759

**Closed by posva** 2020-04-24 07:04 UTC
