### ISSUE TITLE
Feature Request: Promise Resolution Inside Templates

### ISSUE THREAD

**Issue by luciferavada** [vuejs/vue#10484] opened 2019-09-06 04:44 UTC
### What problem does this feature solve?
Allow resolution of promises inside templates.

### What does the proposed API look like?
`{{ await someFunction(value) }}`

**Comment by posva** [comment] 2019-09-06 07:01
Duplicate of https://github.com/vuejs/vue/issues/7520

**Closed by posva** 2019-09-06 07:01 UTC
