### ISSUE TITLE
Regarding Vue Class extending support (Feature Request)

### ISSUE THREAD

**Issue by DusanMilko** [vuejs/vue#7656] opened 2018-02-15 19:53 UTC
I was not able to find in the current documentation but was wondering if there are plans to have Vue supporting the es6 class syntax like below??:

```
class MyComp extends Vue {
   ...
}
```

I know this exists but its for .vue files and its not part of vuejs

https://github.com/vuejs/vue-class-component

**Comment by posva** [comment] 2018-02-15 21:53
Duplicate of https://github.com/vuejs/vue/issues/2371

**Closed by posva** 2018-02-15 21:53 UTC
