### ISSUE TITLE
TypeError: null is not an object (evaluating 'e.parentNode')

### ISSUE THREAD

**Issue by doerme** [vuejs/vue#2952] opened 2016-05-25 10:35 UTC
i had no idea about the error ocurr

[Error] TypeError: null is not an object (evaluating 'e.parentNode')
	B (vue.min.js:6:4913)
	（匿名函数） (vue.min.js:6:4223)
	R (vue.min.js:6:4402)
	D (vue.min.js:6:4206)
	（匿名函数） (vue.min.js:6:15231)
	st (vue.min.js:6:6505)
	te (vue.min.js:6:15198)
	insert (vue.min.js:7:22004)
	diff (vue.min.js:7:20956)
	update (vue.min.js:7:19944)
	_update (vue.min.js:8:7274)
	run (vue.min.js:7:16577)
	Bt (vue.min.js:6:12384)
	It (vue.min.js:6:12250)
	t (vue.min.js:7:8451)

**Comment by simplesmiler** [comment] 2016-05-25 10:48
Hello!

Thanks for reporting the issue. Please follow the Issue Reporting Guidelines and provide a minimal [JSFiddle](https://jsfiddle.net/simplesmiler/Lrk9sxjf/) or JSBin demonstrating the issue. Also make sure to use non-minified version, you will get helpful warnings.

**Comment by yyx990803** [comment] 2016-05-25 15:15
You should be using the non-minified version of Vue during development, maybe there will be a warning for something you did wrong.

**Comment by LinusBorg** [comment] 2016-06-01 11:48
Since there was not reproduction provided within a week, we assume this issue needs no further investigatio and close it.

If there is still a problem, please provide a reproduction and we will re-open the issue.

**Closed by LinusBorg** 2016-06-01 11:48 UTC
Labels: need repro
