### ISSUE TITLE
Component template content: html encoded chars in attributes are not properly decoded

### ISSUE THREAD

**Issue by chessydk** [vuejs/vue#8882] opened 2018-10-01 14:33 UTC
### Version
2.5.17

### Reproduction link
[https://codepen.io/chessydk/pen/ZqGqbr?editors=1010#0](https://codepen.io/chessydk/pen/ZqGqbr?editors=1010#0)

### Steps to reproduce
Hover over the "æøå".

### What is expected?
I would expect html attributes to be html-decoded, just like text-nodes, so when you hover over the text you should see "æøå"

### What is actually happening?
You see `"&#230;&#248;&#229;"`

---
Context: Serving html from CMS backend as JSON and creating dynamic Vue component with the server-generated html, which can have danish characters in attributes (mostly in object-data bindings like :model="{prop: &#230;&#248;&#229;}" , but the problem exists for all attributes.

**Comment by Justineo** [comment] 2018-10-01 15:47
Duplicate of #8805

**Closed by Justineo** 2018-10-01 15:47 UTC
