### ISSUE TITLE
微信中使用vue，在input事件中修改绑定的变量，输入框内容不变

### ISSUE THREAD

**Issue by stonelee** [vuejs/vue#3312] opened 2016-07-23 00:28 UTC
### Vue.js version
1.0.26

### Reproduction Link
http://s.codepen.io/stonelee/debug/QEAbLE

### Steps to reproduce
在输入框里输入数字，期待最多输入3位数字，在chrome中是正常的。

但是在微信和支付宝钱包里打开页面，输入框里超过3位后依然正常输出，而绑定的变量显示已经限制为3位

![image](https://cloud.githubusercontent.com/assets/571863/17074586/4ba1f8f0-50af-11e6-8c4f-b6a696cc3674.png)

**Comment by posva** [comment] 2016-07-23 07:09
Hi, if you provide the editable version that'd be better.
I couldn't find a way to debug in a "wechat browser". Do you have any hint?

**Comment by fnlctrl** [comment] 2016-07-23 07:22
"wechat browser" lives in the IM called "wechat", which can be tedious to debug with. To use something like chrome's devtools, one must install their (ad-ware) QQ browser, and use consoles and inspectors inside it.

**Comment by posva** [comment] 2016-07-23 09:49
thanks for the info @fnlctrl

**Comment by agileago** [comment] 2016-07-23 12:27
觉得应该是异步更新那里顺序在微信的webview上有错乱，具体原因就得问尤大了， 不过这个问题你可以这样来解决,通过watch,vue双向绑定结束之后会触发watch

```
watch: {
      value: function (n, o) {
        // 最多3位
        if (n.length > 3) {
          n = n.substr(0, 3);
        }
        var self = this
        this.$nextTick(function () { self.value = n; })
      }
    }

```

**Comment by crossjs** [comment] 2016-07-23 14:19
why not use max-length?

**Comment by agileago** [comment] 2016-07-23 15:29
如果是textarea的话，maxlength是不起效的，这里讨论的跟maxlength没关系@crossjs

**Comment by YunSun-CN** [comment] 2016-07-25 06:48
这个双向的数据流有点乱了，既然要input，干嘛不绑成单向的呢？
input事件获取值后，再截取并设置到this.value中，而input输入框则使用`:value="value"`就行了呀。

**Comment by cnweibo** [comment] 2016-07-29 09:55
同学们最好用英文啊， 尤大的杰作可是国际化的哦。
Let's use English to discuss here. If we discuss in english, we can contribute more to vuejs.
@yyx990803 , thanks to you hero!

**Comment by hellomotoi** [comment] 2016-08-05 06:01
look...look

**Comment by ibufu** [comment] 2016-08-05 08:19
I have found a same issue. Change event also will fail. So, you can use blur. It works for me.

**Comment by posva** [comment] 2016-08-14 11:46
@stonelee Can you provide the editable version? Also, is there a non-adware version of the browser? I won't intentionally install an adware to debug this...

**Comment by fnlctrl** [comment] 2016-08-14 12:08
@posva Changing the link to http://codepen.io/stonelee/pen/QEAbLE makes it editable.
I've tested on my wechat browser/alipay browser on android 6.0, and couldn't reproduce the bug. 
So I guess it's one of those old ios safari issues.

It's worth mentioning that the code is mutating a v-model bounded value inside `<input>`'s `input` event handler, which (in my opinion) is not a reasonable usage.

**Comment by posva** [comment] 2016-08-14 19:55
@fnlctrl Thanks! I tried `edit` but didn't search any further 😄 
That's great news you could test it.
It doesn't seem right to me either.

@stonelee I think this issue has to deal with the order events are fired in different browsers. The value is updated correctly but the browser seems to be updating the input's `value` after, that's why you see the whole input value. So you actually need to set the input's value (`inputElement.value = this.value`) inside the function or use a `nextTick` as @agileago stated.

I'm therefore closing this. Please, tell me if you still encounter this issue

**Closed by posva** 2016-08-14 19:55 UTC
Labels: 1.x, contribution welcome, need repro
