### ISSUE TITLE
Error in render: "ReferenceError: "sp" undefined"

### ISSUE THREAD

**Issue by windyflying** [vuejs/vue#8228] opened 2018-05-22 14:30 UTC
### Version
2.5.16

### Reproduction link
[https://codepen.io/windyflying/pen/JvzvRb](https://codepen.io/windyflying/pen/JvzvRb)

### Steps to reproduce
1.用Chrome或Firefox或Edge打开重现链接，查看结果，代码按预期工作。
2.用IE11打开重现链接，代码不能按预期运行。检查浏览器控制台，有运行时错误，如标题。

### What is expected?
没有运行时错误

### What is actually happening?
出现运行时错误

---
编译后的模板函数在IE11、 IE10和工作正常的浏览器的不一致。

**Comment by Justineo** [comment] 2018-05-22 14:58
Seems to be a duplicate of #7946. There is already a PR for this: #8048. It should work correctly if you revert to `vue@2.5.15` according to the discussions in #7946.

**Comment by windyflying** [comment] 2018-05-22 15:35
![error1](https://user-images.githubusercontent.com/13942593/40373103-c291777e-5e18-11e8-9e19-d4f22b31d1bf.png)
![vesion](https://user-images.githubusercontent.com/13942593/40373105-c2fccf74-5e18-11e8-94d2-2842e17c6daf.png)

**Comment by posva** [comment] 2018-05-22 18:26
The repro doesn't even run on IE. After fixing the problems there don't seem to be any issue:
```js
const vm = new Vue({
  el: '#app',
  template: '<div id="app"><select style="width:200px"><template v-for="sp in product.specs"><option v-if="sp.id == product.specId" :value="sp.id" selected>{{sp.name}}</option><option v-else :value="sp.id">{{sp.name}}</option></template></select></div>',
  data: {
    product: {
      specId: 2,
      specs: []
    }
  },
  created: function () {
    var self = this 
    setTimeout(function () {
      self.product.specs = [
        {id: 1, name: 'hello'},
        {id: 2, name: 'world'}
      ];
    }, 1e3);
  }
});
```

 BTW it looks like you're trying to mimc v-model

**Closed by posva** 2018-05-22 18:26 UTC

**Comment by posva** [comment] 2018-05-22 18:33
Oh, yeah, forgot to say, you cannot use template inside `select` in in-browser templates because some browsers strips them off

**Comment by windyflying** [comment] 2018-05-23 00:45
Thank you very much
