### ISSUE TITLE
after clone the code and run npm install,then npm run dev, it takes a lot time and no result

### ISSUE THREAD

**Issue by Vincent2015** [vuejs/vue#5159] opened 2017-03-10 03:21 UTC
after clone the code and run npm install,then npm run dev, it takes a lot time and no result,no error
![Uploading 0EBA2427-B1F3-444D-A79F-FF820C3C5957.png…]()

**Comment by nickmessing** [comment] 2017-03-10 03:33
What are you expecting after `npm run dev`? it uses rollup to bundle things. [This](https://github.com/vuejs/vue/blob/f7170324a15dad84c31b86dddc1b5d3dd31b0cdd/build/config.js#L74) is what happens.

**Comment by Vincent2015** [comment] 2017-03-10 03:37
I mean it takes a lot time,about 2 hours,and the npm run dev didn't finish.  i want to know whther is correct

**Comment by nickmessing** [comment] 2017-03-10 03:50
Strange,
```
 ~/P/vue   dev  npm run dev                                                                                       9.8m  Fri 10 Mar 2017 16:48:37 NZDT

> vue@2.2.2 dev /home/nick/Projects/vue
> TARGET=web-full-dev rollup -w -c build/config.js

bundling...
bundled in 2039ms. Watching for changes...
```
Worked as expected for me. What you want to do?

**Comment by yyx990803** [comment] 2017-03-10 06:59
Cannot reproduce. Closing since this is most likely related to your system but not Vue.

**Closed by yyx990803** 2017-03-10 06:59 UTC
