### ISSUE TITLE
Server-side rendering broken due to render callback being invoked multiple times in some situations

### ISSUE THREAD

**Issue by patrick-steele-idem** [vuejs/vue#3861] opened 2016-10-06 16:08 UTC
When creating a server-side rendering benchmark for Vue2 I found that the benchmark was breaking because the render callback passed to Vue2 was being invoked multiple times. The problem did not occur if the Vue2 component is only rendered a few times, but rendering the exact same Vue2 component for a large number of times (as the benchmark was doing) caused the error.

I created a minimal repo to reproduce the problem (with additional docs): https://github.com/patrick-steele-idem/vue2-ssr-bug

Please let me know if I am missing something, but it looks like a bug in Vue2.

**Comment by jbruni** [comment] 2016-10-11 11:31
Have you read the "[Common Pitfalls](http://caolan.github.io/async/)" chapter of async documentation?

Please check "Synchronous iteration functions" section and specially "Multiple callbacks" section, which seems to be the case.

**Comment by patrick-steele-idem** [comment] 2016-10-11 15:06
@jbruni Thanks for the response. Adding a `setImmediate` does fix the problem, but it looks like there might be a couple things at play. I didn't notice the `Maximum call stack size exceeded` error because it was hidden before all of the `Callback was already called.` (it appeared much earlier in the output). I think there is still a bug within Vue2 that is causing the `Callback was already called.` error (Vue2 should never invoke the provided callback multiple times). As a side note, the benchmark was already using `setImmediate` to avoid the `Maximum call stack size exceeded` error, but it wasn't be used during the warmup phase.

**Comment by yyx990803** [comment] 2016-10-12 04:23
Hmm, on the `dev` branch I can't seem to reproduce this, even with `RENDER_COUNT=1000`. Are you using Node 6+? I'll close this for now, but feel free to provide more information to ensure a reproduction.

**Closed by yyx990803** 2016-10-12 04:23 UTC
