### ISSUE TITLE
Wrong parent of component

### ISSUE THREAD

**Issue by dxvladislavvolkov** [vuejs/vue#11381] opened 2020-05-07 12:39 UTC
### Version
2.6.11

### Reproduction link
[https://github.com/dxvladislavvolkov/vue-issue](https://github.com/dxvladislavvolkov/vue-issue)

### Steps to reproduce
1. Clone repo
2. Run npm i
3. Run npm run serve
4. Open console. You see the wrong parent element

### What is expected?
I want to see my-comp2 as the parent of my-comp

### What is actually happening?
I get #app element as the parent of my-comp

---
To reproduce I create two js files and create my components using extend. Then I import my files to index js and create global components using Vue.component. After it, I get the wrong parent of a component when I wrap my-comp

**Comment by posva** [comment] 2020-05-07 12:41
Duplicate of https://github.com/vuejs/vue/issues/11377#issuecomment-624829492

**Closed by posva** 2020-05-07 12:41 UTC
