### ISSUE TITLE
Support more collection data types in v-for

### ISSUE THREAD

**Issue by wenLiangcan** [vuejs/vue#2410] opened 2016-02-28 01:28 UTC
At some situations, plain object isn't the best choise. I tried to render a `Map` object by `v-for`, but seems `Vue` does not support it currently. (Here's a [post](http://forum.vuejs.org/topic/2638/how-to-use-v-for-to-iterate-over-a-map-object/5) I created in the Help thread on the forum.)    

Hope `Vue` can provide the `for ... of` syntax in `v-for` to iterate over data types like `Map` and `Set`.     

For example:

``` javascript
const map = new Map();
map.set('key1', 'val1');
map.set('key2', 'val2');
```

and we can render `map` in this way:

``` html
<ul>
    <li v-for="[key, val] of map">{{key}} - {{val}}</li>
</ul>
```

**Comment by nervgh** [comment] 2016-04-28 12:58
The duplicate of https://github.com/vuejs/vue/issues/1319

**Comment by agalazis** [comment] 2016-08-25 15:43
haha! similar issues open all the time and and people insist that they cannot justify implementation well people want to use it that's one justification I can also list the bazillion of issues closed that ask the same thing xD.  I also found one that justifies the use-case really well and refers to es6 specification when it comes to map order ->still closed.

**Comment by posva** [comment] 2016-08-25 16:10
People wanting to use a feature is not, by itself, an argument that can justify the need of having such feature

**Comment by agalazis** [comment] 2016-08-25 18:57
Yep but still the arguments that people use to close the issue are still not valid or at least not valid for all usecases eg the example of the elipen who justified his usecases very well as I mentioned above

**Comment by LinusBorg** [comment] 2016-08-25 19:43
If you want to discuss a specific issue, link to it please.

**Comment by catsclaw** [comment] 2016-09-07 15:54
It's important to be able to iterate over iterators in loops. That seems plainly obvious. It's a fundamental feature of the language.

The reasons for supporting it are:

1) Iterators, Maps, and Sets are all valid ES6. Refusing to support them means limiting yourself to ES5, which is a decision becoming less and less justified over time.
2) I'm building an application that has internal data stored in Maps and Sets. Instead of making them available to the UI, I now need to keep the data synced between the two manually, or write boilerplate and import it into my templates to do the conversion whenever the data is needed. This is exactly what Vue is intended to avoid.

**Comment by inca** [comment] 2016-12-21 08:33
Since #1319 is closed, it's worth reiterating on current decision here. In short, the feature is not trivial to implement (on observation mechanism level), so it's not about justifying use cases, it's about the amount of work and trade-offs.

I would really appreciate this feature, too. On the other hand, if observing ES6 data types becomes terribly hacky or, for example, compromise performance or other qualities, then people who do not currently use Maps and Sets with Vue might not appreciate this change.

**Comment by lmj0011** [comment] 2017-06-09 20:19
I suppose using [Array.from()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from?v=example) inside a computed function will have to be your best friend for now. :disappointed:

**Comment by alexsandro-xpt** [comment] 2017-07-27 20:28
Any solution for that?

**Comment by nickmessing** [comment] 2017-07-27 20:56
Small update, this will come if/when Vue decides to drop "legacy" browsers and will move to Evergreen ones with `Proxy` instead of `set`/`get` for reactivity.

@alexsandro-xpt, just use a computed function that returns `Array.from(yourDataSet)`.

**Comment by alexsandro-xpt** [comment] 2017-07-27 21:04
@nickmessing I try with Map, doesn't work.

**Comment by inca** [comment] 2017-07-27 21:12
Just `Array.from` is probably not solution you want because of lack of reactivity (changes to `yourDataSet` will not get propagated to Vue).

As mentioned earlier, Sets and Maps are not observable by Vue. In order to use those — either in `v-for`, or in computed properties, methods, watchers, template expressions, etc. — you need to create a serializable replica of this structure and expose it to Vue. Here's a naive example which uses a simple counter for providing Vue with information that Set is updated:

```es6
data() {
  mySetChangeTracker: 1,
  mySet: new Set(),
},
  
computed: {
  mySetAsList() { 
    // By using `mySetChangeTracker` we tell Vue that this property depends on it,
    // so it gets re-evaluated whenever `mySetChangeTracker` changes
    return this.mySetChangeTracker && Array.from(this.mySet);
  },
},

methods: {
  add(item) {
    this.mySet.add(item);
    // Trigger Vue updates
    this.mySetChangeTracker += 1;
  }
}
```

This illustrates a kinda hacky but 100% working method for making non-observable data reactive. Still, in real world cases I ended up with serialized versions of Sets/Maps (e.g. you'd probably want to store the modified versions of sets/maps in localstorage and thus serialize them anyway), so no artificial counters/hacks were involved.

I personally think this is a fair solution to a problem, but it definitely deserves some official documentation — otherwise it's impossible to justify this as non-hacky way of dealing with Vue internals.

**Comment by nickmessing** [comment] 2017-07-27 21:16
@alexsandro-xpt, sorry, I was wrong, computed will be hacky as @inca, another hacky solution would be using `$forceUpdate`, here's an example [fiddle](https://jsfiddle.net/8k9ngkuk/)

**Comment by alexsandro-xpt** [comment] 2017-07-28 13:17
Thank you @nickmessing and @inca, this work fine with my `new Map()`!!

**Comment by dsandber** [comment] 2017-08-13 15:32
Right now when you do a "v-for" over a "Map", the v-for acts as if it had received an empty array.

Regardless of the outcome of the extended discussion about whether/how to support Maps and Sets, it would save a lot of people a lot of debugging time if Vue simply warned "Maps and Sets are not yet supported -- see https://github.com/vuejs/vue/issues/2410".

**Comment by warent** [comment] 2017-09-05 00:47
Yup, Google search for this feature brought me to this ticket (after a few annoying mixups with Vue.set)

👍 This should be in the v-for documentation!

**Comment by alexsandro-xpt** [comment] 2017-09-05 18:58
Truly, should be in v-for documentantion!

**Closed** 2017-09-05 19:14 UTC
Labels: feature request

**Comment by chrisvfritz** [comment] 2017-09-07 06:58
@yyx990803 I wonder if a console warning would be better for this, since that would tell people what's wrong immediately, obviating the need to search for the solution. 

We're also already very explicit in the docs about which types we _do_ support, `Map` and `Set` not being among them. I can definitely see the argument for why one might _hope_ all iterables would work with `v-for`, but I don't think we currently give readers any reason to expect they would.

**Comment by schmod** [comment] 2017-09-11 18:36
I'm not quite seeing the argument against adding support for `Set`.  

`Set` itself can be cleanly polyfilled, and unless I'm missing something, it seems like Vue's approach for adding reactivity to arrays could very easily be extended to sets.  We'd only need to wrap `.add()`, `.clear()`, and `.delete()`.

**Comment by inca** [comment] 2017-09-12 09:25
My best guess (please correct/sorry if I'm wrong): the trickiest part is to wrap a `Set` constructor, which accepts an iterable. I don't see how iterable can be made observable, because in its general form it's just a function (i.e. `next`) with no referenceable state (think of generator-based iterator as an example).

**Comment by schmod** [comment] 2017-09-12 14:30
Why do we need to wrap the constructor?  Wouldn't we be passing pre-existing sets into Vue?

According to [the spec](http://www.ecma-international.org/ecma-262/6.0/#sec-set-iterable), the `Set` constructor immediately runs through the entire iterator, effectively retaining a shallow copy of the unique items returned by the iterator.  Once you've got a `Set` instance, it shouldn't matter whether it was created from an iterator or not.  

In this regard, a `Set` created from an iterator should be no different from an array created from an iterator (via `Array.from()`), which Vue already supports.

**Comment by Glidias** [comment] 2017-09-19 08:49
You can use immutable Maps/sets/ whatever data structures and allow reactivity with them though, but simply because the whole chunk reference changes. You can render them through a render function or computed array (the earlier being better in performance as it skips the creation of a dummy array..).  But mutable ones, not so unless you find a way to notify Vue of the change manually, which would be simply homebrewing yr own solution.

**Comment by zDream** [comment] 2017-12-27 03:20
That's no good. You can't do it

**Comment by zDream** [comment] 2017-12-27 03:23
@wenLiangcan 

```
var map = new Map()
  map.set('key1','Test1')
  map.set('key2','Test2')
```
```

<div class="info" v-for="(key,value) in dataArray">
        <div class="file-name">{{key}}</div>
        <div class="file-size">{{value}}</div>
        <div class="file-process">进度条</div>
        <div class="file-operate">{{msg}}</div>
      </div>
```

**Comment by tomeightyeight** [comment] 2018-01-19 16:54
Keen for support of this : )

**Comment by alexsandro-xpt** [comment] 2018-01-26 14:50
Me too

**Comment by lloydjatkinson** [comment] 2018-01-30 11:27
Any future plans to add support? Is there a technical reason Vue could not support Map and Set?

**Comment by steappe** [comment] 2018-02-10 09:36
The current problem with the Vue.set method on a plain object is that it triggers way too many subscribers when a property is added to the object. Actually, all the subscribers of all the properties are triggered when only one property is added.

The performance of the view is badly impacted when a map like collection contains hundredth of keys. For example, in my project thousands of subscribers are triggered when one element is added to the map using the Vue.set operation:

```
Vue.set(state.items, itemId, item); // where items is a plain object.
```

When I look deeply into the Vue.js code, I can see where the problem comes from. The dependencies that are triggered are those of the object, which means that if the object has one property for each key, then all the dependencies of all the keys are triggered when just adding one key. A less 'aggressive' strategy, would be greatly welcomed.

**Comment by cawa-93** [comment] 2018-03-16 16:35
Is there any news about future plans and possibly about native `Map/Set` support?

**Comment by tomeightyeight** [comment] 2018-04-03 13:45
This article details upcoming support in 2.6 - but there's nothing about that in the official roadmap from what I can see?

https://medium.com/@alberto.park/the-status-of-javascript-libraries-frameworks-2018-beyond-3a5a7cae7513

> "The current latest of the core is 2.5.x. Next minor release(v2.6), will support native ESM import, improved async error handling, iterator on ‘v-for’ directive and more."

Not sure where they got that information from?

**Comment by blackst0ne** [comment] 2018-08-06 23:42
Found this issue while was debugging the heck Vue's behavior over `Set` data objects. :thinking:

**Comment by OCJvanDijk** [comment] 2018-08-07 08:27
For people like me that were wondering about the roadmap for this, Evan You says in [this video](https://youtu.be/8oFexUl7_DE?t=1h13m42s) that Map and Set support is "likely" to arrive in 2.6

**Comment by bradisbell** [comment] 2018-08-14 02:58
@yyx990803 It's unfortunate that this issue in the tracker is marked as closed, especially if you're considering adding support in the near future.  Where can we follow progress on this feature?  Is there another issue somewhere?

**Comment by steven87vt** [comment] 2018-08-21 20:59
Just wondering for the sake of argument, and maybe I am doing it wrong, but since you can track array mutation using the [Mutation Methods](https://vuejs.org/v2/guide/list.html#Mutation-Methods) cant you just track an array of an object and be logically complete? you dont get all the same features implemented in Map but the ones you want would be pretty easily addressed especially if you are using something like _ or lodash.

**Comment by pkanane** [comment] 2018-09-05 17:54
Its sad but until the team adds this we might have to use alternate data structures

**Comment by Dwood15** [comment] 2018-10-31 18:52
Just want to chime in that we were going to use a Map for our data structure, then decided against it because of a lack of first-party support.

**Comment by bodograumann** [comment] 2018-11-01 09:57
This is planned for vue.js v3.0.
Compare: https://medium.com/the-vue-point/plans-for-the-next-iteration-of-vue-js-777ffea6fabf

**Comment by douglasg14b** [comment] 2019-03-28 06:28
This made converting a  TypeScript application over to Vue more difficult than it should have been, and was not something we expected to have to deal with...

**Comment by softwareCobbler** [comment] 2020-09-23 16:28
is this supported now in Vue3?

**Comment by AhmedEzzat12** [comment] 2020-12-30 10:26
any updates ?

**Comment by bodograumann** [comment] 2021-01-15 18:27
I can confirm that `Set.add` is reactive in Vue 3.

**Comment by MattiasMartens** [comment] 2021-03-05 17:17
I've tested Maps for reactivity as well and they work. In particular (for my use case), calls to computed functions that use `map.get()` update as expected as long as (of course) the Map's initialization is wrapped with `reactive()`.

I'll add that I love Maps and use them a lot. They are much more efficient than Object-based dictionaries, especially when working with integer keys. Plus they allow indexing on object references, which can't be done with Objects. I like to use them for managing aggregated data that is useful in various places in the app.

Very happy to see that this is implemented!

**Comment by andrewvasilchuk** [comment] 2022-04-19 19:48
Using [@vue/composition-api](https://www.npmjs.com/package/@vue/composition-api) I have come up with the following solution for Vue 2.

```ts
// useReactiveSet.ts
import { ref, computed } from '@vue/composition-api'

export default function useReactiveSet<T>() {
  const version = ref(1)
  class ReactiveSet extends Set<T> {
    add(value: T) {
      super.add(value)
      version.value += 1
      return this
    }
  }
  const inner = ref(new ReactiveSet())

  const set = computed(() => {
    version.value
    return inner.value
  })

  return set
}

```

```ts
// Component.vue
{
  // ...
  setup() {
    const set = useReactiveSet<number>()

    setTimeout(() => {
      // this will trigger rerender
      set.value.add(2)
    }, 1000)

    return {
      set,
    }
  },
  // ...
}
```

You can use the same approach for `Map`.

**Comment by andrewvasilchuk** [comment] 2022-05-08 09:13
@inca I have created a package that was adopted from your comment. Thank you so much! https://github.com/bluecanvas/vue-reactive-collection

**Comment by Hansomeble** [comment] 2022-05-08 09:18
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我现在没在上网，无法亲自回复您的邮件。我会在上网后，尽快给您回复。

**Comment by wpplumber** [comment] 2022-09-21 18:24
It works by assigning new clone with property changes.

`state.files = new Map(allFiles);`

**Comment by Hansomeble** [comment] 2022-09-21 18:24
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我现在没在上网，无法亲自回复您的邮件。我会在上网后，尽快给您回复。
