### ISSUE TITLE
Events inside a slot cannot perform if another v-show element is around

### ISSUE THREAD

**Issue by Leopoldthecoder** [vuejs/vue#3565] opened 2016-08-30 11:22 UTC
### Vue.js version
2.0.0-rc.4

### Reproduction Link
https://jsbin.com/rifuxuxuxa/1/edit?js,console,output

### Steps to reproduce
1. After hitting 'Run with JS', click the 'click here' button
2. Wait till `this.show` is `true`(8 seconds), click the 'click here' button again

### What is Expected?
In step 1, prints '2333'
In step 2, prints '2333'

### What is actually happening?
In step 1, prints '2333'
In step 2, an error occurs 'o.fn is not a function'

This can only be reproduced when there is a `v-show` element around. I have tried to put the `v-show` element (in this case, the 'balabalabala' span) before the `slot`, after the `slot`, outside the `div`, and they all report the same error after `this.show` is set to `true`.
This may have something to do with [this](https://github.com/vuejs/vue/commit/e6c5f21f86c3d2de4821c99566dba364c18b4c19#diff-607630de25f071aeb86d9962152e26bdR132).

**Comment by yyx990803** [comment] 2016-08-30 14:47
Duplicate of #3556.

**Closed by yyx990803** 2016-08-30 14:47 UTC
