### ISSUE TITLE
'npm test' command fails

### ISSUE THREAD

**Issue by miherlosev** [vuejs/vue#4467] opened 2016-12-13 13:35 UTC
According the [development setup] (https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup) I do the following:
- clone vue repository
- `npm install`
- `npm test`

On `npm run build -- vue.min.js && node test/e2e/runner.js "--env" "phantomjs"` step 
I get error:
```
vue@2.1.5 test:e2e C:\vue_github
> npm run build -- vue.min.js && node test/e2e/runner.js "--env" "phantomjs"


> vue@2.1.5 build C:\vue_github
> node build/build.js "vue.min.js"

Error: Could not load C:\vue_github\src\core/index (imported by C:\vue_github\src\entries\web-runtime.js): ENOENT: no such file or directory, open 'C:\vue_github\src\core\index'
    at C:\vue_github\node_modules\rollup\dist\rollup.js:8833:10
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
Starting selenium server... started - PID:  10820

[Commits] Test Suite
========================

Running:  commits

```

**Comment by fnlctrl** [comment] 2016-12-13 13:37
Duplicate of #4338

> Closing since the source of the issue is in a dependency, and is not a bug in the framework itself.

**Closed by fnlctrl** 2016-12-13 13:37 UTC

**Comment by miherlosev** [comment] 2016-12-13 13:46
Ok.
If it is possible, update dependency to version without this bug.
