### ISSUE TITLE
v-pre doesn't work inside textarea?

### ISSUE THREAD

**Issue by rjurado01** [vuejs/vue#3306] opened 2016-07-21 16:37 UTC
Hello, I have this example: https://jsfiddle.net/rjurado/tq136Lwr/

```javascript
<textarea id="textarea" v-pre>
  {{works}}
</textarea>

<div id="example">
  <p v-pre>{{ work }}</p>
  <textarea v-pre>{{ no wokrs }}</textarea>
</div>
```

```
new Vue({ el: '#textarea' });
new Vue({ el: '#example' });
```

Why second textarea show empty?
If you inspect it you can see this:

```html
<textarea :value="no wokrs">{{ no wokrs }}</textarea>
```

**Comment by sirlancelot** [comment] 2016-07-21 16:44
A temporary workaround would be to surround the `textarea` in a `div` with the `v-pre` directive.

https://jsfiddle.net/81cumjxp/1/

**Comment by rjurado01** [comment] 2016-07-22 06:07
@sirlancelot Thanks this work.

**Comment by hylin** [comment] 2016-07-26 02:31
duplicate of #3184

**Closed** 2016-07-26 03:28 UTC
Labels: bug, contribution welcome
