### ISSUE TITLE
`.number` input modifier is removing decimal on user input

### ISSUE THREAD

**Issue by davesauce14** [vuejs/vue#11989] opened 2021-03-31 00:27 UTC
### Version
2.6.11

### Reproduction link
[ https://codepen.io/davegould41/pen/qBRqyRo?editors=101]( https://codepen.io/davegould41/pen/qBRqyRo?editors=101)

### Steps to reproduce
- Create an input element with event modifier `v-model.number="num"`
- try typing .01
- notice it resets the value to 1
- (inputting 0.01 works though)

### What is expected?
If the user enters `.01` the input element should have the value of `.01`

### What is actually happening?
`.number` input modifier is removing decimal on user input

If a user inputs `.01` they the input element will capture as `1`

---
I realize that javascript evaluates `.0` as `0` but this is a common scenario when adding numbers to an input element

**Comment by yuwu9145** [comment] 2021-03-31 00:34
because `parseFloat(.0)` results in `0`

**Comment by davesauce14** [comment] 2021-03-31 00:45
> because `parseFloat(.0)` results in `0`

I realize that javascript evaluates .0 as 0 but this is a common scenario when adding numbers to an input element

**Comment by yuwu9145** [comment] 2021-03-31 00:55
probably this is a Vuetify issue, as `<input v-model.number="num">` does not have similar symptom

**Comment by davesauce14** [comment] 2021-03-31 02:06
You are right, there already is already bug for that: https://github.com/vuetifyjs/vuetify/issues/6688
Though its already been closed.

Can you please direct me to the logic for your `.number` modifier?

**Comment by posva** [comment] 2021-03-31 06:50
Duplicate of https://github.com/vuejs/vue/issues/7136 (and others with more explanations)

**Closed by posva** 2021-03-31 06:50 UTC
