### ISSUE TITLE
state change in deactivated hook causes re-render

### ISSUE THREAD

**Issue by njh7799** [vuejs/vue#11581] opened 2020-08-09 07:40 UTC
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/quirky-sid-198zy](https://codesandbox.io/s/quirky-sid-198zy)

### Steps to reproduce
change state in deactivated hook

### What is expected?
DOM should not be a re-rendered.

### What is actually happening?
DOM is re-rendered.

---
When I change state in beforeDestroy hook, DOM is not  re-rendered. However if I do the same thing in deactivate hook, DOM is re-rendered for a second, then move to the other route. I think It's definitely a bug.

**Comment by posva** [comment] 2020-08-09 08:55
Duplicate of https://github.com/vuejs/vue/issues/8819

**Closed by posva** 2020-08-09 08:55 UTC
