### ISSUE TITLE
Wrong parameters in custom directive 1.0.27

### ISSUE THREAD

**Issue by shenron** [vuejs/vue#3777] opened 2016-09-26 18:28 UTC
### Vue.js version
1.0.27

### Reproduction Link
https://jsfiddle.net/gckb9mkv/1/

### Steps to reproduce
Open the fiddle and check the console output

### What is Expected?
Same code but with 1.0.26 dependencies.
https://jsfiddle.net/qjvz0p1x/

// p1:Array[2]
// p2:Array[0]
// p3:"toto"

### What is actually happening?
// p1:"a,b"
// p2:true
// p3:"toto"

**Comment by posva** [comment] 2016-09-26 19:53
Thanks for reporting this. This is actually a duplicate of #3768

**Closed by posva** 2016-09-26 19:53 UTC
Labels: 1.x, important, regression
