### ISSUE TITLE
Some of the things that arise about using textarea? 

### ISSUE THREAD

**Issue by sunriseshow** [vuejs/vue#4689] opened 2017-01-11 03:11 UTC
### Vue.js version
2.0.0

### Reproduction Link
[demo](https://jsbin.com/vumoxe/edit?html,css,js,output)
### Steps to reproduce
Add a picture, delete pictures, the previous step, the next step, will save the database
### What is Expected?
The value of textarea and store the last store value, inconsistent, you can not save the database

### What is actually happening?
With the v-model, textarea and store the value of the value is always the same，Always save the data to the database。Without v-model, the display is not correct

Note: I asked in other forums, some people say that this complex situation can not be resolved.
I do not know how it is, so I hope to be resolved.

**Comment by fnlctrl** [comment] 2017-01-11 09:17
Hi, thanks for filing this issue. Closing as it seems to be a usage question. 
If you believe there's a bug please be more specific about your problem, and provide a **minimal** reproduction - please don't copy-paste all of your code to a demo, try to remove the code that doesn't cause the issue.

**Closed by fnlctrl** 2017-01-11 09:17 UTC
