### ISSUE TITLE
Unable to pass directive through functional component template

### ISSUE THREAD

**Issue by brophdawg11** [vuejs/vue#9239] opened 2018-12-21 13:59 UTC
### Version
2.5.17

### Reproduction link
[https://codesandbox.io/s/nrpjvl3v0](https://codesandbox.io/s/nrpjvl3v0)

### Steps to reproduce
If you look at the linked code sandbox, there is a simple directive being used on a normal component, a functional component using a render function, and a functional component using a template.  I could not find a way to get the directive passed through in the functional template example.  Essentially a similar approach to `v-bind="attrs"` and `v-on='listeners"` but for directives.

Is this currently possible?  If not, would it be considered?  Otherwise - in order to write functional template components, you would need to ensure they are never intended to be used with custom directives.

Our specific use case was that we have a base button component that is a functional template components, but it doesn't work with https://www.npmjs.com/package/vue2-touch-events

### What is expected?
A method through the functional template to proxy through directives.

### What is actually happening?
The custom directive cannot be applied to the functional template component.

**Comment by brophdawg11** [comment] 2018-12-21 14:01
Please note - I tried to submit this via https://new-issue.vuejs.org/?repo=vuejs/vue, but the API call to get the available versions is failing with a 403 due too a rate limit error:

```
{
  "message": "API rate limit exceeded for 204.115.126.10. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
```

So I was unable to fill out that field and thus unable to submit the bug.  I copied/pasted the same template from an existing issue in hopes of matching the format and not getting auto-closed :)

**Comment by posva** [comment] 2018-12-21 14:10
I believe this is not possible at the moment
Let's mark this as a duplicate of https://github.com/vuejs/vue-loader/issues/1433

**Closed by posva** 2018-12-21 14:10 UTC

**Comment by brophdawg11** [comment] 2018-12-22 12:51
Ah great, apologies for not catching the dup ahead of time.  Thanks!
