### ISSUE TITLE
Possible incompability with Vue Router or Vuex since v2.1.5

### ISSUE THREAD

**Issue by MrSlide** [vuejs/vue#4501] opened 2016-12-16 15:12 UTC
### Vue.js version
2.1.5 and 2.1.6

### Reproduction
https://github.com/MrSlide/vue-blank-page-issue-example

### Steps to reproduce
I have a Vue + Vuex + Vue Router app, using Webpack 2 and Vue Loader to bundle and precompile the code. I set up my project in a similar way to the HackerNews example provided, but instead of resolving the app on the server side as soon as a route is matched, I resolve it after a route is entered, so that route guards can be used properly. I began building it with v2.1.3 and everything was working on v2.1.4 too.

### What is Expected?
The app renders on the server, and when on the browser everything looks the same as the content rendered on the server.

### What is actually happening?
The app is rendered correctly on the server, and for a fraction of a second the app can actually be seen on the browser sometimes, but immediately becomes empty. There is only a blank screen and the element the app is mounted onto is has no children.

**Comment by LinusBorg** [comment] 2016-12-16 15:48
It will be hard to help you without a reproduction of the issue....

**Comment by MrSlide** [comment] 2016-12-19 11:38
I created a repo that reproduces the problem:
https://github.com/MrSlide/vue-blank-page-issue-example

It's a stripped down version of the project I'm working on. Again, everything works on 2.1.4, but starting on 2.1.5, the page renders server side, but then on client side it goes blank.

**Comment by MrSlide** [comment] 2016-12-19 11:53
After digging a bit further and trying to further strip down the example, I found that removing the component `<progress-spinner>` from the `app` view allows the page to display on the client, but I can't figure out why. I tried removing the transitions from the component, but that didn't change anything. I also tried to use a boolean explicitly instead of a value from the store to display the component, but that didn't seem to fix it either. Removing the component was really the only thing that seemed to fix it.

**Comment by MrSlide** [comment] 2016-12-19 11:58
Simply moving `<progress-spinner>` above the `<transition>` tag in `app.html` seems to also fix the problem for some reason.

**Comment by yyx990803** [comment] 2016-12-24 04:04
So, after some investigation, here's what I've found:

The hydration fails not because of the spinner, but due to the fact that the server-rendered markup is from the state of **after route has been resolved**, but on the client the initial render happens before the route has been resolved. So during hydration, Vue finds an already rendered DOM element, but the corresponding `<router-view>` returns a placeholder node because the route hasn't been resolved yet. This is going to be a mismatch regardless of version - in fact there's the same warning when using 2.1.4 (causing a full re-render), so I don't really consider it "working properly" in 2.1.4...

I'd say this is not really a bug, but a current limitation that makes SSR doesn't play nicely with async route hooks. Definitely something we can improve though. The solution would be something similar to #4506 - we will probably expand on that to make it support `<router-view>` placeholders as well.

**Comment by MrSlide** [comment] 2016-12-24 10:40
Yeah that warning was there regardless of version, also because some of the stuff relies on browser only features, so the SSR version and the client version would always differ a bit.

But still, the problem remains that once I upgrade to 2.1.5 the page renders blank on the client side, when it would render correctly on 2.1.4. And why would changing the placement of the `progress-spinner` tag affect if the page renders blank or correctly? This deffo seems like a bug. Changing the order of the component placement should not affect how or even if a page renders or not.

**Comment by yyx990803** [comment] 2016-12-24 15:45
Well, in general we can't guarantee behavior after there is a warning. Warnings usually mean something is wrong or will go wrong.

Did some further investigation and there's in fact a simple solution: since the resolved route state is already in the store, you can simply force the client-side router to boot with the resolved route by doing this:

``` js
if (window.__INITIAL_STATE__) {
  store.replaceState(window.__INITIAL_STATE__)
  // force client-side router to boot with server-resolved route
  router.history.updateRoute(router.resolve(store.state.route.fullPath).resolved)
}
```

Note this would cause all before route hooks to be skipped on the client - however, if all side effects in those hooks are reflected in the store state, this should not be a problem.

Closing this for now, but we will see if we can make it easier to work with async route hooks in SSR.

**Closed by yyx990803** 2016-12-24 15:45 UTC
Labels: 2.1, improvement
