### ISSUE TITLE
Empty String value passed to  Boolean prop isn't mapped to false 

### ISSUE THREAD

**Issue by wparad** [vuejs/vue#10855] opened 2019-11-22 14:30 UTC
### Version
2.6.10

### Reproduction link
[https://github.com/MKRazz/vue-boolean-prop-issue](https://github.com/MKRazz/vue-boolean-prop-issue)

### Steps to reproduce
1. Create a component with a boolean property, pass the value of empty string to that property.
2. Render the value, shows as empty string, rather than false

### What is expected?
Since the property is set to type boolean the result to should be treated as such.

### What is actually happening?
Components which have a boolean property aren't able to assert that it is actually a boolean.

---
I know there is already https://github.com/vuejs/vue/issues/4710, which was answered. And I can partially agree with that, however this case is slightly different:
* Consider dynamic bindings `:prop="''"` instead of `prop=""`
* Every implementer of vue would need to explicitly coerce the input to a boolean to prevent propagating this problem.
* I want to make sure that the data in vue isn't blindly being passed to the html element, and we need to fix this somewhere.

**Comment by posva** [comment] 2019-11-22 18:49
Duplicate of https://github.com/vuejs/vue/issues/4710

**Closed by posva** 2019-11-22 18:49 UTC
