### ISSUE TITLE
Vue does not check if ob is defined.

### ISSUE THREAD

**Issue by truefusion** [vuejs/vue#12042] opened 2021-04-28 12:55 UTC
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/cdzos023/](https://jsfiddle.net/cdzos023/)

### Steps to reproduce
See fiddle.

---
Since upgrading to Vue 3 is not currently a viable option, I perform a small hack to make my class (which is a subclass of Array) reactive while maintaining its identity. This, however, results in an error when I try to call `sort` on it.

A simple fix could be checking if `ob` is defined before attempting to access any of its members.
https://github.com/vuejs/vue/blob/e7cf0634f59d0edd472c48792e371b91a8c55af7/src/core/observer/array.js#L40
https://github.com/vuejs/vue/blob/e7cf0634f59d0edd472c48792e371b91a8c55af7/src/core/observer/array.js#L42

**Comment by posva** [comment] 2021-04-28 13:51
Duplicate of https://github.com/vuejs/vue/issues/9259

**Closed by posva** 2021-04-28 13:51 UTC

**Comment by truefusion** [comment] 2021-04-29 00:19
I can understand why this would be considered a duplicate of #9259, but the solution differs in extremity. I'm not asking to rewrite Vue 2. A simple if statement would overcome my issue.
