### ISSUE TITLE
Error handling in async watcher

### ISSUE THREAD

**Issue by rightaway** [vuejs/vue#10076] opened 2019-05-28 11:56 UTC
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/anrzf5uh/](https://jsfiddle.net/anrzf5uh/)

### Steps to reproduce
Enter 'obj' in the text input and nothing gets printed to console. Enter `str` in the text input and `uncaught exception: message` gets printed to console. But it's wrong in both cases.

If you remove `async` from the watch method and the call to the `await` method, then it works properly.

Enter 'obj' in the text input and `Object { error: "message" }` gets printed to console. Enter `str` in the text input and `message` gets printed to console. It's right in both cases.

### What is expected?
Error handling should work the same in an async watcher as in a sync watcher.

### What is actually happening?
Error handling works correctly in a sync watcher but not async watcher.

**Comment by posva** [comment] 2019-05-28 12:12
Duplicate of https://github.com/vuejs/vue/issues/10009

**Closed by posva** 2019-05-28 12:12 UTC
