### ISSUE TITLE
memory leaks of server-side-render in vue 2.4.2 

### ISSUE THREAD

**Issue by dreamzhu** [vuejs/vue#6479] opened 2017-08-30 08:40 UTC
### Version
2.4.2

### Reproduction link
[https://github.com/dreamzhu/vue-hackernews-2.0.git](https://github.com/dreamzhu/vue-hackernews-2.0.git)

### Steps to reproduce
1.  npm start
2. memory leaks in server side while visiting  localhost:8080/index

### What is expected?
no memory leak 

### What is actually happening?
memory leak 

---
It's caused by Vue.use,   _installedPlugins can't be release.

**Comment by HerringtonDarkholme** [comment] 2017-08-30 09:56
Hi. I would rather argue this isn't a leakage, or this is an expected leakage.

`Vue.use` installs plugins to the global `Vue` constructor. Using plugins dynamically isn't recommended. It is better to install plugin in entry point. In your case, `runInNewContext: true` will re-evaluate your component code for every request. But `Vue` is a node module file so it will be a persistent object on heap. So your plugins will repeatedly be applied to one same Vue.  Thus using more memory.

Even if we removed `_installedPlugins`, leakage can still happen. Consider, if a plugin itself maintain some objects and assign to `Vue` constructor.

That said, my recommendation is:
1. maintaining _installedPlugins won't use much memory if used correctly.
2. Don't apply plugin dynamically. Use plugin in entry point.
3. Consider using `runInNewContext: 'once'`

**Comment by dreamzhu** [comment] 2017-08-31 03:05
@HerringtonDarkholme 

Thanks for your advice.
The demo may be a bit misleading to you, the demo is to say how to reproduce the problem.

Now the real problem is in the case of runInNewContext: true, even using plugins in entry point, there will be memory leaks. As long as the plugins build into the server bundle, but vue is the use of node module, there will be this problem, vue official did't say that the plugins in server must be defined as node module.

We also  consider changing to runInNewContext: 'once', but think this case of memory leak is problematic, hope vue can repair it.

**Comment by HerringtonDarkholme** [comment] 2017-08-31 06:13
As we can see in the code 

https://github.com/vuejs/vue/blob/049f3171a9d2e97f62c209a4b78a71ec9dae810f/src/core/global-api/use.js#L7

`_installedPlugin` is indeed used. So we cannot release it. It is not a leakage. 

The problem is, sadly, runInNewContext: true. Every new request will create a new plugin object. So we will have many copies of one plugin. :( 

IMHO we should deprecate `runInNewContext: true` .

**Comment by yyx990803** [comment] 2017-09-01 20:30
Note: this is not a bug in Vue, it's just that **the way you are registering plugins is guaranteed to cause a leak with `runInNewContext: true`**. There's no way for us to fix it, it's more important to understand what `runInNewContext: true` does and thus avoid certain patterns using it; or simply understand why you probably should **not** use it.

**Closed by yyx990803** 2017-09-01 20:30 UTC
