### ISSUE TITLE
Vue 1.0.18 版以上组件的data方法会执行2次？

### ISSUE THREAD

**Issue by Yusoo** [vuejs/vue#2713] opened 2016-04-23 07:42 UTC
```
<div id="test">
    {{ message }}
    <my-component></my-component>
</div>

<script>
    var MyComponent = Vue.extend({
        template: '<div>A custom component!</div>',
        data: function () {
            console.log('data');
            return { a: 1 }
        }
    });
    new Vue({
        el: '#test',
        data: {
            message: 'Hello Vue.js!'
        },
        components: {
            'my-component': MyComponent
        }
    });
</script>
```
这里面console.log('data');会执行2次，用1.0.18版本以下则不会，怎么回事呢？

**Comment by posva** [comment] 2016-04-23 08:59
Hello, thanks for reporting the issue.
This is a duplicate of #2687 . It was already fixed and will be release in next Vue version.
The patch is on #2689 in case you need it 😄

**Closed by posva** 2016-04-23 08:59 UTC
