### ISSUE TITLE
form fileds reset on page refresh not working in IE /EDGE 

### ISSUE THREAD

**Issue by sandipbiswasbehala** [vuejs/vue#11393] opened 2020-05-14 03:24 UTC
### Version
2.6.11

### Reproduction link
[https://vuejs.org/v2/guide/forms.html](https://vuejs.org/v2/guide/forms.html)

### Steps to reproduce
fill textbox, checkbox, select etc.

### What is expected?
field reset on page refresh in IE/Edge

### What is actually happening?
html components are retaining the previous  selection where data is refreshed on page refresh in IE /Edge.

**Comment by posva** [comment] 2020-05-14 09:29
Duplicate of https://github.com/vuejs/vue/issues/11182 and https://github.com/vuejs/vue/issues/11165

**Closed by posva** 2020-05-14 09:29 UTC

**Comment by sandipbiswasbehala** [comment] 2020-05-14 09:41
This issue is not duplicate. I am talking about IE/ Edge. 

https://vuejs.org/v2/guide/forms.html 
Working fine in chrome.But same page is holding previously selected/ typed value on page refresh in IE /EDGE. And this is the case with Vue. Same kind of example made with react / angular / backbone js / plain js / jquery --- all are working and resetting form values in IE/ Edge.  It seems that vue is bot compatible for IE/Edge. And I have found that vue throw error when we try to generate 1lacs row in a component. 


Instead of blindly close any issue, try to give soln after properly reading it . I have seen many comments of yours including Evan You. You guys are ready to accept any criticism about vue.  There is scope of improvement . Pls accept it.
