### ISSUE TITLE
this.$data.{my_attribute} return null in @v1.0.24

### ISSUE THREAD

**Issue by mkante** [vuejs/vue#2960] opened 2016-05-26 20:51 UTC
So I had a Vue with this code
```
export default {
  data: function() {
    return {
        number: "13"
    }
  },

  compiled: function() {
    var value = this.$data.number // use to return 13
    // Now it's returning null
    // Then I try "this.number". Still doesn't work
  }
}
```
To work around this. I set my vue version to v1.0.8

**Comment by simplesmiler** [comment] 2016-05-26 21:02
Hello!

Thanks for reporting the issue. Please follow the Issue Reporting Guidelines and provide a minimal [JSFiddle](https://jsfiddle.net/simplesmiler/Lrk9sxjf/) demonstrating the issue.

**Comment by mkante** [comment] 2016-05-26 21:06
Ho my bad. My release is on fire now. I will do it ASAP

**Comment by simplesmiler** [comment] 2016-05-26 21:11
Probably a typo somewhere. Put a `debugger` in `compiled` hook, and see what's available on `this`.

**Comment by LinusBorg** [comment] 2016-06-01 11:47
Since there was not reproduction provided within a week, we assume this issue needs no further investigatio and close it.

If there is still a problem, please provide a reproduction and we will re-open the issue.

**Closed by LinusBorg** 2016-06-01 11:47 UTC
Labels: need repro
