### ISSUE TITLE
Click <form> 'reset' button, the v-model has no change

### ISSUE THREAD

**Issue by k55k32** [vuejs/vue#4683] opened 2017-01-10 06:55 UTC
when I click the `reset`, the input value was empty. 
but the v-model `message` still was old value. 
Code here: 
https://jsfiddle.net/50wL7mdz/9404/

**Comment by phanan** [comment] 2017-01-10 06:58
Duplicate of #833

**Closed by phanan** 2017-01-10 06:58 UTC
