### ISSUE TITLE
GeoJSON Object

### ISSUE THREAD

**Issue by xereda** [vuejs/vue#4081] opened 2016-11-01 12:28 UTC
### Vue.js version
2.0.3

### Reproduction Link
 https://jsfiddle.net/xereda/zbt6sn1h/42/

### Steps to reproduce
Change the values for latitude and longitude. No reactivity.

### What is Expected?
The Geolocation fields update the data object.

### What is actually happening?
The array that deals with geolocation information (MongoDB GeoJSON Object) are not reactive.

Note the following example:

`  	local: {
    	name: 'Empresa XYZ',
      address: 'Rua Fulano da Veiga, 888',
      number: 9888,
      geoLocation: {
      	coordinates: [
        	65.234902,
          75.349902
        ],
        type: 'Pointer'
      }
    }`

The only fields that are not reactives are based on the internal array of the Geolocation object. Note this:

<form>
    Nome: <input type="text" v-model="local['name']"><br>
    Endereço: <input type="text" v-model="local['address']"><br>
    Número: <input type="number" v-model="local['number']"><br>
    Geolocalização (long): <input type="text" v-model="local['geoLocation'].coordinates[0]"><br>
    Geolocalização (lat): <input type="text" v-model="local['geoLocation'].coordinates[1]"><br>
    Geolocalização (type): <input type="text" v-model="local['geoLocation'].type"><br>
  </form>

**Comment by sqal** [comment] 2016-11-01 12:52
Check this PR https://github.com/vuejs/vue/pull/3988 I think it's the same issue

**Comment by yyx990803** [comment] 2016-11-01 13:09
This is not related to GeoJSON but a duplicate of #3958 & #3979, fixed by #3988 and will be out in 2.0.4.

**Closed by yyx990803** 2016-11-01 13:09 UTC

**Comment by xereda** [comment] 2016-11-01 13:27
https://jsfiddle.net/zbt6sn1h/54/
