### ISSUE TITLE
Template Tags Being Stripped

### ISSUE THREAD

**Issue by Daeluse** [vuejs/vue#11292] opened 2020-04-07 17:14 UTC
### Version
2.6.11

### Reproduction link
[https://stackblitz.com/edit/vuejs-template-issue](https://stackblitz.com/edit/vuejs-template-issue)

### Steps to reproduce
Using the minimal reproduction link:

1. Visit the minimal reproduction link
2. Inspect the document under both "Template Content" headers. 
    - Notice that under the first header the template tags are being stripped.
    - Notice that under the second header the template tags are being preserved.

To re-create this in a sandbox of your own, you can perform the following:

1. Create a block level element with the v-pre directive and place template tags a children.
    - Observe the template tags being removed.
2. Add any VueJS compiled element as a sibling to the block level element with v-pre.
    - Observe the template tags are being preserved. 

### What is expected?
In both cases the presence of v-pre should instruct Vue not to remove the template tags.

### What is actually happening?
v-pre is only preserving the template tags when a VueJS compiled element is sibling to the element with the v-pre tag.

---
I am working on integrating Web Components into VueJS applications and would like to leverage the power of the Shadow DOM.

**Comment by posva** [comment] 2020-04-07 19:21
Duplicate of https://github.com/vuejs/vue/issues/10717

**Closed by posva** 2020-04-07 19:21 UTC
