### ISSUE TITLE
allow await value in Template

### ISSUE THREAD

**Issue by zhangenming** [vuejs/vue#10270] opened 2019-07-15 03:22 UTC
### What problem does this feature solve?
```
So far  a hack such as
<template>
{{foo}}
</template>

//js
var promise = new Promise(s=>setTimeout(s(1)))
{
    data:{foo:''},
    computed:{
        async bar(){
            return await promise
        }
    },
    watch:{
        async bar(){
            this.foo = await bar
        }
    }
}


```

### What does the proposed API look like?
```
<template>
{{await foo}}
</template>

//js
var promise = new Promise(s=>setTimeout(s(1)))
{
    computed:{
        async foo(){
            return await promise
        }
    },
}


```

**Comment by zhangenming** [comment] 2019-07-15 03:25
find duplicate issue https://github.com/vuejs/vue/issues/4083
so will consider it achieve in vue 3+ ?

**Comment by posva** [comment] 2019-07-15 07:20
Duplicate of https://github.com/vuejs/vue/issues/7520

**Closed by posva** 2019-07-15 07:20 UTC
