### ISSUE TITLE
Non-string 'value' prop is stringified on custom element

### ISSUE THREAD

**Issue by zengguirong** [vuejs/vue#12369] opened 2021-11-30 03:56 UTC
### Version
2.6.14

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/gallant-feather-wxyot?file=/src/my-element.js)

### Steps to reproduce
View the codesandbox render result

### What is expected?
The custom element render the json content

### What is actually happening?
The custom element render "[object Object]"

---
Accorading to source code:
https://github.com/vuejs/vue/blob/0603ff695d2f41286239298210113cbe2b209e28/src/platforms/web/runtime/modules/dom-props.js#L49
, any prop name 'value' on dom element will be stringified, but when using custom elements, the 'value' prop may be an object or number and it should not be stringified.

**Comment by posva** [comment] 2021-11-30 08:36
Duplicate of https://github.com/vuejs/vue/issues/10255

**Closed by posva** 2021-11-30 08:36 UTC
