### ISSUE TITLE
Scoped css data attribute is not always applied

### ISSUE THREAD

**Issue by Demivan** [vuejs/vue#10452] opened 2019-08-29 11:48 UTC
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/embed/vue-template-3pnsx](https://codesandbox.io/embed/vue-template-3pnsx)

### Steps to reproduce
Click "toggle loading" button

### What is expected?
Both child elements should have data attribute applied and should be green.

### What is actually happening?
First child element is missing data attribute

---
Looks like div element is reused between loader and first child of the slot content

**Comment by posva** [comment] 2019-08-29 11:51
Duplicate of https://github.com/vuejs/vue/issues/10416

**Closed by posva** 2019-08-29 11:51 UTC
