### ISSUE TITLE
Event modifiers do not pass additional arguments

### ISSUE THREAD

**Issue by Soviut** [vuejs/vue#11686] opened 2020-09-28 05:11 UTC
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/Soviut/0nmfpz9h/4/](https://jsfiddle.net/Soviut/0nmfpz9h/4/)

### Steps to reproduce
- Note the component emits an $event along with an extra argument string
- Click the "no prevent" button
- Note that the message is passed and is displayed
- Click the "has prevent" button
- Note that the message is undefined and clears the display

Both buttons also log to the console for more detailed output.

### What is expected?
Additional arguments would be passed when event modifiers are used.

### What is actually happening?
Additional arguments are being ignored/removed.

**Comment by posva** [comment] 2020-09-28 09:20
Duplicate of https://github.com/vuejs/vue/issues/10867

**Closed by posva** 2020-09-28 09:20 UTC
