### ISSUE TITLE
Memory leak (DOM) when use select element

### ISSUE THREAD

**Issue by gr8den** [vuejs/vue#10048] opened 2019-05-18 14:07 UTC
### Version
2.6.10

### Reproduction link
[https://github.com/gr8den/vue-select-memory-leak/blob/master/vue-select-memory-leak.html](https://github.com/gr8den/vue-select-memory-leak/blob/master/vue-select-memory-leak.html)

### Steps to reproduce
1. Open vue-select-memory-leak.html from repo (I use Google Chrome 74.0.3729.157)
2. Open Chrome DevTools on this page
3. Go to page Performance, enable Memory checkbox
4. Start Record, click Collect garbage
5. Click Toggle button multiple times (I clicking 50 seconds, multiple times in second)
6. Click Collect garbage, click Stop record
7. See nodes leak on Memory chart - count of nodes not decreased after Collecting garbage (in my case nodes increased from 50 to ~2500)

### What is expected?
No memory leak - Count of nodes must be decrease after force collect garbage

### What is actually happening?
Have memory leak (DOM)

---
I try replace "select" element to "input" element and after it DOM nodes cleaned right (no leak). Also I try add 10000 options to select, browser still not clean nodes, but use a lot of RAM

**Comment by posva** [comment] 2019-05-18 14:12
Duplicate of https://github.com/vuejs/vue/issues/9823

**Closed by posva** 2019-05-18 14:12 UTC
