### ISSUE TITLE
Boolean attribute negation

### ISSUE THREAD

**Issue by pedro-gilmora** [vuejs/vue#12086] opened 2021-05-20 13:53 UTC
### What problem does this feature solve?
Actually we use `:bool-prop="false"`. What would be the chances of implementing `!bool-prop`?

### What does the proposed API look like?
Instead of 
```js
<button :ripple="false">Download</button>
```
Would be

```js
<button !ripple>Download</button>
```
Think of several props in the same element.

**Comment by Justineo** [comment] 2021-05-20 14:39
Duplicate of #8549 and #11562

**Closed by Justineo** 2021-05-20 14:39 UTC
