### ISSUE TITLE
Simple nested scoped slot

### ISSUE THREAD

**Issue by SerikDM** [vuejs/vue#7464] opened 2018-01-17 08:03 UTC
### What problem does this feature solve?
Provide slot for grandchildren

### What does the proposed API look like?
For example I have components Parent > GroupedList > SimpleList.
I want to provide slot from Parent to SimpleList

Currently I have to write in GroupedList like this:

```vue
<template slot="item" slot-scope="{ itemData }">
    <slot name="item" :itemData="itemData"></slot>
</template>
```

Simple way(which doesn't work):

```vue
<slot name="item" :itemData="itemData"  slot="item" slot-scope="{ itemData }"></slot>
```

Or just like:

```vue
<slot name="item" slot="item"></slot>
```

**Comment by HerringtonDarkholme** [comment] 2018-01-17 09:39
Possible duplicate of https://github.com/vuejs/vue/issues/7178

**Comment by posva** [comment] 2018-01-17 10:31
Are you asking for a way to do [this](http://jsfiddle.net/86xaa8n6/) using templates?

**Comment by SerikDM** [comment] 2018-01-17 10:41
I'm looking for a way to do [this](http://jsfiddle.net/86xaa8n6/1/) (and it doesn't work)
As you see slot template is in Parent, but slot data(number) is in GrandChild

**Comment by posva** [comment] 2018-01-17 10:45
You simply need to repeat the pattern used in `Parent` 😄 : http://jsfiddle.net/7zLxjzga/

**Comment by SerikDM** [comment] 2018-01-17 10:53
Is there a way to do this via templates?

**Comment by posva** [comment] 2018-01-17 11:29
Nope, at least for the moment

Closing as duplicate of #7178

**Closed by posva** 2018-01-17 11:29 UTC
