### ISSUE TITLE
In ios 9.2，touch[start|move|end] don't trigger at some time

### ISSUE THREAD

**Issue by zhiqinyigu** [vuejs/vue#11272] opened 2020-04-02 10:55 UTC
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/rdjjpc7a/2080/](https://jsfiddle.net/rdjjpc7a/2080/)
The Link to minimal reproduction was forged by me,  please take some time to read my description.

### Steps to reproduce
The premise is that you have an iPhone with the system version IOS9.
The Steps to reproduce seem to be a nested amount of custom components.

The problem happened in 2.6.x. I had discovered this problem a year ago. Since I couldn't provide a minimal reproduction at the time (and it is now), I have been rolling back to 2.5.x until now.

But I now find the source of the problem in the source code.
https://github.com/vuejs/vue/blob/v2.6.11/src/platforms/web/runtime/modules/events.js#L69.

In IOS9, Condition "e.timeStamp >= attachedTimestamp" is never holds.
```javascript
console.log(e.timeStamp, attachedTimestamp); // In IOS9, eg: 1585822331076 1585824221635
```

You can compare 2.5.x to solve this problem.

### What is expected?
touch event trigger

### What is actually happening?
events of the touch series are not triggered

---

Only happened in 2.6.x,  only events of the touch series

**Comment by posva** [comment] 2020-04-02 11:13
Seems like a duplicate of https://github.com/vuejs/vue/issues/10964 and https://github.com/vuejs/vue/issues/11014

**Closed by posva** 2020-04-02 11:13 UTC
