### ISSUE TITLE
infinite recursive listener.fn object from "function updateListeners"

### ISSUE THREAD

**Issue by lampard7824** [vuejs/vue#3588] opened 2016-09-02 14:37 UTC
Hi there, this is my first time reporting a issue in github  :p

I got the following error:
(Uncaught TypeError: o.fn.apply is not a function(anonymous function) @ vue.js?3de6:1574

I tried to trace the error and it seems it's caused by the updateListeners function @ vue.js line 1548.
I suspect that there's a mistake made in line 1548, setting
`   old.fn = cur`

this cause the listener.fn having infinite recursive object.

![image](https://cloud.githubusercontent.com/assets/4320720/18207880/a6f43bf2-715f-11e6-82e7-0a31368237e7.png)

### Vue.js version
2.0.0-rc.4

### Reproduction Link
i am in the midst of writing a complicated set of form components and came across this bug after latest rc4 update.
I am not sure how to reproduce... really sorry about that

**Comment by fnlctrl** [comment] 2016-09-02 15:15
Please try removing any extra code that doesn't cause the bug to the minimum, and use that minimum code to [create a fiddle](https://jsfiddle.net/)

**Comment by yyx990803** [comment] 2016-09-02 16:06
Most likely a duplicate of #3556 (and fixed). I'll close this for now.

**Closed by yyx990803** 2016-09-02 16:06 UTC
Labels: need repro
