### ISSUE TITLE
Property injection in functional component does not work

### ISSUE THREAD

**Issue by misq007** [vuejs/vue#9570] opened 2019-02-25 13:00 UTC
### Version
2.6.7

### Reproduction link
[https://jsfiddle.net/misq007/a5wth0rf/39/](https://jsfiddle.net/misq007/a5wth0rf/39/)

### Steps to reproduce
the error will popup

### What is expected?
Provide/Inject to work properly for the first level component in the same way as it is working when nested.

### What is actually happening?
Injection "mode" not found

**Comment by posva** [comment] 2019-02-25 13:07
Duplicate of #5837

**Closed by posva** 2019-02-25 13:07 UTC
