### ISSUE TITLE
v-bind="$attrs" or v-on="$listeners" cause performance problem 

### ISSUE THREAD

**Issue by yywc** [vuejs/vue#11508] opened 2020-07-11 09:21 UTC
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/pvzkc51t/4/](https://jsfiddle.net/pvzkc51t/4/)

### Steps to reproduce
1. open the jsfiddle.
2. wait page loaded.
3. input some charactor in <input> element.
4. see the console.

### What is expected?
nothing in console.

### What is actually happening?
"Why should I update" outputs in console.

---
$attrs and $listeners appeared to reduce workload.
But they occur with form element will cause component update catastrophically.
Event though nothing change in $attrs.

**Comment by posva** [comment] 2020-07-11 17:05
Duplicate of https://github.com/vuejs/vue/issues/7257

**Closed by posva** 2020-07-11 17:05 UTC
