### ISSUE TITLE
props in the data of a vnode will not be resolved into the $attrs of the component instance of the vnode

### ISSUE THREAD

**Issue by AllenField** [vuejs/vue#10172] opened 2019-06-20 11:04 UTC
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/fubai7/a2znbx94/](https://jsfiddle.net/fubai7/a2znbx94/)

### Steps to reproduce
```
Vue.component('test', {
  inheritAttrs: false,
  template: '<div>{{$attrs.content}}</div>'
})

Vue.component('container0', {
  template: '<test content="container0"></test>'
})

Vue.component('container1', {
  render (h) {
    return h('test', {
      props: {
        content: 'container1'
      }
    })
  }
})

Vue.component('container2', {
  render (h) {
    return h('test', {
      attrs: {
        content: 'container2'
      }
    })
  }
})

new Vue({
  el: '#app'
})
```

### What is expected?
props in the data of a vnode will be resolved into the $attrs of the component instance of the vnode

### What is actually happening?
props in the data of a vnode will not be resolved into the $attrs of the component instance of the vnode

**Comment by zrh122** [comment] 2019-06-20 19:51
The props of the component is extracted from `vnode.data.props` and `vnode.data.attrs`, after extracted (some data in `data.attrs` may be deleted according to component props you have defined) the `data.attrs` will be assigned to the $attrs in the component instance. @AllenField

**Comment by KaelWD** [comment] 2019-06-21 07:40
I'd call that working as intended, otherwise props is just an alias for attrs.

**Comment by posva** [comment] 2019-06-22 19:09
As mentioned, this is working as intended

**Closed by posva** 2019-06-22 19:09 UTC
