### ISSUE TITLE
Evaluation of slot content's context is inconsistent with "slot-scope" behavior.

### ISSUE THREAD

**Issue by dasdeck** [vuejs/vue#7856] opened 2018-03-19 12:48 UTC
### Version
2.5.16

### Reproduction link
[https://codepen.io/dasdeck/pen/LdbqLL?editors=0001](https://codepen.io/dasdeck/pen/LdbqLL?editors=0001)

### Steps to reproduce
When you open the pen, a message box will get opened because the full context of Consumer1 gets evaluated.
Since the slot is not shown, this evaluation is unnecessary at this point and negates optimizations.
When one declares a slot-scope, like in the Consumer2 components, Vue shows the "correct" behavior.

### What is expected?
The slotted context should evaluate in a lazy manner

### What is actually happening?
The slotted context gets evaluate right away.

**Comment by LinusBorg** [comment] 2018-03-20 12:14
I see you point, but that would be a huge breaking change, so it would have to wait until Vue 3, which is a long time away.

**Comment by LinusBorg** [comment] 2018-03-20 12:16
Thining out loud: On the other hand, we *could* maybe transform the $slots object in a way that replaces the propertys like `$slots.default` with a getter that lazily evaluates to the vnodes?

**Comment by dasdeck** [comment] 2018-03-20 12:30
Hmm. are we talking about the same? I could not find the current behavior defined inside the api. Maybe I'm wrong. I don't see why anyone would rely on expressions being evaluated when the result is discarded anyways? Or are you saying the possible solution you are thinking of breaks changes? Why can't you just use the behavior of the latter example and extrapolate it? Ah, ok, people might want to access the content from inside the component that defines the slot. This is what you are referring to right? How is this evaluated differently when using slot scopes? I'll have a look at the code....

**Comment by dasdeck** [comment] 2018-03-20 13:09
Maybe a compromise would be to add s `lazy` attribute that internally just acts as if a slot scope is defined? Or just allow the usage of the `slot-scope` attribute without an actual value assignment?
That would not break anything, costs a line of code and opens up some room for DOM optimisations using slot.

**Comment by LinusBorg** [comment] 2018-03-20 15:51
> Hmm. are we talking about the same? I could not find the current behavior defined inside the api. Maybe I'm wrong. I don't see why anyone would rely on expressions being evaluated when the result is discarded anyways?

My point is this: In your example, the render function resulting from the template looks roughly like this:
```javascript
render(h) {
  return h('div', [
    // skipping the unrelated textnode
    h('container1', this.contentText)
])
}
```
The `contentText` compued prop is evaluated in the *parent* in order to generate the vnodes that are *available* through `this.$slots.default` in the child component.

The current publi API guarantees that `this.$slot.default` returns an array of VNodes if any content was passed to the default slot in the parent, which is why the vnodes are already generated in the parent.

Skipping this evaluation in the parent would require something *like* scoped slots, namely wrapping the code that generates the scope's vnodes in some kind of function which we would pass down to the child:
```html
//pseudocode:
function lazyDefaultSlot () {
 return [h('container1', this.contentText)]
}
```
...but according to the public API,  `this.$slots.default` doesn't return a function, it returns an array of vnodes.

So we would have to find a way to evaluate this function when someone accesses ``this.$slots.default` to keep the API consistent and return an array of vnodes.

My initial gut reaction was to replace e,.g. the `default` prop on `this.$slots` with a [getter](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Functions/get) to allow us to evaluate that function when the `default` property is accessed.

That's no more than a gut reaction, though.

**Comment by dasdeck** [comment] 2018-03-21 10:00
Already got it, but thanks a lot for your in depth explanation! Using a getter sounds good to me!
Don't you have tests that define the API? So if it passes the current tests, it would be good to go?
Anyways! We have another solution for our case, so it is really not a pressing issue at all.

Keep up the good work!

Cheers!

**Comment by sebastiandedeyne** [comment] 2018-03-23 13:28
I'd really like to see this in Vue, not for performance reasons but because it would allow us to conditionally render things with slots. I can provide concrete use cases if interested.

This is currently only possible with scoped slots. However, you can't declare a scoped slot without a slot-scope so this isn't a plausible solution when you don't have any props to pass to the slot.

**Comment by LinusBorg** [comment] 2018-03-23 15:53
I don't see how conditional rendering is not possible? 

Well yeah, the vnodes are created by the parent no matter what, but that is the part of the equation (performance) which you set aside, so I don't think that's your point?

**Comment by sebastiandedeyne** [comment] 2018-03-23 16:55
I was playing around with the idea of using slots to conditionally render templates if some state is available in my application.

Consider the following component

```vue
<!-- IfLoggedIn.vue -->

<template>
    <div v-if="user">
        <slot></slot>
    </div>
</template>

<script>
export default {
    computed: {
        user() {
            return this.$store.state.user;
        },
    },
};
</script>
```

We could use this to remove all `if (this.user)` conditionals in the child component, because it will only render if `user` is available.

```vue
<template>
    <if-logged-in>
        <h1>{{ userName }}</h1>
    </if-logged-in>
</template>

<script>
export default {
    computed: {
        user() {
            return this.$store.state.user;
        },

        userName() {
            // No need to check if `user` exists here, because we guarded 
            // execution with `if-logged-in`
            return `${this.$store.state.user.firstName} ${this.$store.state.user.lastName}`;
        },
    },
};
</script>
```

This _is_ possible with scoped slots, but currently scoped slots can only exist if you declare something in the `slot-scope` attribute.

**Comment by fenduru** [comment] 2018-04-12 20:46
@LinusBorg This is causing me issues in a use case similar to Portal - basically only slotScopes preserve reactivity when moving the slot to another location. See my comment [here](https://github.com/LinusBorg/portal-vue/issues/105#issuecomment-380937189) as well.

Isn't "making $slots.default a getter" essentially just saying "making $slots reactive"? Slots and refs not being reactive has always struck me as strange, since there isn't really much overhead and there is presumably already logic in Vue that causes a change in $slots.default to trigger a render (which would just happen naturally if $slots was reactive).

I do agree with the general idea that in the future there shouldn't be a distinction between scoped/unscoped slots - an unscoped slot is really just a scoped slot that is invoked once and passed no data. But yes this would be a breaking change. We could possibly have this be an option on the component like `slotsAlwaysScoped: true` (name pending) that would let us make the change in an opt in way.

If there is consensus from @LinusBorg / @yyx990803 on a general direction here I'm willing to work on a PR.

**Comment by yyx990803** [comment] 2018-08-20 21:39
Closing as the original issue is the expected behavior. Although it can theoretically be improved, this is not something that we will consider until 3.x because it will be technically breaking.

In 3.x, we will likely make all slots lazy-evaluated like scoped slots now.

**Closed by yyx990803** 2018-08-20 21:39 UTC
Labels: has PR, improvement
