### ISSUE TITLE
Render with contenteditable makes duplicated text

### ISSUE THREAD

**Issue by toshirin** [vuejs/vue#12496] opened 2022-03-08 06:19 UTC
### Version
2.6.14

### Reproduction link
[codepen.io](https://codepen.io/toshirin/pen/GROapeK)

### Steps to reproduce
1. Go to: https://codepen.io/toshirin/pen/GROapeK
2. Type something to text box.
3. Duplicated text appears.

It may happen when initial text is empty("").If there is some text in the initial text, it doesn't happen.

### What is expected?
No duplicated text is displayed.
Display the text same as I was typed.

### What is actually happening?
Duplicates text which was not typed by me is appeared.

---
In my investigation, I found updateChildren()'s addVnodes()(see below) causes this.
https://github.com/vuejs/vue/blob/dev/src/core/vdom/patch.js#L470
During the issue is occuring, the debbuger says:
```
oldCh=[];
newCh=[<vnode>]; (which includes typed text)
oldStartIdx=0;
oldEndIdx=-1;
```
So L468's condition `oldStartIdx > oldEndIdx` seem to be true.
But I don't know how I fix.

**Comment by anyanyan07** [comment] 2022-03-24 06:11
`

    Vue.component('edit_box', {
          data () {
            return {
              content: "",
            };
          },
          render: function (createElement) {
            return createElement(
              "div",
              {
                ref: "edit",
                class: [
                  "margin",
                  "edit_box"
                ],
                attrs: {
                  contenteditable: true
                },
                on: {
                  input: (event) => {
                    console.log(event.data)
                    this.content = event.target.innerText;
                  }
                }
              },
              // [
              //   this.content
              // ]
            );
          }
        });

`

**Comment by posva** [comment] 2022-03-24 08:20
Duplicate of https://github.com/vuejs/vue/issues/5805

**Closed by posva** 2022-03-24 08:20 UTC
