### ISSUE TITLE
IE11 下双向绑定失效，chrome正常

### ISSUE THREAD

**Issue by doocal** [vuejs/vue#7750] opened 2018-03-06 02:29 UTC
### Version
2.5.13

### Reproduction link
[https://doocal.github.io/demo/demo1](https://doocal.github.io/demo/demo1)

### Steps to reproduce
点击控件会有一个弹层，关闭弹层会有回调事件更新vue值。

IE11（版本：11.125.16299.0，更新版本：11.0.49(kb4052978)） 下如果控件有placeholder 属性(如果有默认值更新又正常的)， 弹窗回调后不能更新控件值，chrome正常。 
注：vue 2.3.0 没有此问题。

### What is expected?
可以在IE11下绑定值正常。

### What is actually happening?
IE11下无法正常绑定。

**Comment by posva** [comment] 2018-03-06 08:20
It looks like IE is triggering the focus **before** displaying the modal thus not reflecting any changes to the variable because it focuses it again when the modal is closed, just before you set the variables. You can probably work around this by blurring the input before creating the modal so the behaviour is consistent across all browsers.
Please, don't open issues with external libraries before checking the error doesn't come from there. If you have a demo with no external libraries that reproduces the problem I will be interested in checking it

**Closed by posva** 2018-03-06 08:20 UTC
