### ISSUE TITLE
Module Federation w/ vue-ssr

### ISSUE THREAD

**Issue by cubevision** [vuejs/vue#12466] opened 2022-02-11 10:47 UTC
### What problem does this feature solve?
Trying to build an SSR application w/ vue-ssr while using the somewhat newly introduced module federation plugin in webpack 5 (https://webpack.js.org/concepts/module-federation/) won't work currently. It does when focusing only on the client build but is not when trying to prerender. The webpack plugin is not working out of the box while building for node. In order to make this work, one can use a package from telenko (https://github.com/telenko/node-mf), which will hook into the process and allow for module federation to work in node. Nevertheless, due to the adjustments, namely relying on URL, vue-server-renderer will fail to build.

### What does the proposed API look like?
To make this work it basically only requires to add nodes URL to the sandboxed node environment.

```js
function createSandbox (context) {
  var sandbox = {
    Buffer: Buffer,
    URL: URL, // add URL
    console: console,
    process: process,
    setTimeout: setTimeout,
    setInterval: setInterval,
    setImmediate: setImmediate,
    clearTimeout: clearTimeout,
    clearInterval: clearInterval,
    clearImmediate: clearImmediate,
    __VUE_SSR_CONTEXT__: context
  };
  sandbox.global = sandbox;
  return sandbox
}
```

**Comment by posva** [comment] 2022-02-11 13:01
Duplicate of https://github.com/vuejs/vue/pull/10414

**Closed by posva** 2022-02-11 13:01 UTC
