### ISSUE TITLE
slot-scope support multiple parameters

### ISSUE THREAD

**Issue by tangjinzhou** [vuejs/vue#9468] opened 2019-02-10 07:42 UTC
### What problem does this feature solve?
slot-scope support multiple parameters in version 2.6.x.
It is supported in version 2.5.x.
If not supported, our component library([ant-design-vue](https://github.com/vueComponent/ant-design-vue)) has to change some API.

### What does the proposed API look like?
like 2.5.x
```html
<template slot="name" slot-scope="text, record, index..."></template>
```

**Comment by tangjinzhou** [comment] 2019-02-10 07:51
Maybe we can change this code 
https://github.com/vuejs/vue/blob/b2a093fa03704b2f0c6b2e9ee4d10b7ed156698d/src/core/vdom/helpers/normalize-scoped-slots.js#L46
to
```js
let res = fn(arguments.length ? ...arguments : {})
```

**Comment by posva** [comment] 2019-02-10 10:14
mmh, why did you preferred that syntax over the drestructuring one? Is it browser support without using a transpiler?

**Comment by tangjinzhou** [comment] 2019-02-10 13:28
@posva 
A transpiler is required to support this syntax.
I think this is not a problem, babel will solve this.
Of course, other ways are fine. I just prefer this syntax. It makes me write a lot less characters.

**Comment by Justineo** [comment] 2019-02-10 13:37
Since this is a [documented usage](https://vuejs.org/v2/api/#slot-scope-deprecated), I think this issue should be marked as a regression (I just did). And I created [a working sandbox](https://codesandbox.io/s/2p7on5np3r) for 2.5.22.

**Comment by yyx990803** [comment] 2019-02-11 03:17
I'm a bit torn on this. I will fix this because it worked in the past and I don't want to force you to re-design your API, but you really should avoid using this in the future, and possibly migrate away from it when you can.

The disadvantage compared to destructuring is:

1. It's impossible to pass parameters like this when using templates via `<slot foo="bar"/>`, and it's never been explicitly documented with an example - so it will confuse users who don't know about render functions.

2. Users have to use the arguments in fixed order and cannot omit the ones you don't need. e.g. if you have a slot that passes in 5 arguments but the user actually only need the last 2 of them, they will have  to declare all 5 just to use the last 2.

3. If you switch back and forth between the two styles of usage it creates more inconsistency.

**Closed** 2019-02-11 03:22 UTC
Labels: regression

**Comment by lirunwin** [comment] 2019-05-14 03:54
v-slot:[col.key]="text, record", and I really do not need 'text', text is in record object. and my editor is complaining
