### ISSUE TITLE
Deep JSON is cropped when assigning to data

### ISSUE THREAD

**Issue by buelsenfrucht** [vuejs/vue#6390] opened 2017-08-17 11:02 UTC
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/50wL7mdz/54386/](https://jsfiddle.net/50wL7mdz/54386/)

### Steps to reproduce
When Vue instance is created, I fetch JSON data that has a lot of data kind of deeply nested.

Structure is:
screens -> rooms -> { devices -> items, scenes -> items, sensors -> items }

Now when I fetch the data and parse it, everything is fine, but when I assign it to Vue data "this.screens" as a whole, then all items are gone, the rest is still there.

Fun thing is, that this assignment alters the response too, so not only "this.screens[1].rooms[0].devices.items" is empty but also "data.screens[1].rooms[0].devices.items".

### What is expected?
I expect that the whole JSON structure is saved in this.screens

### What is actually happening?
All items are gone.

**Comment by simplesmiler** [comment] 2017-08-17 11:15
Hello!

Your repro does not actually reproduce the issue, neither you provided the data you are trying to assign.
I've tried to infer the data from your description, but was unable to reproduce the issue: https://jsfiddle.net/50wL7mdz/54390/

I'm closing this, because it's likely that the issue is somewhere else. If you're able to provide a working repro, feel free to open a new issue.

**Closed by simplesmiler** 2017-08-17 11:15 UTC
