### ISSUE TITLE
Residual transition classes

### ISSUE THREAD

**Issue by narwajea** [vuejs/vue#4835] opened 2017-02-01 19:38 UTC
### Vue.js version
2.1.10

### Reproduction Link

http://jsfiddle.net/x5rtyd8a/1/

### Steps to reproduce
Open Chrome dev tools
Locate & open the `<ul>` element
Play around by focusing in the input, then focusing out, very quickly. Play with hover too.

### What is Expected?

The `<ul>` element is shown when both hide & hover are false.

Classes "expand-leave-to" and "expand-enter-to" should be removed when transition/animation finishes.

![image](https://cloud.githubusercontent.com/assets/1114091/22522550/38f26d8e-e8bc-11e6-9cf0-941b444fac66.png)

![image](https://cloud.githubusercontent.com/assets/1114091/22523177/b6726974-e8be-11e6-8b19-b970f960a364.png)

### What is actually happening?

The `<ul>` element is sometimes hidden (because of class "expand-leave-to": "max-height: 0;").

Classes "expand-leave-to" and "expand-enter-to" are not removed when transition/animation finishes.

![image](https://cloud.githubusercontent.com/assets/1114091/22522552/3cb94596-e8bc-11e6-9ab8-01c5e11151c5.png)

![image](https://cloud.githubusercontent.com/assets/1114091/22522531/2ca53084-e8bc-11e6-8a30-4097d30847fd.png)
![image](https://cloud.githubusercontent.com/assets/1114091/22522543/3328de60-e8bc-11e6-885f-a8649ba44b84.png)

**Comment by posva** [comment] 2017-02-02 09:30
> Locate & open the <ul> element
Play around by focusing in the input, then focusing out, very quickly. Play with hover too.

I _played_ around a bunch of times but couldn't reproduce the bug. Can you please be more specific on what to do?

**Comment by narwajea** [comment] 2017-02-02 09:55
I have updated the fiddle, and could identify the following steps to reproduce the bug:

1. focus in the input by clicking in it
2. focus out the input by clicking between the input and the `<div>` containing the `<ul>` element.
3. precisely at the end of the transition (just before the `<ul>` element finishes to disappear), move the mouse over it (so that hover becomes true)

It looks like the bug appears when the mouseover event is triggered (or processed ?) at the same time the transition/animation finishes (just guessing from the [documentation](https://vuejs.org/v2/guide/transitions.html#Transition-Classes)).

**Comment by posva** [comment] 2017-03-02 17:16
@narwajea Hey, sorry for the delay. I tried again and could reproduce with Vue 2.1 but it looks fixed with the last version of Vue, can you confirm?
You can paste `<script src="https://unpkg.com/vue"></script>` at the top of the html section and remove the existing external resource to check

**Comment by znck** [comment] 2017-03-20 16:06
Closing due to inactivity. Reopen if not fixed.

**Closed by znck** 2017-03-20 16:06 UTC
