### ISSUE TITLE
Inline statement event handler should be 'return'

### ISSUE THREAD

**Issue by tianjianchn** [vuejs/vue#8999] opened 2018-10-28 04:24 UTC
### What problem does this feature solve?
See `@click="doSomething('params')"`, the generated code will be `function($event){doSomething('params')}`, no return in it. Normal syntax with method name only has the return. So I think  consistent  may be better.  
And the use case is child component may want to manually call the event handler to get the result, not through `this.$emit`

### What does the proposed API look like?
No added api

**Comment by tianjianchn** [comment] 2018-10-28 04:29
@sirlancelot You are right. So I use `this.$listeners.click($event)`

**Comment by tianjianchn** [comment] 2018-10-28 04:38
@sirlancelot Maybe `$emit()` can return the result array if there are multiple handlers? Anyway, that's another topic😀

**Comment by posva** [comment] 2018-10-28 07:50
Duplicate of https://github.com/vuejs/vue/issues/7628

**Closed by posva** 2018-10-28 07:50 UTC
