### ISSUE TITLE
Deleting an item of Set 

### ISSUE THREAD

**Issue by Fasteel** [vuejs/vue#10640] opened 2019-10-14 14:03 UTC
### Version
2.6.10

### Reproduction link
[https://codepen.io/fasteel/pen/qBBZbgO](https://codepen.io/fasteel/pen/qBBZbgO)

### Steps to reproduce
Create a set in the object data, and try to delete an item via the delete method.

### What is expected?
When the text "DELETE" clicked, the item should disappear.

### What is actually happening?
Nothing

**Comment by posva** [comment] 2019-10-14 14:09
Duplicate of https://github.com/vuejs/vue/issues/6774

**Closed by posva** 2019-10-14 14:09 UTC
