### ISSUE TITLE
Add cross-platform keyboard event modifiers

### ISSUE THREAD

**Issue by davestewart** [vuejs/vue#11302] opened 2020-04-10 19:06 UTC
### What problem does this feature solve?

Macs and PCs use different keyboard modifiers for the same tasks, i.e. `CTRL C` and `CMD C` or in keyboard event terms `.ctrl` and `.meta`.

Because you can't add modifiers dynamically, you have to build handlers yourself, losing out on the built in sugar:

```js
function onKeyPress (event) {
  const isCopy = event.key === 'c' && ((isMac && event.metaKey) || event.ctrlKey)
  ...
}
```

Or use a plugin and do something like:

```vue
<GlobalEvents v-if="isMac" @keypress.meta.c="copy" />
<GlobalEvents v-if="isWin" @keypress.ctrl.c="copy" />
```

### What does the proposed API look like?

I'm proposing several new cross-platform modifiers that would make it much easier to work with cross-platform keyboard shortcuts, on top of the existing excellent keyboard event handling:

- `action` - substitute the correct modifier key `ctrl` or `meta` depending on platform
- `mac` - limit the modifier to mac only
- `win` - limit the modifier to windows / linux only

That would allow combinations like so:

```vue
// automatic
<input @keypress.action.c="copy" />
```

```vue
// manual, perhaps with different handling based on platform
<input @keypress.mac.meta.v="pasteMac" @keypress.win.ctrl.v="pasteWin"  />
```

**Comment by posva** [comment] 2020-04-10 19:50
Duplicate of https://github.com/vuejs/vue/issues/4843

**Closed by posva** 2020-04-10 19:50 UTC
