### ISSUE TITLE
Scoped CSS is inherited incorrectly when use component as root of another component

### ISSUE THREAD

**Issue by lusarz** [vuejs/vue#10433] opened 2019-08-23 14:15 UTC
### Version
2.6.10

### Reproduction link
[https://github.com/lusarz/scoped-css-inheritance-issue](https://github.com/lusarz/scoped-css-inheritance-issue)

### Steps to reproduce
1) Create generic component ([VPanel](https://github.com/lusarz/scoped-css-inheritance-issue/blob/master/src/components/VPanel.vue)) with slot, and `.title` class
2) Use VPanel as root of specific component ([VSamplePanel](https://github.com/lusarz/scoped-css-inheritance-issue/blob/master/src/components/VSamplePanel.vue#L2))
3) Define [div with class `.title`](https://github.com/lusarz/scoped-css-inheritance-issue/blob/master/src/components/VSamplePanel.vue#L4) inside specific component
![repro](https://user-images.githubusercontent.com/10059264/63599104-2b75a100-c5c1-11e9-9a87-71baa564a119.png)

### What is expected?
Div with class `.title` created inside VSamplePanel shouldn't inherit styling from VPanel (font-size in provided example)

### What is actually happening?
Div with class `.title` inside VSamplePanel inherits styling from VPanel (font-size: 48px).

---
I need to create some generic components like card, panel etc in project. I don't want to care about name of classes used in these generic components when writing it's instances.

**Comment by posva** [comment] 2019-08-23 14:20
Duplicate of https://github.com/vuejs/vue/issues/7548

**Closed by posva** 2019-08-23 14:20 UTC

**Comment by lusarz** [comment] 2019-08-23 17:52
Thank you @posva for closing. I was sure that someone met this issue before me, but I couldn't find appropriate issue in github :)

**Comment by posva** [comment] 2019-08-23 18:02
Yeah, I understand, it's sometimes really hard to find the duplicates, even for me

**Comment by lusarz** [comment] 2019-08-25 16:49
I think you managing it very well!

**Comment by posva** [comment] 2019-08-25 18:59
Thank you 🙂
