### ISSUE TITLE
v-else preventing update of variables in nested slots

### ISSUE THREAD

**Issue by Quentin01** [vuejs/vue#11553] opened 2020-07-30 15:05 UTC
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/n8bkg4pw/](https://jsfiddle.net/n8bkg4pw/)

### Steps to reproduce
When clicking on the `inc` button, the displays of `nb_foo.value` will change of value but one out of the three won't change of value because of the bug.

### What is expected?
All of the display of `nb_foo.value` to change of value

### What is actually happening?
One out of the three display of `nb_foo.value` won't change of value because of the bug.

---
It's only happening when in a `v-else` itself in the slot of the `fake` component. When inverting the condition (putting the second `fake` in a `v-if` instead of a `v-else`) it's properly working.

I encountered this error with a much more complex example with two components nested in a similar way.

**Comment by posva** [comment] 2020-07-30 18:14
Duplicate of https://github.com/vuejs/vue/issues/10330

**Closed by posva** 2020-07-30 18:14 UTC
