### ISSUE TITLE
Multiple choice Select element init data wrong

### ISSUE THREAD

**Issue by zhuqling** [vuejs/vue#2267] opened 2016-01-30 09:28 UTC
change selection，reopen the element，it show wrong。
Default "selected" attribute make this error.

**Comment by azamat-sharapov** [comment] 2016-01-30 10:49
Please provide reproduction.

**Comment by zhuqling** [comment] 2016-01-31 01:55
![](http://static.oschina.net/uploads/space/2016/0131/094445_DlLB_2610173.jpg)

**Comment by zhuqling** [comment] 2016-02-24 15:31
I paste new screenshot now

**Comment by yyx990803** [comment] 2016-02-28 06:44
Looks like this is an iOS bug since iOS7 (and still not fixed today... great job, Apple).

There's nothing Vue can do about this, but it can be fixed in user code by adding a disabled option as the first one: `<option disabled></option>`

**Closed by yyx990803** 2016-02-28 06:44 UTC
Labels: bug
