### ISSUE TITLE
[DOCS] Dark mode for docs website

### ISSUE THREAD

**Issue by nainardev** [vuejs/vue#11008] opened 2020-01-13 17:48 UTC
### What problem does this feature solve?
It's very difficult to read the docs for long time due to light theme. Please made a dark theme toggle

### What does the proposed API look like?
.

**Comment by posva** [comment] 2020-01-14 09:13
Duplicate of https://github.com/vuejs/vuejs.org/issues/552

**Closed by posva** 2020-01-14 09:13 UTC
