### ISSUE TITLE
aliasing component "props" names

### ISSUE THREAD

**Issue by jossef** [vuejs/vue#8522] opened 2018-07-19 10:58 UTC
### What problem does this feature solve?
similar to angularjs directives, would like the ability to alias the names the component's parent uses to pass values 

### What does the proposed API look like?
component:
```
export default {
		name: "paging",
		props: {
			"count": {"name": "pagingCount", "type": Number}
		},

```

parent:
```
<paging v-bind:paging-count="itemsCount"></paging>
```

**Comment by posva** [comment] 2018-07-19 11:34
Duplicate of #7943

**Closed by posva** 2018-07-19 11:34 UTC
