### ISSUE TITLE
Vue replace my el not correctlly,  it seem some problem in vue diff func

### ISSUE THREAD

**Issue by weituotian** [vuejs/vue#8502] opened 2018-07-17 05:06 UTC
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/weituotian/k5hLxf1d/](https://jsfiddle.net/weituotian/k5hLxf1d/)

### Steps to reproduce
1. make sure the curPage in data is 1 or 2 or 3
1.  click add transition
1.  click change page

### What is expected?
not all the transition of  `li` disapper. 
every time it should be one disapper.

### What is actually happening?
the transition is Disappear. all of the `li`
This shows that vue replaces all elements instead of incremental updates.

if the curPage is 0,4,5, not all the transition of `li` wiil disapper

---
do not close my issue so easily.
i will close it myself if i find the appropriate answer.

**Comment by Justineo** [comment] 2018-07-17 07:42
Actually Vue doesn't replace all elements. They are just moved in certain cases. Just by moving these elements the transition will stop working.

F.Y.I for your case the patching process goes like the following:

When changing from `curPage` is `1`:

```
<ol>
  <li>a</li> <!-- 1 -->
  <li>b</li> <!-- 2 -->
  <li>c</li> <!-- 3 -->
  <!---->    <!-- 4 -->
  <!---->    <!-- 5 -->
  <!---->    <!-- 6 -->
</ol>

<ol>
  <!---->    <!-- 4 move -->
  <li>a</li> <!-- 1 -->
  <li>b</li> <!-- 2 -->
  <li>c</li> <!-- 3 -->
  <!---->    <!-- 5 -->
  <!---->    <!-- 6 -->
</ol>

<ol>
  <!---->    <!-- 4 -->
  <li>b</li> <!-- 2 move -->
  <li>a</li> <!-- 1 -->
  <li>c</li> <!-- 3 -->
  <!---->    <!-- 5 -->
  <!---->    <!-- 6 -->
</ol>

<ol>
  <!---->    <!-- 4 -->
  <li>b</li> <!-- 2 -->
  <li>c</li> <!-- 3 move -->
  <li>a</li> <!-- 1 -->
  <!---->    <!-- 5 -->
  <!---->    <!-- 6 -->
</ol>

<ol>
  <!---->    <!-- 4 -->
  <li>b</li> <!-- 2 -->
  <li>c</li> <!-- 3 -->
  <li>d</li> <!-- 7 create -->
  <li>a</li> <!-- 1 -->
  <!---->    <!-- 5 -->
  <!---->    <!-- 6 -->
</ol>

<ol>
  <!---->    <!-- 4 -->
  <li>b</li> <!-- 2 -->
  <li>c</li> <!-- 3 -->
  <li>d</li> <!-- 7 -->
  <!---->    <!-- 5 -->
  <!---->    <!-- 6 -->
</ol>
```

When changing from `curPage` is `4`:

```
<ol>
  <!---->    <!-- 1 -->
  <!---->    <!-- 2 -->
  <!---->    <!-- 3 -->
  <li>d</li> <!-- 4 -->
  <li>e</li> <!-- 5 -->
  <li>f</li> <!-- 6 -->
</ol>

<ol>
  <!---->    <!-- 2 -->
  <!---->    <!-- 3 -->
  <li>d</li> <!-- 4 -->
  <!---->    <!-- 1 move -->
  <li>e</li> <!-- 5 -->
  <li>f</li> <!-- 6 -->
</ol>

<ol>
  <!---->    <!-- 3 -->
  <li>d</li> <!-- 4 -->
  <!---->    <!-- 2 move -->
  <!---->    <!-- 1 -->
  <li>e</li> <!-- 5 -->
  <li>f</li> <!-- 6 -->
</ol>

<ol>
  <li>d</li> <!-- 4 -->
  <!---->    <!-- 3 move -->
  <!---->    <!-- 2 -->
  <!---->    <!-- 1 -->
  <li>e</li> <!-- 5 -->
  <li>f</li> <!-- 6 -->
</ol>

<ol>
  <li>a</li> <!-- 7 create -->
  <li>d</li> <!-- 4 -->
  <!---->    <!-- 3 -->
  <!---->    <!-- 2 -->
  <!---->    <!-- 1 -->
  <li>e</li> <!-- 5 -->
  <li>f</li> <!-- 6 -->
</ol>

<ol>
  <li>a</li> <!-- 7 -->
  <!---->    <!-- 3 -->
  <!---->    <!-- 2 -->
  <!---->    <!-- 1 -->
  <li>e</li> <!-- 5 -->
  <li>f</li> <!-- 6 -->
</ol>
```

As you can see the later one doesn't move any `<li>` element at all, so the transition retains. The former one moved all elements so the transition is gone.

I guess it's probably because Vue's patching algorithm cannot always guarantee that elements stay in their original position. I think there might be some space for it to be optimized though.

**Comment by posva** [comment] 2018-07-17 08:58
Duplicate of #4362

**Closed by posva** 2018-07-17 08:58 UTC

**Comment by weituotian** [comment] 2018-07-17 09:16
@posva is there some method to avoid this? it is Urgent.

**Comment by posva** [comment] 2018-07-17 09:21
not that I am aware of. You can maybe find a way to solve it using transition component but I couldn't tell. Cheers

**Comment by yyx990803** [comment] 2018-07-17 13:55
FYI: we decide whether we want to close your issue or not, it's not your decision.
