### ISSUE TITLE
Custom directive v-focus in docs does not focus input element on insert in iOS Safari

### ISSUE THREAD

**Issue by amirrustam** [vuejs/vue#4608] opened 2016-12-30 03:58 UTC
### Vue.js version
2.1.7

### Reproduction Link
See custom directive `v-focus` demo within the documentation: 
[https://vuejs.org/v2/guide/custom-directive.html]( https://vuejs.org/v2/guide/custom-directive.html)

```javascript
// Register a global custom directive called v-focus
Vue.directive('focus', {
  // When the bound element is inserted into the DOM...
  inserted: function (el) {
    // Focus the element
    el.focus()
  }
})
```

### Steps to reproduce
Load `v-focus` [demo](https://vuejs.org/v2/guide/custom-directive.html).

### What is Expected?
The documentation in the demo states the following expectation:

> When the page loads, that element gains focus. In fact, if you haven’t clicked on anything else since visiting this page, the input above should be focused now.

### What is actually happening?
In iOS Safari (10.2.1) the `v-focus` demo **does not focus** on the input element upon page load.

**Comment by amirrustam** [comment] 2016-12-30 04:09
A relevant StackOverflow answer:

> I think this is a feature of mobile Safari rather than a bug. In our work on FastClick, my colleagues and I found that iOS will only allow focus to be triggered on other elements, from within a function, if the first function in the call stack was triggered by a non-programmatic event.

Source: [http://stackoverflow.com/a/7332160](http://stackoverflow.com/a/7332160)

**Comment by LinusBorg** [comment] 2016-12-30 11:28
...So we can close this because it's Safari's problem?

**Comment by amirrustam** [comment] 2016-12-30 12:27
I'm not certain, but if that's going to be our final answer then should the docs mention something about this?

**Comment by defcc** [comment] 2016-12-30 13:58
Seems by design of mobile safari, not an issue of Vue. We might add an extra infomation about it in the doc.

**Comment by defcc** [comment] 2016-12-30 14:20
I opened a PR in the doc repository, so I'll close this issue.

**Closed by defcc** 2016-12-30 14:20 UTC

**Comment by mesqueeb** [comment] 2017-11-17 06:38
Does anyone know a work around for this?

**Comment by zhouyali** [comment] 2017-12-15 08:50
I dont think it could be solved by javascript.
