### ISSUE TITLE
mousemove event executed before watcher

### ISSUE THREAD

**Issue by mygaochunming** [vuejs/vue#7560] opened 2018-01-30 01:08 UTC
### Version
2.5.13

### Reproduction link
[https://jsfiddle.net/mygaochunming/gkmpvxsm/10/](https://jsfiddle.net/mygaochunming/gkmpvxsm/10/)

### Steps to reproduce
use chrome 49 in winXP, click inner component, then see the console log

### What is expected?
mousemove event triggered affter watcher

### What is actually happening?
mousemove event triggered before watcher

---
Maybe you will say use the latest chrome version. But my customers do use winXP and the 49 version is the last version in winXP. So .....

I don't known if this is a vue bug or a chrome bug(in chrome 49, when user click the component, it triggered click and mousemove event). but it works well in [vue version 2.4.4 demo](https://jsfiddle.net/mygaochunming/gkmpvxsm/9/).

I have seen the vue release log that change the v-on event handler to macro task. But I still do not understand the log below:

vue2.4.4_chrome49_winXP

![vue2 4 4_chrome49_winxp](https://user-images.githubusercontent.com/21029140/35542858-2fb1a89e-059d-11e8-9ac9-f398d41e297b.png)

vue2.5.13_chrome49_winXP

![vue2 5 13_chrome49_winxp](https://user-images.githubusercontent.com/21029140/35542864-36de17a6-059d-11e8-8b83-33dd3d46a534.png)

**Comment by fnlctrl** [comment] 2018-02-06 21:05
Hi, thanks for filling this issue.
I'm able to get both results on latest chrome for both vue 2.5.13 and vue 2.4.4.

The following logs can be seen on either vue version, so vue version doesn't matter here.

Before watcher
![image](https://user-images.githubusercontent.com/5557143/35883987-22fd7ff6-0bc4-11e8-9a53-dd6e7e919107.png)

After watcher
![image](https://user-images.githubusercontent.com/5557143/35884035-3f604f8e-0bc4-11e8-9a52-7d6619e6d691.png)

Closing as this is simply a **race condition** caused by your implementation, whether you move your mouse immediately after clicking - it has nothing to do with OS/Chrome/Vue version.

**Closed by fnlctrl** 2018-02-06 21:05 UTC
