### ISSUE TITLE
Native element with component :is v-model does not work as expected

### ISSUE THREAD

**Issue by bencasling** [vuejs/vue#10444] opened 2019-08-27 12:33 UTC
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/just_ben1996/5bfs80gk/14/](https://jsfiddle.net/just_ben1996/5bfs80gk/14/)

### Steps to reproduce
- Create a component with a :is to an 'input' native element.
- v-model this component to something within your data as shown.
- Note the input isn't pre-populated with the value, and on change it does not change the value it is bound to with v-model.

### What is expected?
v-model should work as usual, updating the value when changed and displaying the value initially in the component.

### What is actually happening?
The initial value is not shown in the input component, and on change it does not update the value it is bound to.

**Comment by posva** [comment] 2019-08-27 12:43
Duplicate of https://github.com/vuejs/vue/issues/4763

There is no need to do multiple v-if though, as using a dynamic `type` is supported. But the generated template is different for dynamic components and for native inputs: https://template-explorer.vuejs.org/#%3Cdiv%3E%0A%20%20%3Ccomponent%20%3Ais%3D%22inputComponent%22%20v-model%3D%22someValue%22%3E%3C%2Fcomponent%3E%0A%20%20%3Cinput%20v-model%3D%22someValue%22%3E%0A%3C%2Fdiv%3E

So you will have to manually bind the prop and event:

```vue
<component :is="inputComponent" :value.prop="someValue" @input="value = $event"></component>
```

**Closed by posva** 2019-08-27 12:43 UTC
