### ISSUE TITLE
TypeError when route-link with sibling slot used

### ISSUE THREAD

**Issue by Darkside73** [vuejs/vue#4584] opened 2016-12-27 17:20 UTC
### Vue.js version
2.1.7

### Reproduction Link
https://jsfiddle.net/1anum7y4/1/

This template fails to compile if no default slot given

```html
<p>
  <router-link :to="{ name: 'foo' }">foo</router-link>
  <slot></slot>
</p>
```
It does not reproduce if slot given or ```<slot></slot>``` wrapped by any tag

### What is Expected?
Component renders without slot

### What is actually happening?
Uncaught TypeError: Cannot set property 'isRootInsert' of undefined

**Comment by mmochetti** [comment] 2016-12-27 19:00
Having same issue in an SPA...
![image](https://cloud.githubusercontent.com/assets/3678598/21506276/9a87a338-cc4d-11e6-809f-59b2f3ed2263.png)

**Comment by johnleider** [comment] 2016-12-27 21:02
Same, submitted issue on the vue-router repo [#1051](https://github.com/vuejs/vue-router/issues/1051).

**Comment by samuelantonioli** [comment] 2016-12-27 21:03
**the problem**

The difference seems to be the following between the versions:
Vue 2.1.7 calls createElm with an undefined vnode (`createElm(undefined, ...)`)

`console.log` in `createElm` reveals the following:

Vue 2.1.6:
![216](https://cloud.githubusercontent.com/assets/6854707/21507918/db781164-cc7c-11e6-8a5b-d5d8f81e8fca.png)

Vue 2.1.7:
![217](https://cloud.githubusercontent.com/assets/6854707/21507926/e739946e-cc7c-11e6-8093-e392e57269d8.png)

So here's the problem: `createElem` gets called with an undefined vnode.
calling Vue 2.1.6's `createElm` with an undefined `vnode` creates the same error:

> Uncaught TypeError: Cannot set property 'isRootInsert' of undefined

- - -

**bug**

The relevant part is [src/core/vdom/patch.js#L89](https://github.com/vuejs/vue/blob/c83458fb94e2fe007e3cda1b63f7020a4515fdd6/src/core/vdom/patch.js#L89)

- - -

**solution**

I think it would be a good idea to add the following lines in `createElm` which just make sure
that the function doesn't want to access attributes of an `undefined` object:

```javascript
if (typeof(vnode) === 'undefined') {
    return
}
```

This seems to solve the problem for Vue 2.1.7 and also Vue 2.1.6 when calling `createElm(undefined, ...)`.

It should be analyzed where the error gets introduced (i.e. why `createElm` gets called with an undefined vnode), but I think it is a good idea to do a bit type checking here regardless.  
Maybe a unit test should be added to check for this case.

Would be glad to help.

**Comment by yyx990803** [comment] 2016-12-27 21:13
This should actually be the same issue with #4564 and is fixed by #4572 (confirmed for @Darkside73 and @johnleider 's cases)

@mmochetti @samuelantonioli you can try the patch in #4572 in your local Vue dist file to see if they are the same issue - if the error persists, they are likely different bugs and please open separate issue with repro.

**Closed by yyx990803** 2016-12-27 21:13 UTC
Labels: bug

**Comment by samuelantonioli** [comment] 2016-12-27 21:14
@johnleider

it seems that there's the same problem with missing type checking before accessing the attributes in your referenced issue https://github.com/vuejs/vue/issues/4584

The relevant part for this bug is here: [src/core/instance/render.js#L293](https://github.com/vuejs/vue/blob/c83458fb94e2fe007e3cda1b63f7020a4515fdd6/src/core/instance/render.js#L293). Replacing the current `if` statement there with the following lines solves the problem for me (patching my local dist for testing):

```javascript
if (
  typeof(child) === 'object' &&
  (child.context === context || child.functionalContext === context) &&
  child.data && (name = child.data.slot)
) {
    ...
}
```

**Comment by samuelantonioli** [comment] 2016-12-27 21:23
@yyx990803 Thanks, after applying the changes to `getNormalizationType`, everything works as expected.
