### ISSUE TITLE
Error 'URL is not defined' when webpack5 builds the server program

### ISSUE THREAD

**Issue by lzxb** [vuejs/vue#12418] opened 2022-01-13 08:11 UTC
### What problem does this feature solve?
The 'Vue server renderer' package should pass in a URL object when creating a sandbox

### What does the proposed API look like?
```javascript
createBundleRenderer(bundle, {
            ...renderOptions,
            runInNewContext: 'once',
            sandbox: {
                URL: URL
            }
        });
```

**Comment by lzxb** [comment] 2022-01-13 08:12
webpack5 
https://webpack.js.org/configuration/module/#moduleparserjavascripturl

**Comment by lzxb** [comment] 2022-01-13 08:35
![image](https://user-images.githubusercontent.com/8424643/149294672-710c7095-92fc-41c3-ae3c-e6127182e7e7.png)

Or support URL directly here

**Comment by posva** [comment] 2022-01-13 08:56
Duplicate of https://github.com/vuejs/vue/pull/10414

**Closed by posva** 2022-01-13 08:56 UTC
