### ISSUE TITLE
about directives

### ISSUE THREAD

**Issue by alioygur** [vuejs/vue#1732] opened 2015-11-06 17:26 UTC
I have wrote directive for wraping the [timeago](http://timeago.yarp.com/) plugin.

there is my directive

```js
module.exports = {
  bind: function() {
    var self = this;
    setTimeout(function() {
      $(self.el).timeago();
    }, 500);
    // $(self.el).timeago();
  }
};
```

I am using it like below

    <time datetime="2015-11-06T17:18:17Z" v-time-ago></time>

but it does not work without setTimeOut function. so what is the problem ?

**Comment by yyx990803** [comment] 2015-11-06 17:28
Please provide a reproduction.

**Comment by alioygur** [comment] 2015-11-06 17:35
reproduction ? sorry, I don't understand.

**Comment by yyx990803** [comment] 2015-11-06 17:39
Make a live, editable demo using a service like http://jsfiddle.net/ so I can debug it.

**Comment by alioygur** [comment] 2015-11-06 17:47
okey I will do it.

**Comment by alioygur** [comment] 2015-11-06 22:58
@yyx990803 i just tried in jsfiddle it worked. but it does not work with webpack require.

**Comment by yyx990803** [comment] 2015-11-06 23:15
Hmm, then this doesn't seem to be a Vue core issue. Closing for now. Maybe we can get more info If you can provide a repository with your webpack setup.

**Closed by yyx990803** 2015-11-06 23:15 UTC
Labels: need repro

**Comment by alioygur** [comment] 2015-11-06 23:20
can you provide to me your email address ? I will add you to my repo on bitbucket.

**Comment by yyx990803** [comment] 2015-11-06 23:23
Sorry, but I don't really have time to look into full projects - you will need to isolate the problem and provide a minimal reproduction repo on GitHub.

**Comment by alioygur** [comment] 2015-11-06 23:23
okey, I will do it. thank you dear.

**Comment by alioygur** [comment] 2015-11-10 15:28
@yyx990803 hi dear, i have done it.

[jsfiddle](https://jsfiddle.net/alioygur/4yuarm04/3/)

it does not work in nested component.

**Comment by alioygur** [comment] 2015-11-10 16:32
okey i have fixed it with nextTick()

[is this right way](http://jsfiddle.net/alioygur/4yuarm04/4/) ?

**Comment by simplesmiler** [comment] 2015-11-10 16:35
If you open the fiddle and wait a minute, you'll see that `timeago` updated both element correctly. It looks like an issue with the `timeago` library.

**Comment by alioygur** [comment] 2015-11-10 16:42
@simplesmiler no. it is not about timeago. [why it work well](http://jsfiddle.net/alioygur/4yuarm04/4/) ?

**Comment by alioygur** [comment] 2015-11-10 16:44
I am getting this problem with other plugins. which one is [animateModal.js](http://joaopereirawd.github.io/animatedModal.js/)

**Comment by simplesmiler** [comment] 2015-11-10 16:56
@alioygur
I may have been a bit offensive, I did not mean it. What I'm talking about is the fact that `$(this.el).timeago();` does not work in the `bind` callback, while for some jquery plugins similar code does work properly: http://vuejs.org/examples/select2.html.

**Comment by alioygur** [comment] 2015-11-10 17:16
@simplesmiler okey. I got it.

**Comment by simplesmiler** [comment] 2015-11-10 19:00
@alioygur anyway `nextTick` is a fine workaround, unless you are willing to dig into the jquery plugin code.

**Comment by alioygur** [comment] 2015-11-11 09:46
@simplesmiler yes you right. thank you dear.
