### ISSUE TITLE
`v-switch` `v-case` `v-default` directives

### ISSUE THREAD

**Issue by PedroCuadra** [vuejs/vue#11905] opened 2021-02-10 15:38 UTC
### What problem does this feature solve?
Hello everyone,

Sometimes i want to show different content depending on a variable value and `v-if`  is a bit less legible than this proposed `v-switch` directive 

### What does the proposed API look like?
```html
<template v-switch="variable">
  <div v-case="1">
   ... some content A
  </div>
  <div v-case="2">
   ... some content B
  </div>
  <div v-default>
   ... some content C
  </div>
</template>
```

Note that the `<div>`s can be `<template>`s or components as well

**Comment by posva** [comment] 2021-02-10 15:56
Please check existing issues: https://github.com/vuejs/vue/issues?q=is%3Aissue+sort%3Aupdated-desc+v-switch+is%3Aclosed

Duplicate of https://github.com/vuejs/vue/issues/8097

**Closed by posva** 2021-02-10 15:56 UTC
