### ISSUE TITLE
$nextTick timing events introduce breaking changes from 2.5.x to 2.6.x

### ISSUE THREAD

**Issue by waaronking** [vuejs/vue#11380] opened 2020-05-07 11:34 UTC
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/vue2611-q4ky0?file=/src/components/HelloWorld.vue](https://codesandbox.io/s/vue2611-q4ky0?file=/src/components/HelloWorld.vue)

### Steps to reproduce
1. Follow the codesandbox link
2. Click on the "Component Vue 2.6.11" text in the browser view to enable "edit mode"
3. Click "cancel edit" to exit "edit mode"

### What is expected?
It is expected that $nextTick will defer the setting of the variable "editMode" to false, preventing the parent container click event from executing and re-setting the variable to true. (see line 26)

### What is actually happening?
$nextTick isn't deferring execution as it did in 2.5.x. The variable "editMode" is being set to false and then the parent container click event immediately resets it to true.

---
Here is the codesandbox link for v2.5.22 to see how it behaved prior to 2.6.x:
https://codesandbox.io/s/vue2522-xo346?file=/src/components/HelloWorld.vue

I ran into this bug while trying to upgrade from 2.5.22 to 2.6.11. It broke our production app everywhere this edit component was used. For this type of edit component, this is a pretty natural design pattern. 

Side note: If this is an intentional breaking change, are there recommended work arounds for these type of components (besides DOM restructuring)?

**Comment by Justineo** [comment] 2020-05-07 12:10
Duplicate of #9340

Also see #9478, #9464 and more details [here](https://gist.github.com/yyx990803/d1a0eaac052654f93a1ccaab072076dd).

**Closed by Justineo** 2020-05-07 12:10 UTC
