### ISSUE TITLE
nested dynamic components occur memory leaks

### ISSUE THREAD

**Issue by 15757115286** [vuejs/vue#10544] opened 2019-09-21 02:01 UTC
### Version
2.6.10

### Reproduction link
[https://codepen.io/15757115286/pen/MWgZYgg](https://codepen.io/15757115286/pen/MWgZYgg)

### Steps to reproduce
1. collect garbage and take a snapshot before click the button toggleB  

2.click button toggleB, change the value of the input 

3.click button toggle A, make sure the external dynamic component is componentA 

4.collect garbage and take a snapshot

### What is expected?
the delta of the VueComponent is 0

### What is actually happening?
the delta of the VueComponent is bigger than 0

---
the version of the chrome is 77.0.3865.90
when toggle the componet repeatedly, the count of VueComponent in memory  is always increase

**Comment by posva** [comment] 2019-09-21 14:02
seems to be related to the inputs
Duplicate of https://github.com/vuejs/vue/issues/10004

**Closed by posva** 2019-09-21 14:02 UTC
